Beam Longitudinal Dynamics code (BLonD): vector_math.h File Reference
vector_math.h File Reference
#include <algorithm>
#include <functional>
#include <cassert>
#include <vector>
#include <iostream>
#include <iterator>
Functions
template<typename T , typename F >
static std::vector< T > apply_f (const std::vector< T > &a, F op)
template<typename T , typename F >
static std::vector< T > apply_f (const std::vector< T > &a, const std::vector< T > &b, F op)
template<typename T , typename F >
static void apply_f_in_place (std::vector< T > &a, F op)
template<typename T , typename F >
static void apply_f_in_place (std::vector< T > &a, const std::vector< T > &b, F op)
template<typename T >
static std::vector< bool > operator!= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator!= (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< T > operator* (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator* (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator* (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator*= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator*= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator+ (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator+ (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator+ (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator+= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator+= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator- (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator- (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator- (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator-= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator-= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator/ (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator/ (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator/ (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator/= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator/= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< bool > operator< (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator< (const std::vector< T > &a, const T &b)
template<typename T >
static std::ostream & operator<< (std::ostream &os, const std::vector< T > &a)
template<typename T >
static std::vector< bool > operator<= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator<= (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator== (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator== (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator> (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator> (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator>= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator>= (const std::vector< T > &a, const T &b)
template<typename T >
static T pick (const std::vector< T > &a, const int i)
template<typename T >
static std::vector< T > pick (const std::vector< T > &a, const std::vector< int > &indexes)
template<typename T >
static std::vector< T > pick (const std::vector< T > &a, const std::vector< bool > &indexes)
template<typename T >
static std::vector< T > slice (const std::vector< T > &a, const int start=0, int end=0, const int step=1)
Function Documentation
template<typename T , typename F > static std::vector<T> apply_f (const std::vector< T > & a, F op) inline static
Definition at line 25 of file vector_math.h.
Referenced by distribution_density_function(), matched_from_distribution_density(), operator*(), operator+(), operator-(), operator/(), and Slices::rms().
 {
     // const size_t size = a.size();
     // std::vector<T> result(size);
     // for (size_t i = 0; i < size; i++)
     //     result[i] = op(a[i]);
     std::vector<T> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(), op);
     return result;
 }
template<typename T , typename F > static std::vector<T> apply_f (const std::vector< T > & a, const std::vector< T > & b, F op) inline static
Definition at line 50 of file vector_math.h.
 {
     // const size_t size = a.size();
     // std::vector<T> result(size);
     // for (size_t i = 0; i < size; i++)
     //     result[i] = op(a[i], b[i]);
     assert(a.size() == b.size());
     std::vector<T> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(), result.begin(), op);
     return result;
 }
template<typename T , typename F > static void apply_f_in_place (std::vector< T > & a, F op) inline static
Definition at line 39 of file vector_math.h.
Referenced by operator*=(), operator+=(), operator-=(), and operator/=().
 {
     // const size_t size = a.size();
     // for (size_t i = 0; i < size; i++)
     //     a[i] = op(a[i]);
     std::transform(a.begin(), a.end(), a.begin(), op);
 }
template<typename T , typename F > static void apply_f_in_place (std::vector< T > & a, const std::vector< T > & b, F op) inline static
Definition at line 66 of file vector_math.h.
 {
     // const size_t size = a.size();
     // for (size_t i = 0; i < size; i++)
     //     a[i] = op(a[i], b[i]);
     assert(a.size() == b.size());
     std::transform(a.begin(), a.end(), b.begin(), a.begin(), op);
 }
template<typename T > static std::vector<bool> operator!= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 287 of file vector_math.h.
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::not_equal_to<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator!= (const std::vector< T > & a, const T & b) inline static
Definition at line 352 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::not_equal_to<T>(), b));
     return result;
 }
template<typename T > static std::vector<T> operator* (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 114 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, b, std::multiplies<T>());
 }
template<typename T , typename U > static std::vector<T> operator* (const std::vector< T > & a, const U & b) inline static
Definition at line 189 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::multiplies<T>(), b));
 }
template<typename T , typename U > static std::vector<T> operator* (const U & b, const std::vector< T > & a) inline static
Definition at line 195 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::multiplies<T>(), b));
 }
template<typename T > static std::vector<T> operator*= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 121 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, b, std::multiplies<T>());
     return a;
 }
template<typename T , typename U > static std::vector<T> operator*= (std::vector< T > & a, const U & b) inline static
Definition at line 201 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, std::bind2nd(std::multiplies<T>(), b));
     return a;
 }
template<typename T > static std::vector<T> operator+ (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 83 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, b, std::plus<T>());
 }
template<typename T , typename U > static std::vector<T> operator+ (const std::vector< T > & a, const U & b) inline static
Definition at line 151 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::plus<T>(), b));
 }
template<typename T , typename U > static std::vector<T> operator+ (const U & b, const std::vector< T > & a) inline static
Definition at line 157 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::plus<T>(), b));
 }
template<typename T > static std::vector<T> operator+= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 90 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, b, std::plus<T>());
     return a;
 }
template<typename T , typename U > static std::vector<T> operator+= (std::vector< T > & a, const U & b) inline static
Definition at line 163 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, std::bind2nd(std::plus<T>(), b));
     return a;
 }
template<typename T > static std::vector<T> operator- (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 99 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, b, std::minus<T>());
 }
template<typename T , typename U > static std::vector<T> operator- (const std::vector< T > & a, const U & b) inline static
Definition at line 170 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::minus<T>(), b));
 }
template<typename T , typename U > static std::vector<T> operator- (const U & b, const std::vector< T > & a) inline static
Definition at line 176 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind1st(std::minus<T>(), b));
 }
template<typename T > static std::vector<T> operator-= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 106 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, b, std::minus<T>());
     return a;
 }
template<typename T , typename U > static std::vector<T> operator-= (std::vector< T > & a, const U & b) inline static
Definition at line 182 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, std::bind2nd(std::minus<T>(), b));
     return a;
 }
template<typename T > static std::vector<T> operator/ (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 130 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, b, std::divides<T>());
 }
template<typename T , typename U > static std::vector<T> operator/ (const std::vector< T > & a, const U & b) inline static
Definition at line 208 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind2nd(std::divides<T>(), b));
 }
template<typename T , typename U > static std::vector<T> operator/ (const U & b, const std::vector< T > & a) inline static
Definition at line 214 of file vector_math.h.
References apply_f().
 {
     return apply_f(a, std::bind1st(std::divides<T>(), b));
 }
template<typename T > static std::vector<T> operator/= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 137 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, b, std::divides<T>());
     return a;
 }
template<typename T , typename U > static std::vector<T> operator/= (std::vector< T > & a, const U & b) inline static
Definition at line 220 of file vector_math.h.
References apply_f_in_place().
 {
     apply_f_in_place(a, std::bind2nd(std::divides<T>(), b));
     return a;
 }
template<typename T > static std::vector<bool> operator< (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 298 of file vector_math.h.
Referenced by matched_from_distribution_density(), matched_from_line_density(), Slices::sort_particles(), and Music::track().
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::less<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator< (const std::vector< T > & a, const T & b) inline static
Definition at line 362 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::less<T>(), b));
     return result;
 }
template<typename T > static std::ostream& operator<< (std::ostream & os, const std::vector< T > & a) inline static
Definition at line 402 of file vector_math.h.
 {
     os << "[ ";
     std::copy(a.begin(), a.end(), std::ostream_iterator<T>(os, ", "));
     os << "\b\b ]\n";
     return os;
 }
template<typename T > static std::vector<bool> operator<= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 309 of file vector_math.h.
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::less_equal<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator<= (const std::vector< T > & a, const T & b) inline static
Definition at line 372 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::less_equal<T>(), b));
     return result;
 }
template<typename T > static std::vector<bool> operator== (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 276 of file vector_math.h.
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::equal_to<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator== (const std::vector< T > & a, const T & b) inline static
Definition at line 343 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::equal_to<T>(), b));
     return result;
 }
template<typename T > static std::vector<bool> operator> (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 321 of file vector_math.h.
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::greater<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator> (const std::vector< T > & a, const T & b) inline static
Definition at line 382 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::greater<T>(), b));
     return result;
 }
template<typename T > static std::vector<bool> operator>= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 332 of file vector_math.h.
 {
     assert(a.size() == b.size());
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), b.begin(),
                    result.begin(), std::greater_equal<T>());
     return result;
 }
template<typename T > static std::vector<bool> operator>= (const std::vector< T > & a, const T & b) inline static
Definition at line 392 of file vector_math.h.
 {
     std::vector<bool> result(a.size());
     std::transform(a.begin(), a.end(), result.begin(),
                    std::bind2nd(std::greater_equal<T>(), b));
     return result;
 }
template<typename T > static T pick (const std::vector< T > & a, const int i) inline static
Definition at line 227 of file vector_math.h.
 {
     assert(std::abs(i) < a.size());
     if (i >= 0)
         return a[i];
     else
         return a.rbegin()[-i - 1];
 }
template<typename T > static std::vector<T> pick (const std::vector< T > & a, const std::vector< int > & indexes) inline static
Definition at line 237 of file vector_math.h.
 {
     std::vector<T> res;
     res.reserve(indexes.size());
     for (const auto &i : indexes) {
         res.push_back(a[i]);
     }
     return res;
 }
template<typename T > static std::vector<T> pick (const std::vector< T > & a, const std::vector< bool > & indexes) inline static
Definition at line 249 of file vector_math.h.
 {
     std::vector<T> res;
     res.reserve(indexes.size());
     for (uint i = 0; i < indexes.size(); i++)
         if (indexes[i] == true)
             res.push_back(a[i]);
     return res;
 }
template<typename T > static std::vector<T> slice (const std::vector< T > & a, const int start = 0, int end = 0, const int step = 1) inline static
Definition at line 261 of file vector_math.h.
 {
     if (end == 0) end = a.size();
     else if (end < 0) end = a.size() + end;
     std::vector<T> result;
     result.reserve((end - start + step - 1) / step);
     for (int i = start; i < end; i += step)
         result.push_back(a[i]);
     return result;
 }