Beam Longitudinal Dynamics code (BLonD): plot_llrf.cpp File Reference
plot_llrf.cpp File Reference
#include <blond/plots/plot_llrf.h>
#include <blond/python.h>
#include <blond/monitors/Monitors.h>
#include <memory>
Functions
int plot_COM_motion (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_LHCNoiseFB (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_LHCNoiseFB_FWHM (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_LHCNoiseFB_FWHM_bbb (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_noise_spectrum (f_vector_t &frequency, f_vector_t &spectrum, int sampling, std::string dirname, int figno)
int plot_phase_noise (f_vector_t &time, f_vector_t &dphi, int sampling, std::string dirname, int figno)
int plot_PL_bunch_phase (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_PL_freq_corr (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_PL_phase_corr (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_PL_RF_freq (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_PL_RF_phase (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_RF_phase_error (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
int plot_RL_radial_error (RfParameters *RfP, std::string h5data, int output_freq, std::string dirname)
Function Documentation
int plot_COM_motion (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 234 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_COM_motion");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/mean_dt",
                                   "double", &dims));
     auto pMeanDt = python::convert_double_array(array.get(), dims);
     array = std::unique_ptr<double> ((double *) read_1D(h5data,
                                      "Beam/mean_dE", "double", &dims));
     auto pMeanDE = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pMeanDt,
                                             pMeanDE, pOutputFreq, pDirname,
                                             NULL);
     return ret != nullptr;
 }
int plot_LHCNoiseFB (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 265 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/LHC_noise_FB_factor",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_LHCNoiseFB_FWHM (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 291 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB_FWHM");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/LHC_noise_FB_bl", "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_LHCNoiseFB_FWHM_bbb (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 316 of file plot_llrf.cpp.
References python::convert_double_2d_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_2D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB_FWHM_bbb");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims[2];
     std::unique_ptr<double> array((double *) read_2D(h5data,
                                   "Beam/LHC_noise_FB_bl_bbb",
                                   "double", dims));
     f_vector_2d_t temp;
     for (uint i = 0; i < dims[0]; i++) {
         temp.push_back(f_vector_t(&array.get()[i * dims[1]],
                                   &array.get()[(i + 1) * dims[1]]));
     }
     auto ph5Data = python::convert_double_2d_array(temp);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_noise_spectrum (f_vector_t & frequency, f_vector_t & spectrum, int sampling, std::string dirname, int figno)
Definition at line 7 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), and python::import().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_noise_spectrum");
     auto pFigNo = python::convert_int(figno);
     auto pSampling = python::convert_int(sampling);
     auto pDirname = python::convert_string(dirname);
     auto pFreq = python::convert_double_array(frequency.data(),
                  frequency.size());
     auto pSpectrum = python::convert_double_array(spectrum.data(),
                      spectrum.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pFreq,
                                             pSpectrum, pSampling,
                                             pDirname, pFigNo, NULL);
     return ret != nullptr;
     // assert(ret);
 }
int plot_phase_noise (f_vector_t & time, f_vector_t & dphi, int sampling, std::string dirname, int figno)
Definition at line 32 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), and python::import().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_phase_noise");
     auto pFigNo = python::convert_int(figno);
     auto pSampling = python::convert_int(sampling);
     auto pDirname = python::convert_string(dirname);
     auto pTime = python::convert_double_array(time.data(),
                  time.size());
     auto pDPhi = python::convert_double_array(dphi.data(),
                  dphi.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pTime, pDPhi, pSampling,
                                             pDirname, pFigNo, NULL);
     return ret != nullptr;
     // assert(ret);
 }
int plot_PL_bunch_phase (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 56 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_bunch_phase");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *)read_1D(h5data,
                                   "Beam/PL_bunch_phase",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_PL_freq_corr (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 158 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_freq_corr");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/PL_omegaRF_corr",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_PL_phase_corr (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 108 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_phase_corr");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/PL_phase_corr", "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_PL_RF_freq (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 133 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_RF_freq");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/PL_omegaRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_PL_RF_phase (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 83 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_RF_phase");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/PL_phiRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_RF_phase_error (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 184 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_RF_phase_error");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/SL_dphiRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int plot_RL_radial_error (RfParameters * RfP, std::string h5data, int output_freq, std::string dirname)
Definition at line 209 of file plot_llrf.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), RfParameters::counter, python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_RL_radial_error");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/RL_drho",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }