Beam Longitudinal Dynamics code (BLonD): Slices Class Reference
Slices Class Reference
#include <Slices.h>
Public Types
enum cuts_unit_t { s, rad }
enum fit_t { normal, gaussian }
Public Member Functions
Slices (RfParameters *RfP, Beams *Beam, int _n_slices, int _n_sigma=0, double cut_left=0, double cut_right=0, cuts_unit_t cuts_unit=s, fit_t fit_option=normal, bool direct_slicing=false)
~Slices ()
void beam_profile_derivative (f_vector_t &x, f_vector_t &derivative, std::string mode="gradient")
void beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int &nCoefficients, f_vector_t &b, f_vector_t &a)
void beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int &nCoefficients, f_vector_t &transferFreq, complex_vector_t &transferGain)
void beam_spectrum_generation (int n, bool onlyRFFT=false)
double convert_coordinates (double cut, cuts_unit_t type)
void fwhm (const double shift=0)
void fwhm_multibunch ()
void gaussian_fit ()
void histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
void rms ()
void set_cuts ()
void slice_constant_space_histogram ()
void slice_constant_space_histogram_smooth ()
void smooth_histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
void sort_particles ()
void track ()
void track_cuts ()
Public Attributes
Beams * beam
f_vector_t bin_centers
double bl_fwhm
double bl_gauss
double bl_rms
double bp_fwhm
double bp_gauss
double bp_rms
double cut_left
double cut_right
cuts_unit_t cuts_unit
f_vector_t edges
complex_vector_t fBeamSpectrum
f_vector_t fBeamSpectrumFreq
fit_t fit_option
f_vector_t n_macroparticles
int n_sigma
int n_slices
RfParameters * rfp
Private Member Functions
f_vector_t gaussian_filter1d (f_vector_t &x, int sigma, int order, std::string mode)
f_vector_t gradient (f_vector_t &x, double dist)
Detailed Description
Definition at line 22 of file Slices.h.
Member Enumeration Documentation
enum Slices::cuts_unit_t
Enumerator
s
rad
Definition at line 29 of file Slices.h.
 { s, rad };
enum Slices::fit_t
Enumerator
normal
gaussian
Definition at line 30 of file Slices.h.
 { normal, gaussian };
Constructor & Destructor Documentation
Slices::Slices (RfParameters * RfP, Beams * Beam, int _n_slices, int _n_sigma = 0, double cut_left = 0, double cut_right = 0, cuts_unit_t cuts_unit = s, fit_t fit_option = normal, bool direct_slicing = false)
Definition at line 14 of file Slices.cpp.
References beam, bin_centers, bl_gauss, bp_gauss, cut_left, cut_right, cuts_unit, edges, fit_option, gaussian, n_macroparticles, n_sigma, n_slices, rfp, set_cuts(), and track().
 {
     beam = Beam;
     rfp = RfP;
     this->n_slices = n_slices;
     this->cut_left = cut_left;
     this->cut_right = cut_right;
     this->cuts_unit = cuts_unit;
     this->fit_option = fit_option;
     this->n_sigma = n_sigma;
     this->n_macroparticles.resize(n_slices, 0);
     this->edges.resize(n_slices + 1, 0.0);
     this->bin_centers.resize(n_slices, 0.0);
     set_cuts();
     if (fit_option == gaussian) {
         bl_gauss = 0.0;
         bp_gauss = 0.0;
     }
     if (direct_slicing) track();
 }
Slices::~Slices ()
Definition at line 40 of file Slices.cpp.
References fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
void Slices::beam_profile_derivative (f_vector_t & x, f_vector_t & derivative, std::string mode = "gradient")
Definition at line 371 of file Slices.cpp.
References bin_centers, gaussian_filter1d(), gradient(), mymath::interp(), and n_macroparticles.
Referenced by plot_beam_profile_derivative().
 {
     /*
     The input is one of the two available methods for differentiating
     a function. The two outputs are the coordinate step and the discrete
     derivative of the Beam profile respectively.
     */
     x = bin_centers;
     const auto dist_centers = x[1] - x[0];
     if (mode == "filter1d") {
         derivative = gaussian_filter1d(n_macroparticles, 1, 1, "wrap");
         for (auto &d : derivative) d /= dist_centers;
     } else if (mode == "gradient") {
         derivative = gradient(n_macroparticles, dist_centers);
     } else if (mode == "diff") {
         derivative.resize(n_macroparticles.size() - 1);
         for (uint i = 1; i < n_macroparticles.size(); i++)
             derivative[i - 1] = (n_macroparticles[i] - n_macroparticles[i - 1])
                                 / dist_centers;
         f_vector_t diffCenters(x.begin(), x.end() - 1);
         diffCenters += dist_centers / 2.;
         derivative = mymath::interp(x, diffCenters, derivative);
     } else {
         std::cerr << "Option for derivative is not recognized.\n";
         exit(-1);
     }
 }
void Slices::beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int & nCoefficients, f_vector_t & b, f_vector_t & a)
Definition at line 444 of file Slices.cpp.
References bin_centers, python::convert_dictionary(), python::convert_double(), python::convert_double_array(), python::convert_int(), python::import(), n_macroparticles, and n_slices.
 {
     python::import();
     auto pFunc = python::import("utilities", "beam_profile_filter_chebyshev");
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pResolution = python::convert_double(bin_centers[1] - bin_centers[0]);
     auto pNSlices = python::convert_int(n_slices);
     if (filter_option.find("transfer_function_plot") != filter_option.end()
             && filter_option["transfer_function_plot"] == "true") {
         std::cerr << "[beam_profile_filter_chebyshev] A complex vector must\n"
                   << "be pased as the last argument in order to call this\n"
                   << "function with transfer_function_plot ==true\n";
         exit(-1);
     }
     auto pFilterOption = python::convert_dictionary(filter_option);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pNMacroparticles,
                                             pResolution, pNSlices,
                                             pFilterOption, NULL);
     if (!ret) {
         std::cerr << "[beam_profile_filter_chebyshev] An error occured "
                   << "while running a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     nCoefficients = res[0];
     assert(len == 3 + 2 * nCoefficients);
     b = f_vector_t(&res[1], &res[1 + 1 + nCoefficients]);
     a = f_vector_t(&res[2 + nCoefficients], &res[3 + 2 * nCoefficients]);
 }
void Slices::beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int & nCoefficients, f_vector_t & transferFreq, complex_vector_t & transferGain)
Definition at line 488 of file Slices.cpp.
References bin_centers, python::convert_dictionary(), python::convert_double(), python::convert_double_array(), python::convert_int(), python::import(), n_macroparticles, and n_slices.
 {
     python::import();
     auto pFunc = python::import("utilities", "beam_profile_filter_chebyshev");
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pResolution = python::convert_double(bin_centers[1] - bin_centers[0]);
     auto pNSlices = python::convert_int(n_slices);
     if (filter_option.find("transfer_function_plot") == filter_option.end()
             || filter_option["transfer_function_plot"] != "true") {
         std::cerr << "[beam_profile_filter_chebyshev] A double vector must\n"
                   << "be pased as the last argument in order to call this\n"
                   << "function without transfer_function_plot == true\n";
         exit(-1);
     }
     auto pFilterOption = python::convert_dictionary(filter_option);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pNMacroparticles,
                                             pResolution, pNSlices,
                                             pFilterOption, NULL);
     if (!ret) {
         std::cerr << "[beam_profile_filter_chebyshev] An error occured "
                   << "while running a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     assert(len == 1 + 3 * n_slices);
     nCoefficients = res[0];
     transferFreq = f_vector_t(&res[1], &res[1 + n_slices]);
     for (int i = 1 + n_slices; i < 1 + 2 * n_slices; i++) {
         transferGain.push_back({res[i], res[i + n_slices]});
     }
 }
void Slices::beam_spectrum_generation (int n, bool onlyRFFT = false)
Definition at line 360 of file Slices.cpp.
References bin_centers, fBeamSpectrum, fBeamSpectrumFreq, n_macroparticles, Context::n_threads, fft::rfft(), and fft::rfftfreq().
Referenced by InducedVoltageFreq::induced_voltage_generation(), and InducedVoltageFreq::reprocess().
 {
     fBeamSpectrumFreq = fft::rfftfreq(n, bin_centers[1] - bin_centers[0]);
     if (onlyRFFT == false) {
         auto v = n_macroparticles;
         fft::rfft(v, fBeamSpectrum, n, Context::n_threads);
     }
 }
double Slices::convert_coordinates (double cut, cuts_unit_t type)
Definition at line 107 of file Slices.cpp.
References RfParameters::counter, RfParameters::omega_rf, rfp, and s.
Referenced by set_cuts().
 {
     /*
     *Method to convert a value from one input_unit_type to 's'.*
     */
     if (type == s)
         return cut;
     else  /*if (type == rad)*/
         return cut / rfp->omega_rf[0][rfp->counter];
 }
void Slices::fwhm (const double shift = 0)
Definition at line 285 of file Slices.cpp.
References ALL, bin_centers, bl_fwhm, bp_fwhm, cfwhm, mymath::max(), n_macroparticles, and n_slices.
 {
     /*
     * Computation of the bunch length and position from the FWHM
     assuming Gaussian line density.*
     */
     int max = *std::max_element(ALL(n_macroparticles));
     double half_max = shift + 0.5 * (max - shift);
     double timeResolution = bin_centers[1] - bin_centers[0];
     // First aproximation for the half maximum values
     int taux1, taux2;
     int i = 0;
     while (i < n_slices && n_macroparticles[i] < half_max) i++;
     taux1 = i;
     // prev1 is one before taux1, if taux1 is 0, then prev1 is the last
     int prev1 = taux1 > 0 ? taux1 - 1 : n_slices - 1;
     i = n_slices - 1;
     while (i >= 0 && n_macroparticles[i] < half_max) i--;
     taux2 = i;
     // dprintf("taux1, taux2 = %d, %d\n", taux1, taux2);
     double t1, t2;
     if (taux1 < n_slices && taux2 < n_slices - 1 && taux2 >= 0) {
         t1 = bin_centers[taux1] -
              (n_macroparticles[taux1] - half_max) /
              (n_macroparticles[taux1] - n_macroparticles[prev1]) *
              timeResolution;
         t2 = bin_centers[taux2] +
              (n_macroparticles[taux2] - half_max) /
              (n_macroparticles[taux2] - n_macroparticles[taux2 + 1]) *
              timeResolution;
         bl_fwhm = 4 * (t2 - t1) / cfwhm;
         bp_fwhm = (t1 + t2) / 2;
     } else {
         bl_fwhm = nan("");
         bp_fwhm = nan("");
     }
 }
void Slices::fwhm_multibunch ()
Definition at line 358 of file Slices.cpp.
 {}
f_vector_t Slices::gaussian_filter1d (f_vector_t & x, int sigma, int order, std::string mode) private
Definition at line 406 of file Slices.cpp.
References python::convert_double_array(), python::convert_int(), python::convert_string(), and python::import().
Referenced by beam_profile_derivative().
 {
     python::import();
     auto pFunc = python::import("utilities", "gaussian_filter1d");
     auto pX = python::convert_double_array(x.data(), x.size());
     auto pSigma = python::convert_int(sigma);
     auto pOrder = python::convert_int(order);
     auto pMode = python::convert_string(mode);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pSigma, pOrder, pMode,
                                             NULL);
     assert(ret);
     auto npArray = (PyArrayObject *)(ret);
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     return f_vector_t(&res[0], &res[len]);
 }
void Slices::gaussian_fit ()
Definition at line 533 of file Slices.cpp.
References ALL, beam, bin_centers, bl_gauss, bp_gauss, python::convert_double_array(), Beams::dt, python::import(), mymath::max(), mymath::mean(), n_macroparticles, and mymath::standard_deviation().
Referenced by track().
 {
     f_vector_t p0;
     double max = *std::max_element(ALL(n_macroparticles));
     if (bl_gauss == 0 && bp_gauss == 0) {
         p0 = {max,
               mymath::mean(beam->dt),
               mymath::standard_deviation(beam->dt)
              };
     } else {
         p0 = {max,
               bp_gauss,
               bl_gauss / 4
              };
     }
     python::import();
     auto pFunc = python::import("utilities", "curve_fit");
     auto pBinCenters = python::convert_double_array(bin_centers.data(),
                        bin_centers.size());
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pP0 = python::convert_double_array(p0.data(), p0.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBinCenters,
                                             pNMacroparticles, pP0, NULL);
     if (!ret) {
         std::cerr << "[gaussian_fit] An error occured while running"
                   << "a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *pfit_gauss = (double *) PyArray_DATA(npArray);
     bl_gauss = 4 * std::abs(pfit_gauss[2]);
     bp_gauss = std::abs(pfit_gauss[1]);
 }
f_vector_t Slices::gradient (f_vector_t & x, double dist) private
Definition at line 426 of file Slices.cpp.
References python::convert_double(), python::convert_double_array(), and python::import().
Referenced by beam_profile_derivative().
 {
     python::import();
     auto pFunc = python::import("utilities", "gradient");
     auto pX = python::convert_double_array(x.data(), x.size());
     auto pDist = python::convert_double(dist);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pDist, NULL);
     assert(ret);
     auto npArray = (PyArrayObject *)(ret);
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     return f_vector_t(&res[0], &res[len]);
 }
void Slices::histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
Definition at line 142 of file Slices.cpp.
References cut_left, mymath::min(), n_slices, omp_get_num_threads(), and omp_get_thread_num().
Referenced by slice_constant_space_histogram().
 {
     const double inv_bin_width = n_slices / (cut_right - cut_left);
     // histogram is faster with ints
     typedef double hist_t;
     hist_t *h;
     #pragma omp parallel
     {
         const int threads = omp_get_num_threads();
         const int id = omp_get_thread_num();
         int tile = (n_macroparticles + threads - 1) / threads;
         int start = id * tile;
         int end = std::min(start + tile, n_macroparticles);
         const int row = id * n_slices;
         #pragma omp single
         h = (hist_t *)calloc(threads * n_slices, sizeof(hist_t));
         hist_t *h_row = &h[row];
         for (int i = start; i < end; ++i) {
             const double a = input[i];
             if (a < cut_left || a > cut_right) continue;
             const int ffbin = (int)((a - cut_left) * inv_bin_width);
             h_row[ffbin]++;
         }
         #pragma omp barrier
         tile = (n_slices + threads - 1) / threads;
         start = id * tile;
         end = std::min(start + tile, n_slices);
         for (int i = start; i < end; i++)
             output[i] = 0;
         // memset(&output[start], 0, (end-start) * sizeof(double));
         for (int i = 0; i < threads; ++i) {
             const int r = i * n_slices;
             for (int j = start; j < end; ++j) {
                 output[j] += h[r + j];
             }
         }
     }
     if (h) free(h);
 }
void Slices::rms ()
Definition at line 264 of file Slices.cpp.
References apply_f(), bin_centers, bl_rms, bp_rms, n_macroparticles, and mymath::trapezoid().
 {
     /*
     * Computation of the RMS bunch length and position from the line density
     (bunch length = 4sigma).*
     */
     const auto timeResolution = bin_centers[1] - bin_centers[0];
     const auto trap = mymath::trapezoid(n_macroparticles, timeResolution);
     auto lineDen = n_macroparticles / trap;
     bp_rms = mymath::trapezoid(bin_centers * lineDen, timeResolution);
     auto temp = mymath::trapezoid(
                     apply_f(bin_centers - bp_rms,
     [](double x) {return x * x; }) * lineDen, timeResolution);
     bl_rms = 4 * std::sqrt(temp);
 }
void Slices::set_cuts ()
Definition at line 42 of file Slices.cpp.
References beam, bin_centers, convert_coordinates(), cut_left, cut_right, cuts_unit, Beams::dt, edges, mymath::linspace(), mymath::mean(), n_sigma, n_slices, sort_particles(), and mymath::standard_deviation().
Referenced by Slices().
 {
     /*
     *Method to set the self.cut_left and self.cut_right properties. This is
     done as a pre-processing if the mode is set to 'const_space', for
     'const_charge' this is calculated each turn.*
     *The frame is defined by :math:`n\sigma_{RMS}` or manually by the user.
     If not, a default frame consisting of taking the whole bunch +5% of the
     maximum distance between two particles in the bunch will be taken
     in each side of the frame.*
     */
     if (cut_left == 0 && cut_right == 0) {
         if (n_sigma == 0) {
             sort_particles();
             cut_left =
                 beam->dt.front() - 0.05 * (beam->dt.back() - beam->dt.front());
             cut_right =
                 beam->dt.back() + 0.05 * (beam->dt.back() - beam->dt.front());
         } else {
             double mean_coords = mymath::mean(beam->dt.data(), beam->dt.size());
             double sigma_coords = mymath::standard_deviation(
                                       beam->dt.data(), beam->dt.size(), mean_coords);
             cut_left = mean_coords - n_sigma * sigma_coords / 2;
             cut_right = mean_coords + n_sigma * sigma_coords / 2;
         }
     } else {
         cut_left = convert_coordinates(cut_left, cuts_unit);
         cut_right = convert_coordinates(cut_right, cuts_unit);
     }
     mymath::linspace(edges.data(), cut_left, cut_right, n_slices + 1);
     for (uint i = 0; i < bin_centers.size(); ++i)
         bin_centers[i] = (edges[i + 1] + edges[i]) / 2;
 }
void Slices::slice_constant_space_histogram ()
Definition at line 127 of file Slices.cpp.
References beam, cut_left, cut_right, Beams::dt, histogram(), Beams::n_macroparticles, n_macroparticles, and n_slices.
Referenced by track().
 {
     /*
     *Constant space slicing with the built-in numpy histogram function,
     with a constant frame. This gives the same profile as the
     slice_constant_space method, but no compute statistics possibilities
     (the index of the particles is needed).*
     *This method is faster than the classic slice_constant_space method
     for high number of particles (~1e6).*
     */
     histogram(beam->dt.data(), n_macroparticles.data(), cut_left, cut_right,
               n_slices, beam->n_macroparticles);
 }
void Slices::slice_constant_space_histogram_smooth ()
Definition at line 255 of file Slices.cpp.
References beam, cut_left, cut_right, Beams::dt, Beams::n_macroparticles, n_macroparticles, n_slices, and smooth_histogram().
 {
     /*
     At the moment 4x slower than slice_constant_space_histogram but smoother.
     */
     smooth_histogram(beam->dt.data(), n_macroparticles.data(), cut_left,
                      cut_right, n_slices, beam->n_macroparticles);
 }
void Slices::smooth_histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
Definition at line 211 of file Slices.cpp.
References cut_left, n_macroparticles, and n_slices.
Referenced by slice_constant_space_histogram_smooth().
 {
     int i;
     double a;
     double fbin;
     double ratioffbin;
     double ratiofffbin;
     double distToCenter;
     int ffbin = 0;
     int fffbin = 0;
     const double inv_bin_width = n_slices / (cut_right - cut_left);
     const double bin_width = (cut_right - cut_left) / n_slices;
     for (i = 0; i < n_slices; i++) {
         output[i] = 0;
     }
     for (i = 0; i < n_macroparticles; i++) {
         a = input[i];
         if ((a < (cut_left + bin_width * 0.5)) ||
                 (a > (cut_right - bin_width * 0.5)))
             continue;
         fbin = (a - cut_left) * inv_bin_width;
         ffbin = (int)(fbin);
         distToCenter = fbin - (double)(ffbin);
         if (distToCenter > 0.5)
             fffbin = (int)(fbin + 1.0);
         ratioffbin = 1.5 - distToCenter;
         ratiofffbin = 1 - ratioffbin;
         if (distToCenter < 0.5)
             fffbin = (int)(fbin - 1.0);
         ratioffbin = 0.5 - distToCenter;
         ratiofffbin = 1 - ratioffbin;
         output[ffbin] = output[ffbin] + ratioffbin;
         output[fffbin] = output[fffbin] + ratiofffbin;
     }
 }
void Slices::sort_particles ()
Definition at line 78 of file Slices.cpp.
References API, beam, Beams::dE, Beams::dt, Beams::id, and operator<().
Referenced by set_cuts().
 {
     /*
     *Sort the particles with respect to their position.*
     */
     struct API particle {
         double dE;
         double dt;
         int id;
         bool operator<(const particle &other) const
         {
             return dt < other.dt;
         }
     };
     std::vector<particle> particles(beam->dE.size());
     for (uint i = 0; i < particles.size(); i++)
         particles[i] = {beam->dE[i], beam->dt[i], beam->id[i]};
     std::sort(particles.begin(), particles.end());
     for (uint i = 0; i < particles.size(); i++) {
         beam->dE[i] = particles[i].dE;
         beam->dt[i] = particles[i].dt;
         beam->id[i] = particles[i].id;
     }
 }
void Slices::track ()
Definition at line 120 of file Slices.cpp.
References fit_option, gaussian_fit(), and slice_constant_space_histogram().
Referenced by Slices().
 {
     slice_constant_space_histogram();
     if (fit_option == fit_t::gaussian)
         gaussian_fit();
 }
void Slices::track_cuts ()
Definition at line 195 of file Slices.cpp.
References beam, bin_centers, cut_left, cut_right, edges, and Beams::mean_dt.
 {
     /*
     *Track the slice frame (limits and slice position) as the mean of the
     bunch moves.
     Requires Beam statistics!
     Method to be refined!*
     */
     double delta = beam->mean_dt - 0.5 * (cut_left + cut_right);
     cut_left += delta;
     cut_right += delta;
     edges += delta;
     bin_centers += delta;
 }
Member Data Documentation
Beams* Slices::beam
Definition at line 32 of file Slices.h.
Referenced by gaussian_fit(), set_cuts(), slice_constant_space_histogram(), slice_constant_space_histogram_smooth(), Slices(), sort_particles(), and track_cuts().
f_vector_t Slices::bin_centers
Definition at line 44 of file Slices.h.
Referenced by beam_profile_derivative(), beam_profile_filter_chebyshev(), beam_spectrum_generation(), fwhm(), LHCNoiseFB::fwhm_interpolation(), gaussian_fit(), InducedVoltageFreq::InducedVoltageFreq(), InducedVoltageTime::InducedVoltageTime(), plot_beam_profile(), plot_induced_voltage_vs_bin_centers(), InducedVoltageTime::reprocess(), InducedVoltageFreq::reprocess(), RingAndRfSection::rf_voltage_calculation(), rms(), set_cuts(), Slices(), TotalInducedVoltage::TotalInducedVoltage(), InducedVoltageTime::track(), InducedVoltageFreq::track(), TotalInducedVoltage::track(), and track_cuts().
double Slices::bl_fwhm
Definition at line 35 of file Slices.h.
Referenced by fwhm().
double Slices::bl_gauss
Definition at line 48 of file Slices.h.
Referenced by gaussian_fit(), and Slices().
double Slices::bl_rms
Definition at line 36 of file Slices.h.
Referenced by rms().
double Slices::bp_fwhm
Definition at line 35 of file Slices.h.
Referenced by fwhm().
double Slices::bp_gauss
Definition at line 49 of file Slices.h.
Referenced by gaussian_fit(), and Slices().
double Slices::bp_rms
Definition at line 36 of file Slices.h.
Referenced by rms().
double Slices::cut_left
Definition at line 38 of file Slices.h.
Referenced by histogram(), set_cuts(), slice_constant_space_histogram(), slice_constant_space_histogram_smooth(), Slices(), smooth_histogram(), and track_cuts().
double Slices::cut_right
Definition at line 39 of file Slices.h.
Referenced by set_cuts(), slice_constant_space_histogram(), slice_constant_space_histogram_smooth(), Slices(), and track_cuts().
cuts_unit_t Slices::cuts_unit
Definition at line 41 of file Slices.h.
Referenced by set_cuts(), and Slices().
f_vector_t Slices::edges
Definition at line 43 of file Slices.h.
Referenced by InducedVoltageFreq::InducedVoltageFreq(), set_cuts(), Slices(), and track_cuts().
complex_vector_t Slices::fBeamSpectrum
Definition at line 46 of file Slices.h.
Referenced by beam_spectrum_generation(), InducedVoltageFreq::induced_voltage_generation(), plot_beam_spectrum(), and plot_impedance_vs_frequency().
f_vector_t Slices::fBeamSpectrumFreq
Definition at line 47 of file Slices.h.
Referenced by beam_spectrum_generation(), InducedVoltageFreq::induced_voltage_generation(), plot_beam_spectrum(), plot_impedance_vs_frequency(), and InducedVoltageFreq::reprocess().
fit_t Slices::fit_option
Definition at line 45 of file Slices.h.
Referenced by Slices(), and track().
f_vector_t Slices::n_macroparticles
Definition at line 42 of file Slices.h.
Referenced by beam_profile_derivative(), beam_profile_filter_chebyshev(), beam_spectrum_generation(), fwhm(), gaussian_fit(), InducedVoltageTime::induced_voltage_generation(), matched_from_line_density(), plot_beam_profile(), rms(), slice_constant_space_histogram(), slice_constant_space_histogram_smooth(), Slices(), and smooth_histogram().
int Slices::n_sigma
Definition at line 40 of file Slices.h.
Referenced by set_cuts(), and Slices().
int Slices::n_slices
Definition at line 37 of file Slices.h.
Referenced by beam_profile_filter_chebyshev(), fwhm(), histogram(), InducedVoltageTime::induced_voltage_generation(), InducedVoltageFreq::induced_voltage_generation(), InducedVoltageFreq::InducedVoltageFreq(), InducedVoltageTime::InducedVoltageTime(), InducedVoltageTime::reprocess(), InducedVoltageFreq::reprocess(), set_cuts(), slice_constant_space_histogram(), slice_constant_space_histogram_smooth(), Slices(), smooth_histogram(), InducedVoltageTime::track(), InducedVoltageFreq::track(), and TotalInducedVoltage::track().
RfParameters* Slices::rfp
Definition at line 33 of file Slices.h.
Referenced by convert_coordinates(), matched_from_line_density(), and Slices().