Beam Longitudinal Dynamics code (BLonD): blond::LHC_F Class Reference
blond::LHC_F Class Reference
#include <PhaseLoop.h>
Public Member Functions
LHC_F (double PL_gain, double window_coefficient=0, double FL_gain=0, PhaseNoise *phaseNoise=NULL, LHCNoiseFB *LHCNoiseFB=NULL, uint delay=0)
~LHC_F ()
void track ()
Public Member Functions inherited from blond::PhaseLoop
PhaseLoop (f_vector_t PL_gain, double window_coefficient, uint _delay, PhaseNoise *phaseNoise, LHCNoiseFB *LHCNoiseFB)
PhaseLoop ()
virtual ~PhaseLoop ()
void beam_phase ()
void default_track ()
void phase_difference ()
void radial_difference ()
void radial_steering_from_freq ()
Public Attributes
double gain
double gain2
Public Attributes inherited from blond::PhaseLoop
double alpha = 0
uint delay = 0
double domega_rf = 0
double dphi = 0
double drho = 0
LHCNoiseFB * noiseFB
double phi_beam = 0
double reference = 0
PhaseNoise * RFnoise
Detailed Description
Definition at line 84 of file PhaseLoop.h.
Constructor & Destructor Documentation
LHC_F::LHC_F (double PL_gain, double window_coefficient = 0, double FL_gain = 0, PhaseNoise * phaseNoise = NULL, LHCNoiseFB * LHCNoiseFB = NULL, uint delay = 0)
Definition at line 412 of file PhaseLoop.cpp.
References blond::PhaseLoop::alpha, blond::PhaseLoop::delay, gain, gain2, blond::PhaseLoop::noiseFB, and blond::PhaseLoop::RFnoise.
 {
     this->gain = PL_gain;
     this->alpha = window_coefficient;
     this->delay = delay;
     this->RFnoise = phaseNoise;
     this->noiseFB = LHCNoiseFB;
     this->gain2 = FL_gain;
     // domega_RF.resize(gain.size());
 }
LHC_F::~LHC_F ()
Definition at line 424 of file PhaseLoop.cpp.
 {}
Member Function Documentation
void LHC_F::track () virtual
Reimplemented from blond::PhaseLoop.
Definition at line 426 of file PhaseLoop.cpp.
References blond::PhaseLoop::beam_phase(), blond::RfParameters::counter, blond::PhaseLoop::default_track(), blond::PhaseLoop::domega_rf, blond::PhaseLoop::dphi, gain, gain2, blond::PhaseLoop::phase_difference(), blond::PhaseLoop::reference, and blond::Context::RfP.
 {
     auto RfP = Context::RfP;
     uint counter = RfP->counter;
     beam_phase();
     phase_difference();
     // Frequency correction from phase loop and frequency loop
     const auto factor =
         RfP->omega_rf[0][counter] - RfP->omega_rf_d[0][counter] + reference;
     // for (int i = 0; i < (int)gain.size(); ++i) {
     domega_rf = -gain * dphi - gain2 * factor;
     // }
     default_track();
 }
Member Data Documentation
double blond::LHC_F::gain
Definition at line 89 of file PhaseLoop.h.
Referenced by LHC_F(), and track().
double blond::LHC_F::gain2
Definition at line 87 of file PhaseLoop.h.
Referenced by LHC_F(), and track().