Beam Longitudinal Dynamics code (BLonD): blond::optionparser::PrintUsageImplementation::LinePartIterator Class Reference
blond::optionparser::PrintUsageImplementation::LinePartIterator Class Reference
#include <optionparser.h>
Public Member Functions
LinePartIterator (const Descriptor usage[])
Creates an iterator for usage.
int column ()
Returns the index (counting from 0) of the column in which the part pointed to by data() is located.
const char * data ()
Returns the current part of the iteration.
int length ()
Returns the length of the part pointed to by data() in raw chars (not UTF-8 characters).
int line ()
Returns the index (counting from 0) of the line within the current column this part belongs to.
bool next ()
Moves iteration to the next part (if any). Has to be called once after each call to nextRow() to move to the 1st part of the row.
bool nextRow ()
Moves iteration to the next row (if any). Has to be called once after each call to nextTable() to move to the 1st row of the table.
bool nextTable ()
Moves iteration to the next table (if any). Has to be called once on a new LinePartIterator to move to the 1st table.
void restartRow ()
Reset iteration to the beginning of the current row.
void restartTable ()
Reset iteration to the beginning of the current table.
int screenLength ()
Returns the width in screen columns of the part pointed to by data(). Takes multi-byte UTF-8 sequences and wide characters into account.
Private Member Functions
void update_length ()
Determines the byte and character lengths of the part at ptr and stores them in len and screenlen respectively.
Private Attributes
int col
Index of current column.
bool hit_target_line
                           Flag whether we encountered a part with
line index target_line_in_block in the current cell.
int len
              Length of the current part (that ptr points at) in
BYTES
int line_in_block
                        Line index within the current cell of the
current part.
int max_line_in_block
                            Greatest index of a line within the
block. This is the number of \v within the cell with the most \vs.
const char * ptr
Ptr to current part within the current row.
const Descriptor * rowdesc
The Descriptor that contains the current row.
const char * rowstart
                          Ptr to 1st character of current row
within rowdesc->help.
int screenlen
                     Length of the current part in screen columns
(taking narrow/wide chars into account).
const Descriptor * tablestart
The 1st descriptor of the current table.
int target_line_in_block
                               Line index of the parts we should
return to the user on this iteration.
Detailed Description
Definition at line 2178 of file optionparser.h.
Constructor & Destructor Documentation
blond::optionparser::PrintUsageImplementation::LinePartIterator::LinePartIterator (const Descriptor usage[]) inline
Creates an iterator for usage.
Definition at line 2243 of file optionparser.h.
                     : tablestart(usage), rowdesc(0), rowstart(0), ptr(0), col(-1),
                       len(0), max_line_in_block(0), line_in_block(0),
                       target_line_in_block(0), hit_target_line(true) {}
Member Function Documentation
int blond::optionparser::PrintUsageImplementation::LinePartIterator::column () inline
Returns the index (counting from 0) of the column in which the part pointed to by data() is located.
Definition at line 2408 of file optionparser.h.
References col.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
 { return col; }
const char* blond::optionparser::PrintUsageImplementation::LinePartIterator::data () inline
Returns the current part of the iteration.
Definition at line 2438 of file optionparser.h.
References ptr.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
 { return ptr; }
int blond::optionparser::PrintUsageImplementation::LinePartIterator::length () inline
Returns the length of the part pointed to by data() in raw chars (not UTF-8 characters).
Definition at line 2425 of file optionparser.h.
References len.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
 { return len; }
int blond::optionparser::PrintUsageImplementation::LinePartIterator::line () inline
Returns the index (counting from 0) of the line within the current column this part belongs to.
Definition at line 2415 of file optionparser.h.
References target_line_in_block.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     return target_line_in_block; // NOT line_in_block !!! It would
                     // be wrong if !hit_target_line
                 }
bool blond::optionparser::PrintUsageImplementation::LinePartIterator::next () inline
Moves iteration to the next part (if any). Has to be called once after each call to nextRow() to move to the 1st part of the row.
Return values
false if moving to next part failed because no further part exists.
See LinePartIterator for details about the iteration.
Definition at line 2339 of file optionparser.h.
References col, hit_target_line, len, line_in_block, max_line_in_block, ptr, rowstart, target_line_in_block, update_length(), and blond::optionparser::PrintUsageImplementation::upmax().
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     if (ptr == 0)
                         return false;
                     if (col == -1) {
                         col = 0;
                         update_length();
                         return true;
                     }
                     ptr += len;
                     while (true) {
                         switch (*ptr) {
                             case '\v':
                                 upmax(max_line_in_block, ++line_in_block);
                                 ++ptr;
                                 break;
                             case '\t':
                                 if (!hit_target_line) { // if previous column did not
                                     // have the targetline
                                     // then "insert" a 0-length part
                                     update_length();
                                     hit_target_line = true;
                                     return true;
                                 }
                                 hit_target_line = false;
                                 line_in_block = 0;
                                 ++col;
                                 ++ptr;
                                 break;
                             case 0:
                             case '\n':
                                 if (!hit_target_line) { // if previous column did not
                                     // have the targetline
                                     // then "insert" a 0-length part
                                     update_length();
                                     hit_target_line = true;
                                     return true;
                                 }
                                 if (++target_line_in_block > max_line_in_block) {
                                     update_length();
                                     return false;
                                 }
                                 hit_target_line = false;
                                 line_in_block = 0;
                                 col = 0;
                                 ptr = rowstart;
                                 continue;
                             default:
                                 ++ptr;
                                 continue;
                         } // switch
                         if (line_in_block == target_line_in_block) {
                             update_length();
                             hit_target_line = true;
                             return true;
                         }
                     } // while
                 }
bool blond::optionparser::PrintUsageImplementation::LinePartIterator::nextRow () inline
Moves iteration to the next row (if any). Has to be called once after each call to nextTable() to move to the 1st row of the table.
Return values
false if moving to next row failed because no further row exists.
Definition at line 2291 of file optionparser.h.
References blond::optionparser::Descriptor::help, ptr, restartRow(), rowdesc, and rowstart.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     if (ptr == 0) {
                         restartRow();
                         return rowstart != 0;
                     }
                     while (*ptr != 0 && *ptr != '\n')
                         ++ptr;
                     if (*ptr == 0) {
                         if ((rowdesc + 1)->help == 0) // table break
                             return false;
                         ++rowdesc;
                         rowstart = rowdesc->help;
                     } else { // if (*ptr == '\n')
                         rowstart = ptr + 1;
                     }
                     restartRow();
                     return true;
                 }
bool blond::optionparser::PrintUsageImplementation::LinePartIterator::nextTable () inline
Moves iteration to the next table (if any). Has to be called once on a new LinePartIterator to move to the 1st table.
Return values
false if moving to next table failed because no further table exists.
Definition at line 2255 of file optionparser.h.
References blond::optionparser::Descriptor::help, restartTable(), rowdesc, rowstart, blond::optionparser::Descriptor::shortopt, and tablestart.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     // If this is NOT the first time nextTable() is called after the
                     // constructor,
                     // then skip to the next table break (i.e. a Descriptor with
                     // help == 0)
                     if (rowdesc != 0) {
                         while (tablestart->help != 0 && tablestart->shortopt != 0)
                             ++tablestart;
                     }
                     // Find the next table after the break (if any)
                     while (tablestart->help == 0 && tablestart->shortopt != 0)
                         ++tablestart;
                     restartTable();
                     return rowstart != 0;
                 }
void blond::optionparser::PrintUsageImplementation::LinePartIterator::restartRow () inline
Reset iteration to the beginning of the current row.
Definition at line 2318 of file optionparser.h.
References col, hit_target_line, len, line_in_block, max_line_in_block, ptr, rowstart, screenlen, and target_line_in_block.
Referenced by nextRow(), and blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     ptr = rowstart;
                     col = -1;
                     len = 0;
                     screenlen = 0;
                     max_line_in_block = 0;
                     line_in_block = 0;
                     target_line_in_block = 0;
                     hit_target_line = true;
                 }
void blond::optionparser::PrintUsageImplementation::LinePartIterator::restartTable () inline
Reset iteration to the beginning of the current table.
Definition at line 2277 of file optionparser.h.
References blond::optionparser::Descriptor::help, ptr, rowdesc, rowstart, and tablestart.
Referenced by nextTable(), and blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     rowdesc = tablestart;
                     rowstart = tablestart->help;
                     ptr = 0;
                 }
int blond::optionparser::PrintUsageImplementation::LinePartIterator::screenLength () inline
Returns the width in screen columns of the part pointed to by data(). Takes multi-byte UTF-8 sequences and wide characters into account.
Definition at line 2433 of file optionparser.h.
References screenlen.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
 { return screenlen; }
void blond::optionparser::PrintUsageImplementation::LinePartIterator::update_length () inline private
Determines the byte and character lengths of the part at ptr and stores them in len and screenlen respectively.
Definition at line 2207 of file optionparser.h.
References blond::optionparser::PrintUsageImplementation::isWideChar(), len, ptr, and screenlen.
Referenced by next().
                 {
                     screenlen = 0;
                     for (len = 0; ptr[len] != 0 && ptr[len] != '\v' &&
                             ptr[len] != '\t' && ptr[len] != '\n';
                             ++len) {
                         ++screenlen;
                         unsigned ch = (unsigned char)ptr[len];
                         if (ch > 0xC1) { // everything <= 0xC1 (yes, even 0xC1
                             // itself) is not a valid UTF-8 start byte
                             // int __builtin_clz (unsigned int x)
                             // Returns the number of leading 0-bits in x, starting
                             // at the most significant bit
                             unsigned mask =
                                 (unsigned) - 1 >> __builtin_clz(ch ^ 0xff);
                             ch = ch & mask; // mask out length bits, we don't verify
                             // their correctness
                             while (((unsigned char)ptr[len + 1] ^ 0x80) <=
                                     0x3F) { // while next byte is continuation byte
                                 ch = (ch << 6) ^ (unsigned char)ptr[len + 1] ^
                                      0x80; // add continuation to char code
                                 ++len;
                             }
                             // ch is the decoded unicode code point
                             if (ch >= 0x1100 && isWideChar(ch)) // the test for
                                 // 0x1100 is here to
                                 // avoid the
                                 // function call in
                                 // the Latin case
                                 ++screenlen;
                         }
                     }
                 }
Member Data Documentation
int blond::optionparser::PrintUsageImplementation::LinePartIterator::col private
Index of current column.
Definition at line 2186 of file optionparser.h.
Referenced by column(), next(), and restartRow().
bool blond::optionparser::PrintUsageImplementation::LinePartIterator::hit_target_line private
                           Flag whether we encountered a part with
line index target_line_in_block in the current cell.
Definition at line 2198 of file optionparser.h.
Referenced by next(), and restartRow().
int blond::optionparser::PrintUsageImplementation::LinePartIterator::len private
              Length of the current part (that ptr points at) in
BYTES
Definition at line 2187 of file optionparser.h.
Referenced by length(), next(), restartRow(), and update_length().
int blond::optionparser::PrintUsageImplementation::LinePartIterator::line_in_block private
                        Line index within the current cell of the
current part.
Definition at line 2194 of file optionparser.h.
Referenced by next(), and restartRow().
int blond::optionparser::PrintUsageImplementation::LinePartIterator::max_line_in_block private
                            Greatest index of a line within the
block. This is the number of \v within the cell with the most \vs.
Definition at line 2191 of file optionparser.h.
Referenced by next(), and restartRow().
const char* blond::optionparser::PrintUsageImplementation::LinePartIterator::ptr private
Ptr to current part within the current row.
Definition at line 2185 of file optionparser.h.
Referenced by data(), next(), nextRow(), restartRow(), restartTable(), and update_length().
const Descriptor* blond::optionparser::PrintUsageImplementation::LinePartIterator::rowdesc private
The Descriptor that contains the current row.
Definition at line 2182 of file optionparser.h.
Referenced by nextRow(), nextTable(), and restartTable().
const char* blond::optionparser::PrintUsageImplementation::LinePartIterator::rowstart private
                          Ptr to 1st character of current row
within rowdesc->help.
Definition at line 2183 of file optionparser.h.
Referenced by next(), nextRow(), nextTable(), restartRow(), and restartTable().
int blond::optionparser::PrintUsageImplementation::LinePartIterator::screenlen private
                     Length of the current part in screen columns
(taking narrow/wide chars into account).
Definition at line 2189 of file optionparser.h.
Referenced by restartRow(), screenLength(), and update_length().
const Descriptor* blond::optionparser::PrintUsageImplementation::LinePartIterator::tablestart private
The 1st descriptor of the current table.
Definition at line 2180 of file optionparser.h.
Referenced by nextTable(), and restartTable().
int blond::optionparser::PrintUsageImplementation::LinePartIterator::target_line_in_block private
                               Line index of the parts we should
return to the user on this iteration.
Definition at line 2196 of file optionparser.h.
Referenced by line(), next(), and restartRow().