Beam Longitudinal Dynamics code (BLonD): vdt::details Namespace Reference
vdt::details Namespace Reference
Classes
union ieee754
Used to switch between different type of interpretations of the data (64 bits)
Functions
uint64_t dp2uint64 (double x)
Converts a double to an unsigned long long long.
double dpANDuint64 (const double x, const uint64_t i)
Makes an AND of a double and a unsigned long long long.
double dpORuint64 (const double x, const uint64_t i)
Makes an OR of a double and a unsigned long long long.
double dpXORuint64 (const double x, const uint64_t i)
Makes a XOR of a double and a unsigned long long long.
void fast_sincos_m45_45 (const double z, double &s, double &c)
Sincos only for -45deg < x < 45deg.
void fast_sincosf_m45_45 (const float x, float &s, float &c)
Sincos only for -45deg < x < 45deg.
uint32_t fp2uint (float x)
Converts a fp to an int.
uint64_t fp2uint (double x)
Converts a fp to an int.
double fpfloor (const double x)
float fpfloor (const float x)
double get_cos_px (const double x)
double get_sin_px (const double x)
double getMantExponent (const double x, double &fe)
Like frexp but vectorising and the exponent is a double.
float getMantExponentf (const float x, float &fe)
Like frexp but vectorising and the exponent is a float.
uint64_t getSignMask (const double x)
uint32_t getSignMask (const float x)
Get the sign mask.
float int2fp (uint32_t i)
Converts an int to fp.
double int2fp (uint64_t i)
Converts an int to fp.
double reduce2quadrant (double x, int32_t &quad)
Reduce to 0 to 45.
float reduce2quadrant (float x, int &quad)
Reduce to 0 to 45.
uint32_t sp2uint32 (float x)
Converts a float to an int.
float spANDuint32 (const float x, const uint32_t i)
Makes an AND of a float and a unsigned long.
float spORuint32 (const float x, const uint32_t i)
Makes an OR of a float and a unsigned long.
float spXORuint32 (const float x, const uint32_t i)
Makes an OR of a float and a unsigned long.
float uint322sp (int x)
Converts an int to a float.
double uint642dp (uint64_t ll)
Converts an unsigned long long to a double.
Variables
const double C1cos = -1.13585365213876817300E-11
const float C1F = 0.693359375f
const double C1sin = 1.58962301576546568060E-10
const double C2cos = 2.08757008419747316778E-9
const float C2F = -2.12194440e-4f
const double C2sin = -2.50507477628578072866E-8
const double C3cos = -2.75573141792967388112E-7
const double C3sin = 2.75573136213857245213E-6
const double C4cos = 2.48015872888517045348E-5
const double C4sin = -1.98412698295895385996E-4
const double C5cos = -1.38888888888730564116E-3
const double C5sin = 8.33333333332211858878E-3
const double C6cos = 4.16666666666665929218E-2
const double C6sin = -1.66666666666666307295E-1
const double DP1 = 7.853981554508209228515625E-1
const float DP1F = 0.78515625
const double DP1sc = 7.85398125648498535156E-1
const double DP2 = 7.94662735614792836714E-9
const float DP2F = 2.4187564849853515625e-4
const double DP2sc = 3.77489470793079817668E-8
const double DP3 = 3.06161699786838294307E-17
const float DP3F = 3.77489497744594108e-8
const double DP3sc = 2.69515142907905952645E-15
const double EXP_LIMIT = 708
const double LOG2E = 1.4426950408889634073599
const float LOG2EF = 1.44269504088896341f
const float MAXLOGF = 88.72283905206835f
const float MAXNUMF = 3.4028234663852885981170418348451692544e38f
const float MINLOGF = -88.f
const double MOREBITS = 6.123233995736765886130E-17
const double ONEOPIO4 = 4. / M_PI
const float ONEOPIO4F = 4. / M_PI
const double PI = M_PI
const float PIF = M_PI
const double PIO2 = M_PI_2
const float PIO2F = M_PI_2
const double PIO4 = M_PI_4
const float PIO4F = M_PI_4
const double PX1exp = 1.26177193074810590878E-4
const float PX1expf = 1.9875691500E-4f
const double PX2exp = 3.02994407707441961300E-2
const float PX2expf = 1.3981999507E-3f
const double PX3exp = 9.99999999999999999910E-1
const float PX3expf = 8.3334519073E-3f
const float PX4expf = 4.1665795894E-2f
const float PX5expf = 1.6666665459E-1f
const float PX6expf = 5.0000001201E-1f
const double QX1exp = 3.00198505138664455042E-6
const double QX2exp = 2.52448340349684104192E-3
const double QX3exp = 2.27265548208155028766E-1
const double QX4exp = 2.00000000000000000009E0
const float T24M1 = 16777215.
const double TWOPI = 2. * M_PI
const float TWOPIF = 2. * M_PI
Function Documentation
uint64_t vdt::details::dp2uint64 (double x) inline
Converts a double to an unsigned long long long.
Definition at line 84 of file vdtcore_common.h.
References vdt::details::ieee754::d, and vdt::details::ieee754::ll.
Referenced by dpANDuint64(), dpORuint64(), dpXORuint64(), fp2uint(), getMantExponent(), and getSignMask().
{
             ieee754 tmp;
             tmp.d = x;
             return tmp.ll;
         }
double vdt::details::dpANDuint64 (const double x, const uint64_t i) inline
Makes an AND of a double and a unsigned long long long.
Definition at line 92 of file vdtcore_common.h.
References dp2uint64(), and uint642dp().
{
             return uint642dp(dp2uint64(x) & i);
         }
double vdt::details::dpORuint64 (const double x, const uint64_t i) inline
Makes an OR of a double and a unsigned long long long.
Definition at line 97 of file vdtcore_common.h.
References dp2uint64(), and uint642dp().
{
             return uint642dp(dp2uint64(x) | i);
         }
double vdt::details::dpXORuint64 (const double x, const uint64_t i) inline
Makes a XOR of a double and a unsigned long long long.
Definition at line 102 of file vdtcore_common.h.
References dp2uint64(), and uint642dp().
{
             return uint642dp(dp2uint64(x) ^ i);
         }
void vdt::details::fast_sincos_m45_45 (const double z, double & s, double & c) inline
Sincos only for -45deg < x < 45deg.
Definition at line 98 of file sincos.h.
References get_cos_px(), and get_sin_px().
Referenced by vdt::fast_sincos().
{
             double zz = z * z;
             s = z + z * zz * get_sin_px(zz);
             c = 1.0 - zz * .5 + zz * zz * get_cos_px(zz);
         }
void vdt::details::fast_sincosf_m45_45 (const float x, float & s, float & c) inline
Sincos only for -45deg < x < 45deg.
Definition at line 160 of file sincos.h.
Referenced by vdt::fast_sincosf().
{
             float z = x * x;
             s = (((-1.9515295891E-4f * z + 8.3321608736E-3f) * z -
                   1.6666654611E-1f) *
                  z * x) +
                 x;
             c = ((2.443315711809948E-005f * z - 1.388731625493765E-003f) * z +
                  4.166664568298827E-002f) *
                     z * z -
                 0.5f * z + 1.0f;
         }
uint32_t vdt::details::fp2uint (float x) inline
Converts a fp to an int.
Definition at line 195 of file vdtcore_common.h.
References sp2uint32().
 { return sp2uint32(x); }
uint64_t vdt::details::fp2uint (double x) inline
Converts a fp to an int.
Definition at line 197 of file vdtcore_common.h.
References dp2uint64().
 { return dp2uint64(x); }
double vdt::details::fpfloor (const double x) inline
A vectorisable floor implementation, not only triggered by fast-math. These functions do not distinguish between -0.0 and 0.0, so are not *IEC6509 compliant for argument -0.0
Definition at line 210 of file vdtcore_common.h.
References sp2uint32().
Referenced by vdt::fast_exp(), and vdt::fast_expf().
{
             // no problem since exp is defined between -708 and 708. Int is
             // enough for it!
             int32_t ret = int32_t(x);
             ret -= (sp2uint32(x) >> 31);
             return ret;
         }
float vdt::details::fpfloor (const float x) inline
A vectorisable floor implementation, not only triggered by fast-math. These functions do not distinguish between -0.0 and 0.0, so are not *IEC6509 compliant for argument -0.0
Definition at line 224 of file vdtcore_common.h.
References sp2uint32().
{
             int32_t ret = int32_t(x);
             ret -= (sp2uint32(x) >> 31);
             return ret;
         }
double vdt::details::get_cos_px (const double x) inline
Definition at line 69 of file sincos.h.
References C1cos, C2cos, C3cos, C4cos, C5cos, and C6cos.
Referenced by fast_sincos_m45_45().
{
             double px = C1cos;
             px *= x;
             px += C2cos;
             px *= x;
             px += C3cos;
             px *= x;
             px += C4cos;
             px *= x;
             px += C5cos;
             px *= x;
             px += C6cos;
             return px;
         }
double vdt::details::get_sin_px (const double x) inline
Definition at line 52 of file sincos.h.
References C1sin, C2sin, C3sin, C4sin, C5sin, and C6sin.
Referenced by fast_sincos_m45_45().
{
             double px = C1sin;
             px *= x;
             px += C2sin;
             px *= x;
             px += C3sin;
             px *= x;
             px += C4sin;
             px *= x;
             px += C5sin;
             px *= x;
             px += C6sin;
             return px;
         }
double vdt::details::getMantExponent (const double x, double & fe) inline
Like frexp but vectorising and the exponent is a double.
Definition at line 153 of file vdtcore_common.h.
References dp2uint64(), constant::e, and uint642dp().
{
             uint64_t n = dp2uint64(x);
             // Shift to the right up to the beginning of the exponent.
             // Then with a mask, cut off the sign bit
             uint64_t le = (n >> 52);
             // chop the head of the number: an int contains more than 11 bits
             // (32)
             int32_t e =
                 le; // This is important since sums on uint64_t do not vectorise
             fe = e - 1023;
             // This puts to 11 zeroes the exponent
             n &= 0x800FFFFFFFFFFFFFULL;
             // build a mask which is 0.5, i.e. an exponent equal to 1022
             // which means *2, see the above +1.
             const uint64_t p05 = 0x3FE0000000000000ULL; // dp2uint64(0.5);
             n |= p05;
             return uint642dp(n);
         }
float vdt::details::getMantExponentf (const float x, float & fe) inline
Like frexp but vectorising and the exponent is a float.
Definition at line 179 of file vdtcore_common.h.
References constant::e, sp2uint32(), and uint322sp().
{
             uint32_t n = sp2uint32(x);
             int32_t e = (n >> 23) - 127;
             fe = e;
             // fractional part
             const uint32_t p05f = 0x3f000000; // //sp2uint32(0.5);
             n &= 0x807fffff;                  // ~0x7f800000;
             n |= p05f;
             return uint322sp(n);
         }
uint64_t vdt::details::getSignMask (const double x) inline
Definition at line 107 of file vdtcore_common.h.
References dp2uint64().
{
             const uint64_t mask = 0x8000000000000000ULL;
             return dp2uint64(x) & mask;
         }
uint32_t vdt::details::getSignMask (const float x) inline
Get the sign mask.
Definition at line 146 of file vdtcore_common.h.
References sp2uint32().
{
             const uint32_t mask = 0x80000000;
             return sp2uint32(x) & mask;
         }
float vdt::details::int2fp (uint32_t i) inline
Converts an int to fp.
Definition at line 199 of file vdtcore_common.h.
References uint322sp().
 { return uint322sp(i); }
double vdt::details::int2fp (uint64_t i) inline
Converts an int to fp.
Definition at line 201 of file vdtcore_common.h.
References uint642dp().
 { return uint642dp(i); }
double vdt::details::reduce2quadrant (double x, int32_t & quad) inline
Reduce to 0 to 45.
Definition at line 86 of file sincos.h.
References DP1, DP2, DP3, and ONEOPIO4.
Referenced by vdt::fast_sincos(), and vdt::fast_sincosf().
{
             x = fabs(x);
             quad = int(ONEOPIO4 * x); // always positive, so (int) == std::floor
             quad = (quad + 1) & (~1);
             const double y = double(quad);
             // Extended precision modular arithmetic
             return ((x - y * DP1) - y * DP2) - y * DP3;
         }
float vdt::details::reduce2quadrant (float x, int & quad) inline
Reduce to 0 to 45.
Definition at line 144 of file sincos.h.
References DP1F, DP2F, DP3F, and ONEOPIO4F.
{
             /* make argument positive */
             x = fabs(x);
             quad = int(ONEOPIO4F * x); /* integer part of x/PIO4 */
             quad = (quad + 1) & (~1);
             const float y = float(quad);
             // quad &=4;
             // Extended precision modular arithmetic
             return ((x - y * DP1F) - y * DP2F) - y * DP3F;
         }
uint32_t vdt::details::sp2uint32 (float x) inline
Converts a float to an int.
Definition at line 122 of file vdtcore_common.h.
References vdt::details::ieee754::f, and vdt::details::ieee754::i.
Referenced by fp2uint(), fpfloor(), getMantExponentf(), getSignMask(), spANDuint32(), spORuint32(), and spXORuint32().
{
             ieee754 tmp;
             tmp.f[0] = x;
             return tmp.i[0];
         }
float vdt::details::spANDuint32 (const float x, const uint32_t i) inline
Makes an AND of a float and a unsigned long.
Definition at line 130 of file vdtcore_common.h.
References sp2uint32(), and uint322sp().
{
             return uint322sp(sp2uint32(x) & i);
         }
float vdt::details::spORuint32 (const float x, const uint32_t i) inline
Makes an OR of a float and a unsigned long.
Definition at line 135 of file vdtcore_common.h.
References sp2uint32(), and uint322sp().
{
             return uint322sp(sp2uint32(x) | i);
         }
float vdt::details::spXORuint32 (const float x, const uint32_t i) inline
Makes an OR of a float and a unsigned long.
Definition at line 141 of file vdtcore_common.h.
References sp2uint32(), and uint322sp().
{
             return uint322sp(sp2uint32(x) ^ i);
         }
float vdt::details::uint322sp (int x) inline
Converts an int to a float.
Definition at line 114 of file vdtcore_common.h.
References vdt::details::ieee754::f, and vdt::details::ieee754::i.
Referenced by vdt::fast_expf(), getMantExponentf(), int2fp(), spANDuint32(), spORuint32(), and spXORuint32().
{
             ieee754 tmp;
             tmp.i[0] = x;
             return tmp.f[0];
         }
double vdt::details::uint642dp (uint64_t ll) inline
Converts an unsigned long long to a double.
Definition at line 75 of file vdtcore_common.h.
References vdt::details::ieee754::d, and vdt::details::ieee754::ll.
Referenced by dpANDuint64(), dpORuint64(), dpXORuint64(), vdt::fast_exp(), getMantExponent(), and int2fp().
{
             ieee754 tmp;
             tmp.ll = ll;
             return tmp.d;
         }
Variable Documentation
const double vdt::details::C1cos = -1.13585365213876817300E-11
Definition at line 31 of file sincos.h.
Referenced by get_cos_px().
const float vdt::details::C1F = 0.693359375f
Definition at line 53 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::C1sin = 1.58962301576546568060E-10
Definition at line 24 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::C2cos = 2.08757008419747316778E-9
Definition at line 32 of file sincos.h.
Referenced by get_cos_px().
const float vdt::details::C2F = -2.12194440e-4f
Definition at line 54 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::C2sin = -2.50507477628578072866E-8
Definition at line 25 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::C3cos = -2.75573141792967388112E-7
Definition at line 33 of file sincos.h.
Referenced by get_cos_px().
const double vdt::details::C3sin = 2.75573136213857245213E-6
Definition at line 26 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::C4cos = 2.48015872888517045348E-5
Definition at line 34 of file sincos.h.
Referenced by get_cos_px().
const double vdt::details::C4sin = -1.98412698295895385996E-4
Definition at line 27 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::C5cos = -1.38888888888730564116E-3
Definition at line 35 of file sincos.h.
Referenced by get_cos_px().
const double vdt::details::C5sin = 8.33333333332211858878E-3
Definition at line 28 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::C6cos = 4.16666666666665929218E-2
Definition at line 36 of file sincos.h.
Referenced by get_cos_px().
const double vdt::details::C6sin = -1.66666666666666307295E-1
Definition at line 29 of file sincos.h.
Referenced by get_sin_px().
const double vdt::details::DP1 = 7.853981554508209228515625E-1
Definition at line 38 of file sincos.h.
Referenced by reduce2quadrant().
const float vdt::details::DP1F = 0.78515625
Definition at line 44 of file sincos.h.
Referenced by reduce2quadrant().
const double vdt::details::DP1sc = 7.85398125648498535156E-1
Definition at line 20 of file sincos.h.
const double vdt::details::DP2 = 7.94662735614792836714E-9
Definition at line 39 of file sincos.h.
Referenced by reduce2quadrant().
const float vdt::details::DP2F = 2.4187564849853515625e-4
Definition at line 45 of file sincos.h.
Referenced by reduce2quadrant().
const double vdt::details::DP2sc = 3.77489470793079817668E-8
Definition at line 21 of file sincos.h.
const double vdt::details::DP3 = 3.06161699786838294307E-17
Definition at line 40 of file sincos.h.
Referenced by reduce2quadrant().
const float vdt::details::DP3F = 3.77489497744594108e-8
Definition at line 46 of file sincos.h.
Referenced by reduce2quadrant().
const double vdt::details::DP3sc = 2.69515142907905952645E-15
Definition at line 22 of file sincos.h.
const double vdt::details::EXP_LIMIT = 708
Definition at line 38 of file exp.h.
Referenced by vdt::fast_exp().
const double vdt::details::LOG2E = 1.4426950408889634073599
Definition at line 48 of file exp.h.
Referenced by vdt::fast_exp().
const float vdt::details::LOG2EF = 1.44269504088896341f
Definition at line 63 of file exp.h.
Referenced by vdt::fast_expf().
const float vdt::details::MAXLOGF = 88.72283905206835f
Definition at line 50 of file exp.h.
Referenced by vdt::fast_expf().
const float vdt::details::MAXNUMF = 3.4028234663852885981170418348451692544e38f
Definition at line 53 of file vdtcore_common.h.
const float vdt::details::MINLOGF = -88.f
Definition at line 51 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::MOREBITS = 6.123233995736765886130E-17
Definition at line 51 of file vdtcore_common.h.
const double vdt::details::ONEOPIO4 = 4. / M_PI
Definition at line 43 of file vdtcore_common.h.
Referenced by reduce2quadrant().
const float vdt::details::ONEOPIO4F = 4. / M_PI
Definition at line 49 of file vdtcore_common.h.
Referenced by reduce2quadrant().
const double vdt::details::PI = M_PI
Definition at line 40 of file vdtcore_common.h.
const float vdt::details::PIF = M_PI
Definition at line 46 of file vdtcore_common.h.
const double vdt::details::PIO2 = M_PI_2
Definition at line 41 of file vdtcore_common.h.
const float vdt::details::PIO2F = M_PI_2
Definition at line 47 of file vdtcore_common.h.
const double vdt::details::PIO4 = M_PI_4
Definition at line 42 of file vdtcore_common.h.
const float vdt::details::PIO4F = M_PI_4
Definition at line 48 of file vdtcore_common.h.
const double vdt::details::PX1exp = 1.26177193074810590878E-4
Definition at line 40 of file exp.h.
Referenced by vdt::fast_exp().
const float vdt::details::PX1expf = 1.9875691500E-4f
Definition at line 56 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::PX2exp = 3.02994407707441961300E-2
Definition at line 41 of file exp.h.
Referenced by vdt::fast_exp().
const float vdt::details::PX2expf = 1.3981999507E-3f
Definition at line 57 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::PX3exp = 9.99999999999999999910E-1
Definition at line 42 of file exp.h.
Referenced by vdt::fast_exp().
const float vdt::details::PX3expf = 8.3334519073E-3f
Definition at line 58 of file exp.h.
Referenced by vdt::fast_expf().
const float vdt::details::PX4expf = 4.1665795894E-2f
Definition at line 59 of file exp.h.
Referenced by vdt::fast_expf().
const float vdt::details::PX5expf = 1.6666665459E-1f
Definition at line 60 of file exp.h.
Referenced by vdt::fast_expf().
const float vdt::details::PX6expf = 5.0000001201E-1f
Definition at line 61 of file exp.h.
Referenced by vdt::fast_expf().
const double vdt::details::QX1exp = 3.00198505138664455042E-6
Definition at line 43 of file exp.h.
Referenced by vdt::fast_exp().
const double vdt::details::QX2exp = 2.52448340349684104192E-3
Definition at line 44 of file exp.h.
Referenced by vdt::fast_exp().
const double vdt::details::QX3exp = 2.27265548208155028766E-1
Definition at line 45 of file exp.h.
Referenced by vdt::fast_exp().
const double vdt::details::QX4exp = 2.00000000000000000009E0
Definition at line 46 of file exp.h.
Referenced by vdt::fast_exp().
const float vdt::details::T24M1 = 16777215.
Definition at line 48 of file sincos.h.
const double vdt::details::TWOPI = 2. * M_PI
Definition at line 39 of file vdtcore_common.h.
const float vdt::details::TWOPIF = 2. * M_PI
Definition at line 45 of file vdtcore_common.h.