Beam Longitudinal Dynamics code (BLonD): option::PrintUsageImplementation::LinePartIterator Class Reference
option::PrintUsageImplementation::LinePartIterator Class Reference
#include <optionparser.h>
Public Member Functions
LinePartIterator (const Descriptor usage[])
Creates an iterator for usage.
int column ()
Returns the index (counting from 0) of the column in which the part pointed to by data() is located.
const char * data ()
Returns the current part of the iteration.
int length ()
Returns the length of the part pointed to by data() in raw chars (not UTF-8 characters).
int line ()
Returns the index (counting from 0) of the line within the current column this part belongs to.
bool next ()
Moves iteration to the next part (if any). Has to be called once after each call to nextRow() to move to the 1st part of the row.
bool nextRow ()
Moves iteration to the next row (if any). Has to be called once after each call to nextTable() to move to the 1st row of the table.
bool nextTable ()
Moves iteration to the next table (if any). Has to be called once on a new LinePartIterator to move to the 1st table.
void restartRow ()
Reset iteration to the beginning of the current row.
void restartTable ()
Reset iteration to the beginning of the current table.
int screenLength ()
Returns the width in screen columns of the part pointed to by data(). Takes multi-byte UTF-8 sequences and wide characters into account.
Private Member Functions
void update_length ()
Determines the byte and character lengths of the part at ptr and stores them in len and screenlen respectively.
Private Attributes
int col
Index of current column.
bool hit_target_line
     Flag whether we encountered a part with
line index target_line_in_block in the current cell.
int len
     Length of the current part (that ptr points at) in
BYTES
int line_in_block
     Line index within the current cell of the
current part.
int max_line_in_block
     Greatest index of a line within the
block. This is the number of \v within the cell with the most \vs.
const char * ptr
Ptr to current part within the current row.
const Descriptor * rowdesc
The Descriptor that contains the current row.
const char * rowstart
    Ptr to 1st character of current row
within rowdesc->help.
int screenlen
      Length of the current part in screen columns
(taking narrow/wide chars into account).
const Descriptor * tablestart
The 1st descriptor of the current table.
int target_line_in_block
     Line index of the parts we should
return to the user on this iteration.
Detailed Description
Definition at line 2131 of file optionparser.h.
Constructor & Destructor Documentation
option::PrintUsageImplementation::LinePartIterator::LinePartIterator (const Descriptor usage[]) inline
Creates an iterator for usage.
Definition at line 2195 of file optionparser.h.
                 : tablestart(usage), rowdesc(0), rowstart(0), ptr(0), col(-1),
                   len(0), max_line_in_block(0), line_in_block(0),
                   target_line_in_block(0), hit_target_line(true) {}
Member Function Documentation
int option::PrintUsageImplementation::LinePartIterator::column () inline
Returns the index (counting from 0) of the column in which the part pointed to by data() is located.
Definition at line 2355 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
 { return col; }
const char* option::PrintUsageImplementation::LinePartIterator::data () inline
Returns the current part of the iteration.
Definition at line 2384 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
 { return ptr; }
int option::PrintUsageImplementation::LinePartIterator::length () inline
Returns the length of the part pointed to by data() in raw chars (not UTF-8 characters).
Definition at line 2371 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
 { return len; }
int option::PrintUsageImplementation::LinePartIterator::line () inline
Returns the index (counting from 0) of the line within the current column this part belongs to.
Definition at line 2362 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 return target_line_in_block; // NOT line_in_block !!! It would
                                              // be wrong if !hit_target_line
             }
bool option::PrintUsageImplementation::LinePartIterator::next () inline
Moves iteration to the next part (if any). Has to be called once after each call to nextRow() to move to the 1st part of the row.
Return values
false if moving to next part failed because no further part exists.
See LinePartIterator for details about the iteration.
Definition at line 2287 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 if (ptr == 0)
                     return false;
                 if (col == -1) {
                     col = 0;
                     update_length();
                     return true;
                 }
                 ptr += len;
                 while (true) {
                     switch (*ptr) {
                     case '\v':
                         upmax(max_line_in_block, ++line_in_block);
                         ++ptr;
                         break;
                     case '\t':
                         if (!hit_target_line) { // if previous column did not
                                                 // have the targetline
                                                 // then "insert" a 0-length part
                             update_length();
                             hit_target_line = true;
                             return true;
                         }
                         hit_target_line = false;
                         line_in_block = 0;
                         ++col;
                         ++ptr;
                         break;
                     case 0:
                     case '\n':
                         if (!hit_target_line) { // if previous column did not
                                                 // have the targetline
                                                 // then "insert" a 0-length part
                             update_length();
                             hit_target_line = true;
                             return true;
                         }
                         if (++target_line_in_block > max_line_in_block) {
                             update_length();
                             return false;
                         }
                         hit_target_line = false;
                         line_in_block = 0;
                         col = 0;
                         ptr = rowstart;
                         continue;
                     default:
                         ++ptr;
                         continue;
                     } // switch
                     if (line_in_block == target_line_in_block) {
                         update_length();
                         hit_target_line = true;
                         return true;
                     }
                 } // while
             }
bool option::PrintUsageImplementation::LinePartIterator::nextRow () inline
Moves iteration to the next row (if any). Has to be called once after each call to nextTable() to move to the 1st row of the table.
Return values
false if moving to next row failed because no further row exists.
Definition at line 2241 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 if (ptr == 0) {
                     restartRow();
                     return rowstart != 0;
                 }
                 while (*ptr != 0 && *ptr != '\n')
                     ++ptr;
                 if (*ptr == 0) {
                     if ((rowdesc + 1)->help == 0) // table break
                         return false;
                     ++rowdesc;
                     rowstart = rowdesc->help;
                 } else { // if (*ptr == '\n')
                     rowstart = ptr + 1;
                 }
                 restartRow();
                 return true;
             }
bool option::PrintUsageImplementation::LinePartIterator::nextTable () inline
Moves iteration to the next table (if any). Has to be called once on a new LinePartIterator to move to the 1st table.
Return values
false if moving to next table failed because no further table exists.
Definition at line 2207 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 // If this is NOT the first time nextTable() is called after the
                 // constructor,
                 // then skip to the next table break (i.e. a Descriptor with
                 // help == 0)
                 if (rowdesc != 0) {
                     while (tablestart->help != 0 && tablestart->shortopt != 0)
                         ++tablestart;
                 }
                 // Find the next table after the break (if any)
                 while (tablestart->help == 0 && tablestart->shortopt != 0)
                     ++tablestart;
                 restartTable();
                 return rowstart != 0;
             }
void option::PrintUsageImplementation::LinePartIterator::restartRow () inline
Reset iteration to the beginning of the current row.
Definition at line 2267 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 ptr = rowstart;
                 col = -1;
                 len = 0;
                 screenlen = 0;
                 max_line_in_block = 0;
                 line_in_block = 0;
                 target_line_in_block = 0;
                 hit_target_line = true;
             }
void option::PrintUsageImplementation::LinePartIterator::restartTable () inline
Reset iteration to the beginning of the current table.
Definition at line 2228 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
{
                 rowdesc = tablestart;
                 rowstart = tablestart->help;
                 ptr = 0;
             }
int option::PrintUsageImplementation::LinePartIterator::screenLength () inline
Returns the width in screen columns of the part pointed to by data(). Takes multi-byte UTF-8 sequences and wide characters into account.
Definition at line 2379 of file optionparser.h.
Referenced by option::PrintUsageImplementation::printUsage().
 { return screenlen; }
void option::PrintUsageImplementation::LinePartIterator::update_length () inline private
Determines the byte and character lengths of the part at ptr and stores them in len and screenlen respectively.
Definition at line 2160 of file optionparser.h.
{
                 screenlen = 0;
                 for (len = 0; ptr[len] != 0 && ptr[len] != '\v' &&
                               ptr[len] != '\t' && ptr[len] != '\n';
                      ++len) {
                     ++screenlen;
                     unsigned ch = (unsigned char)ptr[len];
                     if (ch > 0xC1) { // everything <= 0xC1 (yes, even 0xC1
                         // itself) is not a valid UTF-8 start byte
                         // int __builtin_clz (unsigned int x)
                         // Returns the number of leading 0-bits in x, starting
                         // at the most significant bit
                         unsigned mask =
                             (unsigned)-1 >> __builtin_clz(ch ^ 0xff);
                         ch = ch & mask; // mask out length bits, we don't verify
                         // their correctness
                         while (((unsigned char)ptr[len + 1] ^ 0x80) <=
                                0x3F) { // while next byte is continuation byte
                             ch = (ch << 6) ^ (unsigned char)ptr[len + 1] ^
                                  0x80; // add continuation to char code
                             ++len;
                         }
                         // ch is the decoded unicode code point
                         if (ch >= 0x1100 && isWideChar(ch)) // the test for
                                                             // 0x1100 is here to
                                                             // avoid the
                                                             // function call in
                                                             // the Latin case
                             ++screenlen;
                     }
                 }
             }
Member Data Documentation
int option::PrintUsageImplementation::LinePartIterator::col private
Index of current column.
Definition at line 2139 of file optionparser.h.
bool option::PrintUsageImplementation::LinePartIterator::hit_target_line private
     Flag whether we encountered a part with
line index target_line_in_block in the current cell.
Definition at line 2151 of file optionparser.h.
int option::PrintUsageImplementation::LinePartIterator::len private
     Length of the current part (that ptr points at) in
BYTES
Definition at line 2140 of file optionparser.h.
int option::PrintUsageImplementation::LinePartIterator::line_in_block private
     Line index within the current cell of the
current part.
Definition at line 2147 of file optionparser.h.
int option::PrintUsageImplementation::LinePartIterator::max_line_in_block private
     Greatest index of a line within the
block. This is the number of \v within the cell with the most \vs.
Definition at line 2144 of file optionparser.h.
const char* option::PrintUsageImplementation::LinePartIterator::ptr private
Ptr to current part within the current row.
Definition at line 2138 of file optionparser.h.
const Descriptor* option::PrintUsageImplementation::LinePartIterator::rowdesc private
The Descriptor that contains the current row.
Definition at line 2135 of file optionparser.h.
const char* option::PrintUsageImplementation::LinePartIterator::rowstart private
    Ptr to 1st character of current row
within rowdesc->help.
Definition at line 2136 of file optionparser.h.
int option::PrintUsageImplementation::LinePartIterator::screenlen private
      Length of the current part in screen columns
(taking narrow/wide chars into account).
Definition at line 2142 of file optionparser.h.
const Descriptor* option::PrintUsageImplementation::LinePartIterator::tablestart private
The 1st descriptor of the current table.
Definition at line 2133 of file optionparser.h.
int option::PrintUsageImplementation::LinePartIterator::target_line_in_block private
     Line index of the parts we should
return to the user on this iteration.
Definition at line 2149 of file optionparser.h.