Beam Longitudinal Dynamics code (BLonD): RingAndRfSection Class Reference
RingAndRfSection Class Reference
#include <Tracker.h>
Public Types
enum solver_type { simple, full }
Public Member Functions
RingAndRfSection (RfParameters *RfP=Context::RfP, Beams *Beam=Context::Beam, solver_type solver=simple, PhaseLoop *PL=nullptr, LHCNoiseFB *NoiseFB=nullptr, bool periodicity=false, double dE_max=0, bool rf_kick_interp=false, Slices *Slices=nullptr, TotalInducedVoltage *TotalInducedVoltage=nullptr)
~RingAndRfSection ()
void drift (f_vector_t &beam_dt, f_vector_t &beam_dE, const int index)
void drift (double *__restrict beam_dt, const double *__restrict beam_dE, const solver_type solver, const double T0, const double length_ratio, const int alpha_order, const double eta_zero, const double eta_one, const double eta_two, const double beta, const double energy, const int n_macroparticles)
void horizontal_cut ()
void kick (f_vector_t &beam_dt, f_vector_t &beam_dE, const int index)
void kick (const double *__restrict beam_dt, double *__restrict beam_dE, const int n_rf, const double *__restrict voltage, const double *__restrict omega_RF, const double *__restrict phi_RF, const int n_macroparticles, const double acc_kick)
void rf_voltage_calculation (int turn, Slices *slices)
void set_periodicity ()
void track ()
Public Attributes
f_vector_t acceleration_kick
int & alpha_order
Beams * beam
f_vector_t & beta
double & charge
int & counter
double dE_max
f_vector_t & eta_0
f_vector_t & eta_1
f_vector_t & eta_2
f_vector_t fRfVoltage
f_vector_t fTotalVoltage
f_vector_2d_t & harmonic
int_vector_t indices_inside_frame
int_vector_t indices_left_outside
int_vector_t indices_right_outside
double & length_ratio
int & n_rf
LHCNoiseFB * noiseFB
f_vector_2d_t & omega_rf
bool periodicity
f_vector_2d_t & phi_noise
f_vector_2d_t & phi_rf
f_vector_t & phi_s
PhaseLoop * PL
bool rf_kick_interp
RfParameters * rfp
int & section_index
double & section_length
int_vector_t & sign_eta_0
Slices * slices
solver_type solver
f_vector_t & t_rev
TotalInducedVoltage * totalInducedVoltage
f_vector_2d_t & voltage
Detailed Description
Definition at line 18 of file Tracker.h.
Member Enumeration Documentation
enum RingAndRfSection::solver_type
Enumerator
simple
full
Definition at line 21 of file Tracker.h.
 { simple, full };
Constructor & Destructor Documentation
RingAndRfSection::RingAndRfSection (RfParameters * RfP = Context::RfP, Beams * Beam = Context::Beam, solver_type solver = simple, PhaseLoop * PL = nullptr, LHCNoiseFB * NoiseFB = nullptr, bool periodicity = false, double dE_max = 0, bool rf_kick_interp = false, Slices * Slices = nullptr, TotalInducedVoltage * TotalInducedVoltage = nullptr) inline
Definition at line 83 of file Tracker.h.
         : section_index(RfP->section_index),
           counter(RfP->counter),
           length_ratio(RfP->length_ratio),
           section_length(RfP->section_length),
           t_rev(RfP->t_rev),
           n_rf(RfP->n_rf),
           beta(RfP->beta),
           charge(RfP->charge),
           harmonic(RfP->harmonic),
           voltage(RfP->voltage),
           phi_noise(RfP->phi_noise),
           phi_rf(RfP->phi_rf),
           phi_s(RfP->phi_s),
           omega_rf(RfP->omega_rf),
           eta_0(RfP->eta_0),
           eta_1(RfP->eta_1),
           eta_2(RfP->eta_2),
           sign_eta_0(RfP->sign_eta_0),
           alpha_order(RfP->alpha_order)
     {
         beam = Beam;
         rfp = RfP;
         // this->elapsed_time = 0;
         this->solver = solver;
         this->PL = PL;
         this->noiseFB = NoiseFB;
         this->periodicity = periodicity;
         this->dE_max = dE_max;
         this->rf_kick_interp = rf_kick_interp;
         this->slices = Slices;
         this->totalInducedVoltage = TotalInducedVoltage;
         this->acceleration_kick.resize(rfp->E_increment.size());
         for (uint i = 0; i < rfp->E_increment.size(); ++i)
             acceleration_kick[i] = -rfp->E_increment[i];
         if (solver != simple && solver != full) {
             std::cerr << "ERROR: Choice of longitudinal solver not recognized!\n"
                       << "Aborting...\n";
             exit(-1);
         }
         if (alpha_order > 1) solver = full;
         if (rf_kick_interp && Slices == NULL) {
             std::cerr << "ERROR: A slices object is needed to use the"
                       << " kick_interp option\n";
             exit(-1);
         }
     }
RingAndRfSection::~RingAndRfSection () inline
Definition at line 141 of file Tracker.h.
 {};
Member Function Documentation
void RingAndRfSection::drift (f_vector_t & beam_dt, f_vector_t & beam_dE, const int index)
Definition at line 290 of file Tracker.cpp.
 {
     drift(beam_dt.data(), beam_dE.data(), solver, t_rev[index],
           length_ratio, alpha_order, eta_0[index],
           eta_1[index], eta_2[index], rfp->beta[index],
           rfp->energy[index], beam_dt.size());
 }
void RingAndRfSection::drift (double *__restrict beam_dt, const double *__restrict beam_dE, const solver_type solver, const double T0, const double length_ratio, const int alpha_order, const double eta_zero, const double eta_one, const double eta_two, const double beta, const double energy, const int n_macroparticles) inline
Definition at line 44 of file Tracker.cpp.
 {
     const double T = T0 * length_ratio;
     if (solver == simple) {
         const double T_x_coeff = T * eta_zero / (beta * beta * energy);
         #pragma omp parallel for
         for (int i = 0; i < n_macroparticles; i++)
             beam_dt[i] += T_x_coeff * beam_dE[i];
     } else {
         const double coeff = 1. / (beta * beta * energy);
         const double eta0 = eta_zero * coeff;
         const double eta1 = eta_one * coeff * coeff;
         const double eta2 = eta_two * coeff * coeff * coeff;
         if (alpha_order == 1) {
             #pragma omp parallel for
             for (int i = 0; i < n_macroparticles; i++)
                 beam_dt[i] += T * (1. / (1. - eta0 * beam_dE[i]) - 1.);
         } else if (alpha_order == 2) {
             #pragma omp parallel for
             for (int i = 0; i < n_macroparticles; i++)
                 beam_dt[i] += T * (1. / (1. - eta0 * beam_dE[i] -
                                          eta1 * beam_dE[i] * beam_dE[i]) -
                                    1.);
         } else {
             #pragma omp parallel for
             for (int i = 0; i < n_macroparticles; i++)
                 beam_dt[i] +=
                     T * (1. / (1. - eta0 * beam_dE[i] -
                                eta1 * beam_dE[i] * beam_dE[i] -
                                eta2 * beam_dE[i] * beam_dE[i] * beam_dE[i]) -
                          1.);
         }
     }
 }
void RingAndRfSection::horizontal_cut () inline
Definition at line 204 of file Tracker.cpp.
 {
     uint i = 0;
     while (i < beam->dE.size()) {
         if (beam->dE[i] > -dE_max) {
             beam->dE.erase(beam->dE.begin() + i);
             beam->dt.erase(beam->dt.begin() + i);
             beam->id.erase(beam->id.begin() + i);
         } else {
             i++;
         }
     }
     beam->n_macroparticles = beam->dE.size();
 }
void RingAndRfSection::kick (f_vector_t & beam_dt, f_vector_t & beam_dE, const int index)
Definition at line 267 of file Tracker.cpp.
 {
     auto vol = new double[n_rf];
     auto omeg = new double[n_rf];
     auto phi = new double[n_rf];
     for (int i = 0; i < n_rf; ++i) {
         vol[i] = voltage[i][index];
         omeg[i] = omega_rf[i][index];
         phi[i] = phi_rf[i][index];
     }
     kick(beam_dt.data(), beam_dE.data(), n_rf, vol, omeg, phi,
          beam_dt.size(), acceleration_kick[index]);
     delete[] vol;
     delete[] omeg;
     delete[] phi;
 }
void RingAndRfSection::kick (const double *__restrict beam_dt, double *__restrict beam_dE, const int n_rf, const double *__restrict voltage, const double *__restrict omega_RF, const double *__restrict phi_RF, const int n_macroparticles, const double acc_kick) inline
Definition at line 18 of file Tracker.cpp.
References mymath::fast_sin().
 {
     // KICK
     //#pragma omp parallel for collapse(2)
     for (int j = 0; j < n_rf; ++j) {
         #pragma omp parallel for
         for (int i = 0; i < n_macroparticles; ++i) {
             const double a = omega_rf[j] * beam_dt[i] + phi_rf[j];
             beam_dE[i] += voltage[j] * fast_sin(a);
         }
     }
 // SYNCHRONOUS ENERGY CHANGE
     #pragma omp parallel for
     for (int i = 0; i < n_macroparticles; ++i)
         beam_dE[i] += acc_kick;
 }
void RingAndRfSection::rf_voltage_calculation (int turn, Slices * slices)
Definition at line 219 of file Tracker.cpp.
References Slices::bin_centers, and mymath::sum().
 {
     // Calculating the RF voltage seen by the beam at a given turn,
     // needs a Slices object.
     auto vol = new double[n_rf];
     auto omeg = new double[n_rf];
     auto phi = new double[n_rf];
     for (int i = 0; i < n_rf; ++i) {
         vol[i] = voltage[i][turn];
         omeg[i] = omega_rf[i][turn];
         phi[i] = phi_rf[i][turn];
     }
     fRfVoltage.resize(slices->bin_centers.size());
     for (uint j = 0; j < slices->bin_centers.size(); j++) {
         double sum = 0.0;
         for (int i = 0; i < n_rf; i++) {
             sum += vol[i] * sin(omeg[i] * slices->bin_centers[j] + phi[i]);
         }
         fRfVoltage[j] = sum;
     }
     delete[] vol;
     delete[] omeg;
     delete[] phi;
 }
void RingAndRfSection::set_periodicity ()
Definition at line 251 of file Tracker.cpp.
 {
     indices_right_outside.clear();
     indices_inside_frame.clear();
     indices_left_outside.clear();
     // TODO I am not duplicating the insiders dE, dt
     // as done in the python version
     for (int i = 0; i < beam->n_macroparticles; ++i) {
         if (beam->dt[i] > t_rev[counter + 1])
             indices_right_outside.push_back(i);
         else if (beam->dt[i] < t_rev[counter + 1])
             indices_inside_frame.push_back(i);
     }
 }
void RingAndRfSection::track ()
Definition at line 94 of file Tracker.cpp.
References linear_interp_kick().
 {
     if (!phi_noise.empty()) {
         if (noiseFB != NULL) {
             for (uint i = 0; i < phi_rf.size(); ++i)
                 phi_rf[i][counter] +=
                     noiseFB->fX * phi_noise[i][counter];
         } else {
             for (uint i = 0; i < phi_rf.size(); ++i)
                 phi_rf[i][counter] += phi_noise[i][counter];
         }
     }
     // Determine phase loop correction on RF phase and frequency
     if (PL != NULL && counter >= (int) PL->delay)
         PL->track();
     if (periodicity) {
         // Change reference of all the particles on the right of the current
         // frame; these particles skip one kick and drift
         set_periodicity();
         const double tRev = t_rev[counter + 1];
         if (!indices_right_outside.empty()) {
             f_vector_t insiders_dt, insiders_dE;
             insiders_dt.reserve(indices_inside_frame.size());
             insiders_dE.reserve(indices_inside_frame.size());
             for (const auto &i : indices_inside_frame) {
                 insiders_dt.push_back(beam->dt[i]);
                 insiders_dE.push_back(beam->dE[i]);
             }
             for (const auto &i : indices_right_outside)
                 beam->dt[i] -= tRev;
             // Synchronize the bunch with the particles that are on the right of
             // the current frame applying kick and drift to the bunch; after that
             // all the particle are in the new updated frame
             kick(insiders_dt, insiders_dE, counter);
             drift(insiders_dt, insiders_dE, counter + 1);
             int k = 0;
             for (const auto &i : indices_inside_frame) {
                 beam->dt[i] = insiders_dt[k];
                 beam->dE[i] = insiders_dE[k];
                 k++;
             }
         } else {
             kick(beam->dt, beam->dE, counter);
             drift(beam->dt, beam->dE, counter + 1);
             // find left outside particles and kick, drift them one more time
             // indices_left_outside.clear();
             //#pragma omp parallel for reduction(+:a)
             for (int i = 0; i < beam->n_macroparticles; ++i) {
                 if (beam->dt[i] < 0)
                     indices_left_outside.push_back(i);
             }
         }
         if (!indices_left_outside.empty()) {
             f_vector_t left_dt, left_dE;
             left_dt.reserve(indices_left_outside.size());
             left_dE.reserve(indices_left_outside.size());
             for (const auto &i : indices_left_outside) {
                 left_dt.push_back(beam->dt[i] + tRev);
                 left_dE.push_back(beam->dE[i]);
             }
             kick(left_dt, left_dE, counter);
             drift(left_dt, left_dE, counter + 1);
             int k = 0;
             for (const auto &i : indices_left_outside) {
                 beam->dt[i] = left_dt[k];
                 beam->dE[i] = left_dE[k];
                 k++;
             }
         }
         // cout << "right: " << indices_right_outside.size() << '\n';
         // cout << "inside: " << indices_inside_frame.size() << '\n';
         // cout << "left: " << indices_left_outside.size() << '\n';
     } else {
         if (rf_kick_interp) {
             // TODO test this part
             rf_voltage_calculation(counter, slices);
             fTotalVoltage = fRfVoltage;
             if (totalInducedVoltage != NULL)
                 fTotalVoltage += totalInducedVoltage->fInducedVoltage;
             fRfVoltage *= charge;
             linear_interp_kick(beam->dt.data(), beam->dE.data(),
                                fRfVoltage.data(), slices->bin_centers.data(),
                                slices->n_slices, beam->n_macroparticles);
         } else {
             kick(beam->dt, beam->dE, counter);
         }
         drift(beam->dt, beam->dE, counter + 1);
     }
     if (dE_max > 0) horizontal_cut();
     counter++;
 }
Member Data Documentation
f_vector_t RingAndRfSection::acceleration_kick
Definition at line 50 of file Tracker.h.
int& RingAndRfSection::alpha_order
Definition at line 43 of file Tracker.h.
Beams* RingAndRfSection::beam
Definition at line 24 of file Tracker.h.
f_vector_t& RingAndRfSection::beta
Definition at line 31 of file Tracker.h.
double& RingAndRfSection::charge
Definition at line 32 of file Tracker.h.
int& RingAndRfSection::counter
Definition at line 26 of file Tracker.h.
double RingAndRfSection::dE_max
Definition at line 53 of file Tracker.h.
f_vector_t& RingAndRfSection::eta_0
Definition at line 39 of file Tracker.h.
f_vector_t& RingAndRfSection::eta_1
Definition at line 40 of file Tracker.h.
f_vector_t& RingAndRfSection::eta_2
Definition at line 41 of file Tracker.h.
f_vector_t RingAndRfSection::fRfVoltage
Definition at line 51 of file Tracker.h.
f_vector_t RingAndRfSection::fTotalVoltage
Definition at line 61 of file Tracker.h.
f_vector_2d_t& RingAndRfSection::harmonic
Definition at line 33 of file Tracker.h.
int_vector_t RingAndRfSection::indices_inside_frame
Definition at line 47 of file Tracker.h.
int_vector_t RingAndRfSection::indices_left_outside
Definition at line 48 of file Tracker.h.
int_vector_t RingAndRfSection::indices_right_outside
Definition at line 46 of file Tracker.h.
double& RingAndRfSection::length_ratio
Definition at line 27 of file Tracker.h.
int& RingAndRfSection::n_rf
Definition at line 30 of file Tracker.h.
LHCNoiseFB* RingAndRfSection::noiseFB
Definition at line 57 of file Tracker.h.
f_vector_2d_t& RingAndRfSection::omega_rf
Definition at line 38 of file Tracker.h.
bool RingAndRfSection::periodicity
Definition at line 55 of file Tracker.h.
f_vector_2d_t& RingAndRfSection::phi_noise
Definition at line 35 of file Tracker.h.
f_vector_2d_t& RingAndRfSection::phi_rf
Definition at line 36 of file Tracker.h.
f_vector_t& RingAndRfSection::phi_s
Definition at line 37 of file Tracker.h.
PhaseLoop* RingAndRfSection::PL
Definition at line 58 of file Tracker.h.
bool RingAndRfSection::rf_kick_interp
Definition at line 54 of file Tracker.h.
RfParameters* RingAndRfSection::rfp
Definition at line 23 of file Tracker.h.
int& RingAndRfSection::section_index
Definition at line 25 of file Tracker.h.
double& RingAndRfSection::section_length
Definition at line 28 of file Tracker.h.
int_vector_t& RingAndRfSection::sign_eta_0
Definition at line 42 of file Tracker.h.
Slices* RingAndRfSection::slices
Definition at line 59 of file Tracker.h.
solver_type RingAndRfSection::solver
Definition at line 52 of file Tracker.h.
f_vector_t& RingAndRfSection::t_rev
Definition at line 29 of file Tracker.h.
TotalInducedVoltage* RingAndRfSection::totalInducedVoltage
Definition at line 60 of file Tracker.h.
f_vector_2d_t& RingAndRfSection::voltage
Definition at line 34 of file Tracker.h.