Beam Longitudinal Dynamics code (BLonD): InducedVoltage.h File Reference
InducedVoltage.h File Reference
#include <blond/configuration.h>
#include <blond/impedances/Intensity.h>
#include <vector>
Classes
class InducedVoltage
class InducedVoltageFreq
class InducedVoltageTime
class TotalInducedVoltage
Typedefs
typedef enum freq_res_option_t freq_res_option_t
Enumerations
enum freq_res_option_t { round_option, ceil_option, floor_option }
enum time_or_freq { time_domain, freq_domain }
Functions
void linear_interp_kick (const ftype *__restrict beam_dt, ftype *__restrict beam_dE, const ftype *__restrict voltage_array, const ftype *__restrict bin_centers, const int n_slices, const int n_macroparticles)
Typedef Documentation
typedef enum freq_res_option_t freq_res_option_t
Enumeration Type Documentation
enum freq_res_option_t
Enumerator
round_option
ceil_option
floor_option
Definition at line 17 of file InducedVoltage.h.
{
     round_option,
     ceil_option,
     floor_option
 } freq_res_option_t;
enum time_or_freq
Enumerator
time_domain
freq_domain
Definition at line 15 of file InducedVoltage.h.
 { time_domain, freq_domain };
Function Documentation
void linear_interp_kick (const ftype *__restrict beam_dt, ftype *__restrict beam_dE, const ftype *__restrict voltage_array, const ftype *__restrict bin_centers, const int n_slices, const int n_macroparticles)
Definition at line 10 of file InducedVoltage.cpp.
Referenced by InducedVoltageTime::track(), RingAndRfSection::track(), InducedVoltageFreq::track(), and TotalInducedVoltage::track().
 {
     const ftype binFirst = bin_centers[0];
     const ftype binLast = bin_centers[n_slices - 1];
     const ftype inv_bin_width = (n_slices - 1) / (binLast - binFirst);
     #pragma omp parallel for
     for (int i = 0; i < n_macroparticles; ++i) {
         const ftype a = beam_dt[i];
         const int ffbin = static_cast<int>((a - binFirst) * inv_bin_width);
         const ftype voltageKick =
             ((a < binFirst) || (a > binLast))
             ? 0.0
             : voltage_array[ffbin] +
             (a - bin_centers[ffbin]) *
             (voltage_array[ffbin + 1] - voltage_array[ffbin]) *
             inv_bin_width;
         beam_dE[i] += voltageKick;
     }
 }