Beam Longitudinal Dynamics code (BLonD): blond::InducedVoltageTime Class Reference
blond::InducedVoltageTime Class Reference
#include <InducedVoltage.h>
Public Types
enum time_or_freq { time_domain, freq_domain }
Public Member Functions
InducedVoltageTime (Slices *slices, const std::vector< Intensity * > &WakeSourceList, time_or_freq TimeOrFreq=freq_domain)
~InducedVoltageTime ()
f_vector_t induced_voltage_generation (Beams *beam, int length=0)
void reprocess (Slices *newSlices)
void sum_wakes (f_vector_t &v)
void track (Beams *beam)
Public Member Functions inherited from blond::InducedVoltage
InducedVoltage ()
virtual ~InducedVoltage ()
Public Attributes
int fCut
int fShape
f_vector_t fTimeArray
time_or_freq fTimeOrFreq
f_vector_t fTotalWake
std::vector< Intensity * > fWakeSourceList
Public Attributes inherited from blond::InducedVoltage
f_vector_t fInducedVoltage
Slices * fSlices
Detailed Description
Definition at line 39 of file InducedVoltage.h.
Member Enumeration Documentation
enum blond::InducedVoltageTime::time_or_freq
Enumerator
time_domain
freq_domain
Definition at line 41 of file InducedVoltage.h.
 { time_domain, freq_domain };
Constructor & Destructor Documentation
InducedVoltageTime::InducedVoltageTime (Slices * slices, const std::vector< Intensity * > & WakeSourceList, time_or_freq TimeOrFreq = freq_domain)
Definition at line 41 of file InducedVoltage.cpp.
References blond::Slices::bin_centers, fCut, blond::InducedVoltage::fInducedVoltage, fShape, blond::InducedVoltage::fSlices, fTimeArray, fTimeOrFreq, fTotalWake, fWakeSourceList, blond::Slices::n_slices, blond::mymath::next_regular(), and sum_wakes().
 {
     // Induced voltage derived from the sum of
     // several wake fields (time domain).*
     fSlices = slices;
     // *Wake sources inputed as a list (eg: list of BBResonators objects)*
     fWakeSourceList = WakeList;
     // *Time array of the wake in [s]*
     fTimeArray = f_vector_t();
     // *Total wake array of all sources in* [:math:`\Omega / s`]
     fTotalWake = f_vector_t();
     // *Induced voltage from the sum of the wake sources in [V]*
     fInducedVoltage = f_vector_t();
     // Pre-processing the wakes
     fTimeArray = fSlices->bin_centers - fSlices->bin_centers[0];
     sum_wakes(fTimeArray);
     fCut = fTimeArray.size() + fSlices->n_slices - 1;
     fShape = mymath::next_regular(fCut);
     fTimeOrFreq = TimeOrFreq;
 }
InducedVoltageTime::~InducedVoltageTime ()
Definition at line 70 of file InducedVoltage.cpp.
References blond::fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
f_vector_t InducedVoltageTime::induced_voltage_generation (Beams * beam, int length = 0) virtual
Implements blond::InducedVoltage.
Definition at line 108 of file InducedVoltage.cpp.
References blond::Beams::charge, blond::mymath::convolution(), blond::fft::convolution_with_ffts(), blond::constant::e, blond::InducedVoltage::fInducedVoltage, freq_domain, blond::InducedVoltage::fSlices, fTimeOrFreq, fTotalWake, blond::Beams::intensity, blond::Beams::n_macroparticles, blond::Slices::n_macroparticles, blond::Slices::n_slices, and time_domain.
Referenced by track().
 {
     // Method to calculate the induced voltage from wakes with convolution.*
     f_vector_t inducedVoltage;
     const double factor = -beam->charge * constant::e * beam->intensity
                           / beam->n_macroparticles;
     if (fTimeOrFreq == freq_domain) {
         auto in1 = fSlices->n_macroparticles;
         auto in2 = fTotalWake;
         fft::convolution_with_ffts(in1, in2, inducedVoltage);
         inducedVoltage *= factor;
     } else if (fTimeOrFreq == time_domain) {
         inducedVoltage.resize(fTotalWake.size() + fSlices->n_slices - 1);
         mymath::convolution(fTotalWake.data(), fTotalWake.size(),
                             fSlices->n_macroparticles.data(),
                             fSlices->n_macroparticles.size(),
                             inducedVoltage.data());
         inducedVoltage *= factor;
     } else {
         std::cerr << "Error: Only freq_domain or time_domain are allowed\n";
         exit(-1);
     }
     fInducedVoltage = inducedVoltage;
     fInducedVoltage.resize(fSlices->n_slices);
     if (length > 0)
         inducedVoltage.resize(length, 0);
     return inducedVoltage;
 }
void InducedVoltageTime::reprocess (Slices * newSlices) virtual
Implements blond::InducedVoltage.
Definition at line 93 of file InducedVoltage.cpp.
References blond::Slices::bin_centers, fCut, fShape, blond::InducedVoltage::fSlices, fTimeArray, blond::Slices::n_slices, blond::mymath::next_regular(), and sum_wakes().
 {
     // *Reprocess the wake contributions with respect to the new_slicing.*
     // WARNING As Slice is a global variable,
     // users will have to change this variable and call reprocess()
     fSlices = newSlices;
     // fTimeArray.resize(fSlices->n_slices);
     fTimeArray = fSlices->bin_centers - fSlices->bin_centers[0];
     sum_wakes(fTimeArray);
     fCut = fTimeArray.size() + fSlices->n_slices - 1;
     fShape = mymath::next_regular(fCut);
 }
void InducedVoltageTime::sum_wakes (f_vector_t & v)
Definition at line 82 of file InducedVoltage.cpp.
References fTotalWake, and fWakeSourceList.
Referenced by InducedVoltageTime(), and reprocess().
 {
     // *Summing all the wake contributions in one total wake.*
     fTotalWake.resize(TimeArray.size());
     std::fill(fTotalWake.begin(), fTotalWake.end(), 0);
     for (const auto &i : fWakeSourceList) {
         i->wake_calc(TimeArray);
         fTotalWake += i->fWake;
     }
 }
void InducedVoltageTime::track (Beams * beam) inline virtual
Implements blond::InducedVoltage.
Definition at line 72 of file InducedVoltage.cpp.
References blond::Slices::bin_centers, blond::Beams::charge, blond::Beams::dE, blond::Beams::dt, blond::InducedVoltage::fSlices, induced_voltage_generation(), blond::linear_interp_kick(), blond::Beams::n_macroparticles, and blond::Slices::n_slices.
 {
     // Tracking Method
     f_vector_t v = this->induced_voltage_generation(beam) * beam->charge;
     linear_interp_kick(beam->dt.data(), beam->dE.data(), v.data(),
                        fSlices->bin_centers.data(), fSlices->n_slices,
                        beam->n_macroparticles);
 }
Member Data Documentation
int blond::InducedVoltageTime::fCut
Definition at line 46 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
int blond::InducedVoltageTime::fShape
Definition at line 47 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
f_vector_t blond::InducedVoltageTime::fTimeArray
Definition at line 44 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
time_or_freq blond::InducedVoltageTime::fTimeOrFreq
Definition at line 48 of file InducedVoltage.h.
Referenced by induced_voltage_generation(), and InducedVoltageTime().
f_vector_t blond::InducedVoltageTime::fTotalWake
Definition at line 45 of file InducedVoltage.h.
Referenced by induced_voltage_generation(), InducedVoltageTime(), and sum_wakes().
std::vector<Intensity *> blond::InducedVoltageTime::fWakeSourceList
Definition at line 43 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and sum_wakes().