Beam Longitudinal Dynamics code (BLonD): blond::LHCNoiseFB Class Reference
blond::LHCNoiseFB Class Reference
#include <LHCNoiseFB.h>
Public Member Functions
LHCNoiseFB (double bl_target, double gain=0.1e9, double factor=0.93, double update_frequency=22500, bool variable_gain=true, f_vector_t bunch_pattern=f_vector_t())
~LHCNoiseFB ()
double fwhm_interpolation (uint_vector_t index, double half_height)
void fwhm_multi_bunch ()
void fwhm_single_bunch ()
void track ()
Public Attributes
double fA
double fBlMeas
f_vector_t fBlMeasBBB
double fBlTarg
f_vector_t fBunchPattern
std::function< void()> fFwhm
f_vector_t fG
uint fNUpdate
bool fVariableGain
double fX
Static Private Attributes
static const double cfwhm = std::sqrt(2.0 / std::log(2.0))
Detailed Description
Definition at line 26 of file LHCNoiseFB.h.
Constructor & Destructor Documentation
LHCNoiseFB::LHCNoiseFB (double bl_target, double gain = 0.1e9, double factor = 0.93, double update_frequency = 22500, bool variable_gain = true, f_vector_t bunch_pattern = f_vector_t())
Definition at line 22 of file LHCNoiseFB.cpp.
References fA, fBlMeas, fBlMeasBBB, fBlTarg, fBunchPattern, fFwhm, fG, fNUpdate, fVariableGain, fwhm_multi_bunch(), fwhm_single_bunch(), fX, blond::Context::GP, and blond::Context::RfP.
{
     fX = 0.0;
     fBlTarg = bl_target;
     fBlMeas = bl_target;
     fA = factor;
     fNUpdate = update_frequency;
     fVariableGain = variable_gain;
     fBunchPattern = bunch_pattern;
     auto GP = Context::GP;
     auto RfP = Context::RfP;
     if (fVariableGain) {
         fG.resize(GP->n_turns + 1);
         for (uint i = 0; i < fG.size(); ++i)
             fG[i] = gain * pow(RfP->omega_s0[0] / RfP->omega_s0[i], 2);
     } else {
         fG.resize(GP->n_turns + 1, gain);
     }
     if (fBunchPattern.empty()) {
         fFwhm = [&]() { return fwhm_single_bunch(); };
     } else {
         fFwhm = [&]() { return fwhm_multi_bunch(); };
         fBlMeasBBB.resize(fBunchPattern.size(), 0);
     }
 }
LHCNoiseFB::~LHCNoiseFB ()
Definition at line 51 of file LHCNoiseFB.cpp.
 {}
Member Function Documentation
double LHCNoiseFB::fwhm_interpolation (uint_vector_t index, double half_height)
Definition at line 82 of file LHCNoiseFB.cpp.
References blond::Slices::bin_centers, cfwhm, and blond::Context::Slice.
Referenced by fwhm_multi_bunch(), and fwhm_single_bunch().
{
     auto Slice = Context::Slice;
     const auto time_resolution = Slice->bin_centers[1] - Slice->bin_centers[0];
     const int first = index[0];
     const int prev = first > 0 ? first - 1 : Slice->n_slices - 1;
     const auto left =
         Slice->bin_centers[first] -
         (Slice->n_macroparticles[first] - half_height) /
             (Slice->n_macroparticles[first] - Slice->n_macroparticles[prev]) *
             time_resolution;
     const int last = index.back();
     auto right = 0.0;
     if (last < Slice->n_slices - 1) {
         right = Slice->bin_centers[last] +
                 (Slice->n_macroparticles[last] - half_height) /
                     (Slice->n_macroparticles[last] -
                      Slice->n_macroparticles[last + 1]) *
                     time_resolution;
     }
     // std::cout << "time_resolution " << time_resolution << '\n';
     // std::cout << "half_height " << half_height << '\n';
     // std::cout << "first " << first << '\n';
     // std::cout << "bin_centers[first] " << Slice->bin_centers[first] << '\n';
     // std::cout << "bin_centers[last] " << Slice->bin_centers[last] << '\n';
     // std::cout << "n_macroparticles[first] " << Slice->n_macroparticles[first]
     // << '\n';
     // std::cout << "n_macroparticles[prev] " << Slice->n_macroparticles[prev]
     // <<
     // '\n';
     // std::cout << "n_macroparticles[last] " << Slice->n_macroparticles[last]
     // <<
     // '\n';
     // std::cout << "n_macroparticles[last+1] " << Slice->n_macroparticles[last
     // +
     // 1] << '\n';
     // std::cout << "left " << left << '\n';
     // std::cout << "last " << last << '\n';
     // std::cout << "right " << right << '\n';
     // std::cout << "cfwhm " << cfwhm << '\n';
     return cfwhm * (right - left);
 }
void LHCNoiseFB::fwhm_multi_bunch ()
Definition at line 152 of file LHCNoiseFB.cpp.
References fBlMeas, fBlMeasBBB, fBunchPattern, fwhm_interpolation(), blond::mymath::mean(), blond::RfParameters::phi_rf, blond::constant::pi, blond::Context::RfP, and blond::Context::Slice.
Referenced by LHCNoiseFB().
{
     // Multi-bunch FWHM bunch length calculation with interpolation.*
     auto Slice = Context::Slice;
     auto RfP = Context::RfP;
     // Find correct RF buckets
     auto phi_rf = RfP->phi_rf[0][RfP->counter];
     auto omega_rf = RfP->omega_rf[0][RfP->counter];
     // std::cout << phi_rf << "\n";
     // std::cout << omega_rf << "\n";
     f_vector_t bucket_min(fBunchPattern.size());
     for (uint i = 0; i < bucket_min.size(); ++i)
         bucket_min[i] =
             (phi_rf + 2 * constant::pi * fBunchPattern[i]) / omega_rf;
     f_vector_t bucket_max(bucket_min.size());
     for (uint i = 0; i < bucket_min.size(); ++i)
         bucket_max[i] = bucket_min[i] + 2 * constant::pi / omega_rf;
     // Bunch-by-bunch FWHM bunch length
     for (uint i = 0; i < fBunchPattern.size(); ++i) {
         uint_vector_t bind;
         for (int j = 0; j < Slice->n_slices; ++j) {
             if ((Slice->bin_centers[j] - bucket_min[i]) *
                     (Slice->bin_centers[j] - bucket_max[i]) < 0)
                 bind.push_back(j);
         }
         double hheight = 0;
         for (const auto& j : bind) {
             if (Slice->n_macroparticles[j] > hheight)
                 hheight = Slice->n_macroparticles[j];
         }
         hheight = hheight / 2;
         uint_vector_t index;
         auto k = 0;
         for (const auto &j : bind) {
             if (Slice->n_macroparticles[j] > hheight)
                 index.push_back(bind[k]);
             k++;
         }
         // std::cout << "index size = " << index.size() << "\n";
         if (index.empty()) {
             // std::cerr << "[LHCNoiseFB] ERROR! index vector should have at least one element\n";
             continue;
         }
         fBlMeasBBB[i] = fwhm_interpolation(index, hheight);
     }
     fBlMeas = mymath::mean(fBlMeasBBB.data(), fBlMeasBBB.size());
 }
void LHCNoiseFB::fwhm_single_bunch ()
Definition at line 129 of file LHCNoiseFB.cpp.
References fBlMeas, fwhm_interpolation(), blond::mymath::max(), and blond::Context::Slice.
Referenced by LHCNoiseFB().
{
     auto Slice = Context::Slice;
     // Single-bunch FWHM bunch length calculation with interpolation.
     auto i = mymath::max(Slice->n_macroparticles.data(), Slice->n_slices);
     double half_height = Slice->n_macroparticles[i] / 2;
     uint_vector_t index;
     for (int i = 0; i < Slice->n_slices; ++i)
         if (Slice->n_macroparticles[i] > half_height)
             index.push_back(i);
     if (index.empty()) {
         // std::cerr << "[LHCNoiseFB] ERROR! index vector should have at least
         // one element\n";
         return;
     }
     fBlMeas = fwhm_interpolation(index, half_height);
 }
void LHCNoiseFB::track ()
Definition at line 54 of file LHCNoiseFB.cpp.
References fA, fBlMeas, fBlTarg, fFwhm, fG, fNUpdate, fX, blond::mymath::max(), blond::mymath::min(), and blond::Context::RfP.
{
     auto RfP = Context::RfP;
     // Calculate PhaseNoise Feedback scaling factor as a function of measured
     // FWHM bunch length.*
     // Track only in certain turns
     if (RfP->counter % fNUpdate == 0) {
         // Update bunch length, every x turns determined in main file
         fFwhm();
         // Update noise amplitude-scaling factor
         fX = fA * fX + fG[RfP->counter] * (fBlTarg - fBlMeas);
         // Limit to range [0,1]
         fX = std::max(fX, 0.0);
         fX = std::min(fX, 1.0);
         // std::cout.precision(6);
         // std::cout << std::scientific << std::showpos;
         // std::cout << "fA " << fA << "\n";
         // std::cout << "fX " << fX << "\n";
         // std::cout << "fG[counter] " << fG[RfP->counter] << "\n";
         // std::cout << "fBlTarg " << fBlTarg << "\n";
         // std::cout << "fBlMeas " << fBlMeas << "\n";
     }
 }
Member Data Documentation
const double LHCNoiseFB::cfwhm = std::sqrt(2.0 / std::log(2.0)) static private
Definition at line 28 of file LHCNoiseFB.h.
Referenced by fwhm_interpolation().
double blond::LHCNoiseFB::fA
Definition at line 41 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), and track().
double blond::LHCNoiseFB::fBlMeas
Definition at line 38 of file LHCNoiseFB.h.
Referenced by fwhm_multi_bunch(), fwhm_single_bunch(), LHCNoiseFB(), and track().
f_vector_t blond::LHCNoiseFB::fBlMeasBBB
Definition at line 55 of file LHCNoiseFB.h.
Referenced by fwhm_multi_bunch(), and LHCNoiseFB().
double blond::LHCNoiseFB::fBlTarg
Definition at line 35 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), and track().
f_vector_t blond::LHCNoiseFB::fBunchPattern
Definition at line 53 of file LHCNoiseFB.h.
Referenced by fwhm_multi_bunch(), and LHCNoiseFB().
std::function<void()> blond::LHCNoiseFB::fFwhm
Definition at line 57 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), and track().
f_vector_t blond::LHCNoiseFB::fG
Definition at line 50 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), and track().
uint blond::LHCNoiseFB::fNUpdate
Definition at line 44 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), and track().
bool blond::LHCNoiseFB::fVariableGain
Definition at line 47 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB().
double blond::LHCNoiseFB::fX
Definition at line 32 of file LHCNoiseFB.h.
Referenced by LHCNoiseFB(), blond::PhaseLoop::phase_difference(), and track().