var searchData=
[
  ['matched_5ffrom_5fdistribution_5fdensity',['matched_from_distribution_density',['../db/de1/Distributions_8cpp.html#a16a9cf8e5241880f98a62832f9506378',1,'matched_from_distribution_density(FullRingAndRf *full_ring, map&lt; string, string &gt; distribution_opt, string main_harmonic, int n_iterations_input, map&lt; string, string &gt; extraVoltageDict, int seed):&#160;Distributions.cpp'],['../dc/d7d/Distributions_8h.html#a39ba163b714fe197bd81ac64ffa48d30',1,'matched_from_distribution_density(FullRingAndRf *full_ring, std::map&lt; std::string, std::string &gt; distribution_opt, std::string main_harmonic=&quot;lowest_freq&quot;, int n_iterations_input=1, std::map&lt; std::string, std::string &gt; extraVoltageDict=std::map&lt; std::string, std::string &gt;(), int seed=0):&#160;Distributions.cpp']]],
  ['matched_5ffrom_5fline_5fdensity',['matched_from_line_density',['../db/de1/Distributions_8cpp.html#a9c7a5b9b2b4eea6f572d0fa77ba94d6f',1,'matched_from_line_density(Beams *beam, FullRingAndRf *full_ring, map&lt; string, string &gt; line_density_opt, string main_harmonic, TotalInducedVoltage *totVolt, string plot, string figdir, string half_option, map&lt; string, string &gt; extraVoltageDict, int n_iterations_input, int seed):&#160;Distributions.cpp'],['../dc/d7d/Distributions_8h.html#aa18b9fc400fa994778e7e811423c2f06',1,'matched_from_line_density(Beams *beam, FullRingAndRf *full_ring, std::map&lt; std::string, std::string &gt; line_density_opt, std::string main_harmonic=&quot;lowest_freq&quot;, TotalInducedVoltage *totVolt=nullptr, std::string plot=&quot;&quot;, std::string figdir=&quot;fig&quot;, std::string half_option=&quot;first&quot;, std::map&lt; std::string, std::string &gt; extraVoltageDict=std::map&lt; std::string, std::string &gt;(), int n_iterations_input=100, int seed=0):&#160;Distributions.cpp']]],
  ['max',['max',['../df/d6d/namespacemymath.html#a2a11685fa6ce2396ae977fa1502a2cc4',1,'mymath']]],
  ['mean',['mean',['../df/d6d/namespacemymath.html#ac815b54cedc0318b700fb483ee23ec2e',1,'mymath']]],
  ['min',['min',['../df/d6d/namespacemymath.html#a5bcc40b5ebadd9d98f351775df65ec9f',1,'mymath']]],
  ['minmax_5flocation',['minmax_location',['../db/de1/Distributions_8cpp.html#abbfebf0ac4f8db4363af627e88a18b5e',1,'minmax_location(f_vector_t &amp;x, f_vector_t &amp;f, f_vector_t &amp;min_x_position, f_vector_t &amp;max_x_position, f_vector_t &amp;min_values, f_vector_t &amp;max_values):&#160;Distributions.cpp'],['../dc/d7d/Distributions_8h.html#abbfebf0ac4f8db4363af627e88a18b5e',1,'minmax_location(f_vector_t &amp;x, f_vector_t &amp;f, f_vector_t &amp;min_x_position, f_vector_t &amp;max_x_position, f_vector_t &amp;min_values, f_vector_t &amp;max_values):&#160;Distributions.cpp']]]
];
