Beam Longitudinal Dynamics code (BLonD): TotalInducedVoltage Class Reference
TotalInducedVoltage Class Reference
#include <InducedVoltage.h>
Public Member Functions
TotalInducedVoltage (Beams *beam, Slices *slices, std::vector< InducedVoltage * > &InducedVoltageList, uint NTurnsMemory=0, f_vector_t RevTimeArray=f_vector_t())
~TotalInducedVoltage ()
f_vector_t induced_voltage_generation (Beams *beam, uint length=0)
f_vector_t induced_voltage_sum (Beams *beam, uint length=0)
void reprocess (Slices *newSlices)
void track (Beams *beam)
void track_ghosts_particles (Beams *ghostBeam)
void track_memory ()
Public Member Functions inherited from InducedVoltage
InducedVoltage ()
virtual ~InducedVoltage ()
Public Attributes
Beams * fBeam
uint fCounterTurn = 0
std::vector< InducedVoltage * > fInducedVoltageList
bool fInductiveImpedanceOn = false
uint fNTurnsMemory
f_vector_t fRevTimeArray
f_vector_t fTimeArray
Public Attributes inherited from InducedVoltage
f_vector_t fInducedVoltage
Slices * fSlices
Detailed Description
Definition at line 119 of file InducedVoltage.h.
Constructor & Destructor Documentation
TotalInducedVoltage::TotalInducedVoltage (Beams * beam, Slices * slices, std::vector< InducedVoltage * > & InducedVoltageList, uint NTurnsMemory = 0, f_vector_t RevTimeArray = f_vector_t())
Definition at line 434 of file InducedVoltage.cpp.
References Slices::bin_centers, fBeam, InducedVoltage::fInducedVoltage, fInducedVoltageList, fNTurnsMemory, InducedVoltage::fSlices, and fTimeArray.
 {
     fBeam = beam;
     fSlices = slices;
     fInducedVoltageList = InducedVoltageList;
     fNTurnsMemory = NTurnsMemory;
     fInducedVoltage = f_vector_t();
     fTimeArray = fSlices->bin_centers;
 }
TotalInducedVoltage::~TotalInducedVoltage ()
Definition at line 446 of file InducedVoltage.cpp.
References fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
f_vector_t TotalInducedVoltage::induced_voltage_generation (Beams * beam, uint length = 0) inline virtual
Implements InducedVoltage.
Definition at line 136 of file InducedVoltage.h.
     {
         return f_vector_t();
     };
f_vector_t TotalInducedVoltage::induced_voltage_sum (Beams * beam, uint length = 0)
Definition at line 475 of file InducedVoltage.cpp.
References InducedVoltage::fInducedVoltage, and fInducedVoltageList.
Referenced by track().
 {
     // Method to sum all the induced voltages in one single array.
     f_vector_t tempIndVolt;
     f_vector_t extIndVolt;
     for (auto &v : fInducedVoltageList) {
         auto a = v->induced_voltage_generation(beam, length);
         if (length > 0) {
             extIndVolt.resize(a.size(), 0);
             std::transform(extIndVolt.begin(), extIndVolt.end(), a.begin(),
                            extIndVolt.begin(), std::plus<double>());
         }
         tempIndVolt.resize(v->fInducedVoltage.size(), 0);
         std::transform(tempIndVolt.begin(), tempIndVolt.end(),
                        v->fInducedVoltage.begin(), tempIndVolt.begin(),
                        std::plus<double>());
     }
     fInducedVoltage = tempIndVolt;
     return extIndVolt;
 }
void TotalInducedVoltage::reprocess (Slices * newSlices) virtual
Implements InducedVoltage.
Definition at line 467 of file InducedVoltage.cpp.
References fInducedVoltageList, and InducedVoltage::fSlices.
 {
     fSlices = newSlices;
     for (auto &v : fInducedVoltageList)
         v->reprocess(newSlices);
 }
void TotalInducedVoltage::track (Beams * beam) virtual
Implements InducedVoltage.
Definition at line 449 of file InducedVoltage.cpp.
References Slices::bin_centers, Beams::charge, Beams::dE, Beams::dt, InducedVoltage::fInducedVoltage, InducedVoltage::fSlices, induced_voltage_sum(), linear_interp_kick(), Beams::n_macroparticles, and Slices::n_slices.
 {
     this->induced_voltage_sum(beam);
     auto v = this->fInducedVoltage;
     std::transform(v.begin(), v.end(), v.begin(),
                    std::bind1st(std::multiplies<double>(), beam->charge));
     linear_interp_kick(beam->dt.data(), beam->dE.data(), v.data(),
                        fSlices->bin_centers.data(), fSlices->n_slices,
                        beam->n_macroparticles);
 }
void TotalInducedVoltage::track_ghosts_particles (Beams * ghostBeam)
Definition at line 465 of file InducedVoltage.cpp.
 {}
void TotalInducedVoltage::track_memory ()
Definition at line 463 of file InducedVoltage.cpp.
 {}
Member Data Documentation
Beams* TotalInducedVoltage::fBeam
Definition at line 128 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().
uint TotalInducedVoltage::fCounterTurn = 0
Definition at line 124 of file InducedVoltage.h.
std::vector<InducedVoltage *> TotalInducedVoltage::fInducedVoltageList
Definition at line 121 of file InducedVoltage.h.
Referenced by induced_voltage_sum(), reprocess(), and TotalInducedVoltage().
bool TotalInducedVoltage::fInductiveImpedanceOn = false
Definition at line 126 of file InducedVoltage.h.
uint TotalInducedVoltage::fNTurnsMemory
Definition at line 125 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().
f_vector_t TotalInducedVoltage::fRevTimeArray
Definition at line 123 of file InducedVoltage.h.
f_vector_t TotalInducedVoltage::fTimeArray
Definition at line 122 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().