Beam Longitudinal Dynamics code (BLonD): blond::Slices Class Reference
blond::Slices Class Reference
#include <Slices.h>
Public Types
enum cuts_unit_t { s, rad }
enum fit_t { normal, gaussian }
Public Member Functions
Slices (RfParameters *RfP, Beams *Beam, int _n_slices, int _n_sigma=0, double cut_left=0, double cut_right=0, cuts_unit_t cuts_unit=s, fit_t fit_option=normal, bool direct_slicing=false)
~Slices ()
void beam_profile_derivative (f_vector_t &x, f_vector_t &derivative, std::string mode="gradient")
void beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int &nCoefficients, f_vector_t &b, f_vector_t &a)
void beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int &nCoefficients, f_vector_t &transferFreq, complex_vector_t &transferGain)
void beam_spectrum_generation (int n, bool onlyRFFT=false)
double convert_coordinates (double cut, cuts_unit_t type)
void fwhm (const double shift=0)
void fwhm_multibunch ()
void gaussian_fit ()
void histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
void rms ()
void set_cuts ()
void slice_constant_space_histogram ()
void slice_constant_space_histogram_smooth ()
void smooth_histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
void sort_particles ()
void track ()
void track_cuts ()
Public Attributes
Beams * beam
f_vector_t bin_centers
double bl_fwhm
double bl_gauss
double bl_rms
double bp_fwhm
double bp_gauss
double bp_rms
double cut_left
double cut_right
cuts_unit_t cuts_unit
f_vector_t edges
complex_vector_t fBeamSpectrum
f_vector_t fBeamSpectrumFreq
fit_t fit_option
f_vector_t n_macroparticles
int n_sigma
int n_slices
RfParameters * rfp
Private Member Functions
f_vector_t gaussian_filter1d (f_vector_t &x, int sigma, int order, std::string mode)
f_vector_t gradient (f_vector_t &x, double dist)
Private Attributes
const double cfwhm = 2 * std::sqrt(2 * std::log(2))
double * thread_hist
Detailed Description
Definition at line 22 of file Slices.h.
Member Enumeration Documentation
enum blond::Slices::cuts_unit_t
Enumerator
s
rad
Definition at line 31 of file Slices.h.
 { s, rad };
enum blond::Slices::fit_t
Enumerator
normal
gaussian
Definition at line 32 of file Slices.h.
 { normal, gaussian };
Constructor & Destructor Documentation
Slices::Slices (RfParameters * RfP, Beams * Beam, int _n_slices, int _n_sigma = 0, double cut_left = 0, double cut_right = 0, cuts_unit_t cuts_unit = s, fit_t fit_option = normal, bool direct_slicing = false)
Definition at line 17 of file Slices.cpp.
References blond::omp_get_max_threads().
 {
     beam = Beam;
     rfp = RfP;
     this->n_slices = n_slices;
     this->cut_left = cut_left;
     this->cut_right = cut_right;
     this->cuts_unit = cuts_unit;
     this->fit_option = fit_option;
     this->n_sigma = n_sigma;
     this->n_macroparticles.resize(n_slices, 0);
     this->edges.resize(n_slices + 1, 0.0);
     this->bin_centers.resize(n_slices, 0.0);
     this->thread_hist = (double *) malloc(n_slices * omp_get_max_threads()
                                           * sizeof(double));
     set_cuts();
     if (fit_option == gaussian) {
         bl_gauss = 0.0;
         bp_gauss = 0.0;
     }
     if (direct_slicing) track();
 }
Slices::~Slices ()
Definition at line 46 of file Slices.cpp.
References blond::fft::destroy_plans().
 {
     fft::destroy_plans();
     if (thread_hist) free(thread_hist);
 }
Member Function Documentation
void Slices::beam_profile_derivative (f_vector_t & x, f_vector_t & derivative, std::string mode = "gradient")
Definition at line 361 of file Slices.cpp.
References blond::mymath::interp().
Referenced by blond::plot_beam_profile_derivative().
 {
     /*
     The input is one of the two available methods for differentiating
     a function. The two outputs are the coordinate step and the discrete
     derivative of the Beam profile respectively.
     */
     x = bin_centers;
     const auto dist_centers = x[1] - x[0];
     if (mode == "filter1d") {
         derivative = gaussian_filter1d(n_macroparticles, 1, 1, "wrap");
         for (auto &d : derivative) d /= dist_centers;
     } else if (mode == "gradient") {
         derivative = gradient(n_macroparticles, dist_centers);
     } else if (mode == "diff") {
         derivative.resize(n_macroparticles.size() - 1);
         for (uint i = 1; i < n_macroparticles.size(); i++)
             derivative[i - 1] = (n_macroparticles[i] - n_macroparticles[i - 1])
                                 / dist_centers;
         f_vector_t diffCenters(x.begin(), x.end() - 1);
         diffCenters += dist_centers / 2.;
         derivative = mymath::interp(x, diffCenters, derivative);
     } else {
         std::cerr << "Option for derivative is not recognized.\n";
         exit(-1);
     }
 }
void Slices::beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int & nCoefficients, f_vector_t & b, f_vector_t & a)
Definition at line 434 of file Slices.cpp.
References blond::python::convert_dictionary(), blond::python::convert_double(), blond::python::convert_double_array(), blond::python::convert_int(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("utilities", "beam_profile_filter_chebyshev");
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pResolution = python::convert_double(bin_centers[1] - bin_centers[0]);
     auto pNSlices = python::convert_int(n_slices);
     if (filter_option.find("transfer_function_plot") != filter_option.end()
             && filter_option["transfer_function_plot"] == "true") {
         std::cerr << "[beam_profile_filter_chebyshev] A complex vector must\n"
                   << "be pased as the last argument in order to call this\n"
                   << "function with transfer_function_plot ==true\n";
         exit(-1);
     }
     auto pFilterOption = python::convert_dictionary(filter_option);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pNMacroparticles,
                                             pResolution, pNSlices,
                                             pFilterOption, NULL);
     if (!ret) {
         std::cerr << "[beam_profile_filter_chebyshev] An error occured "
                   << "while running a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     nCoefficients = res[0];
     assert(len == 3 + 2 * nCoefficients);
     b = f_vector_t(&res[1], &res[1 + 1 + nCoefficients]);
     a = f_vector_t(&res[2 + nCoefficients], &res[3 + 2 * nCoefficients]);
 }
void Slices::beam_profile_filter_chebyshev (std::map< std::string, std::string > filter_option, int & nCoefficients, f_vector_t & transferFreq, complex_vector_t & transferGain)
Definition at line 478 of file Slices.cpp.
References blond::python::convert_dictionary(), blond::python::convert_double(), blond::python::convert_double_array(), blond::python::convert_int(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("utilities", "beam_profile_filter_chebyshev");
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pResolution = python::convert_double(bin_centers[1] - bin_centers[0]);
     auto pNSlices = python::convert_int(n_slices);
     if (filter_option.find("transfer_function_plot") == filter_option.end()
             || filter_option["transfer_function_plot"] != "true") {
         std::cerr << "[beam_profile_filter_chebyshev] A double vector must\n"
                   << "be pased as the last argument in order to call this\n"
                   << "function without transfer_function_plot == true\n";
         exit(-1);
     }
     auto pFilterOption = python::convert_dictionary(filter_option);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pNMacroparticles,
                                             pResolution, pNSlices,
                                             pFilterOption, NULL);
     if (!ret) {
         std::cerr << "[beam_profile_filter_chebyshev] An error occured "
                   << "while running a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     assert(len == 1 + 3 * n_slices);
     nCoefficients = res[0];
     transferFreq = f_vector_t(&res[1], &res[1 + n_slices]);
     for (int i = 1 + n_slices; i < 1 + 2 * n_slices; i++) {
         transferGain.push_back({res[i], res[i + n_slices]});
     }
 }
void Slices::beam_spectrum_generation (int n, bool onlyRFFT = false)
Definition at line 350 of file Slices.cpp.
References blond::Context::n_threads, blond::fft::rfft(), and blond::fft::rfftfreq().
Referenced by blond::InducedVoltageFreq::induced_voltage_generation(), and blond::InducedVoltageFreq::reprocess().
 {
     fBeamSpectrumFreq = fft::rfftfreq(n, bin_centers[1] - bin_centers[0]);
     if (onlyRFFT == false) {
         auto v = n_macroparticles;
         fft::rfft(v, fBeamSpectrum, n, Context::n_threads);
     }
 }
double Slices::convert_coordinates (double cut, cuts_unit_t type)
Definition at line 117 of file Slices.cpp.
 {
     /*
     *Method to convert a value from one input_unit_type to 's'.*
     */
     if (type == s)
         return cut;
     else  /*if (type == rad)*/
         return cut / rfp->omega_rf[0][rfp->counter];
 }
void Slices::fwhm (const double shift = 0)
Definition at line 275 of file Slices.cpp.
References ALL, and blond::mymath::max().
 {
     /*
     * Computation of the bunch length and position from the FWHM
     assuming Gaussian line density.*
     */
     double max = *max_element(ALL(n_macroparticles));
     double half_max = shift + 0.5 * (max - shift);
     double timeResolution = bin_centers[1] - bin_centers[0];
     // First aproximation for the half maximum values
     int taux1, taux2;
     int i = 0;
     while (i < n_slices && n_macroparticles[i] < half_max) i++;
     taux1 = i;
     // prev1 is one before taux1, if taux1 is 0, then prev1 is the last
     int prev1 = taux1 > 0 ? taux1 - 1 : n_slices - 1;
     i = n_slices - 1;
     while (i >= 0 && n_macroparticles[i] < half_max) i--;
     taux2 = i;
     double t1, t2;
     if (taux1 < n_slices && taux2 < n_slices - 1 && taux2 >= 0) {
         t1 = bin_centers[taux1] -
              (n_macroparticles[taux1] - half_max) /
              (n_macroparticles[taux1] - n_macroparticles[prev1]) *
              timeResolution;
         t2 = bin_centers[taux2] +
              (n_macroparticles[taux2] - half_max) /
              (n_macroparticles[taux2] - n_macroparticles[taux2 + 1]) *
              timeResolution;
         bl_fwhm = 4 * (t2 - t1) / cfwhm;
         bp_fwhm = (t1 + t2) / 2;
     } else {
         bl_fwhm = nan("");
         bp_fwhm = nan("");
     }
 }
void Slices::fwhm_multibunch ()
Definition at line 346 of file Slices.cpp.
 {
 }
f_vector_t Slices::gaussian_filter1d (f_vector_t & x, int sigma, int order, std::string mode) private
Definition at line 396 of file Slices.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("utilities", "gaussian_filter1d");
     auto pX = python::convert_double_array(x.data(), x.size());
     auto pSigma = python::convert_int(sigma);
     auto pOrder = python::convert_int(order);
     auto pMode = python::convert_string(mode);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pSigma, pOrder, pMode,
                                             NULL);
     assert(ret);
     auto npArray = (PyArrayObject *)(ret);
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     return f_vector_t(&res[0], &res[len]);
 }
void Slices::gaussian_fit ()
Definition at line 523 of file Slices.cpp.
References ALL, blond::python::convert_double_array(), blond::python::import(), blond::mymath::max(), blond::mymath::mean(), and blond::mymath::standard_deviation().
 {
     f_vector_t p0;
     double max = *std::max_element(ALL(n_macroparticles));
     if (bl_gauss == 0 && bp_gauss == 0) {
         p0 = {max,
               mymath::mean(beam->dt),
               mymath::standard_deviation(beam->dt)
              };
     } else {
         p0 = {max,
               bp_gauss,
               bl_gauss / 4
              };
     }
     python::import();
     auto pFunc = python::import("utilities", "curve_fit");
     auto pBinCenters = python::convert_double_array(bin_centers.data(),
                        bin_centers.size());
     auto pNMacroparticles = python::convert_double_array(n_macroparticles.data(),
                             n_macroparticles.size());
     auto pP0 = python::convert_double_array(p0.data(), p0.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBinCenters,
                                             pNMacroparticles, pP0, NULL);
     if (!ret) {
         std::cerr << "[gaussian_fit] An error occured while running"
                   << "a python function\n";
         exit(-1);
     }
     auto npArray = (PyArrayObject *) ret;
     int len = PyArray_SHAPE(npArray)[0];
     double *pfit_gauss = (double *) PyArray_DATA(npArray);
     bl_gauss = 4 * std::abs(pfit_gauss[2]);
     bp_gauss = std::abs(pfit_gauss[1]);
 }
f_vector_t Slices::gradient (f_vector_t & x, double dist) private
Definition at line 416 of file Slices.cpp.
References blond::python::convert_double(), blond::python::convert_double_array(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("utilities", "gradient");
     auto pX = python::convert_double_array(x.data(), x.size());
     auto pDist = python::convert_double(dist);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pDist, NULL);
     assert(ret);
     auto npArray = (PyArrayObject *)(ret);
     int len = PyArray_SHAPE(npArray)[0];
     double *res = (double *) PyArray_DATA(npArray);
     return f_vector_t(&res[0], &res[len]);
 }
void Slices::histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
Definition at line 152 of file Slices.cpp.
References blond::omp_get_num_threads(), and blond::omp_get_thread_num().
 {
     const double inv_bin_width = n_slices / (cut_right - cut_left);
     #pragma omp parallel
     {
         const int id = omp_get_thread_num();
         const int threads = omp_get_num_threads();
         double *h_row = &thread_hist[id * n_slices];
         memset(h_row, 0., n_slices * sizeof(double));
         #pragma omp for
         for (int i = 0; i < n_macroparticles; ++i) {
             if (input[i] < cut_left || input[i] > cut_right) continue;
             h_row[(int)((input[i] - cut_left)*inv_bin_width)] += 1.;
         }
         #pragma omp for
         for (int i = 0; i < n_slices; i++) {
             output[i] = 0.;
             for (int t = 0; t < threads; t++)
                 output[i] += thread_hist[t * n_slices + i];
         }
     }
 }
void Slices::rms ()
Definition at line 254 of file Slices.cpp.
References blond::apply_f(), and blond::mymath::trapezoid().
 {
     /*
     * Computation of the RMS bunch length and position from the line density
     (bunch length = 4sigma).*
     */
     const auto timeResolution = bin_centers[1] - bin_centers[0];
     const auto trap = mymath::trapezoid(n_macroparticles, timeResolution);
     auto lineDen = n_macroparticles / trap;
     bp_rms = mymath::trapezoid(bin_centers * lineDen, timeResolution);
     auto temp = mymath::trapezoid(
                     apply_f(bin_centers - bp_rms,
     [](double x) {return x * x; }) * lineDen, timeResolution);
     bl_rms = 4 * std::sqrt(temp);
 }
void Slices::set_cuts ()
Definition at line 52 of file Slices.cpp.
References blond::mymath::linspace(), blond::mymath::mean(), and blond::mymath::standard_deviation().
 {
     /*
     *Method to set the self.cut_left and self.cut_right properties. This is
     done as a pre-processing if the mode is set to 'const_space', for
     'const_charge' this is calculated each turn.*
     *The frame is defined by :math:`n\sigma_{RMS}` or manually by the user.
     If not, a default frame consisting of taking the whole bunch +5% of the
     maximum distance between two particles in the bunch will be taken
     in each side of the frame.*
     */
     if (cut_left == 0 && cut_right == 0) {
         if (n_sigma == 0) {
             sort_particles();
             cut_left =
                 beam->dt.front() - 0.05 * (beam->dt.back() - beam->dt.front());
             cut_right =
                 beam->dt.back() + 0.05 * (beam->dt.back() - beam->dt.front());
         } else {
             double mean_coords = mymath::mean(beam->dt.data(), beam->dt.size());
             double sigma_coords = mymath::standard_deviation(
                                       beam->dt.data(), beam->dt.size(), mean_coords);
             cut_left = mean_coords - n_sigma * sigma_coords / 2;
             cut_right = mean_coords + n_sigma * sigma_coords / 2;
         }
     } else {
         cut_left = convert_coordinates(cut_left, cuts_unit);
         cut_right = convert_coordinates(cut_right, cuts_unit);
     }
     mymath::linspace(edges.data(), cut_left, cut_right, n_slices + 1);
     for (uint i = 0; i < bin_centers.size(); ++i)
         bin_centers[i] = (edges[i + 1] + edges[i]) / 2;
 }
void Slices::slice_constant_space_histogram ()
Definition at line 137 of file Slices.cpp.
 {
     /*
     *Constant space slicing with the built-in numpy histogram function,
     with a constant frame. This gives the same profile as the
     slice_constant_space method, but no compute statistics possibilities
     (the index of the particles is needed).*
     *This method is faster than the classic slice_constant_space method
     for high number of particles (~1e6).*
     */
     histogram(beam->dt.data(), n_macroparticles.data(), cut_left, cut_right,
               n_slices, beam->n_macroparticles);
 }
void Slices::slice_constant_space_histogram_smooth ()
Definition at line 245 of file Slices.cpp.
 {
     /*
     At the moment 4x slower than slice_constant_space_histogram but smoother.
     */
     smooth_histogram(beam->dt.data(), n_macroparticles.data(), cut_left,
                      cut_right, n_slices, beam->n_macroparticles);
 }
void Slices::smooth_histogram (const double *__restrict input, double *__restrict output, const double cut_left, const double cut_right, const int n_slices, const int n_macroparticles)
Definition at line 201 of file Slices.cpp.
 {
     int i;
     double a;
     double fbin;
     double ratioffbin;
     double ratiofffbin;
     double distToCenter;
     int ffbin = 0;
     int fffbin = 0;
     const double inv_bin_width = n_slices / (cut_right - cut_left);
     const double bin_width = (cut_right - cut_left) / n_slices;
     for (i = 0; i < n_slices; i++) {
         output[i] = 0;
     }
     for (i = 0; i < n_macroparticles; i++) {
         a = input[i];
         if ((a < (cut_left + bin_width * 0.5)) ||
                 (a > (cut_right - bin_width * 0.5)))
             continue;
         fbin = (a - cut_left) * inv_bin_width;
         ffbin = (int)(fbin);
         distToCenter = fbin - (double)(ffbin);
         if (distToCenter > 0.5)
             fffbin = (int)(fbin + 1.0);
         ratioffbin = 1.5 - distToCenter;
         ratiofffbin = 1 - ratioffbin;
         if (distToCenter < 0.5)
             fffbin = (int)(fbin - 1.0);
         ratioffbin = 0.5 - distToCenter;
         ratiofffbin = 1 - ratioffbin;
         output[ffbin] = output[ffbin] + ratioffbin;
         output[fffbin] = output[fffbin] + ratiofffbin;
     }
 }
void Slices::sort_particles ()
Definition at line 88 of file Slices.cpp.
References blond::operator<().
 {
     /*
     *Sort the particles with respect to their position.*
     */
     struct particle {
         double dE;
         double dt;
         int id;
         bool operator<(const particle &other) const
         {
             return dt < other.dt;
         }
     };
     std::vector<particle> particles(beam->dE.size());
     for (uint i = 0; i < particles.size(); i++)
         particles[i] = {beam->dE[i], beam->dt[i], beam->id[i]};
     std::sort(particles.begin(), particles.end());
     for (uint i = 0; i < particles.size(); i++) {
         beam->dE[i] = particles[i].dE;
         beam->dt[i] = particles[i].dt;
         beam->id[i] = particles[i].id;
     }
 }
void Slices::track ()
Definition at line 130 of file Slices.cpp.
 {
     slice_constant_space_histogram();
     if (fit_option == fit_t::gaussian)
         gaussian_fit();
 }
void Slices::track_cuts ()
Definition at line 185 of file Slices.cpp.
 {
     /*
     *Track the slice frame (limits and slice position) as the mean of the
     bunch moves.
     Requires Beam statistics!
     Method to be refined!*
     */
     double delta = beam->mean_dt - 0.5 * (cut_left + cut_right);
     cut_left += delta;
     cut_right += delta;
     edges += delta;
     bin_centers += delta;
 }
Member Data Documentation
Beams* blond::Slices::beam
Definition at line 34 of file Slices.h.
f_vector_t blond::Slices::bin_centers
Definition at line 46 of file Slices.h.
Referenced by blond::LHCNoiseFB::fwhm_interpolation(), blond::InducedVoltageFreq::InducedVoltageFreq(), blond::InducedVoltageTime::InducedVoltageTime(), blond::plot_beam_profile(), blond::plot_induced_voltage_vs_bin_centers(), blond::InducedVoltageTime::reprocess(), blond::InducedVoltageFreq::reprocess(), blond::RingAndRfSection::rf_voltage_calculation(), blond::TotalInducedVoltage::TotalInducedVoltage(), blond::InducedVoltageTime::track(), blond::InducedVoltageFreq::track(), and blond::TotalInducedVoltage::track().
double blond::Slices::bl_fwhm
Definition at line 37 of file Slices.h.
double blond::Slices::bl_gauss
Definition at line 50 of file Slices.h.
double blond::Slices::bl_rms
Definition at line 38 of file Slices.h.
double blond::Slices::bp_fwhm
Definition at line 37 of file Slices.h.
double blond::Slices::bp_gauss
Definition at line 51 of file Slices.h.
double blond::Slices::bp_rms
Definition at line 38 of file Slices.h.
const double blond::Slices::cfwhm = 2 * std::sqrt(2 * std::log(2)) private
Definition at line 24 of file Slices.h.
double blond::Slices::cut_left
Definition at line 40 of file Slices.h.
double blond::Slices::cut_right
Definition at line 41 of file Slices.h.
cuts_unit_t blond::Slices::cuts_unit
Definition at line 43 of file Slices.h.
f_vector_t blond::Slices::edges
Definition at line 45 of file Slices.h.
Referenced by blond::InducedVoltageFreq::InducedVoltageFreq().
complex_vector_t blond::Slices::fBeamSpectrum
Definition at line 48 of file Slices.h.
Referenced by blond::InducedVoltageFreq::induced_voltage_generation(), blond::plot_beam_spectrum(), and blond::plot_impedance_vs_frequency().
f_vector_t blond::Slices::fBeamSpectrumFreq
Definition at line 49 of file Slices.h.
Referenced by blond::InducedVoltageFreq::induced_voltage_generation(), blond::plot_beam_spectrum(), blond::plot_impedance_vs_frequency(), and blond::InducedVoltageFreq::reprocess().
fit_t blond::Slices::fit_option
Definition at line 47 of file Slices.h.
f_vector_t blond::Slices::n_macroparticles
Definition at line 44 of file Slices.h.
Referenced by blond::InducedVoltageTime::induced_voltage_generation(), blond::matched_from_line_density(), and blond::plot_beam_profile().
int blond::Slices::n_sigma
Definition at line 42 of file Slices.h.
int blond::Slices::n_slices
Definition at line 39 of file Slices.h.
Referenced by blond::InducedVoltageTime::induced_voltage_generation(), blond::InducedVoltageFreq::induced_voltage_generation(), blond::InducedVoltageFreq::InducedVoltageFreq(), blond::InducedVoltageTime::InducedVoltageTime(), blond::InducedVoltageTime::reprocess(), blond::InducedVoltageFreq::reprocess(), blond::InducedVoltageTime::track(), blond::InducedVoltageFreq::track(), and blond::TotalInducedVoltage::track().
RfParameters* blond::Slices::rfp
Definition at line 35 of file Slices.h.
Referenced by blond::matched_from_line_density().
double* blond::Slices::thread_hist private
Definition at line 25 of file Slices.h.