Beam Longitudinal Dynamics code (BLonD): Monitors.h File Reference
Monitors.h File Reference
#include <H5Cpp.h>
#include <hdf5.h>
#include <hdf5_hl.h>
#include <blond/configuration.h>
#include <blond/utilities.h>
#include <blond/beams/Beams.h>
#include <blond/beams/Slices.h>
#include <blond/input_parameters/GeneralParameters.h>
#include <blond/input_parameters/RfParameters.h>
#include <blond/llrf/PhaseLoop.h>
#include <blond/llrf/LHCNoiseFB.h>
Classes
class BunchMonitor
class SlicesMonitor
Functions
void * read_1D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
void * read_2D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
Function Documentation
void* read_1D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
Definition at line 42 of file Monitors.cpp.
Referenced by plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), and plot_transmitted_particles().
 {
     auto file_id = H5Fopen(fname.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
     H5T_class_t class_id;
     size_t type_size;
     H5LTget_dataset_info(file_id, dsname.c_str(),
                          dims, &class_id, &type_size);
     std::transform(type.begin(), type.end(), type.begin(), ::tolower);
     void *res = NULL;
     if (type == "int" && sizeof(int) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_int(file_id, dsname.c_str(), (int *)res);
     } else if (type == "double" && sizeof(double) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_double(file_id, dsname.c_str(), (double *)res);
     } else if (type == "float" && sizeof(float) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_float(file_id, dsname.c_str(), (float *)res);
     } else {
         std::cerr << "[Monitors] Requested type not supported or not compatible\n"
                   << "with actual data type size\n";
     }
     return res;
 }
void* read_2D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
Definition at line 15 of file Monitors.cpp.
Referenced by plot_LHCNoiseFB_FWHM_bbb().
 {
     auto file_id = H5Fopen(fname.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
     H5T_class_t class_id;
     size_t type_size;
     H5LTget_dataset_info(file_id, dsname.c_str(),
                          dims, &class_id, &type_size);
     std::transform(type.begin(), type.end(), type.begin(), ::tolower);
     void *res = NULL;
     if (type == "int" && sizeof(int) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_int(file_id, dsname.c_str(), (int *)res);
     } else if (type == "double" && sizeof(double) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_double(file_id, dsname.c_str(), (double *)res);
     } else if (type == "float" && sizeof(float) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_float(file_id, dsname.c_str(), (float *)res);
     } else {
         std::cerr << "[Monitors] Requested type not supported or not compatible\n"
                   << "with actual data type size\n";
     }
     return res;
 }