Beam Longitudinal Dynamics code (BLonD): blond::optionparser::Parser Class Reference
blond::optionparser::Parser Class Reference
Checks argument vectors for validity and parses them into data structures that are easier to work with.
#include <optionparser.h>
Classes
struct Action
class StoreOptionAction
Public Member Functions
Parser ()
Creates a new Parser.
Parser (bool gnu, const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Creates a new Parser and immediately parses the given argument vector.
Parser (bool gnu, const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Parser(...) with non-const argv.
Parser (const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX Parser(...) (gnu==false).
Parser (const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX Parser(...) (gnu==false) with non-const argv.
bool error ()
Returns true if an unrecoverable error occurred while parsing options.
const char * nonOption (int i)
Returns nonOptions()[i] (without checking if i is in range!).
const char ** nonOptions ()
Returns a pointer to an array of non-option arguments (only valid if nonOptionsCount() >0).
int nonOptionsCount ()
Returns the number of non-option arguments that remained at the end of the most recent parse() that actually encountered non-option arguments.
int optionsCount ()
Returns the number of valid Option objects in buffer[].
void parse (bool gnu, const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Parses the given argument vector.
void parse (bool gnu, const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
parse() with non-const argv.
void parse (const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX parse() (gnu==false).
void parse (const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX parse() (gnu==false) with non-const argv.
Static Private Member Functions
static bool instr (char ch, const char *st)
static void shift (const char **args, int count)
static bool streq (const char *st1, const char *st2)
static bool streqabbr (const char *st1, const char *st2, long long min)
static bool workhorse (bool gnu, const Descriptor usage[], int numargs, const char **args, Action &action, bool single_minus_longopt, bool print_errors, int min_abbr_len)
Private Attributes
bool err
const char ** nonop_args
int nonop_count
int op_count
Friends
struct Stats
Detailed Description
Checks argument vectors for validity and parses them into data structures that are easier to work with.
Example:
int main(int argc, char* argv[])
{
  argc-=(argc>0); argv+=(argc>0); // skip program name argv[0] if present
  option::Stats  stats(usage, argc, argv);
  option::Option options[stats.options_max], buffer[stats.buffer_max];
  option::Parser parse(usage, argc, argv, options, buffer);
  if (parse.error())
    return 1;
  if (options[HELP])
  ...
Definition at line 1211 of file optionparser.h.
Constructor & Destructor Documentation
blond::optionparser::Parser::Parser () inline
Creates a new Parser.
Definition at line 1220 of file optionparser.h.
 : op_count(0), nonop_count(0), nonop_args(0), err(false) {}
blond::optionparser::Parser::Parser (bool gnu, const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Creates a new Parser and immediately parses the given argument vector.
Parameters
gnu if true, parse() will not stop at the first non-option argument. Instead it will reorder arguments so that all non-options are at the end. This is the default behaviour of GNU getopt() but is not conforming to POSIX.
Note, that once the argument vector has been reordered, the gnu flag will have no further effect on this argument vector. So it is enough to pass gnu==true when creating Stats.
usage Array of Descriptor objects that describe the options to support. The last entry of this array must have 0 in all fields.
argc The number of elements from argv that are to be parsed. If you pass -1, the number will be determined automatically. In that case the argv list must end with a NULL pointer.
argv The arguments to be parsed. If you pass -1 as argc the last pointer in the argv list must be NULL to mark the end.
options Each entry is the first element of a linked list of Options. Each new option that is parsed will be appended to the list specified by that Option's Descriptor::index. If an entry is not yet used (i.e. the Option is invalid), it will be replaced rather than appended to.
The minimum length of this array is the greatest Descriptor::index value that occurs in usage PLUS ONE.
buffer Each argument that is successfully parsed (including unknown arguments, if they have a Descriptor whose CheckArg does not return ARG_ILLEGAL) will be stored in this array. parse() scans the array for the first invalid entry and begins writing at that index. You can pass bufmax to limit the number of options stored.
min_abbr_len Passing a value min_abbr_len > 0 enables abbreviated long options. The parser will match a prefix of a long option as if it was the full long option (e.g. –foob=10 will be interpreted as if it was –foobar=10), as long as the prefix has at least min_abbr_len characters (not counting the –) and is unambiguous.
Be careful if combining min_abbr_len=1 with single_minus_longopt=true because the ambiguity check does not consider short options and abbreviated single minus long options will take precedence over short options.
single_minus_longopt Passing true for this option allows long options to begin with a single minus. The double minus form will still be recognized. Note that single minus long options take precedence over short options and short option groups. E.g. -file would be interpreted as –file and not as -f -i -l -e (assuming a long option named "file" exists).
bufmax The greatest index in the buffer[] array that parse() will write to is bufmax-1. If there are more options, they will be processed (in particular their CheckArg will be called) but not stored.
If you used Stats::buffer_max to dimension this array, you can pass -1 (or not pass bufmax at all) which tells parse() that the buffer is "large enou.h>.
Attention
Remember that options and buffer store Option objects, not pointers. Therefore it is not possible for the same object to be in both arrays. For those options that are found in both buffer[] and options[] the respective objects are independent copies. And only the objects in options[] are properly linked via Option::next() and Option::prev(). You can iterate over buffer[] to process all options in the order they appear in the argument vector, but if you want access to the other Options with the same Descriptor::index, then you must access the linked list via options[]. You can get the linked list in options from a buffer object via something like options[buffer[i].index()].
Definition at line 1227 of file optionparser.h.
References parse().
                 : op_count(0), nonop_count(0), nonop_args(0), err(false)
             {
                 parse(gnu, usage, argc, argv, options, buffer, min_abbr_len,
                       single_minus_longopt, bufmax);
             }
blond::optionparser::Parser::Parser (bool gnu, const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Parser(...) with non-const argv.
Definition at line 1237 of file optionparser.h.
References parse().
                 : op_count(0), nonop_count(0), nonop_args(0), err(false)
             {
                 parse(gnu, usage, argc, (const char **)argv, options, buffer,
                       min_abbr_len, single_minus_longopt, bufmax);
             }
blond::optionparser::Parser::Parser (const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX Parser(...) (gnu==false).
Definition at line 1247 of file optionparser.h.
References parse().
                 : op_count(0), nonop_count(0), nonop_args(0), err(false)
             {
                 parse(false, usage, argc, argv, options, buffer, min_abbr_len,
                       single_minus_longopt, bufmax);
             }
blond::optionparser::Parser::Parser (const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX Parser(...) (gnu==false) with non-const argv.
Definition at line 1257 of file optionparser.h.
References parse().
                 : op_count(0), nonop_count(0), nonop_args(0), err(false)
             {
                 parse(false, usage, argc, (const char **)argv, options, buffer,
                       min_abbr_len, single_minus_longopt, bufmax);
             }
Member Function Documentation
bool blond::optionparser::Parser::error () inline
Returns true if an unrecoverable error occurred while parsing options.
An illegal argument to an option (i.e. CheckArg returns ARG_ILLEGAL) is an unrecoverable error that aborts the parse. Unknown options are only an error if their CheckArg function returns ARG_ILLEGAL. Otherwise they are collected. In that case if you want to exit the program if either an illegal argument or an unknown option has been passed, use code like this
if (parser.error() || options[UNKNOWN])
  exit(1);
Definition at line 1473 of file optionparser.h.
References err.
 { return err; }
static bool blond::optionparser::Parser::instr (char ch, const char * st) inline static private
Definition at line 1559 of file optionparser.h.
Referenced by workhorse().
             {
                 while (*st != 0 && *st != ch)
                     ++st;
                 return *st == ch;
             }
const char* blond::optionparser::Parser::nonOption (int i) inline
Returns nonOptions()[i] (without checking if i is in range!).
Definition at line 1451 of file optionparser.h.
References nonOptions().
 { return nonOptions()[i]; }
const char** blond::optionparser::Parser::nonOptions () inline
Returns a pointer to an array of non-option arguments (only valid if nonOptionsCount() >0).
Note
parse() does not copy arguments, so this pointer points into the actual argument vector as passed to parse().
As explained at nonOptionsCount() this pointer is only changed by parse() calls that actually encounter non-option arguments. A parse() call that encounters only options, will not change nonOptions().
Definition at line 1445 of file optionparser.h.
References nonop_args.
Referenced by nonOption().
 { return nonop_args; }
int blond::optionparser::Parser::nonOptionsCount () inline
Returns the number of non-option arguments that remained at the end of the most recent parse() that actually encountered non-option arguments.
Note
A parse() that does not encounter non-option arguments will leave this value as well as nonOptions() undisturbed. This means you can feed the Parser a default argument vector that contains non-option arguments (e.g. a default filename). Then you feed it the actual arguments from the user. If the user has supplied at least one non-option argument, all of the non-option arguments from the default disappear and are replaced by the user's non-option arguments. However, if the user does not supply any non-option arguments the defaults will still be in effect.
Definition at line 1428 of file optionparser.h.
References nonop_count.
 { return nonop_count; }
int blond::optionparser::Parser::optionsCount () inline
Returns the number of valid Option objects in buffer[].
Note
The returned value always reflects the number of Options in the buffer[] array used for the most recent call to parse().
The count (and the buffer[]) includes unknown options if they are collected (see Descriptor::longopt).
Definition at line 1404 of file optionparser.h.
References op_count.
 { return op_count; }
void blond::optionparser::Parser::parse (bool gnu, const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Parses the given argument vector.
Parameters
gnu if true, parse() will not stop at the first non-option argument. Instead it will reorder arguments so that all non-options are at the end. This is the default behaviour of GNU getopt() but is not conforming to POSIX.
Note, that once the argument vector has been reordered, the gnu flag will have no further effect on this argument vector. So it is enough to pass gnu==true when creating Stats.
usage Array of Descriptor objects that describe the options to support. The last entry of this array must have 0 in all fields.
argc The number of elements from argv that are to be parsed. If you pass -1, the number will be determined automatically. In that case the argv list must end with a NULL pointer.
argv The arguments to be parsed. If you pass -1 as argc the last pointer in the argv list must be NULL to mark the end.
options Each entry is the first element of a linked list of Options. Each new option that is parsed will be appended to the list specified by that Option's Descriptor::index. If an entry is not yet used (i.e. the Option is invalid), it will be replaced rather than appended to.
The minimum length of this array is the greatest Descriptor::index value that occurs in usage PLUS ONE.
buffer Each argument that is successfully parsed (including unknown arguments, if they have a Descriptor whose CheckArg does not return ARG_ILLEGAL) will be stored in this array. parse() scans the array for the first invalid entry and begins writing at that index. You can pass bufmax to limit the number of options stored.
min_abbr_len Passing a value min_abbr_len > 0 enables abbreviated long options. The parser will match a prefix of a long option as if it was the full long option (e.g. –foob=10 will be interpreted as if it was –foobar=10), as long as the prefix has at least min_abbr_len characters (not counting the –) and is unambiguous.
Be careful if combining min_abbr_len=1 with single_minus_longopt=true because the ambiguity check does not consider short options and abbreviated single minus long options will take precedence over short options.
single_minus_longopt Passing true for this option allows long options to begin with a single minus. The double minus form will still be recognized. Note that single minus long options take precedence over short options and short option groups. E.g. -file would be interpreted as –file and not as -f -i -l -e (assuming a long option named "file" exists).
bufmax The greatest index in the buffer[] array that parse() will write to is bufmax-1. If there are more options, they will be processed (in particular their CheckArg will be called) but not stored.
If you used Stats::buffer_max to dimension this array, you can pass -1 (or not pass bufmax at all) which tells parse() that the buffer is "large enou.h>.
Attention
Remember that options and buffer store Option objects, not pointers. Therefore it is not possible for the same object to be in both arrays. For those options that are found in both buffer[] and options[] the respective objects are independent copies. And only the objects in options[] are properly linked via Option::next() and Option::prev(). You can iterate over buffer[] to process all options in the order they appear in the argument vector, but if you want access to the other Options with the same Descriptor::index, then you must access the linked list via options[]. You can get the linked list in options from a buffer object via something like options[buffer[i].index()].
Definition at line 1716 of file optionparser.h.
References err, and workhorse().
Referenced by parse(), and Parser().
         {
             StoreOptionAction action(*this, options, buffer, bufmax);
             err = !workhorse(gnu, usage, argc, argv, action, single_minus_longopt,
                              true, min_abbr_len);
         }
void blond::optionparser::Parser::parse (bool gnu, const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
parse() with non-const argv.
Definition at line 1367 of file optionparser.h.
References parse().
             {
                 parse(gnu, usage, argc, (const char **)argv, options, buffer,
                       min_abbr_len, single_minus_longopt, bufmax);
             }
void blond::optionparser::Parser::parse (const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX parse() (gnu==false).
Definition at line 1376 of file optionparser.h.
References parse().
             {
                 parse(false, usage, argc, argv, options, buffer, min_abbr_len,
                       single_minus_longopt, bufmax);
             }
void blond::optionparser::Parser::parse (const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX parse() (gnu==false) with non-const argv.
Definition at line 1385 of file optionparser.h.
References parse().
             {
                 parse(false, usage, argc, (const char **)argv, options, buffer,
                       min_abbr_len, single_minus_longopt, bufmax);
             }
static void blond::optionparser::Parser::shift (const char ** args, int count) inline static private
Definition at line 1572 of file optionparser.h.
Referenced by workhorse().
             {
                 for (int i = 0; i > -count; --i) {
                     const char *temp = args[i];
                     args[i] = args[i - 1];
                     args[i - 1] = temp;
                 }
             }
static bool blond::optionparser::Parser::streq (const char * st1, const char * st2) inline static private
Definition at line 1506 of file optionparser.h.
Referenced by workhorse().
             {
                 while (*st1 != 0)
                     if (*st1++ != *st2++)
                         return false;
                 return (*st2 == 0 || *st2 == '=');
             }
static bool blond::optionparser::Parser::streqabbr (const char * st1, const char * st2, long long min) inline static private
Definition at line 1540 of file optionparser.h.
Referenced by workhorse().
             {
                 const char *st1start = st1;
                 while (*st1 != 0 && (*st1 == *st2)) {
                     ++st1;
                     ++st2;
                 }
                 return (*st1 == 0 || (min > 0 && (st1 - st1start) >= min)) &&
                        (*st2 == 0 || *st2 == '=');
             }
bool blond::optionparser::Parser::workhorse (bool gnu, const Descriptor usage[], int numargs, const char ** args, Action & action, bool single_minus_longopt, bool print_errors, int min_abbr_len) inline static private
Definition at line 1746 of file optionparser.h.
References blond::optionparser::Option::arg, blond::optionparser::ARG_IGNORE, blond::optionparser::ARG_ILLEGAL, blond::optionparser::ARG_NONE, blond::optionparser::ARG_OK, blond::optionparser::Descriptor::check_arg, blond::optionparser::Parser::Action::finished(), instr(), blond::optionparser::Parser::Action::perform(), shift(), blond::optionparser::Descriptor::shortopt, streq(), and streqabbr().
Referenced by blond::optionparser::Stats::add(), and parse().
         {
             // protect against NULL pointer
             if (args == 0)
                 numargs = 0;
             int nonops = 0;
             while (numargs != 0 && *args != 0) {
                 const char *param = *args; // param can be --long-option, -srto or
                 // non-option argument
                 // in POSIX mode the first non-option argument terminates the option
                 // list
                 // a lone minus character is a non-option argument
                 if (param[0] != '-' || param[1] == 0) {
                     if (gnu) {
                         ++nonops;
                         ++args;
                         if (numargs > 0)
                             --numargs;
                         continue;
                     } else
                         break;
                 }
                 // -- terminates the option list. The -- itself is skipped.
                 if (param[1] == '-' && param[2] == 0) {
                     shift(args, nonops);
                     ++args;
                     if (numargs > 0)
                         --numargs;
                     break;
                 }
                 bool handle_short_options;
                 const char *longopt_name;
                 if (param[1] == '-') { // if --long-option
                     handle_short_options = false;
                     longopt_name = param + 2;
                 } else {
                     handle_short_options = true;
                     longopt_name = param + 1; // for testing a potential
                     // -long-option
                 }
                 bool try_single_minus_longopt = single_minus_longopt;
                 bool have_more_args =
                     (numargs > 1 || numargs < 0); // is referencing argv[1] valid?
                 do { // loop over short options in group, for long options the body
                     // is executed only once
                     int idx;
                     const char *optarg;
                     /******************** long option **********************/
                     if (handle_short_options == false || try_single_minus_longopt) {
                         idx = 0;
                         while (usage[idx].longopt != 0 &&
                                 !streq(usage[idx].longopt, longopt_name))
                             ++idx;
                         if (usage[idx].longopt == 0 &&
                                 min_abbr_len > 0) { // if we should try to match
                             // abbreviated long options
                             int i1 = 0;
                             while (usage[i1].longopt != 0 &&
                                     !streqabbr(usage[i1].longopt, longopt_name,
                                                min_abbr_len))
                                 ++i1;
                             if (usage[i1].longopt != 0) {
                                 // now test if the match is unambiguous by checking
                                 // for another match
                                 int i2 = i1 + 1;
                                 while (usage[i2].longopt != 0 &&
                                         !streqabbr(usage[i2].longopt, longopt_name,
                                                    min_abbr_len))
                                     ++i2;
                                 if (usage[i2].longopt == 0) // if there was no
                                     // second match it's
                                     // unambiguous, so
                                     // accept i1 as idx
                                     idx = i1;
                             }
                         }
                         // if we found something, disable handle_short_options (only
                         // relevant if single_minus_longopt)
                         if (usage[idx].longopt != 0)
                             handle_short_options = false;
                         try_single_minus_longopt = false; // prevent looking for
                         // longopt in the middle
                         // of shortopt group
                         optarg = longopt_name;
                         while (*optarg != 0 && *optarg != '=')
                             ++optarg;
                         if (*optarg == '=') // attached argument
                             ++optarg;
                         else
                             // possibly detached argument
                             optarg = (have_more_args ? args[1] : 0);
                     }
                     /************************ short option
                     * ***********************************/
                     if (handle_short_options) {
                         if (*++param == 0) // point at the 1st/next option character
                             break;         // end of short option group
                         idx = 0;
                         while (usage[idx].shortopt != 0 &&
                                 !instr(*param, usage[idx].shortopt))
                             ++idx;
                         if (param[1] == 0) // if the potential argument is separate
                             optarg = (have_more_args ? args[1] : 0);
                         else
                             // if the potential argument is attached
                             optarg = param + 1;
                     }
                     const Descriptor *descriptor = &usage[idx];
                     if (descriptor->shortopt ==
                             0) { /**************  unknown option ********************/
                         // look for dummy entry (shortopt == "" and longopt == "")
                         // to use as Descriptor for unknown options
                         idx = 0;
                         while (usage[idx].shortopt != 0 &&
                                 (usage[idx].shortopt[0] != 0 ||
                                  usage[idx].longopt[0] != 0))
                             ++idx;
                         descriptor = (usage[idx].shortopt == 0 ? 0 : &usage[idx]);
                     }
                     if (descriptor != 0) {
                         Option option(descriptor, param, optarg);
                         switch (descriptor->check_arg(option, print_errors)) {
                             case ARG_ILLEGAL:
                                 return false; // fatal
                             case ARG_OK:
                                 // skip one element of the argument vector, if it's a
                                 // separated argument
                                 if (optarg != 0 && have_more_args &&
                                         optarg == args[1]) {
                                     shift(args, nonops);
                                     if (numargs > 0)
                                         --numargs;
                                     ++args;
                                 }
                                 // No further short options are possible after an
                                 // argument
                                 handle_short_options = false;
                                 break;
                             case ARG_IGNORE:
                             case ARG_NONE:
                                 option.arg = 0;
                                 break;
                         }
                         if (!action.perform(option))
                             return false;
                     }
                 } while (handle_short_options);
                 shift(args, nonops);
                 ++args;
                 if (numargs > 0)
                     --numargs;
             } // while
             if (numargs > 0 && *args == 0) // It's a bug in the caller if numargs is
                 // greater than the actual number
                 numargs = 0; // of arguments, but as a service to the user we fix
             // this if we spot it.
             if (numargs < 0) { // if we don't know the number of remaining
                 // non-option arguments
                 // we need to count them
                 numargs = 0;
                 while (args[numargs] != 0)
                     ++numargs;
             }
             return action.finished(numargs + nonops, args - nonops);
         }
Friends And Related Function Documentation
friend struct Stats friend
Definition at line 1476 of file optionparser.h.
Member Data Documentation
bool blond::optionparser::Parser::err private
Definition at line 1215 of file optionparser.h.
Referenced by error(), and parse().
const char** blond::optionparser::Parser::nonop_args private
Definition at line 1214 of file optionparser.h.
Referenced by blond::optionparser::Parser::StoreOptionAction::finished(), and nonOptions().
int blond::optionparser::Parser::nonop_count private
Definition at line 1213 of file optionparser.h.
Referenced by blond::optionparser::Parser::StoreOptionAction::finished(), and nonOptionsCount().
int blond::optionparser::Parser::op_count private
Definition at line 1212 of file optionparser.h.
Referenced by optionsCount(), blond::optionparser::Parser::StoreOptionAction::perform(), and blond::optionparser::Parser::StoreOptionAction::StoreOptionAction().