Beam Longitudinal Dynamics code (BLonD): blond::SPS_RL Class Reference
blond::SPS_RL Class Reference
#include <PhaseLoop.h>
Public Member Functions
SPS_RL (double PL_gain, double window_coefficient=0, double RL_gain=0, PhaseNoise *phaseNoise=NULL, LHCNoiseFB *LHCNoiseFB=NULL, uint delay=0)
~SPS_RL ()
void track ()
Public Member Functions inherited from blond::PhaseLoop
PhaseLoop (f_vector_t PL_gain, double window_coefficient, uint _delay, PhaseNoise *phaseNoise, LHCNoiseFB *LHCNoiseFB)
PhaseLoop ()
virtual ~PhaseLoop ()
void beam_phase ()
void default_track ()
void phase_difference ()
void radial_difference ()
void radial_steering_from_freq ()
Public Attributes
double gain
double gain2
Public Attributes inherited from blond::PhaseLoop
double alpha = 0
uint delay = 0
double domega_rf = 0
double dphi = 0
double drho = 0
LHCNoiseFB * noiseFB
double phi_beam = 0
double reference = 0
PhaseNoise * RFnoise
Detailed Description
Definition at line 97 of file PhaseLoop.h.
Constructor & Destructor Documentation
SPS_RL::SPS_RL (double PL_gain, double window_coefficient = 0, double RL_gain = 0, PhaseNoise * phaseNoise = NULL, LHCNoiseFB * LHCNoiseFB = NULL, uint delay = 0)
Definition at line 445 of file PhaseLoop.cpp.
References blond::PhaseLoop::alpha, blond::PhaseLoop::delay, gain, gain2, blond::PhaseLoop::noiseFB, and blond::PhaseLoop::RFnoise.
 {
     this->gain = PL_gain;
     this->alpha = window_coefficient;
     this->delay = delay;
     this->RFnoise = phaseNoise;
     this->noiseFB = LHCNoiseFB;
     this->gain2 = RL_gain;
 }
SPS_RL::~SPS_RL ()
Definition at line 456 of file PhaseLoop.cpp.
 {}
Member Function Documentation
void SPS_RL::track () virtual
Reimplemented from blond::PhaseLoop.
Definition at line 459 of file PhaseLoop.cpp.
References blond::PhaseLoop::beam_phase(), blond::RfParameters::counter, blond::PhaseLoop::default_track(), blond::PhaseLoop::domega_rf, blond::PhaseLoop::dphi, blond::PhaseLoop::drho, gain, gain2, blond::Context::GP, blond::PhaseLoop::phase_difference(), blond::PhaseLoop::radial_difference(), blond::PhaseLoop::radial_steering_from_freq(), blond::PhaseLoop::reference, and blond::Context::RfP.
 {
     auto GP = Context::GP;
     auto RfP = Context::RfP;
     uint counter = RfP->counter;
     if (reference != 0)
         radial_steering_from_freq();
     beam_phase();
     phase_difference();
     radial_difference();
     // Frequency correction from phase loop and radial loop
     const auto factor = RfP->sign_eta_0[counter] * (reference - drho) /
                         GP->ring_radius;
     // for (int i = 0; i < (int)gain.size(); ++i) {
     domega_rf = -gain * dphi - gain2 * factor;
     // }
     default_track();
 }
Member Data Documentation
double blond::SPS_RL::gain
Definition at line 102 of file PhaseLoop.h.
Referenced by SPS_RL(), and track().
double blond::SPS_RL::gain2
Definition at line 100 of file PhaseLoop.h.
Referenced by SPS_RL(), and track().