Beam Longitudinal Dynamics code (BLonD): blond::LHCFlatSpectrum Class Reference
blond::LHCFlatSpectrum Class Reference
#include <PhaseNoise.h>
Public Member Functions
LHCFlatSpectrum (uint time_points, uint corr_time=10000, double fmin=0.8571, double fmax=1.1, double initial_amplitude=1e-6, int seed1=1234, int seed2=7564, predistortion_t predistortion=predistortion_t::predistortion_none)
~LHCFlatSpectrum ()
void generate ()
Public Member Functions inherited from blond::PhaseNoise
PhaseNoise ()
virtual ~PhaseNoise ()
f_vector_t spectrum_generation (int k, int nt, double df, double ampl, f_vector_t freq, predistortion_t predistortion)
void spectrum_to_phase_noise (f_vector_t &t, f_vector_t &dphi, const f_vector_t &freq_array, const f_vector_t &ReS, transform_t transform=transform_t::transform_none)
Public Attributes
uint fNt
Public Attributes inherited from blond::PhaseNoise
double fAi
uint fCorr
f_vector_t fDphi
double fFMax
double fFMin
f_vector_t fFs
uint fNTurns
predistortion_t fPredistortion
int fSeed1
int fSeed2
Additional Inherited Members
Public Types inherited from blond::PhaseNoise
enum predistortion_t {
exponential, linear, hyperbolic, weightfunction,
predistortion_none
}
enum transform_t { r, c, transform_none }
Detailed Description
Definition at line 52 of file PhaseNoise.h.
Constructor & Destructor Documentation
LHCFlatSpectrum::LHCFlatSpectrum (uint time_points, uint corr_time = 10000, double fmin = 0.8571, double fmax = 1.1, double initial_amplitude = 1e-6, int seed1 = 1234, int seed2 = 7564, predistortion_t predistortion = predistortion_t::predistortion_none)
Definition at line 333 of file PhaseNoise.cpp.
References blond::constant::c, blond::PhaseNoise::fAi, blond::PhaseNoise::fCorr, blond::PhaseNoise::fDphi, blond::PhaseNoise::fFMax, blond::PhaseNoise::fFMin, blond::PhaseNoise::fFs, fNt, blond::PhaseNoise::fNTurns, blond::PhaseNoise::fPredistortion, blond::PhaseNoise::fSeed1, blond::PhaseNoise::fSeed2, blond::Context::GP, blond::constant::pi, and blond::Context::RfP.
 {
     auto RfP = Context::RfP;
     auto GP = Context::GP;
     fNt = time_points;
     fCorr = corr_time;
     fFMin = fmin;
     fFMax = fmax;
     fAi = initial_amplitude;
     fPredistortion = predistortion;
     fSeed1 = seed1;
     fSeed2 = seed2;
     fNTurns = GP->n_turns;
     fDphi.resize(fNTurns + 1, 0);
     if (fPredistortion != predistortion_t::predistortion_none) {
         // Overwrite frequencies
         fFMin = 0.8571;
         fFMax = 1.001;
     }
     if (fNt < 2 * fCorr) {
         std::cerr << "ERROR: Need more time point in LHCFlatSpectrum.\n";
         exit(-1);
     }
     // Synchrotron frequency array
     auto phis =  RfP->calc_phi_s(RfP, RfParameters::acc_sys_t::as_single);
     fFs.resize(phis.size());
     for (uint i = 0; i < fFs.size(); ++i) {
         fFs[i] =
             constant::c / GP->ring_circumference *
             std::sqrt(RfP->harmonic[RfP->section_index][i]
                       * RfP->voltage[RfP->section_index][i] *
                       std::abs(RfP->eta_0[i] * std::cos(phis[i])) /
                       (2 * constant::pi * RfP->energy[i]));
     }
 }
LHCFlatSpectrum::~LHCFlatSpectrum ()
Definition at line 377 of file PhaseNoise.cpp.
References blond::fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
void LHCFlatSpectrum::generate () virtual
Reimplemented from blond::PhaseNoise.
Definition at line 379 of file PhaseNoise.cpp.
References blond::PhaseNoise::fAi, blond::PhaseNoise::fCorr, blond::PhaseNoise::fDphi, blond::PhaseNoise::fFs, fNt, blond::PhaseNoise::fNTurns, blond::PhaseNoise::fPredistortion, blond::PhaseNoise::fSeed1, blond::PhaseNoise::fSeed2, blond::Context::GP, blond::mymath::linspace(), blond::PhaseNoise::spectrum_generation(), blond::PhaseNoise::spectrum_to_phase_noise(), and blond::mymath::standard_deviation().
 {
     auto GP = Context::GP;
     for (uint i = 0; i < fNTurns / fCorr; ++i) {
         // Scale amplitude to keep area (phase noise amplitude) constant
         int k = i * fCorr; // Current time step
         auto ampl = fAi * fFs[0] / fFs[k];
         // Calculate the frequency step
         int nf = fNt / 2 + 1; // #points in frequency domain
         double df = GP->f_rev[k] / fNt;
         f_vector_t freq(nf);
         mymath::linspace(freq.data(), 0, nf * df, nf);
         auto spectrum =
             spectrum_generation(k, fNt, df, ampl, freq, fPredistortion);
         f_vector_t noise_t, noise_dphi;
         spectrum_to_phase_noise(noise_t, noise_dphi, freq, spectrum);
         // spectrum_to_phase_noise();
         fSeed1 += 239;
         fSeed2 += 158;
         // Fill phase noise array
         const uint kmax =
             i < fNTurns / fCorr - 1 ? (i + 1) * fCorr : fNTurns + 1;
         for (uint i = 0; i < kmax - k; ++i)
             fDphi[i + k] = noise_dphi[i];
         auto rms_noise =
             mymath::standard_deviation(noise_dphi.data(), noise_dphi.size());
         // std::cout << "RF noise for time step " << noise_t[1]
         //           << " s (iter " << i << ") has r.m.s phase "
         //           << rms_noise << " rad (" << rms_noise * 180 / constant::pi
         //           << " deg)\n";
     }
 }
Member Data Documentation
uint blond::LHCFlatSpectrum::fNt
Definition at line 55 of file PhaseNoise.h.
Referenced by generate(), and LHCFlatSpectrum().