Beam Longitudinal Dynamics code (BLonD): blond Namespace Reference
blond Namespace Reference
Namespaces
namespace constant
namespace fft
namespace mymath
namespace optionparser
The namespace of The Lean Mean C++ Option Parser.
namespace python
namespace util
namespace vdt
Classes
class Beams
class BunchMonitor
struct Context
struct distribution_denstity_t
class FullRingAndRf
class GeneralParameters
class InducedVoltage
class InducedVoltageFreq
class InducedVoltageTime
class InputTable
class Intensity
class LHC
class LHC_F
class LHCFlatSpectrum
class LHCNoiseFB
struct line_density_t
struct multi_t
class Music
class PhaseLoop
class PhaseNoise
class PSB
class PSBPhaseNoiseInjection
class Resonators
class RfParameters
class RingAndRfSection
class Slices
class SlicesMonitor
class SPS_RL
class TotalInducedVoltage
class TravelingWaveCavity
Typedefs
typedef std::vector< bool > bool_vector_t
typedef std::complex< double > complex_t
typedef std::vector
< complex_vector_t > complex_vector_2d_t
typedef std::vector< complex_t > complex_vector_t
typedef std::vector< f_vector_t > f_vector_2d_t
typedef std::vector< double > f_vector_t
typedef double ftype
typedef std::vector< int_vector_t > int_vector_2d_t
typedef std::vector< int > int_vector_t
typedef std::vector< std::string > string_vector_t
typedef unsigned int uint
typedef std::vector
< uint_vector_t > uint_vector_2d_t
typedef std::vector< uint > uint_vector_t
Functions
template<typename T , typename F >
static std::vector< T > apply_f (const std::vector< T > &a, F op)
template<typename T , typename F >
static std::vector< T > apply_f (const std::vector< T > &a, const std::vector< T > &b, F op)
template<typename T , typename F >
static void apply_f_in_place (std::vector< T > &a, F op)
template<typename T , typename F >
static void apply_f_in_place (std::vector< T > &a, const std::vector< T > &b, F op)
f_vector_t distribution_density_function (const f_vector_t &action_array, const std::string &dist_type, const double length, double exponent=0.)
f_vector_2d_t distribution_density_function (const f_vector_2d_t &action_array, const std::string &dist_type, const double length, double exponent=0.0)
f_vector_t hamiltonian (const GeneralParameters *GP, const RfParameters *RfP, const Beams *Beam, const double *__restrict dt, const double *__restrict dE, const int size, const f_vector_t total_voltage={})
double hamiltonian (const GeneralParameters *GP, const RfParameters *RfP, const Beams *Beam, const double dt, const double dE, const f_vector_t total_voltage={})
std::vector< int > is_in_separatrix (const GeneralParameters *GP, const RfParameters *RfP, const Beams *Beam, const f_vector_t &dt, const f_vector_t &dE, const f_vector_t total_voltage={})
f_vector_t line_density_function (const f_vector_t &coord_array, const std::string &dist_type, const double bunch_length, const double bunch_position=0., double exponent=0.)
void linear_interp_kick (const double *__restrict beam_dt, double *__restrict beam_dE, const double *__restrict voltage_array, const double *__restrict bin_centers, const int n_slices, const int n_macroparticles)
void longitudinal_bigaussian (GeneralParameters *GP, RfParameters *RfP, Beams *Beam, double sigma_dt, double sigma_dE=0, int seed=0, bool reinsertion=false)
distribution_denstity_t matched_from_distribution_density (Beams *beam, FullRingAndRf *full_ring, std::map< std::string, multi_t > distribution_opt, FullRingAndRf::main_harmonic_t main_harmonic_opt=FullRingAndRf::lowest_freq, TotalInducedVoltage *totVolt=nullptr, std::map< std::string, f_vector_t > extraVoltageDict=std::map< std::string, f_vector_t >(), int n_iterations_input=1, int seed=0)
line_density_t matched_from_line_density (Beams *beam, FullRingAndRf *full_ring, std::map< std::string, std::string > line_density_opt, FullRingAndRf::main_harmonic_t main_harmonic_opt=FullRingAndRf::lowest_freq, TotalInducedVoltage *totVolt=nullptr, std::string plot="", std::string figdir="fig", std::string half_option="first", std::map< std::string, f_vector_t > extraVoltageDict=std::map< std::string, f_vector_t >(), int n_iterations_input=100, int seed=0)
void minmax_location (const f_vector_t &x, const f_vector_t &f, f_vector_t &min_x_position, f_vector_t &max_x_position, f_vector_t &min_values, f_vector_t &max_values)
static int omp_get_max_threads ()
static int omp_get_num_threads ()
static int omp_get_thread_num ()
static void omp_set_num_threads (int threads)
template<typename T >
static std::vector< bool > operator!= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator!= (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< T > operator* (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator* (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator* (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator*= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator*= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator+ (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator+ (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator+ (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator+= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator+= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator- (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator- (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator- (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator-= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator-= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< T > operator/ (const std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator/ (const std::vector< T > &a, const U &b)
template<typename T , typename U >
static std::vector< T > operator/ (const U &b, const std::vector< T > &a)
template<typename T >
static std::vector< T > operator/= (std::vector< T > &a, const std::vector< T > &b)
template<typename T , typename U >
static std::vector< T > operator/= (std::vector< T > &a, const U &b)
template<typename T >
static std::vector< bool > operator< (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator< (const std::vector< T > &a, const T &b)
template<typename T >
static std::ostream & operator<< (std::ostream &os, const std::vector< T > &a)
template<typename T >
static std::vector< bool > operator<= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator<= (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator== (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator== (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator> (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator> (const std::vector< T > &a, const T &b)
template<typename T >
static std::vector< bool > operator>= (const std::vector< T > &a, const std::vector< T > &b)
template<typename T >
static std::vector< bool > operator>= (const std::vector< T > &a, const T &b)
static double phase_modulo_above_transition (const double phi)
static double phase_modulo_below_transition (const double phi)
template<typename T >
static T pick (const std::vector< T > &a, const int i)
template<typename T >
static std::vector< T > pick (const std::vector< T > &a, const std::vector< int > &indexes)
template<typename T >
static std::vector< T > pick (const std::vector< T > &a, const std::vector< bool > &indexes)
int plot_beam_profile (Slices *Slices, int counter, std::string style="-", std::string dirname="fig")
int plot_beam_profile_derivative (Slices *Slices, int counter, std::string style="-", std::string dirname="fig", string_vector_t modes={"diff"})
int plot_beam_spectrum (Slices *Slices, int counter, std::string style="-", std::string dirname="fig")
int plot_bunch_length_evol (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_bunch_length_evol_gaussian (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_COM_motion (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_energy_evol (RfParameters *RfP, std::string h5data, int output_freq=1, std::string style=".", std::string dirname="fig")
void plot_generated_bunch (f_vector_t &time_line_den, f_vector_t &line_density, f_vector_t &time_coord_for_grid, f_vector_t &rec_line_den, std::string plot, std::string figdir)
int plot_impedance_vs_frequency (int counter, InducedVoltageFreq *indVoltFreq, Slices *slices, std::string option1="sum", std::string option2="no_spectrum", std::string option3="freq_fft", std::string style="-", f_vector_t cut_left_right={}, f_vector_t cut_up_down={}, std::string dirname="fig")
int plot_induced_voltage_vs_bin_centers (int counter, TotalInducedVoltage *totIndVolt, Slices *slices, std::string style="-", std::string dirname="fig")
int plot_LHCNoiseFB (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_LHCNoiseFB_FWHM (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_LHCNoiseFB_FWHM_bbb (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_long_phase_space (GeneralParameters *GP, RfParameters *RfP, Beams *Beam, double xmin, double xmax, double ymin, double ymax, std::string xunit="s", int sampling=1, bool separatrix_plot=false, bool histograms_plot=true, std::string dirname="fig", int alpha=1)
int plot_noise_spectrum (f_vector_t &frequency, f_vector_t &spectrum, int sampling=1, std::string dirname="fig", int figno=0)
int plot_phase_noise (f_vector_t &frequency, f_vector_t &spectrum, int sampling=1, std::string dirname="fig", int figno=0)
int plot_PL_bunch_phase (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_PL_freq_corr (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_PL_phase_corr (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_PL_RF_freq (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_PL_RF_phase (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_position_evol (RfParameters *RfP, std::string h5data, int output_freq=1, std::string style=".", std::string dirname="fig")
int plot_RF_phase_error (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_RL_radial_error (RfParameters *RfP, std::string h5data, int output_freq=1, std::string dirname="fig")
int plot_transmitted_particles (RfParameters *RfP, std::string h5data, int output_freq=1, std::string style=".", std::string dirname="fig")
int plot_voltage_programme (f_vector_t &time, f_vector_t &voltage, int sampling=1, std::string dirname="fig", int figno=0)
int plot_xy (f_vector_t xArray, f_vector_t yArray, std::string figureName, std::string dirName, std::string saveFigName, double xMax=0)
void potential_well_cut (const f_vector_t &theta_coord_array, const f_vector_t &potential_array, f_vector_t &theta_coord_sep, f_vector_t &potential_well_sep)
void preprocess_ramp (GeneralParameters::particle_t particle_type, double circumference, f_vector_t &time, f_vector_t &data, f_vector_t &time_interp, f_vector_t &momentum_interp, std::string data_type="momentum", std::string interpolation="linear", int smoothing=0, int flat_bottom=0, int t_start=0, int t_end=-1, bool plot=false, std::string figdir="fig", std::string figname="data", int sampling=1, double user_mass=0.)
void preprocess_rf_params (GeneralParameters *GP, f_vector_2d_t &time_arrays, f_vector_2d_t &data_arrays, f_vector_t &data_interp, std::string interpolation="linear", bool plot=false, std::string figdir="fig", std::vector< std::string > figname={"data"}, int sampling=1)
void * read_1D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
void * read_2D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
template<typename T >
static std::vector< T > slice (const std::vector< T > &a, const int start=0, int end=0, const int step=1)
Variables
const unsigned PRECISION = 8
Typedef Documentation
typedef std::vector<bool> blond::bool_vector_t
Definition at line 18 of file configuration.h.
typedef std::complex<double> blond::complex_t
Definition at line 17 of file configuration.h.
typedef std::vector<complex_vector_t> blond::complex_vector_2d_t
Definition at line 28 of file configuration.h.
typedef std::vector<complex_t> blond::complex_vector_t
Definition at line 22 of file configuration.h.
typedef std::vector<f_vector_t> blond::f_vector_2d_t
Definition at line 25 of file configuration.h.
typedef std::vector<double> blond::f_vector_t
Definition at line 19 of file configuration.h.
typedef double blond::ftype
Definition at line 14 of file configuration.h.
typedef std::vector<int_vector_t> blond::int_vector_2d_t
Definition at line 26 of file configuration.h.
typedef std::vector<int> blond::int_vector_t
Definition at line 20 of file configuration.h.
typedef std::vector<std::string> blond::string_vector_t
Definition at line 23 of file configuration.h.
typedef unsigned int blond::uint
Definition at line 15 of file configuration.h.
typedef std::vector<uint_vector_t> blond::uint_vector_2d_t
Definition at line 27 of file configuration.h.
typedef std::vector<uint> blond::uint_vector_t
Definition at line 21 of file configuration.h.
Function Documentation
template<typename T , typename F > static std::vector<T> blond::apply_f (const std::vector< T > & a, F op) inline static
Definition at line 25 of file vector_math.h.
Referenced by distribution_density_function(), matched_from_distribution_density(), operator*(), operator+(), operator-(), operator/(), and blond::Slices::rms().
     {
         // const size_t size = a.size();
         // std::vector<T> result(size);
         // for (size_t i = 0; i < size; i++)
         //     result[i] = op(a[i]);
         std::vector<T> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(), op);
         return result;
     }
template<typename T , typename F > static std::vector<T> blond::apply_f (const std::vector< T > & a, const std::vector< T > & b, F op) inline static
Definition at line 50 of file vector_math.h.
     {
         // const size_t size = a.size();
         // std::vector<T> result(size);
         // for (size_t i = 0; i < size; i++)
         //     result[i] = op(a[i], b[i]);
         assert(a.size() == b.size());
         std::vector<T> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(), result.begin(), op);
         return result;
     }
template<typename T , typename F > static void blond::apply_f_in_place (std::vector< T > & a, F op) inline static
Definition at line 39 of file vector_math.h.
Referenced by operator*=(), operator+=(), operator-=(), and operator/=().
     {
         // const size_t size = a.size();
         // for (size_t i = 0; i < size; i++)
         //     a[i] = op(a[i]);
         std::transform(a.begin(), a.end(), a.begin(), op);
     }
template<typename T , typename F > static void blond::apply_f_in_place (std::vector< T > & a, const std::vector< T > & b, F op) inline static
Definition at line 66 of file vector_math.h.
     {
         // const size_t size = a.size();
         // for (size_t i = 0; i < size; i++)
         //     a[i] = op(a[i], b[i]);
         assert(a.size() == b.size());
         std::transform(a.begin(), a.end(), b.begin(), a.begin(), op);
     }
f_vector_t blond::distribution_density_function (const f_vector_t & action_array, const std::string & dist_type, const double length, double exponent = 0.)
Definition at line 919 of file Distributions.cpp.
References apply_f().
Referenced by distribution_density_function(), and matched_from_distribution_density().
 {
     f_vector_t ret(action_array.size());
     if (dist_type == "binomial") {
         for (uint i = 0; i < action_array.size(); i++) {
             if (action_array[i] > length)
                 ret[i] = 0.;
             else
                 ret[i] = pow((1. - action_array[i] / length), exponent);
         }
         return ret;
     } else if (dist_type == "waterbag") {
         for (uint i = 0; i < action_array.size(); i++) {
             if (action_array[i] > length)
                 ret[i] = 0.;
             else
                 ret[i] = 1.;
         }
         return ret;
     } else if (dist_type == "parabolic_amplitude") {
         for (uint i = 0; i < action_array.size(); i++) {
             if (action_array[i] > length)
                 ret[i] = 0.;
             else
                 ret[i] = (1 - action_array[i] / length);
         }
         return ret;
     } else if (dist_type == "parabolic_line") {
         exponent = 0.5;
         for (uint i = 0; i < action_array.size(); i++) {
             if (action_array[i] > length)
                 ret[i] = 0.;
             else
                 ret[i] = pow((1. - action_array[i] / length), exponent);
         }
         return ret;
     } else if (dist_type == "gaussian") {
         ret = apply_f(action_array, [length](double x) {return exp(-2 * x / length);});
     } else {
         cerr << "[distribution_density_function] The dist_type was not recognized\n";
         exit(-1);
     }
     return ret;
 }
f_vector_2d_t blond::distribution_density_function (const f_vector_2d_t & action_array, const std::string & dist_type, const double length, double exponent = 0.0)
Definition at line 967 of file Distributions.cpp.
References distribution_density_function().
 {
     f_vector_2d_t ret;
     for (const auto &row : action_array)
         ret.push_back(distribution_density_function(row, dist_type,
                       length, exponent));
     return ret;
 }
f_vector_t blond::hamiltonian (const GeneralParameters * GP, const RfParameters * RfP, const Beams * Beam, const double *__restrict dt, const double *__restrict dE, const int size, const f_vector_t total_voltage = {})
Definition at line 65 of file utilities.cpp.
References blond::RfParameters::beta, blond::constant::c, blond::GeneralParameters::charge, blond::RfParameters::counter, blond::RfParameters::energy, blond::RfParameters::eta_0, blond::RfParameters::eta_tracking(), blond::mymath::fast_cos(), blond::mymath::fast_sin(), blond::RfParameters::harmonic, blond::RfParameters::n_rf, blond::GeneralParameters::n_sections, blond::RfParameters::omega_rf, phase_modulo_above_transition(), phase_modulo_below_transition(), blond::RfParameters::phi_rf, blond::RfParameters::phi_s, blond::constant::pi, blond::GeneralParameters::ring_circumference, and blond::RfParameters::voltage.
Referenced by is_in_separatrix().
 {
     if (GP->n_sections > 1)
         cerr << "WARNING: The Hamiltonian is not yet properly computed"
              << "for several sections!\n";
     if (RfP->n_rf > 1)
         cerr << "WARNING: The Hamiltonian will be calculated for"
              << "the first harmonic only!\n";
     const int counter = RfP->counter;
     const double h0 = RfP->harmonic[0][counter];
     double v0;
     if (total_voltage.empty())
         v0 = RfP->voltage[0][counter] * GP->charge;
     else
         v0 = total_voltage[counter] * GP->charge;
     // TODO it should be dE instead of 0.0
     const double c1 = RfP->eta_tracking(Beam, counter, 0.0)
                       * constant::pi * constant::c
                       / (GP->ring_circumference * RfP->beta[counter] *
                          RfP->energy[counter]);
     const double c2 = constant::c * RfP->beta[counter] * v0
                       / (h0 * GP->ring_circumference);
     const double phi_s = RfP->phi_s[counter];
     const double omega_rf0 = RfP->omega_rf[0][counter];
     const double phi_rf0 = RfP->phi_rf[0][counter];
     f_vector_t phi_b(size, phi_rf0);
     #pragma omp parallel for
     for (int i = 0; i < size; i++)
         phi_b[i] += omega_rf0 * dt[i];
     const double eta0 = RfP->eta_0[counter];
     if (eta0 < 0)
         #pragma omp parallel for
         for (int i = 0; i < size; i++)
             phi_b[i] = phase_modulo_below_transition(phi_b[i]);
     else if (eta0 > 0)
         #pragma omp parallel for
         for (int i = 0; i < size; i++)
             phi_b[i] = phase_modulo_above_transition(phi_b[i]);
     const double cos_phi_s = mymath::fast_cos(phi_s);
     const double sin_phi_s = mymath::fast_sin(phi_s);
     #pragma omp parallel for
     for (int i = 0; i < size; i++)
         phi_b[i] = c1 * dE[i] * dE[i]
                    + c2 * (mymath::fast_cos(phi_b[i]) - cos_phi_s
                            + (phi_b[i] - phi_s) * sin_phi_s);
     return phi_b;
 }
double blond::hamiltonian (const GeneralParameters * GP, const RfParameters * RfP, const Beams * Beam, const double dt, const double dE, const f_vector_t total_voltage = {})
Definition at line 133 of file utilities.cpp.
References blond::Beams::beta, blond::constant::c, blond::GeneralParameters::charge, blond::RfParameters::counter, blond::Beams::energy, blond::RfParameters::eta_0, blond::RfParameters::eta_tracking(), blond::mymath::fast_cos(), blond::mymath::fast_sin(), blond::RfParameters::harmonic, blond::RfParameters::n_rf, blond::GeneralParameters::n_sections, blond::RfParameters::omega_rf, phase_modulo_above_transition(), phase_modulo_below_transition(), blond::RfParameters::phi_rf, blond::RfParameters::phi_s, blond::constant::pi, blond::GeneralParameters::ring_circumference, and blond::RfParameters::voltage.
 {
     if (GP->n_sections > 1)
         cerr << "WARNING: The Hamiltonian is not yet properly computed"
              << "for several sections!\n";
     if (RfP->n_rf > 1)
         cerr << "WARNING: The Hamiltonian will be calculated for"
              << "the first harmonic only!\n";
     const int counter = RfP->counter;
     const double h0 = RfP->harmonic[0][counter];
     double v0;
     if (total_voltage.empty())
         v0 = RfP->voltage[0][counter];
     else
         v0 = total_voltage[counter];
     v0 *= GP->charge;
     const double c1 = RfP->eta_tracking(Beam, counter, dE)
                       * constant::pi * constant::c
                       / (GP->ring_circumference * Beam->beta *
                          Beam->energy);
     const double c2 = constant::c * Beam->beta * v0
                       / (h0 * GP->ring_circumference);
     const double phi_s = RfP->phi_s[counter];
     double phi_b = RfP->omega_rf[0][counter] * dt + RfP->phi_rf[0][counter];
     const double eta0 = RfP->eta_0[counter];
     if (eta0 < 0)
         phi_b = phase_modulo_below_transition(phi_b);
     else if (eta0 > 0)
         phi_b = phase_modulo_above_transition(phi_b);
     return c1 * dE * dE
            + c2 * (mymath::fast_cos(phi_b) - mymath::fast_cos(phi_s)
                    + (phi_b - phi_s) * mymath::fast_sin(phi_s));
 }
int_vector_t blond::is_in_separatrix (const GeneralParameters * GP, const RfParameters * RfP, const Beams * Beam, const f_vector_t & dt, const f_vector_t & dE, const f_vector_t total_voltage = {})
Definition at line 18 of file utilities.cpp.
References blond::RfParameters::counter, hamiltonian(), blond::RfParameters::n_rf, blond::GeneralParameters::n_sections, blond::RfParameters::omega_rf, blond::RfParameters::phi_rf, blond::RfParameters::phi_s, and blond::constant::pi.
Referenced by longitudinal_bigaussian(), and blond::Beams::losses_separatrix().
 {
     /*
     Condition for being inside the separatrix.
     For the time being, for single RF section only or from total voltage.
     Single RF sinusoidal.
     Uses beta, energy averaged over the turn.
     To be generalized.
     */
     if (GP->n_sections > 1)
         cerr << "WARNING: is_in_separatrix is not yet properly computed"
              << "for several sections!\n";
     if (RfP->n_rf > 1)
         cerr << "WARNING: is_in_separatrix will be calculated for"
              << "the first harmonic only!\n";
     const int counter = RfP->counter;
     const double dt_sep = (constant::pi - RfP->phi_s[counter]
                            - RfP->phi_rf[0][counter])
                           / RfP->omega_rf[0][counter];
     const double Hsep = abs(hamiltonian(GP, RfP, Beam, dt_sep, 0.0));
     auto temp = hamiltonian(GP, RfP, Beam, dt.data(),
                             dE.data(), dt.size(),
                             total_voltage);
     // vector<bool> is not thread safe!!
     int_vector_t isin(temp.size());
     const int size = isin.size();
     #pragma omp parallel for
     for (int i = 0; i < size; i++)
         isin[i] = abs(temp[i]) < Hsep;
     return isin;
 }
f_vector_t blond::line_density_function (const f_vector_t & coord_array, const std::string & dist_type, const double bunch_length, const double bunch_position = 0., double exponent = 0.)
Definition at line 979 of file Distributions.cpp.
References blond::constant::pi.
Referenced by matched_from_line_density().
 {
     f_vector_t ret(coord_array.size());
     if (dist_type == "binomial") {
         for (uint i = 0; i < coord_array.size(); i++) {
             if (abs(coord_array[i] - bunch_position) > bunch_length / 2.)
                 ret[i] = 0.;
             else
                 ret[i] = pow(1 -
                              pow((coord_array[i] - bunch_position)
                                  / (bunch_length / 2.), 2.),
                              exponent + 0.5);
         }
         return ret;
     } else if (dist_type == "waterbag") {
         exponent = 0.;
         for (uint i = 0; i < coord_array.size(); i++) {
             if (abs(coord_array[i] - bunch_position) > bunch_length / 2.)
                 ret[i] = 0.;
             else
                 ret[i] = pow(1 -
                              pow((coord_array[i] - bunch_position)
                                  / (bunch_length / 2.), 2.),
                              exponent + 0.5);
         }
         return ret;
     } else if (dist_type == "parabolic_amplitude") {
         exponent = 1.;
         for (uint i = 0; i < coord_array.size(); i++) {
             if (abs(coord_array[i] - bunch_position) > bunch_length / 2.)
                 ret[i] = 0.;
             else
                 ret[i] = pow(1 -
                              pow((coord_array[i] - bunch_position)
                                  / (bunch_length / 2.), 2.),
                              exponent + 0.5);
         }
         return ret;
     } else if (dist_type == "parabolic_line") {
         exponent = 0.5;
         for (uint i = 0; i < coord_array.size(); i++) {
             if (abs(coord_array[i] - bunch_position) > bunch_length / 2.)
                 ret[i] = 0.;
             else
                 ret[i] = pow(1 -
                              pow((coord_array[i] - bunch_position)
                                  / (bunch_length / 2.), 2.),
                              exponent + 0.5);
         }
         return ret;
     } else if (dist_type == "gaussian") {
         const double sigma = bunch_length / 4.;
         for (uint i = 0; i < coord_array.size(); i++)
             ret[i] = exp(- pow(coord_array[i] - bunch_position, 2)
                          / (2 * sigma * sigma));
     } else if (dist_type == "cosine_squared") {
         for (uint i = 0; i < coord_array.size(); i++) {
             if (abs(coord_array[i] - bunch_position) > bunch_length / 2.)
                 ret[i] = 0.;
             else
                 ret[i] = pow(cos(constant::pi
                                  * (coord_array[i] - bunch_position)
                                  / bunch_length),
                              2);
         }
         return ret;
     } else {
         cerr << "[line_density_function] The dist_type was not recognized\n";
         exit(-1);
     }
     return ret;
 }
void blond::linear_interp_kick (const double *__restrict beam_dt, double *__restrict beam_dE, const double *__restrict voltage_array, const double *__restrict bin_centers, const int n_slices, const int n_macroparticles)
Definition at line 13 of file InducedVoltage.cpp.
Referenced by blond::InducedVoltageTime::track(), blond::RingAndRfSection::track(), blond::InducedVoltageFreq::track(), and blond::TotalInducedVoltage::track().
 {
     const double binFirst = bin_centers[0];
     const double binLast = bin_centers[n_slices - 1];
     const double inv_bin_width = (n_slices - 1) / (binLast - binFirst);
     #pragma omp parallel for
     for (int i = 0; i < n_macroparticles; ++i) {
         const double a = beam_dt[i];
         const int ffbin = static_cast<int>((a - binFirst) * inv_bin_width);
         const double voltageKick =
             ((a < binFirst) || (a > binLast))
             ? 0.0
             : voltage_array[ffbin] +
             (a - bin_centers[ffbin]) *
             (voltage_array[ffbin + 1] - voltage_array[ffbin]) *
             inv_bin_width;
         beam_dE[i] += voltageKick;
     }
 }
void blond::longitudinal_bigaussian (GeneralParameters * GP, RfParameters * RfP, Beams * Beam, double sigma_dt, double sigma_dE = 0, int seed = 0, bool reinsertion = false)
Definition at line 1059 of file Distributions.cpp.
References blond::GeneralParameters::beta, blond::GeneralParameters::charge, blond::RfParameters::counter, blond::Beams::dE, blond::Beams::dt, blond::GeneralParameters::energy, blond::RfParameters::eta_0, blond::RfParameters::harmonic, is_in_separatrix(), blond::Beams::n_macroparticles, blond::RfParameters::n_rf, blond::GeneralParameters::n_sections, blond::RfParameters::omega_rf, blond::RfParameters::phi_rf, blond::RfParameters::phi_s, blond::constant::pi, blond::util::read_vector_from_file(), blond::Beams::sigma_dE, blond::Beams::sigma_dt, and blond::RfParameters::voltage.
 {
     if (GP->n_sections > 1) {
         cerr << "WARNING: longitudinal_bigaussian is not yet properly\n"
              << "computed for several sections!\n";
     }
     if (RfP->n_rf > 1) {
         cerr << "WARNING: longitudinal_bigaussian for multiple RF\n"
              << "is not yet implemented\n";
     }
     int counter = RfP->counter;
     double harmonic = RfP->harmonic[0][counter];
     double energy = GP->energy[0][counter];
     double beta = GP->beta[0][counter];
     double omega_rf = RfP->omega_rf[0][counter];
     double phi_s = RfP->phi_s[counter];
     double phi_rf = RfP->phi_rf[0][counter];
     double eta0 = RfP->eta_0[counter];
     if (sigma_dE == 0) {
         auto voltage = GP->charge * RfP->voltage[0][counter];
         auto phi_b = omega_rf * sigma_dt + phi_s;
         sigma_dE =
             sqrt(voltage * energy * beta * beta *
                  (cos(phi_b) - cos(phi_s) + (phi_b - phi_s) * sin(phi_s)) /
                  (constant::pi * harmonic * eta0));
     }
     Beam->sigma_dE = sigma_dE;
     Beam->sigma_dt = sigma_dt;
     if (seed < 0) {
         f_vector_t random;
         util::read_vector_from_file(random, TEST_FILES "/normal_distribution.dat");
         for (int i = 0; i < Beam->n_macroparticles; ++i) {
             double r = random[i % random.size()];
             if (eta0 > 0)
                 Beam->dt[i] = sigma_dt * r
                               + (phi_s - phi_rf) / omega_rf;
             else
                 Beam->dt[i] = sigma_dt * r
                               + (phi_s - phi_rf - constant::pi) / omega_rf;
             Beam->dE[i] = sigma_dE * r;
         }
     } else {
         default_random_engine generator(seed);
         normal_distribution<double> distribution(0.0, 1.0);
         for (int i = 0; i < Beam->n_macroparticles; ++i) {
             double r = distribution(generator);
             if (eta0 > 0)
                 Beam->dt[i] = sigma_dt * r + (phi_s - phi_rf) / omega_rf;
             else
                 Beam->dt[i] =
                     sigma_dt * r + (phi_s - phi_rf - constant::pi) / omega_rf;
             r = distribution(generator);
             Beam->dE[i] = sigma_dE * r;
         }
     }
     // TODO test this one
     if (reinsertion == true) {
         auto is_not_in = is_in_separatrix(GP, RfP, Beam, Beam->dt, Beam->dE);
         for (auto &b : is_not_in) b = 1 - b;
         int size = accumulate(is_not_in.begin(), is_not_in.end(), 0);
         default_random_engine generator(seed);
         normal_distribution<double> distribution(0.0, 1.0);
         while (size != 0) {
             for (int i = 0; i < size; ++i) {
                 if (is_not_in[i] == false) continue;
                 double r = distribution(generator);
                 if (eta0 > 0)
                     Beam->dt[i] = sigma_dt * r + (phi_s - phi_rf) / omega_rf;
                 else
                     Beam->dt[i] = sigma_dt * r
                                   + (phi_s - phi_rf - constant::pi) / omega_rf;
                 r = distribution(generator);
                 Beam->dE[i] = sigma_dE * r;
             }
             is_not_in = is_in_separatrix(GP, RfP, Beam, Beam->dt, Beam->dE);
             size = accumulate(is_not_in.begin(), is_not_in.end(), 0);
         }
     }
 }
distribution_denstity_t blond::matched_from_distribution_density (Beams * beam, FullRingAndRf * full_ring, std::map< std::string, multi_t > distribution_opt, FullRingAndRf::main_harmonic_t main_harmonic_opt = FullRingAndRf::lowest_freq, TotalInducedVoltage * totVolt = nullptr, std::map< std::string, f_vector_t > extraVoltageDict = std::map<std::string, f_vector_t>(), int n_iterations_input = 1, int seed = 0)
Definition at line 517 of file Distributions.cpp.
References ALL, apply_f(), blond::mymath::arange(), blond::Beams::beta, blond::Beams::charge, blond::mymath::cum_trapezoid(), blond::Beams::dE, distribution_density_function(), blond::Beams::dt, blond::Beams::energy, blond::mymath::flatten(), FOR, blond::FullRingAndRf::fPotentialWell, blond::FullRingAndRf::fPotentialWellCoordinates, blond::FullRingAndRf::fRingList, blond::InducedVoltage::fSlices, blond::TotalInducedVoltage::induced_voltage_sum(), blond::mymath::interp(), blond::mymath::linspace(), blond::mymath::meshgrid(), blond::Beams::n_macroparticles, operator<(), blond::constant::pi, potential_well_cut(), blond::FullRingAndRf::potential_well_generation(), blond::mymath::random_choice(), blond::TotalInducedVoltage::reprocess(), blond::mymath::sign(), blond::mymath::sum(), and blond::mymath::trapezoid().
 {
     // NOTE
     // Not setting distribution_opt["exponent"] to null
     // Not defining distribution_density_function
     double slippage_factor = full_ring->fRingList[0]->eta_0[0];
     double eom_factor_dE = abs(slippage_factor) / (2 * beam->beta
                            * beam->beta * beam->energy);
     double eom_factor_potential = sign(slippage_factor)
                                   * beam->charge
                                   / full_ring->fRingList[0]->t_rev[0];
     int n_points_potential = 10000;
     full_ring->potential_well_generation(0, n_points_potential,
                                          main_harmonic_opt, 0.4);
     auto potential_well_array = full_ring->fPotentialWell;
     auto time_coord_array = full_ring->fPotentialWellCoordinates;
     double time_resolution = time_coord_array[1] - time_coord_array[0];
     f_vector_t extra_potential, induced_potential(potential_well_array.size(),0);
     f_vector_t line_density, time_coord_low_res, deltaE_coord_array;
     f_vector_2d_t density_grid;
     f_vector_2d_t time_grid, deltaE_grid;
     if (!extraVoltageDict.empty()) {
         auto extra_voltage_time_input = extraVoltageDict["time_array"];
         auto extra_voltage_input = extraVoltageDict["voltage_array"];
         auto extra_potential_input = (-eom_factor_potential)
                                      * cum_trapezoid(extra_voltage_input,
                                              extra_voltage_time_input[1]
                                              - extra_voltage_time_input[0]);
         extra_potential_input.insert(extra_potential_input.begin(), 0);
         extra_potential = interp(time_coord_array, extra_voltage_time_input,
                                  extra_potential_input);
     }
     auto total_potential = extra_potential.empty() ? potential_well_array + induced_potential :
                            potential_well_array + induced_potential + extra_potential;
     int n_iterations = n_iterations_input;
     if (totVolt == nullptr)
         n_iterations = 1;
     for (int i = 0; i < n_iterations; i++) {
         auto old_potential = total_potential;
         total_potential = extra_potential.empty() ? potential_well_array + induced_potential :
                           potential_well_array + induced_potential + extra_potential;
         double sse = sqrt(sum(apply_f(old_potential, total_potential,
         [](double a, double b) {return (a - b) * (a - b);})));
         cout <<  "Matching the bunch... (iteration: " << i
              << " and sse: " << sse << ")\n";
         f_vector_t time_coord_sep, potential_well_sep;
         potential_well_cut(time_coord_array, total_potential,
                            time_coord_sep, potential_well_sep);
         potential_well_sep -= *min_element(ALL(potential_well_sep));
         n_points_potential = potential_well_sep.size();
         auto max_potential = *max_element(ALL(potential_well_sep));
         auto max_deltaE = sqrt(max_potential / eom_factor_dE);
         auto H_array_dE0 = potential_well_sep;
         int n_points_grid = 1000;
         auto potential_well_indexes = arange(0.0, 1.0 * n_points_potential);
         auto grid_indexes = arange(0.0, 1.0 * n_points_grid)
                             * (1.0 * n_points_potential / n_points_grid);
         time_coord_low_res = interp(grid_indexes, potential_well_indexes,
                                     time_coord_sep);
         deltaE_coord_array = linspace(-max_deltaE, max_deltaE, n_points_grid);
         auto potential_well_low_res = interp(grid_indexes,
                                              potential_well_indexes,
                                              potential_well_sep);
         meshgrid(time_coord_low_res, deltaE_coord_array,
                  time_grid, deltaE_grid);
         f_vector_2d_t potential_well_grid, trash;
         meshgrid(potential_well_low_res, potential_well_low_res,
                  potential_well_grid, trash);
         f_vector_t J_array_dE0(n_points_grid, 0.);
         for (int j = 0; j < n_points_grid; j++) {
             auto dE_trajectory = apply_f(H_array_dE0,
             [eom_factor_dE, &potential_well_low_res, j](double x) {
                 auto num = (potential_well_low_res[j] - x) / eom_factor_dE;
                 return (num < 0.0) ? 0.0 : sqrt(num);
             });
             J_array_dE0[j] = (2.0 / (2.*constant::pi))
                              * trapezoid(dE_trajectory, time_resolution);
         }
         H_array_dE0 = potential_well_low_res;
         struct node {
             double h, j;
             bool operator<(const node &o) const
             {
                 return h < o.h;
             }
         };
         vector<node> nodes(H_array_dE0.size());
         for (uint i = 0; i < nodes.size(); i++)
             nodes[i] = {H_array_dE0[i], J_array_dE0[i]};
         sort(ALL(nodes));
         for (uint i = 0; i < nodes.size(); i++) {
             H_array_dE0[i] = nodes[i].h;
             J_array_dE0[i] = nodes[i].j;
         }
         f_vector_2d_t H_grid, J_grid;
         for (uint j = 0; j < deltaE_grid.size(); j++)
             H_grid.push_back(eom_factor_dE * deltaE_grid[j] * deltaE_grid[j]
                              + potential_well_grid[j]);
         for (auto &row : H_grid)
             J_grid.push_back(interp(row, H_array_dE0, J_array_dE0, 0.0,
                                     numeric_limits<double>::infinity()));
         auto density_variable = distribution_opt["density_variable"].s;
         double X0 = 0.;
         if (distribution_opt.find("bunch_length") != distribution_opt.end()) {
             double tau = 0.0;
             double X_low, X_hi, X_min, X_max, X_accuracy;
             if (density_variable == "density_from_J") {
                 X_low = J_array_dE0[0];
                 X_hi = J_array_dE0[n_points_grid - 1];
                 X_min = X_low;
                 X_max = X_hi;
                 X_accuracy = J_array_dE0[1] - J_array_dE0[0] / 2;
             } else if (density_variable == "density_from_H") {
                 X_low = H_array_dE0[0];
                 X_hi = H_array_dE0[n_points_grid - 1];
                 X_min = X_low;
                 X_max = X_hi;
                 X_accuracy = H_array_dE0[1] - H_array_dE0[0] / 2;
             } else {
                 cerr << "[Distribution density] The density_variable was not "
                      << "recognized\n";
                 exit(-1);
             }
             double bunch_length_accuracy = (time_coord_low_res[1]
                                             - time_coord_low_res[0]) / 2;
             while (abs(distribution_opt["bunch_length"].d - tau) > bunch_length_accuracy) {
                 X0 = 0.5 * (X_low + X_hi);
                 density_grid.clear();
                 if (density_variable == "density_from_J") {
                     if (distribution_opt["type"].s == "user_input") {
                         for (auto &row : J_grid)
                             density_grid.push_back(
                                 distribution_opt["function"].f(
                                     row, distribution_opt["type"].s,
                                     X0, distribution_opt["exponent"].d));
                     } else {
                         density_grid = distribution_density_function(J_grid,
                                        distribution_opt["type"].s,
                                        X0, distribution_opt["exponent"].d);
                     }
                 } else { // density_variable == "density_from_H"
                     if (distribution_opt["type"].s == "user_input") {
                         for (auto &row : H_grid)
                             density_grid.push_back(
                                 distribution_opt["function"].f(
                                     row, distribution_opt["type"].s,
                                     X0, distribution_opt["exponent"].d));
                     } else {
                         density_grid = distribution_density_function(H_grid,
                                        distribution_opt["type"].s,
                                        X0, distribution_opt["exponent"].d);
                     }
                 }
                 double density_grid_sum = 0;
                 for (auto &row : density_grid) density_grid_sum += sum(row);
                 for (auto &row : density_grid) row /= density_grid_sum;
                 line_density.clear();
                 line_density.resize(density_grid[0].size(), 0);
                 for (auto &row : density_grid) line_density += row;
                 bool flag = false;
                 FOR(line_density, it) flag = flag | (*it > 0);
                 if (flag) {
                     auto square = [](double x) {return x * x;};
                     tau = 4 * sqrt(
                               sum(
                                   apply_f(time_coord_low_res
                                           - sum(line_density * time_coord_low_res)
                                           / sum(line_density), square) * line_density)
                               / sum(line_density));
                     if (distribution_opt.find("bunch_length_fit") != distribution_opt.end()) {
                         auto slices = Slices(full_ring->fRingList[0]->rfp, beam,
                                              n_points_grid);
                         slices.n_macroparticles = line_density;
                         slices.bin_centers = time_coord_low_res;
                         slices.edges =
                             linspace(
                                 slices.bin_centers[0]
                                 - (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                 slices.bin_centers.back()
                                 + (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                 slices.bin_centers.size() + 1);
                         auto bunch_length_fit = distribution_opt["bunch_length_fit"].s;
                         if (bunch_length_fit == "gauss") {
                             slices.bl_gauss = tau;
                             slices.bp_gauss = sum(line_density * time_coord_low_res)
                                               / sum(line_density);
                             slices.gaussian_fit();
                             tau = slices.bl_gauss;
                         } else if (bunch_length_fit == "fwhm") {
                             slices.fwhm();
                             tau = slices.bl_fwhm;
                         } else if (bunch_length_fit == "end_to_end") {
                             double first, last;
                             int i = 0;
                             while (i < n_points_grid && slices.n_macroparticles[i] <= 0.) i++;
                             first = i < n_points_grid ? slices.bin_centers[i] : 0;
                             i = n_points_grid - 1;
                             while (i >= 0 && slices.n_macroparticles[i] <= 0.) i--;
                             last = i >= 0 ? slices.bin_centers[i] : 0;
                             tau = last - first;
                         }
                     }
                 }
                 if (tau >= distribution_opt["bunch_length"].d) X_hi = X0;
                 else X_low = X0;
                 if (X_max - X0 < X_accuracy) {
                     cerr << "[distribution density] Warning: The bucket is too "
                          << "small to have the desired bunch length!\n"
                          << "Input is " << distribution_opt["bunch_length"].d
                          << "\n, the generation gave " << tau
                          << ", the error is " << distribution_opt["bunch_length"].d - tau
                          << "%\n";
                     break;
                 }
                 if (X0 - X_min < X_accuracy)
                     cerr << "[distribution density] Warning: The desired bunch "
                          << "is too small to be generated accurately\n";
             }
         }
         if (distribution_opt["type"].s != "user_input_table") {
             density_grid.clear();
             if (density_variable == "density_from_J") {
                 if (distribution_opt.find("emittance") != distribution_opt.end()) {
                     X0 = distribution_opt["emittance"].d / (2 * constant::pi);
                 }
                 density_grid = distribution_density_function(J_grid,
                                distribution_opt["type"].s,
                                X0, distribution_opt["exponent"].d);
             } else { // density_variable == "density_from_H"
                 if (distribution_opt.find("emittance") != distribution_opt.end()) {
                     auto emittance = distribution_opt["emittance"].d / (2 * constant::pi);
                     auto H0 = interp({emittance}, J_array_dE0, H_array_dE0);
                     X0 = H0[0];
                 }
                 density_grid = distribution_density_function(H_grid,
                                distribution_opt["type"].s,
                                X0, distribution_opt["exponent"].d);
             }
         } else {
             density_grid.clear();
             if (density_variable == "density_from_J") {
                 for (auto &row : J_grid)
                     density_grid.push_back(
                         interp(row, distribution_opt["user_table_action"].v,
                                distribution_opt["user_table_density"].v));
             } else { // density_variable == "density_from_H"
                 for (auto &row : H_grid)
                     density_grid.push_back(
                         interp(row, distribution_opt["user_table_action"].v,
                                distribution_opt["user_table_density"].v));
             }
         }
         double density_grid_sum = 0;
         for (uint i = 0; i < H_grid.size(); i++) {
             for (uint j = 0; j < H_grid[i].size(); j++)
                 if (H_grid[i][j] > H_array_dE0.back())
                     density_grid[i][j] = 0;
             density_grid_sum += sum(density_grid[i]);
         }
         for (auto &row : density_grid) row /= density_grid_sum;
         line_density.clear();
         line_density.resize(density_grid[0].size(), 0);
         for (auto &row : density_grid) line_density += row;
         line_density /= (sum(line_density) / beam->n_macroparticles);
         // plot_generated_bunch(time_coord_low_res, line_density,
         //                      time_coord_low_res, line_density, "savefig", "fig");
         // continue here
         if (totVolt != nullptr) {
             auto slices = Slices(full_ring->fRingList[0]->rfp,
                                  beam, n_points_grid);
             slices.n_macroparticles = line_density;
             slices.bin_centers = time_coord_low_res;
             slices.edges = linspace(slices.bin_centers[0]
                                     - (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                     slices.bin_centers.back()
                                     + (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                     slices.bin_centers.size() + 1);
             // slices.n_slices and slices.fit_option are already set
             auto old_slices = totVolt->fSlices;
             totVolt->reprocess(&slices);
             int induced_voltage_length_sep = ceil((time_coord_array.back() - time_coord_low_res[0])
                                                   / (time_coord_low_res[1] - time_coord_low_res[0]));
             auto induced_voltage = totVolt->induced_voltage_sum(beam,
                                    induced_voltage_length_sep);
             auto time_induced_voltage = linspace(time_coord_low_res[0],
                                                  time_coord_low_res[0]
                                                  + (induced_voltage_length_sep - 1)
                                                  * (time_coord_low_res[1] - time_coord_low_res[0]),
                                                  induced_voltage_length_sep);
             auto induced_potential_low_res = - eom_factor_potential
                                              * cum_trapezoid(induced_voltage,
                                                      time_induced_voltage[1]
                                                      - time_induced_voltage[0]);
             induced_potential_low_res.insert(induced_potential_low_res.begin(), 0);
             induced_potential = interp(time_coord_array,
                                             time_induced_voltage,
                                             induced_potential_low_res);
             totVolt->reprocess(old_slices);
         }
     }
     //populating the bunch
     f_vector_t density_grid_flat = flatten(density_grid);
     auto indexes = random_choice(arange(0, (int)density_grid_flat.size()),
                                  beam->n_macroparticles,
                                  density_grid_flat);
     auto time_grid_flat = flatten(time_grid);
     auto deltaE_grid_flat = flatten(deltaE_grid);
     const double delta_time_coord = time_coord_low_res[1] - time_coord_low_res[0];
     const double delta_deltaE = deltaE_coord_array[1] - deltaE_coord_array[0];
     default_random_engine gen(seed);
     uniform_real_distribution<double> d(0.0, 1.0);
     for (int i = 0; i < beam->n_macroparticles; i++) {
         beam->dt[i] = time_grid_flat[indexes[i]] + (d(gen) - 0.5) * delta_time_coord;
         beam->dE[i] = deltaE_grid_flat[indexes[i]] + (d(gen) - 0.5) * delta_deltaE;
     }
     // cout << "beam dt mean: " << mean(beam->dt) << "\n";
     // cout << "beam dt std: " << standard_deviation(beam->dt) << "\n";
     // cout << "beam dE mean: " << mean(beam->dE) << "\n";
     // cout << "beam dE std: " << standard_deviation(beam->dE) << "\n";
     return {time_coord_low_res, line_density};
 }
line_density_t blond::matched_from_line_density (Beams * beam, FullRingAndRf * full_ring, std::map< std::string, std::string > line_density_opt, FullRingAndRf::main_harmonic_t main_harmonic_opt = FullRingAndRf::lowest_freq, TotalInducedVoltage * totVolt = nullptr, std::string plot = "", std::string figdir = "fig", std::string half_option = "first", std::map< std::string, f_vector_t > extraVoltageDict = std::map<std::string, f_vector_t>(), int n_iterations_input = 100, int seed = 0)
Definition at line 21 of file Distributions.cpp.
References ALL, blond::mymath::arange(), blond::Beams::beta, blond::Beams::charge, blond::mymath::cum_trapezoid(), blond::Beams::dE, blond::Beams::dt, blond::constant::e, blond::Beams::energy, blond::mymath::flatten(), FOR, blond::FullRingAndRf::fPotentialWell, blond::FullRingAndRf::fPotentialWellCoordinates, blond::FullRingAndRf::fRingList, blond::InducedVoltage::fSlices, blond::mymath::interp(), line_density_function(), blond::mymath::linspace(), blond::mymath::max(), blond::mymath::meshgrid(), minmax_location(), blond::Beams::n_macroparticles, blond::Slices::n_macroparticles, operator<(), blond::constant::pi, plot_generated_bunch(), potential_well_cut(), blond::FullRingAndRf::potential_well_generation(), blond::mymath::random_choice(), blond::TotalInducedVoltage::reprocess(), blond::Slices::rfp, blond::mymath::sign(), blond::util::string_to_double_vector(), blond::mymath::sum(), and blond::mymath::trapezoid().
 {
     // not setting line_density_opt["exponent"] to null
     double slippage_factor = full_ring->fRingList[0]->eta_0[0];
     double eom_factor_dE = abs(slippage_factor) / (2 * beam->beta
                            * beam->beta * beam->energy);
     double eom_factor_potential = sign(slippage_factor)
                                   * beam->charge
                                   / full_ring->fRingList[0]->t_rev[0];
     int n_points_potential = 1e4;
     full_ring->potential_well_generation(0, n_points_potential,
                                          main_harmonic_opt,
                                          0.4);
     auto potential_well_array = full_ring->fPotentialWell;
     auto time_coord_array = full_ring->fPotentialWellCoordinates;
     f_vector_t extra_potential;
     int n_points_line_den = 0;
     f_vector_t line_density, time_line_den;
     double line_den_resolution = 0.;
     if (!extraVoltageDict.empty()) {
         auto &extra_voltage_time_input = extraVoltageDict["time_array"];
         auto &extra_voltage_input = extraVoltageDict["voltage_array"];
         auto extra_potential_input = cum_trapezoid(extra_voltage_input,
                                      extra_voltage_time_input[1]
                                      - extra_voltage_time_input[0]);
         extra_potential_input.insert(extra_potential_input.begin(), 0);
         extra_potential_input *= -eom_factor_potential;
         extra_potential = interp(time_coord_array, extra_voltage_time_input,
                                  extra_potential_input);
     }
     if (line_density_opt.find("type") == line_density_opt.end()) {
         cerr << "[matched_from_line_density] The input for the"
              << "matched_from_line_density function was not recognized\n";
         exit(-1);
     }
     if (line_density_opt["type"] != "user_input") {
         n_points_line_den = 1e4;
         time_line_den = linspace(time_coord_array.front(),
                                  time_coord_array.back(),
                                  n_points_line_den);
         line_den_resolution = time_line_den[1] - time_line_den[0];
         auto exponent = (line_density_opt.find("exponent") == line_density_opt.end()) ?
                         0. : stod(line_density_opt["exponent"]);
         line_density = line_density_function(time_line_den,
                                              line_density_opt["type"],
                                              stod(line_density_opt["bunch_length"]),
                                              (time_coord_array.front()
                                               + time_coord_array.back()) / 2.,
                                              exponent);
         line_density -= *min_element(ALL(line_density));
         line_density *= (beam->n_macroparticles / sum(line_density));
     } else { // (line_density_opt["type"] == "user_input") {
         time_line_den = util::string_to_double_vector(line_density_opt["time_line_den"]);
         n_points_line_den = time_line_den.size();
         line_den_resolution = time_line_den[1] - time_line_den[0];
         line_density = util::string_to_double_vector(
                            line_density_opt["line_density"]);
         line_density -= *min_element(ALL(line_density));
         line_density *= (beam->n_macroparticles / sum(line_density));
     }
     f_vector_t induced_potential_final, induced_potential, time_induced_voltage;
     int n_iterations = 1;
     int induced_voltage_length = 0;
     if (totVolt != nullptr) {
         auto rfp = totVolt->fSlices->rfp;
         auto slices = Slices(rfp, beam, n_points_line_den);
         slices.n_macroparticles = line_density;
         slices.bin_centers = time_line_den;
         slices.edges = linspace(time_line_den[0]
                                 - (time_line_den[1] - time_line_den[0]) / 2,
                                 time_line_den.back()
                                 + (time_line_den[1] - time_line_den[0]) / 2,
                                 time_line_den.size() + 1);
         // fit option is already normal
         auto induced_voltage_object = *totVolt;
         induced_voltage_object.reprocess(&slices);
         induced_voltage_length = 1.5 * n_points_line_den;
         auto induced_voltage = induced_voltage_object.induced_voltage_sum(
                                    beam, induced_voltage_length);
         time_induced_voltage = linspace(time_line_den[0],
                                         time_line_den[0] + (induced_voltage_length - 1)
                                         * line_den_resolution,
                                         induced_voltage_length);
         induced_potential = cum_trapezoid(induced_voltage,
                                           time_induced_voltage[1] - time_induced_voltage[0]);
         induced_potential *= -eom_factor_potential;
         induced_potential.insert(induced_potential.begin(), 0);
         n_iterations = n_iterations_input;
     }
     double max_profile_pos = 0.;
     f_vector_t time_coord_sep, potential_well_sep;
     for (int i = 0; i < n_iterations; i++) {
         if (totVolt != nullptr)
             induced_potential_final = interp(time_coord_array,
                                              time_induced_voltage,
                                              induced_potential);
         uint size = max(potential_well_array.size(),
                         max(induced_potential_final.size(),
                             extra_potential.size()));
         f_vector_t total_potential(size, 0.);
         for (uint j = 0; j < size; j++) {
             if (j < potential_well_array.size())
                 total_potential[j] += potential_well_array[j];
             if (j < induced_potential_final.size())
                 total_potential[j] += induced_potential_final[j];
             if (j < extra_potential.size())
                 total_potential[j] += extra_potential[j];
         }
         potential_well_cut(time_coord_array, total_potential,
                            time_coord_sep, potential_well_sep);
         f_vector_t min_positions_potential, max_positions_potential;
         f_vector_t min_values_potential, max_values_potential;
         minmax_location(time_coord_sep, potential_well_sep,
                         min_positions_potential, max_positions_potential,
                         min_values_potential, max_values_potential);
         f_vector_t min_positions_profile, max_positions_profile;
         f_vector_t min_values_profile, max_values_profile;
         f_vector_t time_line_den_non_zero;
         f_vector_t line_density_non_zero;
         for (uint i = 0; i < line_density.size(); i++) {
             if (abs(line_density[i]) > 1e-20) {
                 time_line_den_non_zero.push_back(time_line_den[i]);
                 line_density_non_zero.push_back(line_density[i]);
             }
         }
         minmax_location(time_line_den_non_zero, line_density_non_zero,
                         min_positions_profile, max_positions_profile,
                         min_values_profile, max_values_profile);
         int n_minima_potential = min_positions_potential.size();
         int n_maxima_profile = max_positions_profile.size();
         if (n_maxima_profile > 1) {
             cerr << "[matched_from_line_density] Warning: the profile has \n"
                  << "several max, the highest one is taken. Be sure the \n"
                  << "profile is monotonous and not too noisy.\n";
             int p = 0;
             for (uint i = 0; i < max_values_profile.size(); i++) {
                 if (max_values_profile[i] > max_values_profile[p])
                     p = i;
             }
             max_profile_pos = max_positions_profile[p];
         } else {
             max_profile_pos = max_positions_profile[0];
         }
         double min_potential_pos = 0.;
         if (n_minima_potential > 1) {
             cerr << "[matched_from_line_density] Warning: the potential well \n"
                  << "has several min, the deepest one is taken. The induced \n"
                  << "potential is probably splitting the potential well.\n";
             int p = 0;
             for (uint i = 0; i < min_values_potential.size(); i++) {
                 if (min_values_potential[i] > min_values_potential[p])
                     p = i;
             }
             min_potential_pos = min_positions_potential[p];
         } else {
             min_potential_pos = min_positions_potential[0];
         }
         // NOTE what is happening here?
         // can max_profile_pos be more than one element?
         if (totVolt == nullptr) {
             time_line_den -= (max_profile_pos - min_potential_pos);
             max_profile_pos = max_profile_pos -
                               (max_profile_pos - min_potential_pos);
         }
         if (i != n_iterations - 1) {
             time_line_den -= (max_profile_pos - min_potential_pos);
             time_induced_voltage =
                 linspace(time_line_den[0], time_line_den[0]
                          + (induced_voltage_length - 1) * line_den_resolution,
                          induced_voltage_length);
         }
     }
     int n_points_abel = 10000;
     int abel_both_step = 1;
     f_vector_2d_t density_function_average;
     f_vector_2d_t hamiltonian_average;
     f_vector_t potential_half;
     f_vector_t density_function, hamiltonian_coord;
     if (half_option == "both") {
         abel_both_step = 2;
         density_function_average = f_vector_2d_t(n_points_abel, f_vector_t(2));
         hamiltonian_average = f_vector_2d_t(n_points_abel, f_vector_t(2));
     }
     for (int abel_index = 0; abel_index < abel_both_step; abel_index++) {
         f_vector_t line_den_half, time_coord_half;
         if (half_option == "first") {
             FOR(time_line_den, it) {
                 if (*it >= time_line_den[0] && *it <= max_profile_pos) {
                     auto idx = it - time_line_den.begin();
                     line_den_half.push_back(line_density[idx]);
                     time_coord_half.push_back(time_line_den[idx]);
                 }
             }
         } else if (half_option == "second") {
             FOR(time_line_den, it) {
                 if (*it <= time_line_den.back() && *it >= max_profile_pos) {
                     auto idx = it - time_line_den.begin();
                     line_den_half.push_back(line_density[idx]);
                     time_coord_half.push_back(time_line_den[idx]);
                 }
             }
         } else if (half_option == "both" && abel_index == 0) {
             FOR(time_line_den, it) {
                 if (*it >= time_line_den[0] && *it <= max_profile_pos) {
                     auto idx = it - time_line_den.begin();
                     line_den_half.push_back(line_density[idx]);
                     time_coord_half.push_back(time_line_den[idx]);
                 }
             }
         } else if (half_option == "both" && abel_index == 1) {
             FOR(time_line_den, it) {
                 if (*it <= time_line_den.back() && *it >= max_profile_pos) {
                     auto idx = it - time_line_den.begin();
                     line_den_half.push_back(line_density[idx]);
                     time_coord_half.push_back(time_line_den[idx]);
                 }
             }
         }
         const double time_coord_diff = time_coord_half[1] - time_coord_half[0];
         potential_half = interp(time_coord_half,
                                 time_coord_sep, potential_well_sep);
         potential_half -= *min_element(ALL(potential_half));
         f_vector_t line_den_diff;
         adjacent_difference(ALL(line_den_half), back_inserter(line_den_diff));
         line_den_diff.erase(line_den_diff.begin());
         line_den_diff /= time_coord_diff;
         auto time_line_den_diff = time_coord_half;
         time_line_den_diff.pop_back();
         time_line_den_diff += (time_coord_diff) / 2.;
         line_den_diff = interp(time_coord_half, time_line_den_diff,
                                line_den_diff, 0.0, 0.0);
         auto time_abel = linspace(time_coord_half[0],
                                   time_coord_half.back(),
                                   n_points_abel);
         auto line_den_diff_abel = interp(time_abel, time_coord_half,
                                          line_den_diff);
         auto potential_abel = interp(time_abel, time_coord_half,
                                      potential_half);
         density_function.resize(n_points_abel, 0.);
         hamiltonian_coord.resize(n_points_abel, 0.);
         if (half_option == "first" || (half_option == "both" && abel_index == 0)) {
             for (int i = 0; i < n_points_abel; i++) {
                 f_vector_t integrand(i + 1);
                 for (int j = 0; j < i + 1; j++) {
                     if (potential_abel[j] - potential_abel[i] <= 0.0)
                         integrand[j] = 0.0;
                     else
                         integrand[j] = line_den_diff_abel[j] / sqrt(potential_abel[j]
                                        - potential_abel[i]);
                 }
                 if (integrand.size() > 2) {
                     auto rit = integrand.rbegin();
                     rit[0] = rit[1] + (rit[1] - rit[2]);
                 } else if (integrand.size() > 1) {
                     auto rit = integrand.rbegin();
                     rit[0] = rit[1];
                 } else {
                     integrand = {0};
                 }
                 density_function[i] = sqrt(eom_factor_dE) / constant::pi
                                       * trapezoid(integrand, time_coord_diff);
                 hamiltonian_coord[i] = potential_abel[i];
             }
         } else if (half_option == "second" || (half_option == "both" && abel_index == 1)) {
             for (int i = 0; i < n_points_abel; i++) {
                 f_vector_t integrand;
                 for (uint j = i; j < line_den_diff_abel.size(); j++)
                     if (potential_abel[j] - potential_abel[i] <= 0.0)
                         integrand.push_back(0.0);
                     else
                         integrand.push_back(line_den_diff_abel[j] / sqrt(potential_abel[j]
                                             - potential_abel[i]));
                 if (integrand.size() > 2) {
                     integrand[0] = integrand[1] + (integrand[2] - integrand[1]);
                 } else if (integrand.size() > 1) {
                     integrand[0] = integrand[1];
                 } else {
                     integrand = {0};
                 }
                 density_function[i] = - sqrt(eom_factor_dE) / constant::pi
                                       * trapezoid(integrand, time_coord_diff);
                 hamiltonian_coord[i] = potential_abel[i];
             }
         }
         FOR(density_function, it) {
             if (std::isnan(*it) || std::isinf(*it) || *it < 0.)
                 *it = 0.;
         }
         if (half_option == "both") {
             for (uint i = 0; i < hamiltonian_coord.size(); i++) {
                 hamiltonian_average[i][abel_index] = hamiltonian_coord[i];
                 density_function_average[i][abel_index] = density_function[i];
             }
         }
     }
     if (half_option == "both") {
         hamiltonian_coord.clear();
         f_vector_t hamiltonian_average1;
         f_vector_t density_average0, density_average1;
         FOR(hamiltonian_average, row) {
             hamiltonian_coord.push_back(row[0][0]);
             hamiltonian_average1.push_back(row[0][1]);
         }
         FOR(density_function_average, row) {
             density_average0.push_back(row[0][0]);
             density_average1.push_back(row[0][1]);
         }
         density_function = interp(hamiltonian_coord, hamiltonian_average1,
                                   density_average1);
         FOR(density_function, it) {
             int idx = it - density_function.begin();
             *it = (*it + density_average0[idx]) / 2.;
         }
     }
     double max_potential = *max_element(ALL(potential_half));
     double max_deltaE = sqrt(max_potential / eom_factor_dE);
     int n_points_grid = 1000;
     auto grid_indexes = arange<double>(0., n_points_grid)
                         * (time_line_den.size() / n_points_grid);
     auto time_coord_indexes = arange<double>(0., time_line_den.size());
     auto time_coord_for_grid = interp(grid_indexes, time_coord_indexes,
                                       time_line_den);
     auto deltaE_for_grid = linspace(-max_deltaE, max_deltaE, n_points_grid);
     auto potential_well_for_grid = interp(time_coord_for_grid, time_coord_sep,
                                           potential_well_sep);
     potential_well_for_grid -= *min_element(ALL(potential_well_for_grid));
     f_vector_2d_t time_grid, deltaE_grid, potential_well_grid, dummy;
     meshgrid(time_coord_for_grid, deltaE_for_grid, time_grid, deltaE_grid);
     meshgrid(potential_well_for_grid, potential_well_for_grid,
              potential_well_grid, dummy);
     f_vector_2d_t hamiltonian_grid;
     for (uint i = 0; i < deltaE_grid.size(); i++)
         hamiltonian_grid.push_back(eom_factor_dE * deltaE_grid[i] * deltaE_grid[i]
                                    + potential_well_grid[i]);
     struct node {
         double df, hc;
         bool operator<(const node &o) const
         {
             return hc < o.hc;
         }
     };
     vector<node> nodes(density_function.size());
     for (uint i = 0; i < density_function.size(); i++)
         nodes[i] = {density_function[i], hamiltonian_coord[i]};
     sort(ALL(nodes));
     for (uint i = 0; i < density_function.size(); i++) {
         density_function[i] = nodes[i].df;
         hamiltonian_coord[i] = nodes[i].hc;
     }
     f_vector_2d_t density_grid;
     for (auto &row : hamiltonian_grid) {
         density_grid.push_back(interp(row, hamiltonian_coord, density_function));
     }
     double grid_sum = 0.;
     for (auto &row : density_grid) {
         for (auto &e : row)
             if (std::isnan(e) || std::isinf(e) || e < 0.) e = 0.;
         grid_sum += accumulate(ALL(row), 0.0);
     }
     FOR(density_grid, row) *row /= grid_sum;
     f_vector_t reconstructed_line_den(density_grid[0].size(), 0.0);
     FOR(density_grid, row) reconstructed_line_den += *row;
     if (plot != "")
         plot_generated_bunch(time_line_den, line_density, time_coord_for_grid,
                              reconstructed_line_den, plot, figdir);
     f_vector_t density_grid_flat = flatten(density_grid);
     auto indexes = random_choice(arange(0, (int)density_grid_flat.size()),
                                  beam->n_macroparticles,
                                  density_grid_flat);
     auto time_grid_flat = flatten(time_grid);
     auto deltaE_grid_flat = flatten(deltaE_grid);
     const double delta_time_coord = time_coord_for_grid[1] - time_coord_for_grid[0];
     const double delta_deltaE = deltaE_for_grid[1] - deltaE_for_grid[0];
     std::default_random_engine gen(seed);
     std::uniform_real_distribution<double> d(0.0, 1.0);
     for (int i = 0; i < beam->n_macroparticles; i++) {
         beam->dt[i] = time_grid_flat[indexes[i]] + (d(gen) - 0.5) * delta_time_coord;
         beam->dE[i] = deltaE_grid_flat[indexes[i]] + (d(gen) - 0.5) * delta_deltaE;
     }
     // cout << "beam dt mean: " << mean(beam->dt) << "\n";
     // cout << "beam dt std: " << standard_deviation(beam->dt) << "\n";
     // cout << "beam dE mean: " << mean(beam->dE) << "\n";
     // cout << "beam dE std: " << standard_deviation(beam->dE) << "\n";
     // TODO test this part
     if (totVolt != nullptr) {
         auto rfp = totVolt->fSlices->rfp;
         auto slices = Slices(rfp, beam, time_coord_for_grid.size());
         slices.n_macroparticles = reconstructed_line_den * beam->n_macroparticles;
         slices.bin_centers = time_coord_for_grid;
         slices.edges = linspace(slices.bin_centers[0]
                                 - (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                 slices.bin_centers.back()
                                 + (slices.bin_centers[1] - slices.bin_centers[0]) / 2,
                                 slices.bin_centers.size() + 1);
         // fit option is already normal
         auto induced_voltage_object = *totVolt;
         induced_voltage_object.reprocess(&slices);
         induced_voltage_object.induced_voltage_sum(beam);
     }
     return {hamiltonian_coord,
             density_function,
             time_line_den,
             line_density};
 }
void blond::minmax_location (const f_vector_t & x, const f_vector_t & f, f_vector_t & min_x_position, f_vector_t & max_x_position, f_vector_t & min_values, f_vector_t & max_values)
Definition at line 178 of file utilities.cpp.
References blond::mymath::interp().
Referenced by matched_from_line_density(), and potential_well_cut().
 {
     min_x_position.clear(); max_x_position.clear();
     min_values.clear(); max_values.clear();
     f_vector_t f_derivative;
     adjacent_difference(f.begin(), f.end(), back_inserter(f_derivative));
     f_derivative.erase(f_derivative.begin());
     f_vector_t x_derivative;
     for (uint i = 0; i < x.size() - 1; i++)
         x_derivative.push_back(x[i] + (x[1] - x[0]) / 2);
     f_derivative = mymath::interp(x, x_derivative, f_derivative);
     f_vector_t f_derivative_second;
     adjacent_difference(f_derivative.begin(), f_derivative.end(),
                         back_inserter(f_derivative_second));
     f_derivative_second.erase(f_derivative_second.begin());
     f_derivative_second = mymath::interp(x, x_derivative, f_derivative_second);
     f_vector_t f_derivative_zeros;
     for (uint i = 0; i < f_derivative.size() - 1; i++) {
         if (f_derivative[i] == 0. || (f_derivative[i + 1] / f_derivative[i] < 0.))
             f_derivative_zeros.push_back(i);
     }
     for (const auto &i : f_derivative_zeros)
         if (f_derivative_second[i] > 0)
             min_x_position.push_back((x[i + 1] + x[i]) / 2.);
         else
             max_x_position.push_back((x[i + 1] + x[i]) / 2.);
     min_values = mymath::interp(min_x_position, x, f);
     max_values = mymath::interp(max_x_position, x, f);
 }
static int blond::omp_get_max_threads () inline static
Definition at line 18 of file openmp.h.
Referenced by blond::fft::convolution_with_ffts(), and blond::Slices::Slices().
 {return 1;}
static int blond::omp_get_num_threads () inline static
Definition at line 17 of file openmp.h.
Referenced by blond::Slices::histogram().
 {return 1;}
static int blond::omp_get_thread_num () inline static
Definition at line 19 of file openmp.h.
Referenced by blond::Slices::histogram().
 {return 0;}
static void blond::omp_set_num_threads (int threads) inline static
Definition at line 20 of file openmp.h.
 {}
template<typename T > static std::vector<bool> blond::operator!= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 287 of file vector_math.h.
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::not_equal_to<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator!= (const std::vector< T > & a, const T & b) inline static
Definition at line 352 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::not_equal_to<T>(), b));
         return result;
     }
template<typename T > static std::vector<T> blond::operator* (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 114 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, b, std::multiplies<T>());
     }
template<typename T , typename U > static std::vector<T> blond::operator* (const std::vector< T > & a, const U & b) inline static
Definition at line 189 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::multiplies<T>(), b));
     }
template<typename T , typename U > static std::vector<T> blond::operator* (const U & b, const std::vector< T > & a) inline static
Definition at line 195 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::multiplies<T>(), b));
     }
template<typename T > static std::vector<T> blond::operator*= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 121 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, b, std::multiplies<T>());
         return a;
     }
template<typename T , typename U > static std::vector<T> blond::operator*= (std::vector< T > & a, const U & b) inline static
Definition at line 201 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, std::bind2nd(std::multiplies<T>(), b));
         return a;
     }
template<typename T > static std::vector<T> blond::operator+ (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 83 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, b, std::plus<T>());
     }
template<typename T , typename U > static std::vector<T> blond::operator+ (const std::vector< T > & a, const U & b) inline static
Definition at line 151 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::plus<T>(), b));
     }
template<typename T , typename U > static std::vector<T> blond::operator+ (const U & b, const std::vector< T > & a) inline static
Definition at line 157 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::plus<T>(), b));
     }
template<typename T > static std::vector<T> blond::operator+= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 90 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, b, std::plus<T>());
         return a;
     }
template<typename T , typename U > static std::vector<T> blond::operator+= (std::vector< T > & a, const U & b) inline static
Definition at line 163 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, std::bind2nd(std::plus<T>(), b));
         return a;
     }
template<typename T > static std::vector<T> blond::operator- (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 99 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, b, std::minus<T>());
     }
template<typename T , typename U > static std::vector<T> blond::operator- (const std::vector< T > & a, const U & b) inline static
Definition at line 170 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::minus<T>(), b));
     }
template<typename T , typename U > static std::vector<T> blond::operator- (const U & b, const std::vector< T > & a) inline static
Definition at line 176 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind1st(std::minus<T>(), b));
     }
template<typename T > static std::vector<T> blond::operator-= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 106 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, b, std::minus<T>());
         return a;
     }
template<typename T , typename U > static std::vector<T> blond::operator-= (std::vector< T > & a, const U & b) inline static
Definition at line 182 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, std::bind2nd(std::minus<T>(), b));
         return a;
     }
template<typename T > static std::vector<T> blond::operator/ (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 130 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, b, std::divides<T>());
     }
template<typename T , typename U > static std::vector<T> blond::operator/ (const std::vector< T > & a, const U & b) inline static
Definition at line 208 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind2nd(std::divides<T>(), b));
     }
template<typename T , typename U > static std::vector<T> blond::operator/ (const U & b, const std::vector< T > & a) inline static
Definition at line 214 of file vector_math.h.
References apply_f().
     {
         return apply_f(a, std::bind1st(std::divides<T>(), b));
     }
template<typename T > static std::vector<T> blond::operator/= (std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 137 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, b, std::divides<T>());
         return a;
     }
template<typename T , typename U > static std::vector<T> blond::operator/= (std::vector< T > & a, const U & b) inline static
Definition at line 220 of file vector_math.h.
References apply_f_in_place().
     {
         apply_f_in_place(a, std::bind2nd(std::divides<T>(), b));
         return a;
     }
template<typename T > static std::vector<bool> blond::operator< (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 298 of file vector_math.h.
Referenced by matched_from_distribution_density(), matched_from_line_density(), blond::Slices::sort_particles(), and blond::Music::track().
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::less<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator< (const std::vector< T > & a, const T & b) inline static
Definition at line 362 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::less<T>(), b));
         return result;
     }
template<typename T > static std::ostream& blond::operator<< (std::ostream & os, const std::vector< T > & a) inline static
Definition at line 402 of file vector_math.h.
     {
         os << "[ ";
         std::copy(a.begin(), a.end(), std::ostream_iterator<T>(os, ", "));
         os << "\b\b ]\n";
         return os;
     }
template<typename T > static std::vector<bool> blond::operator<= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 309 of file vector_math.h.
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::less_equal<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator<= (const std::vector< T > & a, const T & b) inline static
Definition at line 372 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::less_equal<T>(), b));
         return result;
     }
template<typename T > static std::vector<bool> blond::operator== (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 276 of file vector_math.h.
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::equal_to<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator== (const std::vector< T > & a, const T & b) inline static
Definition at line 343 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::equal_to<T>(), b));
         return result;
     }
template<typename T > static std::vector<bool> blond::operator> (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 321 of file vector_math.h.
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::greater<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator> (const std::vector< T > & a, const T & b) inline static
Definition at line 382 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::greater<T>(), b));
         return result;
     }
template<typename T > static std::vector<bool> blond::operator>= (const std::vector< T > & a, const std::vector< T > & b) inline static
Definition at line 332 of file vector_math.h.
     {
         assert(a.size() == b.size());
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), b.begin(),
                        result.begin(), std::greater_equal<T>());
         return result;
     }
template<typename T > static std::vector<bool> blond::operator>= (const std::vector< T > & a, const T & b) inline static
Definition at line 392 of file vector_math.h.
     {
         std::vector<bool> result(a.size());
         std::transform(a.begin(), a.end(), result.begin(),
                        std::bind2nd(std::greater_equal<T>(), b));
         return result;
     }
static double blond::phase_modulo_above_transition (const double phi) inline static
Definition at line 18 of file trackers/utilities.h.
References blond::constant::pi.
Referenced by hamiltonian().
     {
         return phi - 2.0 * constant::pi * std::floor(phi / (2.0 * constant::pi));
     }
static double blond::phase_modulo_below_transition (const double phi) inline static
Definition at line 24 of file trackers/utilities.h.
References blond::constant::pi.
Referenced by hamiltonian().
     {
         return phi - 2.0 * constant::pi *
                (std::floor(phi / (2.0 * constant::pi) + 0.5));
     }
template<typename T > static T blond::pick (const std::vector< T > & a, const int i) inline static
Definition at line 227 of file vector_math.h.
     {
         assert(std::abs(i) < a.size());
         if (i >= 0)
             return a[i];
         else
             return a.rbegin()[-i - 1];
     }
template<typename T > static std::vector<T> blond::pick (const std::vector< T > & a, const std::vector< int > & indexes) inline static
Definition at line 237 of file vector_math.h.
     {
         std::vector<T> res;
         res.reserve(indexes.size());
         for (const auto &i : indexes) {
             res.push_back(a[i]);
         }
         return res;
     }
template<typename T > static std::vector<T> blond::pick (const std::vector< T > & a, const std::vector< bool > & indexes) inline static
Definition at line 249 of file vector_math.h.
     {
         std::vector<T> res;
         res.reserve(indexes.size());
         for (uint i = 0; i < indexes.size(); i++)
             if (indexes[i] == true)
                 res.push_back(a[i]);
         return res;
     }
int blond::plot_beam_profile (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig")
Definition at line 6 of file plot_slices.cpp.
References blond::Slices::bin_centers, blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::python::import(), and blond::Slices::n_macroparticles.
 {
     // python::initialize();
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_profile");
     auto pBinCenters = python::convert_double_array(Slices->bin_centers.data(),
                        Slices->bin_centers.size());
     auto pNMacropaticles = python::convert_double_array(Slices->n_macroparticles.data(),
                            Slices->n_macroparticles.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBinCenters, pNMacropaticles,
                                             pCounter, pStyle,  pDirname,
                                             NULL);
     return ret != nullptr;
     // python::finalize();
 }
int blond::plot_beam_profile_derivative (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig", string_vector_t modes = {"diff"})
Definition at line 31 of file plot_slices.cpp.
References blond::Slices::beam_profile_derivative(), blond::python::convert_double_2d_array(), blond::python::convert_int(), blond::python::convert_string(), blond::python::convert_string_array(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_profile_derivative");
     f_vector_2d_t x(modes.size(), f_vector_t());
     f_vector_2d_t derivative(modes.size(), f_vector_t());
     for (uint i = 0; i < modes.size(); i++)
         Slices->beam_profile_derivative(x[i], derivative[i], modes[i]);
     auto pX = python::convert_double_2d_array(x);
     auto pDerivative = python::convert_double_2d_array(derivative);
     auto pModes = python::convert_string_array(modes.data(), modes.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pDerivative, pCounter,
                                             pStyle, pDirname, pModes, NULL);
     return ret != nullptr;
 }
int blond::plot_beam_spectrum (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig")
Definition at line 59 of file plot_slices.cpp.
References blond::python::convert_complex_array(), blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::Slices::fBeamSpectrum, blond::Slices::fBeamSpectrumFreq, and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_spectrum");
     auto pBeamSpectrumFreq = python::convert_double_array(
                                  Slices->fBeamSpectrumFreq.data(),
                                  Slices->fBeamSpectrumFreq.size());
     auto pBeamSpectrum = python::convert_complex_array(
                              Slices->fBeamSpectrum.data(),
                              Slices->fBeamSpectrum.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBeamSpectrumFreq,
                                             pBeamSpectrum, pCounter, pStyle,
                                             pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_bunch_length_evol (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 109 of file plot_beams.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_beams", "plot_bunch_length_evol");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> sigma_dt((double *) read_1D(h5data, "Beam/sigma_dt",
                                      "double", &dims));
     auto pSigmaDt = python::convert_double_array(sigma_dt.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pSigmaDt,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_bunch_length_evol_gaussian (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 135 of file plot_beams.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_beams", "plot_bunch_length_evol_gaussian");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> bl_gauss((double *) read_1D(h5data,
                                      "Beam/bunch_length_gaussian",
                                      "double", &dims));
     auto pBlGauss = python::convert_double_array(bl_gauss.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pBlGauss,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_COM_motion (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 235 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_COM_motion");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/mean_dt",
                                   "double", &dims));
     auto pMeanDt = python::convert_double_array(array.get(), dims);
     array = std::unique_ptr<double> ((double *) read_1D(h5data,
                                      "Beam/mean_dE", "double", &dims));
     auto pMeanDE = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pMeanDt,
                                             pMeanDE, pOutputFreq, pDirname,
                                             NULL);
     return ret != nullptr;
 }
int blond::plot_energy_evol (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string style = ".", std::string dirname = "fig")
Definition at line 190 of file plot_beams.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_beams", "plot_energy_evol");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     auto pStyle = python::convert_string(style);
     hsize_t dims;
     std::unique_ptr<double> mean_dE((double *) read_1D(h5data, "Beam/mean_dE",
                                     "double", &dims));
     auto pMeanDE = python::convert_double_array(mean_dE.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pMeanDE,
                                             pOutputFreq, pStyle, pDirname,
                                             NULL);
     return ret != nullptr;
 }
void blond::plot_generated_bunch (f_vector_t & time_line_den, f_vector_t & line_density, f_vector_t & time_coord_for_grid, f_vector_t & rec_line_den, std::string plot, std::string figdir)
Definition at line 1149 of file Distributions.cpp.
References blond::python::convert_double_array(), blond::python::convert_string(), and blond::python::import().
Referenced by matched_from_line_density().
 {
     python::import();
     auto pFunc = python::import("distributions",
                                 "plot_generated_bunch");
     auto pTimeLineDen = python::convert_double_array(time_line_den.data(),
                         time_line_den.size());
     auto pLineDen = python::convert_double_array(line_density.data(),
                     line_density.size());
     auto pTimeCoord = python::convert_double_array(time_coord.data(),
                       time_coord.size());
     auto pRecLineDen = python::convert_double_array(rec_line_den.data(),
                        rec_line_den.size());
     auto pPlot = python::convert_string(plot);
     auto pFigDir = python::convert_string(figdir);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pTimeLineDen,
                                             pLineDen, pTimeCoord,
                                             pRecLineDen, pPlot, pFigDir, NULL);
     if (!ret) {
         std::cerr << "[plot_generated_bunch] An error occured while "
                   << "executing python code\n";
         exit(-1);
     }
 }
int blond::plot_impedance_vs_frequency (int counter, InducedVoltageFreq * indVoltFreq, Slices * slices, std::string option1 = "sum", std::string option2 = "no_spectrum", std::string option3 = "freq_fft", std::string style = "-", f_vector_t cut_left_right = {}, f_vector_t cut_up_down = {}, std::string dirname = "fig")
Definition at line 5 of file plot_impedance.cpp.
References blond::python::convert_complex_array(), blond::python::convert_double_2d_array(), blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::Slices::fBeamSpectrum, blond::Slices::fBeamSpectrumFreq, blond::InducedVoltageFreq::fFreqArray, blond::InducedVoltageFreq::fImpedanceSourceList, blond::InducedVoltageFreq::fTotalImpedance, and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_impedance",
                                 "plot_impedance_vs_frequency");
     auto pCounter = python::convert_int(counter);
     auto pDirname = python::convert_string(dirname);
     auto pStyle = python::convert_string(style);
     auto pOption1 = python::convert_string(option1);
     auto pOption2 = python::convert_string(option2);
     auto pOption3 = python::convert_string(option3);
     auto pCutLR = python::convert_double_array(cut_left_right.data(),
                   cut_left_right.size());
     auto pCutUD = python::convert_double_array(cut_up_down.data(),
                   cut_up_down.size());
     auto pTotalImpedance = python::convert_complex_array(
                                indVoltFreq->fTotalImpedance.data(),
                                indVoltFreq->fTotalImpedance.size());
     auto pBeamSpec = python::convert_complex_array(
                          slices->fBeamSpectrum.data(),
                          slices->fBeamSpectrum.size());
     auto pBeamSpecFreq = python::convert_double_array(
                              slices->fBeamSpectrumFreq.data(),
                              slices->fBeamSpectrumFreq.size());
     auto pFreqArray = python::convert_double_array(
                           indVoltFreq->fFreqArray.data(),
                           indVoltFreq->fFreqArray.size());
     f_vector_2d_t freq_array_2d;
     f_vector_2d_t impedance_real_2d;
     f_vector_2d_t impedance_imag_2d;
     for (auto &intensity : indVoltFreq->fImpedanceSourceList) {
         auto p = dynamic_cast<InputTable *>(intensity);
         if (p != nullptr && option3 == "freq_table") {
             freq_array_2d.push_back(p->fFrequencyArrayLoaded);
             impedance_real_2d.push_back(p->fReZArrayLoaded);
             impedance_imag_2d.push_back(p->fImZArrayLoaded);
         } else {
             freq_array_2d.push_back(indVoltFreq->fFreqArray);
             f_vector_t real, imag;
             for (const auto &z : intensity->fImpedance) {
                 real.push_back(z.real());
                 imag.push_back(z.imag());
             }
             impedance_real_2d.push_back(real);
             impedance_imag_2d.push_back(imag);
         }
     }
     auto pFreqArray2D = python::convert_double_2d_array(freq_array_2d);
     auto pIMpedanceReal2D = python::convert_double_2d_array(impedance_real_2d);
     auto pIMpedanceImag2D = python::convert_double_2d_array(impedance_imag_2d);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pCounter, pFreqArray,
                                             pTotalImpedance, pBeamSpec,
                                             pBeamSpecFreq, pFreqArray2D,
                                             pIMpedanceReal2D, pIMpedanceImag2D,
                                             pOption1, pOption2, pOption3,
                                             pStyle, pCutLR, pCutUD,
                                             pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_induced_voltage_vs_bin_centers (int counter, TotalInducedVoltage * totIndVolt, Slices * slices, std::string style = "-", std::string dirname = "fig")
Definition at line 90 of file plot_impedance.cpp.
References blond::Slices::bin_centers, blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::InducedVoltage::fInducedVoltage, and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_impedance",
                                 "plot_induced_voltage_vs_bin_centers");
     auto pCounter = python::convert_int(counter);
     auto pDirname = python::convert_string(dirname);
     auto pStyle = python::convert_string(style);
     auto pBinCenters = python::convert_double_array(
                            slices->bin_centers.data(),
                            slices->bin_centers.size());
     auto pInducedVoltage = python::convert_double_array(
                                totIndVolt->fInducedVoltage.data(),
                                totIndVolt->fInducedVoltage.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pCounter, pBinCenters,
                                             pInducedVoltage, pStyle,
                                             pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_LHCNoiseFB (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 266 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/LHC_noise_FB_factor",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_LHCNoiseFB_FWHM (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 292 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB_FWHM");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/LHC_noise_FB_bl", "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_LHCNoiseFB_FWHM_bbb (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 317 of file plot_llrf.cpp.
References blond::python::convert_double_2d_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_2D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_LHCNoiseFB_FWHM_bbb");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims[2];
     std::unique_ptr<double> array((double *) read_2D(h5data,
                                   "Beam/LHC_noise_FB_bl_bbb",
                                   "double", dims));
     f_vector_2d_t temp;
     for (uint i = 0; i < dims[0]; i++) {
         temp.push_back(f_vector_t(&array.get()[i * dims[1]],
                                   &array.get()[(i + 1) * dims[1]]));
     }
     auto ph5Data = python::convert_double_2d_array(temp);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_long_phase_space (GeneralParameters * GP, RfParameters * RfP, Beams * Beam, double xmin, double xmax, double ymin, double ymax, std::string xunit = "s", int sampling = 1, bool separatrix_plot = false, bool histograms_plot = true, std::string dirname = "fig", int alpha = 1)
Definition at line 6 of file plot_beams.cpp.
References blond::RfParameters::beta, blond::GeneralParameters::charge, blond::python::convert_bool(), blond::python::convert_double(), blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_int_array(), blond::python::convert_string(), blond::RfParameters::counter, blond::Beams::dE, blond::Beams::dt, blond::RfParameters::E_increment, blond::RfParameters::energy, blond::RfParameters::eta_0, blond::python::get_none(), blond::RfParameters::harmonic, blond::Beams::id, blond::python::import(), blond::RfParameters::n_rf, blond::GeneralParameters::n_sections, blond::RfParameters::omega_rf, blond::RfParameters::phi_rf, blond::RfParameters::phi_s, blond::GeneralParameters::t_rev, and blond::RfParameters::voltage.
 {
     // python::initialize();
     python::import();
     auto pFunc = python::import("plot_beams", "plot_long_phase_space");
     uint turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pRfPOmegaRf0 = python::convert_double(RfP->omega_rf[0][turn]);
     auto pRfPPhiRf0 = python::convert_double(RfP->phi_rf[0][turn]);
     auto pBeamDE = python::convert_double_array(Beam->dE.data(), Beam->dE.size());
     auto pBeamDt = python::convert_double_array(Beam->dt.data(), Beam->dt.size());
     auto pBeamId = python::convert_int_array(Beam->id.data(), Beam->id.size());
     auto pXMin = python::convert_double(xmin);
     auto pXMax = python::convert_double(xmax);
     auto pYMin = python::convert_double(ymin);
     auto pYMax = python::convert_double(ymax);
     auto pXUnit = python::convert_string(xunit);
     auto pSampling = python::convert_int(sampling);
     auto pSeparatrixPlot = python::convert_bool(separatrix_plot);
     auto pHistogramsPlot = python::convert_bool(histograms_plot);
     auto pDirname = python::convert_string(dirname);
     auto pAlpha = python::convert_int(alpha);
     if (separatrix_plot == true) {
         auto pGPNSections = python::convert_int(GP->n_sections);
         auto pGPCharge = python::convert_double(GP->charge);
         auto pGPTRev = python::convert_double(GP->t_rev[turn]);
         f_vector_t temp;
         for (auto &row : RfP->voltage) temp.push_back(row[turn]);
         auto pRfPVoltage = python::convert_double_array(temp.data(), temp.size());
         temp.clear();
         for (auto &row : RfP->omega_rf) temp.push_back(row[turn]);
         auto pRfPOmegaRf = python::convert_double_array(temp.data(), temp.size());
         temp.clear();
         for (auto &row : RfP->phi_rf) temp.push_back(row[turn]);
         auto pRfPPhiRf = python::convert_double_array(temp.data(), temp.size());
         auto pRfPEta0 = python::convert_double(RfP->eta_0[turn]);
         auto pRfPBeta = python::convert_double(RfP->beta[turn]);
         auto pRfPEnergy = python::convert_double(RfP->energy[turn]);
         auto pRfPNRf = python::convert_int(RfP->n_rf);
         auto pRfPHarmonic = python::convert_double(RfP->harmonic[0][turn]);
         auto pRfPPhiS = python::convert_double(RfP->phi_s[turn]);
         auto pRfPEIncrement = turn >= RfP->E_increment.size() ?
                               python::convert_double(RfP->E_increment.back()) :
                               python::convert_double(RfP->E_increment[turn]);
         auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pRfPOmegaRf0,
                                                 pRfPPhiRf0, pBeamId, pBeamDt,
                                                 pBeamDE, pXMin, pXMax, pYMin, pYMax,
                                                 pXUnit, pSampling, pSeparatrixPlot,
                                                 pGPNSections, pGPCharge, pGPTRev,
                                                 pRfPVoltage, pRfPOmegaRf, pRfPPhiRf,
                                                 pRfPEta0, pRfPBeta, pRfPEnergy, pRfPNRf,
                                                 pRfPHarmonic, pRfPPhiS, pRfPEIncrement,
                                                 pHistogramsPlot, pDirname, pAlpha,
                                                 NULL);
         return ret != nullptr;
     } else {
         auto pGPNSections = python::get_none();
         auto pGPCharge = python::get_none();
         auto pGPTRev = python::get_none();
         auto pRfPVoltage = python::get_none();
         auto pRfPOmegaRf = python::get_none();
         auto pRfPPhiRf = python::get_none();
         auto pRfPEta0 = python::get_none();
         auto pRfPBeta = python::get_none();
         auto pRfPEnergy = python::get_none();
         auto pRfPNRf = python::get_none();
         auto pRfPHarmonic = python::get_none();
         auto pRfPPhiS = python::get_none();
         auto pRfPEIncrement = python::get_none();
         auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pRfPOmegaRf0,
                                                 pRfPPhiRf0, pBeamId, pBeamDt,
                                                 pBeamDE, pXMin, pXMax, pYMin, pYMax,
                                                 pXUnit, pSampling, pSeparatrixPlot,
                                                 pGPNSections, pGPCharge, pGPTRev,
                                                 pRfPVoltage, pRfPOmegaRf, pRfPPhiRf,
                                                 pRfPEta0, pRfPBeta, pRfPEnergy, pRfPNRf,
                                                 pRfPHarmonic, pRfPPhiS, pRfPEIncrement,
                                                 pHistogramsPlot, pDirname, pAlpha,
                                                 NULL);
         return ret != nullptr;
     }
     // python::finalize();
 }
int blond::plot_noise_spectrum (f_vector_t & frequency, f_vector_t & spectrum, int sampling = 1, std::string dirname = "fig", int figno = 0)
Definition at line 8 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_noise_spectrum");
     auto pFigNo = python::convert_int(figno);
     auto pSampling = python::convert_int(sampling);
     auto pDirname = python::convert_string(dirname);
     auto pFreq = python::convert_double_array(frequency.data(),
                  frequency.size());
     auto pSpectrum = python::convert_double_array(spectrum.data(),
                      spectrum.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pFreq,
                                             pSpectrum, pSampling,
                                             pDirname, pFigNo, NULL);
     return ret != nullptr;
     // assert(ret);
 }
int blond::plot_phase_noise (f_vector_t & frequency, f_vector_t & spectrum, int sampling = 1, std::string dirname = "fig", int figno = 0)
Definition at line 33 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_phase_noise");
     auto pFigNo = python::convert_int(figno);
     auto pSampling = python::convert_int(sampling);
     auto pDirname = python::convert_string(dirname);
     auto pTime = python::convert_double_array(time.data(),
                  time.size());
     auto pDPhi = python::convert_double_array(dphi.data(),
                  dphi.size());
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pTime, pDPhi, pSampling,
                                             pDirname, pFigNo, NULL);
     return ret != nullptr;
     // assert(ret);
 }
int blond::plot_PL_bunch_phase (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 57 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_bunch_phase");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *)read_1D(h5data,
                                   "Beam/PL_bunch_phase",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_PL_freq_corr (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 159 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_freq_corr");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/PL_omegaRF_corr",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_PL_phase_corr (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 109 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_phase_corr");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data,
                                   "Beam/PL_phase_corr", "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_PL_RF_freq (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 134 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_RF_freq");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/PL_omegaRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_PL_RF_phase (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 84 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_PL_RF_phase");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/PL_phiRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_position_evol (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string style = ".", std::string dirname = "fig")
Definition at line 162 of file plot_beams.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_beams", "plot_position_evol");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     auto pStyle = python::convert_string(style);
     hsize_t dims;
     std::unique_ptr<double> mean_dt((double *) read_1D(h5data, "Beam/mean_dt",
                                     "double", &dims));
     auto pMeanDt = python::convert_double_array(mean_dt.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pMeanDt,
                                             pOutputFreq, pStyle, pDirname,
                                             NULL);
     return ret != nullptr;
 }
int blond::plot_RF_phase_error (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 185 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_RF_phase_error");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/SL_dphiRF",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_RL_radial_error (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string dirname = "fig")
Definition at line 210 of file plot_llrf.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_llrf", "plot_RL_radial_error");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     hsize_t dims;
     std::unique_ptr<double> array((double *) read_1D(h5data, "Beam/RL_drho",
                                   "double", &dims));
     auto ph5Data = python::convert_double_array(array.get(), dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, ph5Data,
                                             pOutputFreq, pDirname, NULL);
     return ret != nullptr;
 }
int blond::plot_transmitted_particles (RfParameters * RfP, std::string h5data, int output_freq = 1, std::string style = ".", std::string dirname = "fig")
Definition at line 216 of file plot_beams.cpp.
References blond::python::convert_int(), blond::python::convert_int_array(), blond::python::convert_string(), blond::RfParameters::counter, blond::python::import(), and read_1D().
 {
     python::import();
     auto pFunc = python::import("plot_beams", "plot_transmitted_particles");
     int turn = RfP->counter;
     auto pRfPCounter = python::convert_int(turn);
     auto pOutputFreq = python::convert_int(output_freq);
     auto pDirname = python::convert_string(dirname);
     auto pStyle = python::convert_string(style);
     hsize_t dims;
     std::unique_ptr<int> n_macroparticles_alive((int *) read_1D(h5data,
             "Beam/n_macroparticles_alive",
             "int", &dims));
     auto pPartsAlive = python::convert_int_array(n_macroparticles_alive.get(),
                        dims);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pRfPCounter, pPartsAlive,
                                             pOutputFreq, pStyle, pDirname,
                                             NULL);
     return ret != nullptr;
 }
int blond::plot_voltage_programme (f_vector_t & time, f_vector_t & voltage, int sampling = 1, std::string dirname = "fig", int figno = 0)
Definition at line 7 of file plot_parameters.cpp.
References blond::python::convert_double_array(), blond::python::convert_int(), blond::python::convert_string(), and blond::python::import().
 {
     // python::initialize();
     python::import();
     auto pFunc = python::import("plot_parameters", "plot_voltage_programme");
     auto pTime = python::convert_double_array(time.data(), time.size());
     auto pVoltage = python::convert_double_array(voltage.data(), voltage.size());
     auto pSampling = python::convert_int(sampling);
     auto pDirname = python::convert_string(dirname);
     auto pFigno = python::convert_int(figno);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pTime, pVoltage, pSampling,
                                             pDirname, pFigno, NULL);
     return ret != nullptr;
 }
int blond::plot_xy (f_vector_t xArray, f_vector_t yArray, std::string figureName, std::string dirName, std::string saveFigName, double xMax = 0)
Definition at line 14 of file plot_xy.cpp.
References blond::python::convert_double(), blond::python::convert_double_array(), blond::python::convert_string(), and blond::python::import().
 {
     python::import();
     auto pFunc = python::import("plot_xy", "plot_xy");
     auto py_xArray = python::convert_double_array(xArray.data(), xArray.size());
     auto py_yArray = python::convert_double_array(yArray.data(), yArray.size());
     auto py_figureName = python::convert_string(figureName);
     auto py_dirName = python::convert_string(dirName);
     auto py_saveFigName = python::convert_string(saveFigName);
     auto py_xMax = python::convert_double(xMax);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, py_xArray, py_yArray, py_figureName, py_dirName, py_saveFigName, py_xMax, NULL);
     return ret != nullptr;
 }
void blond::potential_well_cut (const f_vector_t & theta_coord_array, const f_vector_t & potential_array, f_vector_t & theta_coord_sep, f_vector_t & potential_well_sep)
Definition at line 221 of file utilities.cpp.
References ALL, blond::mymath::min(), and minmax_location().
Referenced by matched_from_distribution_density(), and matched_from_line_density().
 {
     theta_coord_sep.clear();
     potential_well_sep.clear();
     f_vector_t min_theta_positions, max_theta_positions;
     f_vector_t min_potential_values, max_potential_values;
     minmax_location(theta_coord_array, potential_array,
                     min_theta_positions, max_theta_positions,
                     min_potential_values, max_potential_values);
     int n_minima = min_theta_positions.size();
     int n_maxima = max_theta_positions.size();
     // cout << "minima: " << n_minima << "\n";
     // cout << "maxima: " << n_maxima << "\n";
     if (n_minima == 0) { // tested
         cerr << "[potential_well_cut] The potential well has no minima...\n";
         exit(-1);
     }
     if (n_minima > n_maxima && n_maxima == 1) {
         cerr << "[potential_well_cut] The potential well has more minima,\n"
              << " and only one maximum\n";
         exit(-1);
     }
     if (n_maxima == 0) {
         cout << "[potential_well_cut] Warning: The maximum of the potential \n"
              << "well could not be found... You may reconsider the options to \n"
              << "calculate the potential well as the main harmonic is probably \n"
              << "not the expected one. You may also increase the percentage of \n"
              << "margin to compute the potential well.\n"
              << "The full potential well will be taken\n";
     } else if (n_maxima == 1) { // tested
         if (min_theta_positions[0] > max_theta_positions[0]) {
             for (uint i = 0; i < potential_array.size(); ++i) {
                 if (potential_array[i] < max_potential_values[0]
                         && theta_coord_array[i] > max_theta_positions[0]) {
                     theta_coord_sep.push_back(theta_coord_array[i]);
                     potential_well_sep.push_back(potential_array[i]);
                 }
             }
             if (potential_array.back() < potential_array[0]) {
                 cerr << "[potential_well_cut] The potential well is not well defined.\n"
                      << "You may reconsider the options to calculate \n"
                      << "the potential well as the main harmonic is \n"
                      << "probably not the expected one.\n";
                 exit(-1);
             }
         } else {
             for (uint i = 0; i < potential_array.size(); ++i) {
                 if (potential_array[i] < max_potential_values[0]
                         && theta_coord_array[i] < max_theta_positions[0]) {
                     theta_coord_sep.push_back(theta_coord_array[i]);
                     potential_well_sep.push_back(potential_array[i]);
                 }
             }
             if (potential_array.back() < potential_array[0]) {
                 cerr << "[potential_well_cut] The potential well is not well defined.\n"
                      << "You may reconsider the options to calculate \n"
                      << "the potential well as the main harmonic is \n"
                      << "probably not the expected one.\n";
                 exit(-1);
             }
         }
     } else if (n_maxima == 2) { // tested
         auto lower_maximum_value = *min_element(ALL(max_potential_values));
         auto higher_maximum_value = *max_element(ALL(max_potential_values));
         f_vector_t lower_maximum_theta, higher_maximum_theta;
         for (uint i = 0; i < max_theta_positions.size(); i++) {
             if (max_potential_values[i] == lower_maximum_value)
                 lower_maximum_theta.push_back(max_theta_positions[i]);
             if (max_potential_values[i] == higher_maximum_value)
                 higher_maximum_theta.push_back(max_theta_positions[i]);
         }
         if (lower_maximum_theta.size() == 2) {
             for (uint i = 0; i < potential_array.size(); ++i) {
                 if (potential_array[i] < lower_maximum_value
                         && theta_coord_array[i] > lower_maximum_theta[0]
                         && theta_coord_array[i] < lower_maximum_theta[1]) {
                     theta_coord_sep.push_back(theta_coord_array[i]);
                     potential_well_sep.push_back(potential_array[i]);
                 }
             }
         } else if (min_theta_positions[0] > lower_maximum_theta[0]) {
             for (uint i = 0; i < potential_array.size(); ++i) {
                 if (potential_array[i] < lower_maximum_value
                         && theta_coord_array[i] > lower_maximum_theta[0]
                         && theta_coord_array[i] < higher_maximum_theta[0]) {
                     theta_coord_sep.push_back(theta_coord_array[i]);
                     potential_well_sep.push_back(potential_array[i]);
                 }
             }
         } else {
             for (uint i = 0; i < potential_array.size(); ++i) {
                 if (potential_array[i] < lower_maximum_value
                         && theta_coord_array[i] < lower_maximum_theta[0]
                         && theta_coord_array[i] > higher_maximum_theta[0]) {
                     theta_coord_sep.push_back(theta_coord_array[i]);
                     potential_well_sep.push_back(potential_array[i]);
                 }
             }
         }
     } else { // tested
         auto left_max_theta = *min_element(max_theta_positions.begin(),
                                            max_theta_positions.end());
         auto right_max_theta = *max_element(max_theta_positions.begin(),
                                             max_theta_positions.end());
         f_vector_t left_max_value, right_max_value;
         for (uint i = 0; i < max_theta_positions.size(); i++) {
             if (max_theta_positions[i] == left_max_theta)
                 left_max_value.push_back(max_potential_values[i]);
             if (max_theta_positions[i] == right_max_theta)
                 right_max_value.push_back(max_potential_values[i]);
         }
         auto separatrix_value = min(
                                     *min_element(left_max_value.begin(), left_max_value.end()),
                                     *min_element(right_max_value.begin(), right_max_value.end()));
         for (uint i = 0; i < theta_coord_array.size(); ++i) {
             if (theta_coord_array[i] > left_max_theta
                     && theta_coord_array[i] < right_max_theta
                     && potential_array[i] < separatrix_value) {
                 theta_coord_sep.push_back(theta_coord_array[i]);
                 potential_well_sep.push_back(potential_array[i]);
             }
         }
     }
 }
void blond::preprocess_ramp (GeneralParameters::particle_t particle_type, double circumference, f_vector_t & time, f_vector_t & data, f_vector_t & time_interp, f_vector_t & momentum_interp, std::string data_type = "momentum", std::string interpolation = "linear", int smoothing = 0, int flat_bottom = 0, int t_start = 0, int t_end = -1, bool plot = false, std::string figdir = "fig", std::string figname = "data", int sampling = 1, double user_mass = 0.)
void blond::preprocess_rf_params (GeneralParameters * GP, f_vector_2d_t & time_arrays, f_vector_2d_t & data_arrays, f_vector_t & data_interp, std::string interpolation = "linear", bool plot = false, std::string figdir = "fig", std::vector< std::string > figname = {"data"}, int sampling = 1)
Definition at line 13 of file preprocess.cpp.
 {}
void * blond::read_1D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
Definition at line 44 of file Monitors.cpp.
Referenced by plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), and plot_transmitted_particles().
 {
     auto file_id = H5Fopen(fname.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
     H5T_class_t class_id;
     size_t type_size;
     H5LTget_dataset_info(file_id, dsname.c_str(),
                          dims, &class_id, &type_size);
     std::transform(type.begin(), type.end(), type.begin(), ::tolower);
     void *res = NULL;
     if (type == "int" && sizeof(int) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_int(file_id, dsname.c_str(), (int *)res);
     } else if (type == "double" && sizeof(double) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_double(file_id, dsname.c_str(), (double *)res);
     } else if (type == "float" && sizeof(float) == type_size) {
         res = malloc(dims[0] * type_size);
         H5LTread_dataset_float(file_id, dsname.c_str(), (float *)res);
     } else {
         std::cerr << "[Monitors] Requested type not supported or not compatible\n"
                   << "with actual data type size\n";
     }
     return res;
 }
void * blond::read_2D (std::string fname, std::string dsname, std::string type, hsize_t dims[])
Definition at line 17 of file Monitors.cpp.
Referenced by plot_LHCNoiseFB_FWHM_bbb().
 {
     auto file_id = H5Fopen(fname.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
     H5T_class_t class_id;
     size_t type_size;
     H5LTget_dataset_info(file_id, dsname.c_str(),
                          dims, &class_id, &type_size);
     std::transform(type.begin(), type.end(), type.begin(), ::tolower);
     void *res = NULL;
     if (type == "int" && sizeof(int) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_int(file_id, dsname.c_str(), (int *)res);
     } else if (type == "double" && sizeof(double) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_double(file_id, dsname.c_str(), (double *)res);
     } else if (type == "float" && sizeof(float) == type_size) {
         res = malloc(dims[0] * dims[1] * type_size);
         H5LTread_dataset_float(file_id, dsname.c_str(), (float *)res);
     } else {
         std::cerr << "[Monitors] Requested type not supported or not compatible\n"
                   << "with actual data type size\n";
     }
     return res;
 }
template<typename T > static std::vector<T> blond::slice (const std::vector< T > & a, const int start = 0, int end = 0, const int step = 1) inline static
Definition at line 261 of file vector_math.h.
     {
         if (end == 0) end = a.size();
         else if (end < 0) end = a.size() + end;
         std::vector<T> result;
         result.reserve((end - start + step - 1) / step);
         for (int i = start; i < end; i += step)
             result.push_back(a[i]);
         return result;
     }
Variable Documentation
const unsigned blond::PRECISION = 8
Definition at line 30 of file configuration.h.
Referenced by blond::util::dump().