Beam Longitudinal Dynamics code (BLonD): blond::vdt Namespace Reference
blond::vdt Namespace Reference
Namespaces
namespace details
Functions
void expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double fast_exp (double initial_x)
Exponential Function double precision.
float fast_expf (float initial_x)
Exponential Function single precision.
void fast_expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void fast_expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double fast_sin (double x)
Double precision sine: just call sincos.
void fast_sincos (const double xx, double &s, double &c)
Double precision sincos.
void fast_sincosf (const float xx, float &s, float &c)
Single precision sincos.
float fast_sinf (float x)
void fast_sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void fast_sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
void sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
Function Documentation
void blond::vdt::expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void blond::vdt::expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double blond::vdt::fast_exp (double initial_x) inline
Exponential Function double precision.
Definition at line 70 of file exp.h.
References blond::vdt::details::EXP_LIMIT, blond::vdt::details::fpfloor(), blond::vdt::details::LOG2E, blond::vdt::details::PX1exp, blond::vdt::details::PX2exp, blond::vdt::details::PX3exp, blond::vdt::details::QX1exp, blond::vdt::details::QX2exp, blond::vdt::details::QX3exp, blond::vdt::details::QX4exp, and blond::vdt::details::uint642dp().
Referenced by blond::mymath::fast_exp().
         {
             double x = initial_x;
             double px = details::fpfloor(details::LOG2E * x + 0.5);
             const int32_t n = int32_t(px);
             x -= px * 6.93145751953125E-1;
             x -= px * 1.42860682030941723212E-6;
             const double xx = x * x;
             // px = x * P(x**2).
             px = details::PX1exp;
             px *= xx;
             px += details::PX2exp;
             px *= xx;
             px += details::PX3exp;
             px *= x;
             // Evaluate Q(x**2).
             double qx = details::QX1exp;
             qx *= xx;
             qx += details::QX2exp;
             qx *= xx;
             qx += details::QX3exp;
             qx *= xx;
             qx += details::QX4exp;
             // e**x = 1 + 2x P(x**2)/( Q(x**2) - P(x**2) )
             x = px / (qx - px);
             x = 1.0 + 2.0 * x;
             // Build 2^n in double.
             x *= details::uint642dp((((uint64_t)n) + 1023) << 52);
             if (initial_x > details::EXP_LIMIT)
                 x = std::numeric_limits<double>::infinity();
             if (initial_x < -details::EXP_LIMIT)
                 x = 0.;
             return x;
         }
float blond::vdt::fast_expf (float initial_x) inline
Exponential Function single precision.
Definition at line 119 of file exp.h.
References blond::vdt::details::C1F, blond::vdt::details::C2F, blond::vdt::details::fpfloor(), blond::vdt::details::LOG2EF, blond::vdt::details::MAXLOGF, blond::vdt::details::MINLOGF, blond::vdt::details::PX1expf, blond::vdt::details::PX2expf, blond::vdt::details::PX3expf, blond::vdt::details::PX4expf, blond::vdt::details::PX5expf, blond::vdt::details::PX6expf, and blond::vdt::details::uint322sp().
         {
             float x = initial_x;
             float z =
                 details::fpfloor(details::LOG2EF * x +
                                  0.5f); /* floor() truncates toward -infinity. */
             x -= z * details::C1F;
             x -= z * details::C2F;
             const int32_t n = int32_t(z);
             const float x2 = x * x;
             z = x * details::PX1expf;
             z += details::PX2expf;
             z *= x;
             z += details::PX3expf;
             z *= x;
             z += details::PX4expf;
             z *= x;
             z += details::PX5expf;
             z *= x;
             z += details::PX6expf;
             z *= x2;
             z += x + 1.0f;
             /* multiply by power of 2 */
             z *= details::uint322sp((n + 0x7f) << 23);
             if (initial_x > details::MAXLOGF)
                 z = std::numeric_limits<float>::infinity();
             if (initial_x < details::MINLOGF)
                 z = 0.f;
             return z;
         }
void blond::vdt::fast_expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void blond::vdt::fast_expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double blond::vdt::fast_sin (double x) inline
Double precision sine: just call sincos.
Definition at line 39 of file sin.h.
References blond::constant::c, and fast_sincos().
Referenced by blond::mymath::fast_cos(), and blond::mymath::fast_sin().
         {
             double s, c;
             fast_sincos(x, s, c);
             return s;
         }
void blond::vdt::fast_sincos (const double xx, double & s, double & c) inline
Double precision sincos.
Definition at line 115 of file sincos.h.
References blond::constant::c, blond::vdt::details::fast_sincos_m45_45(), and blond::vdt::details::reduce2quadrant().
Referenced by fast_sin().
         {
             // I have to use doubles to make it vectorise...
             int j;
             double x = details::reduce2quadrant(xx, j);
             const double signS = (j & 4);
             j -= 2;
             const double signC = (j & 4);
             const double poly = j & 2;
             details::fast_sincos_m45_45(x, s, c);
             // swap
             if (poly == 0) {
                 const double tmp = c;
                 c = s;
                 s = tmp;
             }
             if (signC == 0.)
                 c = -c;
             if (signS != 0.)
                 s = -s;
             if (xx < 0.)
                 s = -s;
         }
void blond::vdt::fast_sincosf (const float xx, float & s, float & c) inline
Single precision sincos.
Definition at line 188 of file sincos.h.
References blond::vdt::details::fast_sincosf_m45_45(), and blond::vdt::details::reduce2quadrant().
Referenced by fast_sinf().
         {
             int j;
             const float x = details::reduce2quadrant(xx, j);
             int signS = (j & 4);
             j -= 2;
             const int signC = (j & 4);
             const int poly = j & 2;
             float ls, lc;
             details::fast_sincosf_m45_45(x, ls, lc);
             // swap
             if (poly == 0) {
                 const float tmp = lc;
                 lc = ls;
                 ls = tmp;
             }
             if (signC == 0)
                 lc = -lc;
             if (signS != 0)
                 ls = -ls;
             if (xx < 0)
                 ls = -ls;
             c = lc;
             s = ls;
         }
float blond::vdt::fast_sinf (float x) inline
Definition at line 48 of file sin.h.
References blond::constant::c, and fast_sincosf().
         {
             float s, c;
             fast_sincosf(x, s, c);
             return s;
         }
void blond::vdt::fast_sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void blond::vdt::fast_sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
void blond::vdt::sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void blond::vdt::sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)