Beam Longitudinal Dynamics code (BLonD): option::PrintUsageImplementation Struct Reference
option::PrintUsageImplementation Struct Reference
#include <optionparser.h>
Classes
struct FunctionWriter
struct IStringWriter
class LinePartIterator
class LineWrapper
struct OStreamWriter
struct StreamWriter
struct SyscallWriter
struct TemporaryWriter
Static Public Member Functions
static void indent (IStringWriter &write, int &x, int want_x)
static bool isWideChar (unsigned ch)
Returns true if ch is the unicode code point of a wide character.
static void printUsage (IStringWriter &write, const Descriptor usage[], int width=80, int last_column_min_percent=50, int last_column_own_line_max_percent=75)
static void upmax (int &i1, int i2)
Detailed Description
Definition at line 1908 of file optionparser.h.
Member Function Documentation
static void option::PrintUsageImplementation::indent (IStringWriter & write, int & x, int want_x) inline static
Definition at line 2031 of file optionparser.h.
{
             int indent = want_x - x;
             if (indent < 0) {
                 write("\n", 1);
                 indent = want_x;
             }
             if (indent > 0) {
                 char space = ' ';
                 for (int i = 0; i < indent; ++i)
                     write(&space, 1);
                 x = want_x;
             }
         }
static bool option::PrintUsageImplementation::isWideChar (unsigned ch) inline static
Returns true if ch is the unicode code point of a wide character.
Note
The following character ranges are treated as wide
1100..115F
2329..232A  (just 2 characters!)
2E80..A4C6  except for 303F
A960..A97C
AC00..D7FB
F900..FAFF
FE10..FE6B
FF01..FF60
FFE0..FFE6
1B000......
Definition at line 2065 of file optionparser.h.
{
             if (ch == 0x303F)
                 return false;
             return ((0x1100 <= ch && ch <= 0x115F) ||
                     (0x2329 <= ch && ch <= 0x232A) ||
                     (0x2E80 <= ch && ch <= 0xA4C6) ||
                     (0xA960 <= ch && ch <= 0xA97C) ||
                     (0xAC00 <= ch && ch <= 0xD7FB) ||
                     (0xF900 <= ch && ch <= 0xFAFF) ||
                     (0xFE10 <= ch && ch <= 0xFE6B) ||
                     (0xFF01 <= ch && ch <= 0xFF60) ||
                     (0xFFE0 <= ch && ch <= 0xFFE6) || (0x1B000 <= ch));
         }
static void option::PrintUsageImplementation::printUsage (IStringWriter & write, const Descriptor usage[], int width = 80, int last_column_min_percent = 50, int last_column_own_line_max_percent = 75) inline static
Definition at line 2657 of file optionparser.h.
References option::PrintUsageImplementation::LinePartIterator::column(), option::PrintUsageImplementation::LinePartIterator::data(), option::PrintUsageImplementation::LineWrapper::flush(), option::PrintUsageImplementation::LinePartIterator::length(), option::PrintUsageImplementation::LinePartIterator::line(), option::PrintUsageImplementation::LinePartIterator::next(), option::PrintUsageImplementation::LinePartIterator::nextRow(), option::PrintUsageImplementation::LinePartIterator::nextTable(), option::PrintUsageImplementation::LineWrapper::process(), option::PrintUsageImplementation::LinePartIterator::restartRow(), option::PrintUsageImplementation::LinePartIterator::restartTable(), and option::PrintUsageImplementation::LinePartIterator::screenLength().
Referenced by option::printUsage().
{
             if (width < 1) // protect against nonsense values
                 width = 80;
             if (width >
                 10000) // protect against overflow in the following computation
                 width = 10000;
             int last_column_min_width =
                 ((width * last_column_min_percent) + 50) / 100;
             int last_column_own_line_max_width =
                 ((width * last_column_own_line_max_percent) + 50) / 100;
             if (last_column_own_line_max_width == 0)
                 last_column_own_line_max_width = 1;
             LinePartIterator part(usage);
             while (part.nextTable()) {
                 /***************** Determine column widths
                 * *******************************/
                 const int maxcolumns = 8; // 8 columns are enough for everyone
                 int col_width[maxcolumns];
                 int lastcolumn;
                 int leftwidth;
                 int overlong_column_threshold = 10000;
                 do {
                     lastcolumn = 0;
                     for (int i = 0; i < maxcolumns; ++i)
                         col_width[i] = 0;
                     part.restartTable();
                     while (part.nextRow()) {
                         while (part.next()) {
                             if (part.column() < maxcolumns) {
                                 upmax(lastcolumn, part.column());
                                 if (part.screenLength() <
                                     overlong_column_threshold)
                                     // We don't let rows that don't use table
                                     // separators (\t or \v) influence
                                     // the width of column 0. This allows the
                                     // user to interject section headers
                                     // or explanatory paragraphs that do not
                                     // participate in the table layout.
                                     if (part.column() > 0 || part.line() > 0 ||
                                         part.data()[part.length()] == '\t' ||
                                         part.data()[part.length()] == '\v')
                                         upmax(col_width[part.column()],
                                               part.screenLength());
                             }
                         }
                     }
                     /*
                     * If the last column doesn't fit on the same
                     * line as the other columns, we can fix that by starting it
                     * on its own line.
                     * However we can't do this for any of the columns
                     * 0..lastcolumn-1.
                     * If their sum exceeds the maximum width we try to fix this
                     * by iteratively
                     * ignoring the widest line parts in the width determination
                     * until
                     * we arrive at a series of column widths that fit into one
                     * line.
                     * The result is a layout where everything is nicely
                     * formatted
                     * except for a few overlong fragments.
                     * */
                     leftwidth = 0;
                     overlong_column_threshold = 0;
                     for (int i = 0; i < lastcolumn; ++i) {
                         leftwidth += col_width[i];
                         upmax(overlong_column_threshold, col_width[i]);
                     }
                 } while (leftwidth > width);
                 /**************** Determine tab stops and last column handling
                 * **********************/
                 int tabstop[maxcolumns];
                 tabstop[0] = 0;
                 for (int i = 1; i < maxcolumns; ++i)
                     tabstop[i] = tabstop[i - 1] + col_width[i - 1];
                 int rightwidth = width - tabstop[lastcolumn];
                 bool print_last_column_on_own_line = false;
                 if (rightwidth < last_column_min_width &&
                     // if we don't have the minimum requested width for the last
                     // column
                     (col_width[lastcolumn] == 0 || // and all last columns are >
                                                    // overlong_column_threshold
                      rightwidth < col_width[lastcolumn] // or there is at least
                                                         // one last column that
                                                         // requires more than
                                                         // the space available
                      )) {
                     print_last_column_on_own_line = true;
                     rightwidth = last_column_own_line_max_width;
                 }
                 // If lastcolumn == 0 we must disable
                 // print_last_column_on_own_line because
                 // otherwise 2 copies of the last (and only) column would be
                 // output.
                 // Actually this is just defensive programming. It is currently
                 // not
                 // possible that lastcolumn==0 and
                 // print_last_column_on_own_line==true
                 // at the same time, because lastcolumn==0 =>
                 // tabstop[lastcolumn] == 0 =>
                 // rightwidth==width => rightwidth>=last_column_min_width
                 // (unless someone passes
                 // a bullshit value >100 for last_column_min_percent) => the
                 // above if condition
                 // is false => print_last_column_on_own_line==false
                 if (lastcolumn == 0)
                     print_last_column_on_own_line = false;
                 LineWrapper lastColumnLineWrapper(width - rightwidth, width);
                 LineWrapper interjectionLineWrapper(0, width);
                 part.restartTable();
                 /***************** Print out all rows of the table
                 * *************************************/
                 while (part.nextRow()) {
                     int x = -1;
                     while (part.next()) {
                         if (part.column() > lastcolumn)
                             continue; // drop excess columns (can happen if
                                       // lastcolumn == maxcolumns-1)
                         if (part.column() == 0) {
                             if (x >= 0)
                                 write("\n", 1);
                             x = 0;
                         }
                         indent(write, x, tabstop[part.column()]);
                         if ((part.column() < lastcolumn) &&
                             (part.column() > 0 || part.line() > 0 ||
                              part.data()[part.length()] == '\t' ||
                              part.data()[part.length()] == '\v')) {
                             write(part.data(), part.length());
                             x += part.screenLength();
                         } else // either part.column() == lastcolumn or we are
                                // in the special case of
                                // an interjection that doesn't contain \v or \t
{
                             // NOTE: This code block is not necessarily executed
                             // for
                             // each line, because some rows may have fewer
                             // columns.
                             LineWrapper& lineWrapper =
                                 (part.column() == 0) ? interjectionLineWrapper
                                                      : lastColumnLineWrapper;
                             if (!print_last_column_on_own_line ||
                                 part.column() != lastcolumn)
                                 lineWrapper.process(write, part.data(),
                                                     part.length());
                         }
                     } // while
                     if (print_last_column_on_own_line) {
                         part.restartRow();
                         while (part.next()) {
                             if (part.column() == lastcolumn) {
                                 write("\n", 1);
                                 int _ = 0;
                                 indent(write, _, width - rightwidth);
                                 lastColumnLineWrapper.process(
                                     write, part.data(), part.length());
                             }
                         }
                     }
                     write("\n", 1);
                     lastColumnLineWrapper.flush(write);
                     interjectionLineWrapper.flush(write);
                 }
             }
         }
static void option::PrintUsageImplementation::upmax (int & i1, int i2) inline static
Definition at line 2014 of file optionparser.h.
 { i1 = (i1 >= i2 ? i1 : i2); }