Beam Longitudinal Dynamics code (BLonD): blond::PSBPhaseNoiseInjection Class Reference
blond::PSBPhaseNoiseInjection Class Reference
#include <PhaseNoise.h>
Public Types
enum rescale_ampl_t { with_sync_freq, no_scaling }
Public Types inherited from blond::PhaseNoise
enum predistortion_t {
exponential, linear, hyperbolic, weightfunction,
predistortion_none
}
enum transform_t { r, c, transform_none }
Public Member Functions
PSBPhaseNoiseInjection (double delta_f=1.0, uint corr_time=10000, double fmin=0.8571, double fmax=1.1, double initial_amplitude=1e-6, int seed1=1234, int seed2=7564, predistortion_t predistortion=predistortion_t::predistortion_none, rescale_ampl_t rescale_ampl=rescale_ampl_t::with_sync_freq)
~PSBPhaseNoiseInjection ()
void generate ()
Public Member Functions inherited from blond::PhaseNoise
PhaseNoise ()
virtual ~PhaseNoise ()
f_vector_t spectrum_generation (int k, int nt, double df, double ampl, f_vector_t freq, predistortion_t predistortion)
void spectrum_to_phase_noise (f_vector_t &t, f_vector_t &dphi, const f_vector_t &freq_array, const f_vector_t &ReS, transform_t transform=transform_t::transform_none)
Public Attributes
double fDeltaF
rescale_ampl_t fRescaleAmpl
Public Attributes inherited from blond::PhaseNoise
double fAi
uint fCorr
f_vector_t fDphi
double fFMax
double fFMin
f_vector_t fFs
uint fNTurns
predistortion_t fPredistortion
int fSeed1
int fSeed2
Detailed Description
Definition at line 67 of file PhaseNoise.h.
Member Enumeration Documentation
enum blond::PSBPhaseNoiseInjection::rescale_ampl_t
Enumerator
with_sync_freq
no_scaling
Definition at line 70 of file PhaseNoise.h.
 { with_sync_freq, no_scaling };
Constructor & Destructor Documentation
PSBPhaseNoiseInjection::PSBPhaseNoiseInjection (double delta_f = 1.0, uint corr_time = 10000, double fmin = 0.8571, double fmax = 1.1, double initial_amplitude = 1e-6, int seed1 = 1234, int seed2 = 7564, predistortion_t predistortion = predistortion_t::predistortion_none, rescale_ampl_t rescale_ampl = rescale_ampl_t::with_sync_freq)
Definition at line 249 of file PhaseNoise.cpp.
References blond::PhaseNoise::fAi, blond::PhaseNoise::fCorr, fDeltaF, blond::PhaseNoise::fDphi, blond::PhaseNoise::fFMax, blond::PhaseNoise::fFMin, blond::PhaseNoise::fFs, blond::PhaseNoise::fNTurns, blond::PhaseNoise::fPredistortion, fRescaleAmpl, blond::PhaseNoise::fSeed1, blond::PhaseNoise::fSeed2, blond::Context::GP, blond::constant::pi, and blond::Context::RfP.
 {
     auto RfP = Context::RfP;
     auto GP = Context::GP;
     fDeltaF = delta_f;
     fCorr = corr_time;
     fFMin = fmin;
     fFMax = fmax;
     fAi = initial_amplitude;
     fPredistortion = predistortion;
     fSeed1 = seed1;
     fSeed2 = seed2;
     fNTurns = GP->n_turns;
     fDphi.resize(fNTurns + 1, 0);
     fRescaleAmpl = rescale_amplitude;
     fFs.resize(RfP->omega_s0.size());
     std::transform(RfP->omega_s0.begin(), RfP->omega_s0.end(), fFs.begin(),
                    std::bind2nd(std::divides<double>(), 2 * constant::pi));
 }
PSBPhaseNoiseInjection::~PSBPhaseNoiseInjection ()
Definition at line 274 of file PhaseNoise.cpp.
References blond::fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
void PSBPhaseNoiseInjection::generate () virtual
Reimplemented from blond::PhaseNoise.
Definition at line 276 of file PhaseNoise.cpp.
References blond::PhaseNoise::fAi, blond::PhaseNoise::fCorr, fDeltaF, blond::PhaseNoise::fDphi, blond::PhaseNoise::fFs, blond::PhaseNoise::fNTurns, blond::PhaseNoise::fPredistortion, fRescaleAmpl, blond::PhaseNoise::fSeed1, blond::PhaseNoise::fSeed2, blond::Context::GP, blond::mymath::linspace(), blond::mymath::next_regular(), blond::PhaseNoise::spectrum_generation(), blond::PhaseNoise::spectrum_to_phase_noise(), and blond::mymath::standard_deviation().
 {
     auto GP = Context::GP;
     for (uint i = 0; i < fNTurns / fCorr; ++i) {
         // Scale amplitude to keep area (phase noise amplitude) constant
         uint k = i * fCorr; // Current time step
         double f_max = GP->f_rev[k] / 2;
         double f_s0 = fFs[k];
         int n_points_pos_f_incl_zero = (int)(f_max / fDeltaF) + 2;
         int nt = 2 * (n_points_pos_f_incl_zero - 1);
         nt = mymath::next_regular(nt);
         n_points_pos_f_incl_zero = nt / 2 + 1;
         double df = f_max / (n_points_pos_f_incl_zero - 1);
         double ampl = 0.0;
         if (fRescaleAmpl == rescale_ampl_t::with_sync_freq)
             ampl = fAi * fFs[0] / f_s0;
         else if (fRescaleAmpl == rescale_ampl_t::no_scaling)
             ampl = fAi;
         else {
             std::cerr << "ERROR: Illegal Value\n"
                       << "fRescaleAmpl should be one of "
                       << "with_sync_freq or no_scaling\n";
         }
         f_vector_t freq(n_points_pos_f_incl_zero);
         mymath::linspace(freq.data(), 0, f_max, n_points_pos_f_incl_zero);
         auto spectrum =
             spectrum_generation(k, nt, df, ampl, freq, fPredistortion);
         f_vector_t noise_t, noise_dphi;
         spectrum_to_phase_noise(noise_t, noise_dphi, freq, spectrum);
         fSeed1 += 239;
         fSeed2 += 158;
         // Fill phase noise array
         const uint kmax =
             i < fNTurns / fCorr - 1 ? (i + 1) * fCorr : fNTurns + 1;
         std::copy(noise_dphi.begin(), noise_dphi.begin() + kmax - k,
                   fDphi.begin() + k);
         auto rms_noise =
             mymath::standard_deviation(noise_dphi.data(), noise_dphi.size());
         // std::cout << "RF noise for time step " << noise_t[1]
         //           << " s (iter " << i << ") has r.m.s phase "
         //           << rms_noise << " rad (" << rms_noise * 180 / constant::pi
         //           << " deg)\n";
     }
 }
Member Data Documentation
double blond::PSBPhaseNoiseInjection::fDeltaF
Definition at line 72 of file PhaseNoise.h.
Referenced by generate(), and PSBPhaseNoiseInjection().
rescale_ampl_t blond::PSBPhaseNoiseInjection::fRescaleAmpl
Definition at line 73 of file PhaseNoise.h.
Referenced by generate(), and PSBPhaseNoiseInjection().