Beam Longitudinal Dynamics code (BLonD): blond::mymath Namespace Reference
blond::mymath Namespace Reference
Classes
class Ham
Functions
template<typename T >
static std::vector< T > arange (T start, T stop, T step=1)
static void convolution (const double *__restrict signal, const int SignalLen, const double *__restrict kernel, const int KernelLen, double *__restrict res)
template<typename T >
static f_vector_t cum_trapezoid (const T *f, const T deltaX, const int nsub)
template<typename T >
static f_vector_t cum_trapezoid (const T *f, const T deltaX, const T initial, const int nsub)
template<typename T >
static f_vector_t cum_trapezoid (const std::vector< T > &f, const T deltaX)
template<typename T >
static f_vector_t cum_trapezoid (const std::vector< T > &f, const T deltaX, const T initial)
static double fast_cos (double x)
static double fast_exp (double x)
static double fast_sin (double x)
template<typename T >
static std::vector< T > flatten (const std::vector< std::vector< T > > &a)
static f_vector_t imag_part (const std::vector< complex_t > &in)
static void interp (const std::vector< double > &x, const std::vector< double > &xp, const std::vector< double > &yp, std::vector< double > &y, const double left, const double right)
static void interp (const std::vector< double > &x, const std::vector< double > &xp, const std::vector< double > &yp, std::vector< double > &y)
static f_vector_t interp (const f_vector_t &x, const f_vector_t &xp, const f_vector_t &yp)
static f_vector_t interp (const f_vector_t &x, const f_vector_t &xp, const f_vector_t &yp, const double left, const double right)
static void linspace (double *a, const double start, const double end, const int n, const int keep_from=0)
static f_vector_t linspace (const double start, const double end, const int n)
template<typename T >
static uint max (T *a, uint size, uint step=1)
template<typename T >
static double mean (const T data[], const int n)
template<typename T >
static double mean (const std::vector< T > data)
template<typename T >
static void meshgrid (const std::vector< T > &in1, const std::vector< T > &in2, std::vector< std::vector< T > > &out1, std::vector< std::vector< T > > &out2)
template<typename T >
static uint min (T *a, uint size, uint step=1)
static uint next_regular (uint target)
template<typename T >
static std::vector< T > random_choice (const std::vector< T > &elems, const int size, std::vector< double > weights=std::vector< double >())
static f_vector_t real_part (const std::vector< complex_t > &in)
template<typename T >
int sign (const T val)
template<typename T >
static double standard_deviation (const T data[], const int n, const double mean)
template<typename T >
static double standard_deviation (const std::vector< T > data, const double mean)
template<typename T >
static double standard_deviation (const T data[], const int n)
template<typename T >
static double standard_deviation (const std::vector< T > data)
template<typename T >
static double sum (const T data[], const int n)
template<typename T >
static double sum (const std::vector< T > &data)
template<typename T >
static double trapezoid (const T *f, const double *deltaX, const int nsub)
template<typename T >
static double trapezoid (const std::vector< T > &f, const std::vector< double > &deltaX)
template<typename T >
static double trapezoid (const T *f, const double deltaX, const int nsub)
template<typename T >
static double trapezoid (const std::vector< T > &f, const double deltaX)
Function Documentation
template<typename T > static std::vector<T> blond::mymath::arange (T start, T stop, T step = 1) inline static
Definition at line 328 of file math_functions.h.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
         {
             std::vector<T> values;
             for (T value = start; value < stop; value += step)
                 values.push_back(value);
             return values;
         }
static void blond::mymath::convolution (const double *__restrict signal, const int SignalLen, const double *__restrict kernel, const int KernelLen, double *__restrict res) inline static
Definition at line 72 of file math_functions.h.
Referenced by blond::InducedVoltageTime::induced_voltage_generation().
         {
             const int size = KernelLen + SignalLen - 1;
             #pragma omp parallel for
             for (auto n = 0; n < size; ++n) {
                 res[n] = 0;
                 const int kmin = (n >= KernelLen - 1) ? n - (KernelLen - 1) : 0;
                 const int kmax = (n < SignalLen - 1) ? n : SignalLen - 1;
                 for (int k = kmin; k <= kmax; k++) {
                     res[n] += signal[k] * kernel[n - k];
                     //--j;
                 }
             }
         }
template<typename T > static f_vector_t blond::mymath::cum_trapezoid (const T * f, const T deltaX, const int nsub) inline static
Definition at line 167 of file math_functions.h.
Referenced by blond::RfParameters::calc_phi_s(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), and blond::FullRingAndRf::potential_well_generation().
         {
             // initialize the partial sum to be f(a)+f(b) and
             // deltaX to be the step size using nsub subdivisions
             // double *psum = new double[nsub];
             f_vector_t psum(nsub - 1);
             // psum[0] = 0;
             const auto half_dx = deltaX / 2.0;
             psum[0] = (f[1] + f[0]) * half_dx;
             // increment the partial sum
             // #pragma omp parallel for
             for (int i = 1; i < nsub - 1; ++i)
                 psum[i] = psum[i - 1] + (f[i + 1] + f[i]) * half_dx;
             return psum;
         }
template<typename T > static f_vector_t blond::mymath::cum_trapezoid (const T * f, const T deltaX, const T initial, const int nsub) inline static
Definition at line 189 of file math_functions.h.
         {
             // initialize the partial sum to be f(a)+f(b) and
             // deltaX to be the step size using nsub subdivisions
             // double *psum = new double[nsub];
             f_vector_t psum(nsub);
             const auto half_dx = deltaX / 2.0;
             psum[0] = initial;
             psum[1] = (f[1] + f[0]) * half_dx;
             // increment the partial sum
             for (int i = 2; i < nsub; ++i)
                 psum[i] = psum[i - 1] + (f[i] + f[i - 1]) * half_dx;
             return psum;
         }
template<typename T > static f_vector_t blond::mymath::cum_trapezoid (const std::vector< T > & f, const T deltaX) inline static
Definition at line 210 of file math_functions.h.
         {
             return cum_trapezoid<T>(f.data(), deltaX, f.size());
         }
template<typename T > static f_vector_t blond::mymath::cum_trapezoid (const std::vector< T > & f, const T deltaX, const T initial) inline static
Definition at line 217 of file math_functions.h.
         {
             return cum_trapezoid<T>(f.data(), deltaX, initial, f.size());
         }
static double blond::mymath::fast_cos (double x) inline static
Definition at line 67 of file math_functions.h.
References blond::vdt::fast_sin().
Referenced by blond::hamiltonian(), and blond::Music::track().
 { return vdt::fast_sin(x + M_PI_2); }
static double blond::mymath::fast_exp (double x) inline static
Definition at line 69 of file math_functions.h.
References blond::vdt::fast_exp().
Referenced by blond::Music::track().
 { return vdt::fast_exp(x); }
static double blond::mymath::fast_sin (double x) inline static
Definition at line 65 of file math_functions.h.
References blond::vdt::fast_sin().
Referenced by blond::hamiltonian(), blond::RingAndRfSection::kick(), blond::FullRingAndRf::potential_well_generation(), and blond::Music::track().
 { return vdt::fast_sin(x); }
template<typename T > static std::vector<T> blond::mymath::flatten (const std::vector< std::vector< T > > & a) inline static
Definition at line 422 of file math_functions.h.
References FOR.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
         {
             std::vector<T> result;
             FOR(a, row) {
                 result.insert(result.end(), (*row).begin(), (*row).end());
             }
             return result;
         }
static f_vector_t blond::mymath::imag_part (const std::vector< complex_t > & in) inline static
Definition at line 460 of file math_functions.h.
         {
             f_vector_t res; res.reserve(in.size());
             for (const auto &z : in) res.push_back(z.imag());
             return res;
         }
static void blond::mymath::interp (const std::vector< double > & x, const std::vector< double > & xp, const std::vector< double > & yp, std::vector< double > & y, const double left, const double right) inline static
Definition at line 99 of file math_functions.h.
Referenced by blond::Slices::beam_profile_derivative(), blond::InputTable::imped_calc(), interp(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), blond::minmax_location(), and blond::InputTable::wake_calc().
         {
             assert(xp.size() == yp.size());
             assert(std::is_sorted(xp.begin(), xp.end()));
             y.resize(x.size());
             const int M = xp.size();
             const int N = x.size();
             if (N == 0) return;
             // const auto max = xp.back();
             // const auto min = xp.front();
             // #pragma omp parallel for
             for (int i = 0; i < N; ++i) {
                 int pos = std::lower_bound(xp.begin(), xp.end(), x[i]) - xp.begin();
                 if (pos == M)
                     y[i] = right;
                 else if (xp[pos] == x[i])
                     y[i] = yp[pos];
                 else if (pos == 0)
                     y[i] = left;
                 else {
                     y[i] = yp[pos - 1] +
                            (yp[pos] - yp[pos - 1]) * (x[i] - xp[pos - 1]) /
                            (xp[pos] - xp[pos - 1]);
                 }
             }
         }
static void blond::mymath::interp (const std::vector< double > & x, const std::vector< double > & xp, const std::vector< double > & yp, std::vector< double > & y) inline static
Definition at line 134 of file math_functions.h.
References interp().
         {
             auto left = yp.front();
             auto right = yp.back();
             interp(x, xp, yp, y, left, right);
         }
static f_vector_t blond::mymath::interp (const f_vector_t & x, const f_vector_t & xp, const f_vector_t & yp) inline static
Definition at line 144 of file math_functions.h.
References interp().
         {
             f_vector_t res;
             interp(x, xp, yp, res);
             return res;
         }
static f_vector_t blond::mymath::interp (const f_vector_t & x, const f_vector_t & xp, const f_vector_t & yp, const double left, const double right) inline static
Definition at line 153 of file math_functions.h.
References interp().
         {
             f_vector_t res;
             interp(x, xp, yp, res, left, right);
             return res;
         }
static void blond::mymath::linspace (double * a, const double start, const double end, const int n, const int keep_from = 0) inline static
Definition at line 306 of file math_functions.h.
Referenced by blond::RfParameters::calc_phi_s(), blond::LHCFlatSpectrum::generate(), blond::PSBPhaseNoiseInjection::generate(), linspace(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), blond::FullRingAndRf::potential_well_generation(), blond::Slices::set_cuts(), blond::PhaseNoise::spectrum_generation(), and blond::PhaseNoise::spectrum_to_phase_noise().
         {
             const double step = (end - start) / (n - 1);
             // double value = start;
             //#pragma omp parallel for
             for (int i = 0; i < n; ++i) {
                 if (i >= keep_from)
                     a[i - keep_from] = start + i * step;
                 // value += step;
             }
         }
static f_vector_t blond::mymath::linspace (const double start, const double end, const int n) inline static
Definition at line 319 of file math_functions.h.
References linspace().
         {
             f_vector_t res(n);
             linspace(res.data(), start, end, n);
             return res;
         }
template<typename T > static uint blond::mymath::max (T * a, uint size, uint step = 1) inline static
Definition at line 292 of file math_functions.h.
Referenced by blond::Slices::fwhm(), blond::LHCNoiseFB::fwhm_single_bunch(), blond::Slices::gaussian_fit(), blond::matched_from_line_density(), and blond::LHCNoiseFB::track().
         {
             uint p = 0;
             T max = a[0];
             //#pragma omp parallel for shared(p) reduction(max : max)
             for (uint i = 1; i < size; i += step) {
                 if (a[i] > max) {
                     max = a[i];
                     p = i;
                 }
             }
             return p;
         }
template<typename T > static double blond::mymath::mean (const T data[], const int n) inline static
Definition at line 354 of file math_functions.h.
References sum().
Referenced by blond::LHCNoiseFB::fwhm_multi_bunch(), blond::Slices::gaussian_fit(), mean(), blond::Slices::set_cuts(), and standard_deviation().
         {
             return sum(data, n) / n;
         }
template<typename T > static double blond::mymath::mean (const std::vector< T > data) inline static
Definition at line 360 of file math_functions.h.
References mean().
         {
             return mean(data.data(), data.size());
         }
template<typename T > static void blond::mymath::meshgrid (const std::vector< T > & in1, const std::vector< T > & in2, std::vector< std::vector< T > > & out1, std::vector< std::vector< T > > & out2) inline static
Definition at line 407 of file math_functions.h.
References blond::constant::e, and FOR.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
         {
             out1.clear();
             out1.resize(in2.size(), in1);
             out2.clear();
             const int cols = in1.size();
             FOR(in2, e) out2.push_back(std::vector<T>(cols, *e));
         }
template<typename T > static uint blond::mymath::min (T * a, uint size, uint step = 1) inline static
Definition at line 277 of file math_functions.h.
Referenced by blond::RfParameters::calc_phi_s(), blond::potential_well_cut(), and blond::LHCNoiseFB::track().
         {
             uint p = 0;
             T min = a[0];
             //#pragma omp parallel for  shared(p) reduction(min : min)
             for (uint i = 1; i < size; i += step) {
                 if (a[i] < min) {
                     min = a[i];
                     p = i;
                 }
             }
             return p;
         }
static uint blond::mymath::next_regular (uint target) inline static
Definition at line 54 of file math_functions.h.
Referenced by blond::PSBPhaseNoiseInjection::generate(), blond::InducedVoltageFreq::InducedVoltageFreq(), blond::InducedVoltageTime::InducedVoltageTime(), blond::InducedVoltageTime::reprocess(), and blond::InducedVoltageFreq::reprocess().
         {
             for (auto i : Ham({2, 3, 5})) {
                 if (i > target)
                     return i;
             }
             return 0;
         }
template<typename T > static std::vector<T> blond::mymath::random_choice (const std::vector< T > & elems, const int size, std::vector< double > weights = std::vector<double>()) inline static
Definition at line 432 of file math_functions.h.
References ALL.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
         {
             if (weights.empty()) weights.resize(elems.size(), 1);
             assert(weights.size() == elems.size());
             // calculate cumulative sum
             for (uint i = 1; i < weights.size(); i++) {
                 weights[i] += weights[i - 1];
             }
             std::default_random_engine gen(0);
             std::uniform_real_distribution<double> d(0.0, weights.back());
             std::vector<T> result(size);
             for (int i = 0; i < size; i++) {
                 auto w = d(gen);
                 auto it = std::lower_bound(ALL(weights), w);
                 result[i] = elems[it - weights.begin()];
             }
             return result;
         }
static f_vector_t blond::mymath::real_part (const std::vector< complex_t > & in) inline static
Definition at line 453 of file math_functions.h.
         {
             f_vector_t res; res.reserve(in.size());
             for (const auto &z : in) res.push_back(z.real());
             return res;
         }
template<typename T > int blond::mymath::sign (const T val)
Definition at line 400 of file math_functions.h.
Referenced by blond::fft::init_fft(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), blond::FullRingAndRf::potential_well_generation(), blond::RfParameters::RfParameters(), blond::Resonators::wake_calc(), and blond::TravelingWaveCavity::wake_calc().
         {
             return (T(0) < val) - (val < T(0));
         }
template<typename T > static double blond::mymath::standard_deviation (const T data[], const int n, const double mean) inline static
Definition at line 366 of file math_functions.h.
References mean().
Referenced by blond::Slices::gaussian_fit(), blond::LHCFlatSpectrum::generate(), blond::PSBPhaseNoiseInjection::generate(), blond::Slices::set_cuts(), and standard_deviation().
         {
             double sum_deviation = 0.0;
             #pragma omp parallel for reduction(+ : sum_deviation)
             for (int i = 0; i < n; ++i)
                 sum_deviation += (data[i] - mean) * (data[i] - mean);
             return std::sqrt(sum_deviation / n);
         }
template<typename T > static double blond::mymath::standard_deviation (const std::vector< T > data, const double mean) inline static
Definition at line 377 of file math_functions.h.
References mean(), and standard_deviation().
         {
             return standard_deviation(data.data(), data.size(), mean);
         }
template<typename T > static double blond::mymath::standard_deviation (const T data[], const int n) inline static
Definition at line 384 of file math_functions.h.
References mean().
         {
             const double mean = mymath::mean(data, n);
             double sum_deviation = 0.0;
             #pragma omp parallel for reduction(+ : sum_deviation)
             for (int i = 0; i < n; ++i)
                 sum_deviation += (data[i] - mean) * (data[i] - mean);
             return std::sqrt(sum_deviation / n);
         }
template<typename T > static double blond::mymath::standard_deviation (const std::vector< T > data) inline static
Definition at line 395 of file math_functions.h.
References standard_deviation().
         {
             return standard_deviation(data.data(), data.size());
         }
template<typename T > static double blond::mymath::sum (const T data[], const int n) inline static
Definition at line 337 of file math_functions.h.
Referenced by blond::InducedVoltageFreq::induced_voltage_generation(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), mean(), blond::FullRingAndRf::potential_well_generation(), blond::PhaseLoop::radial_difference(), blond::RingAndRfSection::rf_voltage_calculation(), and sum().
         {
             double m = 0.0;
             #pragma omp parallel for reduction(+ : m)
             for (int i = 0; i < n; ++i) {
                 m += data[i];
             }
             return m;
         }
template<typename T > static double blond::mymath::sum (const std::vector< T > & data) inline static
Definition at line 348 of file math_functions.h.
References sum().
         {
             return sum(data.data(), data.size());
         }
template<typename T > static double blond::mymath::trapezoid (const T * f, const double * deltaX, const int nsub) inline static
Definition at line 226 of file math_functions.h.
Referenced by blond::PhaseLoop::beam_phase(), blond::matched_from_distribution_density(), blond::matched_from_line_density(), and blond::Slices::rms().
         {
             // initialize the partial sum to be f(a)+f(b) and
             // deltaX to be the step size using nsub subdivisions
             double psum = 0.0;
 // increment the partial sum
             #pragma omp parallel for reduction(+ : psum)
             for (int i = 1; i < nsub; ++i) {
                 psum += (f[i] + f[i - 1]) * (deltaX[i] - deltaX[i - 1]);
             }
             // return approximation
             return psum / 2;
         }
template<typename T > static double blond::mymath::trapezoid (const std::vector< T > & f, const std::vector< double > & deltaX) inline static
Definition at line 243 of file math_functions.h.
         {
             return trapezoid<T>(f.data(), deltaX.data(), f.size());
         }
template<typename T > static double blond::mymath::trapezoid (const T * f, const double deltaX, const int nsub) inline static
Definition at line 250 of file math_functions.h.
         {
             // initialize the partial sum to be f(a)+f(b) and
             // deltaX to be the step size using nsub subdivisions
             double psum = f[0] + f[nsub - 1]; // f(a)+f(b);
 // double deltaX = (b-a)/nsub;
 // increment the partial sum
             #pragma omp parallel for reduction(+ : psum)
             for (int i = 1; i < nsub - 1; ++i) {
                 psum += 2 * f[i];
             }
             // multiply the sum by the constant deltaX/2.0
             psum = (deltaX / 2) * psum;
             // return approximation
             return psum;
         }
template<typename T > static double blond::mymath::trapezoid (const std::vector< T > & f, const double deltaX) inline static
Definition at line 271 of file math_functions.h.
         {
             return trapezoid<T>(f.data(), deltaX, f.size());
         }