Beam Longitudinal Dynamics code (BLonD): SPS_RL Class Reference
SPS_RL Class Reference
#include <PhaseLoop.h>
Public Member Functions
SPS_RL (ftype PL_gain, ftype window_coefficient=0, ftype RL_gain=0, PhaseNoise *phaseNoise=NULL, LHCNoiseFB *LHCNoiseFB=NULL, uint delay=0)
~SPS_RL ()
void track ()
Public Member Functions inherited from PhaseLoop
PhaseLoop (f_vector_t PL_gain, ftype window_coefficient, uint _delay, PhaseNoise *phaseNoise, LHCNoiseFB *LHCNoiseFB)
PhaseLoop ()
virtual ~PhaseLoop ()
void beam_phase ()
void default_track ()
void phase_difference ()
void radial_difference ()
void radial_steering_from_freq ()
Public Attributes
ftype gain
ftype gain2
Public Attributes inherited from PhaseLoop
ftype alpha = 0
uint delay = 0
ftype domega_RF = 0
ftype dphi = 0
ftype drho = 0
LHCNoiseFB * noiseFB
ftype phi_beam = 0
ftype reference = 0
PhaseNoise * RFnoise
Detailed Description
Definition at line 97 of file PhaseLoop.h.
Constructor & Destructor Documentation
SPS_RL::SPS_RL (ftype PL_gain, ftype window_coefficient = 0, ftype RL_gain = 0, PhaseNoise * phaseNoise = NULL, LHCNoiseFB * LHCNoiseFB = NULL, uint delay = 0)
Definition at line 432 of file PhaseLoop.cpp.
References PhaseLoop::alpha, PhaseLoop::delay, gain, gain2, PhaseLoop::noiseFB, and PhaseLoop::RFnoise.
{
     this->gain = PL_gain;
     this->alpha = window_coefficient;
     this->delay = delay;
     this->RFnoise = phaseNoise;
     this->noiseFB = LHCNoiseFB;
     this->gain2 = RL_gain;
 }
SPS_RL::~SPS_RL ()
Definition at line 442 of file PhaseLoop.cpp.
 {}
Member Function Documentation
void SPS_RL::track () virtual
Reimplemented from PhaseLoop.
Definition at line 445 of file PhaseLoop.cpp.
References PhaseLoop::beam_phase(), RfParameters::counter, PhaseLoop::default_track(), PhaseLoop::domega_RF, PhaseLoop::dphi, PhaseLoop::drho, gain, gain2, Context::GP, PhaseLoop::phase_difference(), PhaseLoop::radial_difference(), PhaseLoop::radial_steering_from_freq(), PhaseLoop::reference, Context::RfP, and mymath::sign().
                    {
     auto GP = Context::GP;
     auto RfP = Context::RfP;
     uint counter = RfP->counter;
     if (reference != 0)
         radial_steering_from_freq();
     beam_phase();
     phase_difference();
     radial_difference();
     // Frequency correction from phase loop and radial loop
     const auto factor = mymath::sign(RfP->eta_0(counter)) * (reference - drho) /
                         GP->ring_radius;
     // for (int i = 0; i < (int)gain.size(); ++i) {
     domega_RF = -gain * dphi - gain2 * factor;
     // }
     default_track();
 }
Member Data Documentation
ftype SPS_RL::gain
Definition at line 102 of file PhaseLoop.h.
Referenced by SPS_RL(), and track().
ftype SPS_RL::gain2
Definition at line 100 of file PhaseLoop.h.
Referenced by SPS_RL(), and track().