Beam Longitudinal Dynamics code (BLonD): blond::FullRingAndRf Class Reference
blond::FullRingAndRf Class Reference
#include <Tracker.h>
Public Types
enum main_harmonic_t { lowest_freq = 0, highest_voltage = 1 }
Public Member Functions
FullRingAndRf (const std::vector< RingAndRfSection * > &RingList)
~FullRingAndRf ()
void potential_well_generation (const int turn=0, const int n_points=100000, const double option=lowest_freq, const double dt_margin_percent=0.0)
void track ()
Public Attributes
f_vector_t fPotentialWell
f_vector_t fPotentialWellCoordinates
double fRingCircumference
std::vector< RingAndRfSection * > fRingList
double fRingRadius
f_vector_t fTotalVoltage
Detailed Description
Definition at line 144 of file Tracker.h.
Member Enumeration Documentation
enum blond::FullRingAndRf::main_harmonic_t
Enumerator
lowest_freq
highest_voltage
Definition at line 147 of file Tracker.h.
 { lowest_freq = 0, highest_voltage = 1 };
Constructor & Destructor Documentation
FullRingAndRf::FullRingAndRf (const std::vector< RingAndRfSection * > & RingList)
Definition at line 301 of file Tracker.cpp.
References blond::constant::pi.
 {
     fRingList = RingList;
     fRingCircumference = 0;
     for (auto &ring : fRingList)
         fRingCircumference += ring->section_length;
     fRingRadius = fRingCircumference / (2 * constant::pi);
 }
FullRingAndRf::~FullRingAndRf ()
Definition at line 312 of file Tracker.cpp.
 {}
Member Function Documentation
void FullRingAndRf::potential_well_generation (const int turn = 0, const int n_points = 100000, const double option = lowest_freq, const double dt_margin_percent = 0.0)
Definition at line 321 of file Tracker.cpp.
References ALL, blond::mymath::cum_trapezoid(), blond::mymath::fast_sin(), blond::mymath::linspace(), blond::constant::pi, blond::mymath::sign(), and blond::mymath::sum().
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
 {
     f_vector_t voltages;
     f_vector_t omega_rf;
     f_vector_t phi_offsets;
     auto charge = fRingList.back()->charge;
     auto &t_rev = fRingList.back()->t_rev;
     for (const auto &ring : fRingList) {
         for (int i = 0; i < ring->n_rf; ++i) {
             voltages.push_back(ring->voltage[i][turn]);
             omega_rf.push_back(ring->omega_rf[i][turn]);
             phi_offsets.push_back(ring->phi_rf[i][turn]);
         }
     }
     double main_omega_rf;
     if (option == 0) {
         main_omega_rf = *min_element(ALL(omega_rf));
     } else if (option == 1) {
         auto maxV = *min_element(ALL(voltages));
         f_vector_t temp;
         for (uint i = 0; i < voltages.size(); ++i)
             if (voltages[i] == maxV)
                 temp.push_back(omega_rf[i]);
         main_omega_rf = *min_element(ALL(omega_rf));
     } else {
         f_vector_t temp;
         copy_if(omega_rf.begin(), omega_rf.end(), back_inserter(temp),
         [option](const double x) { return x == option; });
         if (temp.empty()) {
             cerr << "[ERROR] The desired harmonic to compute"
                  << "the potential well does not"
                  << "match the RF parameters...\n";
             exit(-1);
         }
         main_omega_rf = option;//temp[k];
     }
     // cout << "main_omega_rf: " << main_omega_rf << "\n";
     double time_array_margin =
         dt_margin_percent * 2 * constant::pi / main_omega_rf;
     double slippage_factor = fRingList[0]->eta_0[turn];
     double first_dt = -time_array_margin / 2;
     double last_dt = 2 * constant::pi / main_omega_rf + time_array_margin / 2;
     f_vector_t time_array = linspace(first_dt, last_dt, n_points);
     fTotalVoltage.resize(time_array.size());
     for (int i = 0; i < (int)time_array.size(); ++i) {
         double sum = 0.0;
         for (int j = 0; j < (int)voltages.size(); ++j) {
             sum += voltages[j] * fast_sin(omega_rf[j] * time_array[i] +
                                           phi_offsets[j]);
         }
         fTotalVoltage[i] = sum;
     }
     const double eom_factor_potential = sign(slippage_factor) * charge
                                         / t_rev[turn];
     // cout << "eom_factor_potential: " << eom_factor_potential << "\n";
     // cout << "fTotalVoltage: " << fTotalVoltage << "\n";
     // cout << "time_array: " << time_array[1] - time_array[0] << "\n";
     fPotentialWell = 0.0 - cum_trapezoid(eom_factor_potential / abs(charge)
                                          * (fTotalVoltage
                                             + fRingList[0]->acceleration_kick[turn]),
                                          time_array[1] - time_array[0]);
     fPotentialWell.insert(fPotentialWell.begin(), 0);
     // cout << "fPotentialWell: " << fPotentialWell;
     fPotentialWell -= *min_element(ALL(fPotentialWell));
     fPotentialWellCoordinates = time_array;
 }
void FullRingAndRf::track ()
Definition at line 314 of file Tracker.cpp.
 {
     // Loops over all the RingAndRFSection.track methods.
     for (auto &ring : fRingList)
         ring->track();
 }
Member Data Documentation
f_vector_t blond::FullRingAndRf::fPotentialWell
Definition at line 149 of file Tracker.h.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
f_vector_t blond::FullRingAndRf::fPotentialWellCoordinates
Definition at line 150 of file Tracker.h.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
double blond::FullRingAndRf::fRingCircumference
Definition at line 152 of file Tracker.h.
std::vector<RingAndRfSection * > blond::FullRingAndRf::fRingList
Definition at line 154 of file Tracker.h.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
double blond::FullRingAndRf::fRingRadius
Definition at line 153 of file Tracker.h.
f_vector_t blond::FullRingAndRf::fTotalVoltage
Definition at line 151 of file Tracker.h.