Beam Longitudinal Dynamics code (BLonD): InducedVoltageTime Class Reference
InducedVoltageTime Class Reference
#include <InducedVoltage.h>
Public Types
enum time_or_freq { time_domain, freq_domain }
Public Member Functions
InducedVoltageTime (Slices *slices, std::vector< Intensity * > &WakeSourceList, time_or_freq TimeOrFreq=freq_domain)
~InducedVoltageTime ()
f_vector_t induced_voltage_generation (Beams *beam, uint length=0)
void reprocess (Slices *newSlices)
void sum_wakes (f_vector_t &v)
void track (Beams *beam)
Public Member Functions inherited from InducedVoltage
InducedVoltage ()
virtual ~InducedVoltage ()
Public Attributes
uint fCut
uint fShape
f_vector_t fTimeArray
time_or_freq fTimeOrFreq
f_vector_t fTotalWake
std::vector< Intensity * > fWakeSourceList
Public Attributes inherited from InducedVoltage
f_vector_t fInducedVoltage
Slices * fSlices
Detailed Description
Definition at line 39 of file InducedVoltage.h.
Member Enumeration Documentation
enum InducedVoltageTime::time_or_freq
Enumerator
time_domain
freq_domain
Definition at line 41 of file InducedVoltage.h.
 { time_domain, freq_domain };
Constructor & Destructor Documentation
InducedVoltageTime::InducedVoltageTime (Slices * slices, std::vector< Intensity * > & WakeSourceList, time_or_freq TimeOrFreq = freq_domain)
Definition at line 38 of file InducedVoltage.cpp.
References Slices::bin_centers, fCut, InducedVoltage::fInducedVoltage, fShape, InducedVoltage::fSlices, fTimeArray, fTimeOrFreq, fTotalWake, fWakeSourceList, Slices::n_slices, mymath::next_regular(), and sum_wakes().
 {
     // Induced voltage derived from the sum of
     // several wake fields (time domain).*
     fSlices = slices;
     // *Wake sources inputed as a list (eg: list of BBResonators objects)*
     fWakeSourceList = WakeSourceList;
     // *Time array of the wake in [s]*
     fTimeArray = f_vector_t();
     // *Total wake array of all sources in* [:math:`\Omega / s`]
     fTotalWake = f_vector_t();
     // *Induced voltage from the sum of the wake sources in [V]*
     fInducedVoltage = f_vector_t();
     // Pre-processing the wakes
     fTimeArray.resize(fSlices->n_slices);
     for (uint i = 0; i < fTimeArray.size(); ++i) {
         fTimeArray[i] = fSlices->bin_centers[i] - fSlices->bin_centers[0];
     }
     sum_wakes(fTimeArray);
     fCut = fTimeArray.size() + fSlices->n_slices - 1;
     fShape = mymath::next_regular(fCut);
     fTimeOrFreq = TimeOrFreq;
 }
InducedVoltageTime::~InducedVoltageTime ()
Definition at line 70 of file InducedVoltage.cpp.
References fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
f_vector_t InducedVoltageTime::induced_voltage_generation (Beams * beam, uint length = 0) virtual
Implements InducedVoltage.
Definition at line 114 of file InducedVoltage.cpp.
References Beams::charge, mymath::convolution(), fft::convolution_with_ffts(), dprintf, constant::e, InducedVoltage::fInducedVoltage, freq_domain, InducedVoltage::fSlices, fTimeOrFreq, fTotalWake, Beams::intensity, mymath::min(), Beams::n_macroparticles, Slices::n_macroparticles, Slices::n_slices, and time_domain.
Referenced by track().
 {
     // Method to calculate the induced voltage from wakes with convolution.*
     f_vector_t inducedVoltage;
     const double factor = -beam->charge * constant::e * beam->intensity
                           / beam->n_macroparticles;
     if (fTimeOrFreq == freq_domain) {
         f_vector_t in1(fSlices->n_slices);
         std::copy(fSlices->n_macroparticles.begin(),
                   fSlices->n_macroparticles.end(), in1.begin());
         f_vector_t in2 = fTotalWake;
         fft::convolution_with_ffts(in1, in2, inducedVoltage);
         std::transform(inducedVoltage.begin(), inducedVoltage.end(),
                        inducedVoltage.begin(),
                        std::bind1st(std::multiplies<double>(), factor));
     } else if (fTimeOrFreq == time_domain) {
         f_vector_t temp(fSlices->n_slices);
         std::copy(fSlices->n_macroparticles.begin(),
                   fSlices->n_macroparticles.end(), temp.begin());
         inducedVoltage.resize(fTotalWake.size() + temp.size() - 1);
         mymath::convolution(fTotalWake.data(), fTotalWake.size(), temp.data(),
                             temp.size(), inducedVoltage.data());
         std::transform(inducedVoltage.begin(), inducedVoltage.end(),
                        inducedVoltage.begin(),
                        std::bind1st(std::multiplies<double>(), factor));
     } else {
         dprintf("Error: Only freq_domain or time_domain are allowed\n");
         exit(-1);
     }
     inducedVoltage.resize((uint)fSlices->n_slices);
     fInducedVoltage = inducedVoltage;
     if (length > 0)
         inducedVoltage.resize(std::min((uint)fSlices->n_slices, length), 0);
     return inducedVoltage;
 }
void InducedVoltageTime::reprocess (Slices * newSlices) virtual
Implements InducedVoltage.
Definition at line 97 of file InducedVoltage.cpp.
References Slices::bin_centers, fCut, fShape, InducedVoltage::fSlices, fTimeArray, Slices::n_slices, mymath::next_regular(), and sum_wakes().
 {
     // *Reprocess the wake contributions with respect to the new_slicing.*
     // WARNING As Slice is a global variable,
     // users will have to change this variable and call reprocess()
     fSlices = newSlices;
     fTimeArray.resize(fSlices->n_slices);
     for (uint i = 0; i < fTimeArray.size(); ++i) {
         fTimeArray[i] = fSlices->bin_centers[i] - fSlices->bin_centers[0];
     }
     sum_wakes(fTimeArray);
     fCut = fTimeArray.size() + fSlices->n_slices - 1;
     fShape = mymath::next_regular(fCut);
 }
void InducedVoltageTime::sum_wakes (f_vector_t & v)
Definition at line 85 of file InducedVoltage.cpp.
References fTotalWake, and fWakeSourceList.
Referenced by InducedVoltageTime(), and reprocess().
 {
     // *Summing all the wake contributions in one total wake.*
     fTotalWake.resize(TimeArray.size());
     std::fill(fTotalWake.begin(), fTotalWake.end(), 0);
     for (Intensity *i : fWakeSourceList) {
         i->wake_calc(TimeArray);
         std::transform(fTotalWake.begin(), fTotalWake.end(), i->fWake.begin(),
                        fTotalWake.begin(), std::plus<double>());
     }
 }
void InducedVoltageTime::track (Beams * beam) inline virtual
Implements InducedVoltage.
Definition at line 72 of file InducedVoltage.cpp.
References Slices::bin_centers, Beams::charge, Beams::dE, Beams::dt, InducedVoltage::fSlices, induced_voltage_generation(), linear_interp_kick(), Beams::n_macroparticles, and Slices::n_slices.
 {
     // Tracking Method
     f_vector_t v = this->induced_voltage_generation(beam);
     std::transform(v.begin(), v.end(), v.begin(),
                    std::bind1st(std::multiplies<double>(), beam->charge));
     linear_interp_kick(beam->dt.data(), beam->dE.data(), v.data(),
                        fSlices->bin_centers.data(), fSlices->n_slices,
                        beam->n_macroparticles);
 }
Member Data Documentation
uint InducedVoltageTime::fCut
Definition at line 46 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
uint InducedVoltageTime::fShape
Definition at line 47 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
f_vector_t InducedVoltageTime::fTimeArray
Definition at line 44 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and reprocess().
time_or_freq InducedVoltageTime::fTimeOrFreq
Definition at line 48 of file InducedVoltage.h.
Referenced by induced_voltage_generation(), and InducedVoltageTime().
f_vector_t InducedVoltageTime::fTotalWake
Definition at line 45 of file InducedVoltage.h.
Referenced by induced_voltage_generation(), InducedVoltageTime(), and sum_wakes().
std::vector<Intensity *> InducedVoltageTime::fWakeSourceList
Definition at line 43 of file InducedVoltage.h.
Referenced by InducedVoltageTime(), and sum_wakes().