Beam Longitudinal Dynamics code (BLonD): option::Parser Class Reference
option::Parser Class Reference
Checks argument vectors for validity and parses them into data structures that are easier to work with.
#include <optionparser.h>
Public Member Functions
Parser ()
Creates a new Parser.
Parser (bool gnu, const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Creates a new Parser and immediately parses the given argument vector.
Parser (bool gnu, const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Parser(...) with non-const argv.
Parser (const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX Parser(...) (gnu==false).
Parser (const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX Parser(...) (gnu==false) with non-const argv.
bool error ()
Returns true if an unrecoverable error occurred while parsing options.
virtual bool finished (int numargs, const char **args)
Called by Parser::workhorse() after finishing the parse.
bool finished (int numargs, const char **args)
const char * nonOption (int i)
Returns nonOptions()[i] (without checking if i is in range!).
const char ** nonOptions ()
Returns a pointer to an array of non-option arguments (only valid if nonOptionsCount() >0).
int nonOptionsCount ()
Returns the number of non-option arguments that remained at the end of the most recent parse() that actually encountered non-option arguments.
int optionsCount ()
Returns the number of valid Option objects in buffer[].
void parse (bool gnu, const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
Parses the given argument vector.
void parse (bool gnu, const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
parse() with non-const argv.
void parse (const Descriptor usage[], int argc, const char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX parse() (gnu==false).
void parse (const Descriptor usage[], int argc, char **argv, Option options[], Option buffer[], int min_abbr_len=0, bool single_minus_longopt=false, int bufmax=-1)
POSIX parse() (gnu==false) with non-const argv.
virtual bool perform (Option &)
Called by Parser::workhorse() for each Option that has been successfully parsed (including unknown options if they have a Descriptor whose Descriptor::check_arg does not return ARG_ILLEGAL.
bool perform (Option &option)
StoreOptionAction (Parser &parser_, Option options_[], Option buffer_[], int bufmax_)
Number of slots in buffer. -1 means "large enou.h>.
Static Private Member Functions
static bool instr (char ch, const char *st)
static void shift (const char **args, int count)
static bool streq (const char *st1, const char *st2)
static bool streqabbr (const char *st1, const char *st2, long long min)
static bool workhorse (bool gnu, const Descriptor usage[], int numargs, const char **args, Action &action, bool single_minus_longopt, bool print_errors, int min_abbr_len)
Private Attributes
struct API Action
Option * buffer
int bufmax
bool err
const char ** nonop_args
int nonop_count
int op_count
Option * options
Parser & parser
class API StoreOptionAction
Friends
struct API Stats
Detailed Description
Checks argument vectors for validity and parses them into data structures that are easier to work with.
Example:
int main(int argc, char* argv[])
{
  argc-=(argc>0); argv+=(argc>0); // skip program name argv[0] if present
  option::Stats  stats(usage, argc, argv);
  option::Option options[stats.options_max], buffer[stats.buffer_max];
  option::Parser parse(usage, argc, argv, options, buffer);
  if (parse.error())
    return 1;
  if (options[HELP])
  ...
Definition at line 1190 of file optionparser.h.
Constructor & Destructor Documentation
option::Parser::Parser () inline
Creates a new Parser.
Definition at line 1199 of file optionparser.h.
 : op_count(0), nonop_count(0), nonop_args(0), err(false) {}
option::Parser::Parser (bool gnu, const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Creates a new Parser and immediately parses the given argument vector.
Parameters
gnu if true, parse() will not stop at the first non-option argument. Instead it will reorder arguments so that all non-options are at the end. This is the default behaviour of GNU getopt() but is not conforming to POSIX.
Note, that once the argument vector has been reordered, the gnu flag will have no further effect on this argument vector. So it is enough to pass gnu==true when creating Stats.
usage Array of Descriptor objects that describe the options to support. The last entry of this array must have 0 in all fields.
argc The number of elements from argv that are to be parsed. If you pass -1, the number will be determined automatically. In that case the argv list must end with a NULL pointer.
argv The arguments to be parsed. If you pass -1 as argc the last pointer in the argv list must be NULL to mark the end.
options Each entry is the first element of a linked list of Options. Each new option that is parsed will be appended to the list specified by that Option's Descriptor::index. If an entry is not yet used (i.e. the Option is invalid), it will be replaced rather than appended to.
The minimum length of this array is the greatest Descriptor::index value that occurs in usage PLUS ONE.
buffer Each argument that is successfully parsed (including unknown arguments, if they have a Descriptor whose CheckArg does not return ARG_ILLEGAL) will be stored in this array. parse() scans the array for the first invalid entry and begins writing at that index. You can pass bufmax to limit the number of options stored.
min_abbr_len Passing a value min_abbr_len > 0 enables abbreviated long options. The parser will match a prefix of a long option as if it was the full long option (e.g. –foob=10 will be interpreted as if it was –foobar=10), as long as the prefix has at least min_abbr_len characters (not counting the –) and is unambiguous.
Be careful if combining min_abbr_len=1 with single_minus_longopt=true because the ambiguity check does not consider short options and abbreviated single minus long options will take precedence over short options.
single_minus_longopt Passing true for this option allows long options to begin with a single minus. The double minus form will still be recognized. Note that single minus long options take precedence over short options and short option groups. E.g. -file would be interpreted as –file and not as -f -i -l -e (assuming a long option named "file" exists).
bufmax The greatest index in the buffer[] array that parse() will write to is bufmax-1. If there are more options, they will be processed (in particular their CheckArg will be called) but not stored.
If you used Stats::buffer_max to dimension this array, you can pass -1 (or not pass bufmax at all) which tells parse() that the buffer is "large enou.h>.
Attention
Remember that options and buffer store Option objects, not pointers. Therefore it is not possible for the same object to be in both arrays. For those options that are found in both buffer[] and options[] the respective objects are independent copies. And only the objects in options[] are properly linked via Option::next() and Option::prev(). You can iterate over buffer[] to process all options in the order they appear in the argument vector, but if you want access to the other Options with the same Descriptor::index, then you must access the linked list via options[]. You can get the linked list in options from a buffer object via something like options[buffer[i].index()].
Definition at line 1206 of file optionparser.h.
             : op_count(0), nonop_count(0), nonop_args(0), err(false) {
             parse(gnu, usage, argc, argv, options, buffer, min_abbr_len,
                   single_minus_longopt, bufmax);
         }
option::Parser::Parser (bool gnu, const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Parser(...) with non-const argv.
Definition at line 1215 of file optionparser.h.
             : op_count(0), nonop_count(0), nonop_args(0), err(false) {
             parse(gnu, usage, argc, (const char**)argv, options, buffer,
                   min_abbr_len, single_minus_longopt, bufmax);
         }
option::Parser::Parser (const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX Parser(...) (gnu==false).
Definition at line 1224 of file optionparser.h.
             : op_count(0), nonop_count(0), nonop_args(0), err(false) {
             parse(false, usage, argc, argv, options, buffer, min_abbr_len,
                   single_minus_longopt, bufmax);
         }
option::Parser::Parser (const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX Parser(...) (gnu==false) with non-const argv.
Definition at line 1233 of file optionparser.h.
             : op_count(0), nonop_count(0), nonop_args(0), err(false) {
             parse(false, usage, argc, (const char**)argv, options, buffer,
                   min_abbr_len, single_minus_longopt, bufmax);
         }
Member Function Documentation
bool option::Parser::error () inline
Returns true if an unrecoverable error occurred while parsing options.
An illegal argument to an option (i.e. CheckArg returns ARG_ILLEGAL) is an unrecoverable error that aborts the parse. Unknown options are only an error if their CheckArg function returns ARG_ILLEGAL. Otherwise they are collected. In that case if you want to exit the program if either an illegal argument or an unknown option has been passed, use code like this
if (parser.error() || options[UNKNOWN])
  exit(1);
Definition at line 1445 of file optionparser.h.
 { return err; }
virtual bool option::Parser::finished (int numargs, const char ** args) inline virtual
Called by Parser::workhorse() after finishing the parse.
Parameters
numargs the number of non-option arguments remaining
args pointer to the first remaining non-option argument (if numargs > 0).
Returns
false iff a fatal error has occurred.
Definition at line 1579 of file optionparser.h.
{
             (void)numargs;
             (void)args;
             return true;
         }
bool option::Parser::finished (int numargs, const char ** args) inline
Definition at line 1666 of file optionparser.h.
{
             // only overwrite non-option argument list if there's at least 1
             // new non-option argument. Otherwise we keep the old list. This
             // makes it easy to use default non-option arguments.
             if (numargs > 0) {
                 parser.nonop_count = numargs;
                 parser.nonop_args = args;
             }
             return true;
         }
static bool option::Parser::instr (char ch, const char * st) inline static private
Definition at line 1529 of file optionparser.h.
Referenced by workhorse().
{
             while (*st != 0 && *st != ch)
                 ++st;
             return *st == ch;
         }
const char* option::Parser::nonOption (int i) inline
Returns nonOptions()[i] (without checking if i is in range!).
Definition at line 1423 of file optionparser.h.
 { return nonOptions()[i]; }
const char** option::Parser::nonOptions () inline
Returns a pointer to an array of non-option arguments (only valid if nonOptionsCount() >0).
Note
parse() does not copy arguments, so this pointer points into the actual argument vector as passed to parse().
As explained at nonOptionsCount() this pointer is only changed by parse() calls that actually encounter non-option arguments. A parse() call that encounters only options, will not change nonOptions().
Definition at line 1417 of file optionparser.h.
 { return nonop_args; }
int option::Parser::nonOptionsCount () inline
Returns the number of non-option arguments that remained at the end of the most recent parse() that actually encountered non-option arguments.
Note
A parse() that does not encounter non-option arguments will leave this value as well as nonOptions() undisturbed. This means you can feed the Parser a default argument vector that contains non-option arguments (e.g. a default filename). Then you feed it the actual arguments from the user. If the user has supplied at least one non-option argument, all of the non-option arguments from the default disappear and are replaced by the user's non-option arguments. However, if the user does not supply any non-option arguments the defaults will still be in effect.
Definition at line 1400 of file optionparser.h.
 { return nonop_count; }
int option::Parser::optionsCount () inline
Returns the number of valid Option objects in buffer[].
Note
The returned value always reflects the number of Options in the buffer[] array used for the most recent call to parse().
The count (and the buffer[]) includes unknown options if they are collected (see Descriptor::longopt).
Definition at line 1376 of file optionparser.h.
 { return op_count; }
void option::Parser::parse (bool gnu, const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
Parses the given argument vector.
Parameters
gnu if true, parse() will not stop at the first non-option argument. Instead it will reorder arguments so that all non-options are at the end. This is the default behaviour of GNU getopt() but is not conforming to POSIX.
Note, that once the argument vector has been reordered, the gnu flag will have no further effect on this argument vector. So it is enough to pass gnu==true when creating Stats.
usage Array of Descriptor objects that describe the options to support. The last entry of this array must have 0 in all fields.
argc The number of elements from argv that are to be parsed. If you pass -1, the number will be determined automatically. In that case the argv list must end with a NULL pointer.
argv The arguments to be parsed. If you pass -1 as argc the last pointer in the argv list must be NULL to mark the end.
options Each entry is the first element of a linked list of Options. Each new option that is parsed will be appended to the list specified by that Option's Descriptor::index. If an entry is not yet used (i.e. the Option is invalid), it will be replaced rather than appended to.
The minimum length of this array is the greatest Descriptor::index value that occurs in usage PLUS ONE.
buffer Each argument that is successfully parsed (including unknown arguments, if they have a Descriptor whose CheckArg does not return ARG_ILLEGAL) will be stored in this array. parse() scans the array for the first invalid entry and begins writing at that index. You can pass bufmax to limit the number of options stored.
min_abbr_len Passing a value min_abbr_len > 0 enables abbreviated long options. The parser will match a prefix of a long option as if it was the full long option (e.g. –foob=10 will be interpreted as if it was –foobar=10), as long as the prefix has at least min_abbr_len characters (not counting the –) and is unambiguous.
Be careful if combining min_abbr_len=1 with single_minus_longopt=true because the ambiguity check does not consider short options and abbreviated single minus long options will take precedence over short options.
single_minus_longopt Passing true for this option allows long options to begin with a single minus. The double minus form will still be recognized. Note that single minus long options take precedence over short options and short option groups. E.g. -file would be interpreted as –file and not as -f -i -l -e (assuming a long option named "file" exists).
bufmax The greatest index in the buffer[] array that parse() will write to is bufmax-1. If there are more options, they will be processed (in particular their CheckArg will be called) but not stored.
If you used Stats::buffer_max to dimension this array, you can pass -1 (or not pass bufmax at all) which tells parse() that the buffer is "large enou.h>.
Attention
Remember that options and buffer store Option objects, not pointers. Therefore it is not possible for the same object to be in both arrays. For those options that are found in both buffer[] and options[] the respective objects are independent copies. And only the objects in options[] are properly linked via Option::next() and Option::prev(). You can iterate over buffer[] to process all options in the order they appear in the argument vector, but if you want access to the other Options with the same Descriptor::index, then you must access the linked list via options[]. You can get the linked list in options from a buffer object via something like options[buffer[i].index()].
Definition at line 1679 of file optionparser.h.
References err, StoreOptionAction, and workhorse().
{
         StoreOptionAction action(*this, options, buffer, bufmax);
         err = !workhorse(gnu, usage, argc, argv, action, single_minus_longopt,
                          true, min_abbr_len);
     }
void option::Parser::parse (bool gnu, const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
parse() with non-const argv.
Definition at line 1342 of file optionparser.h.
{
             parse(gnu, usage, argc, (const char**)argv, options, buffer,
                   min_abbr_len, single_minus_longopt, bufmax);
         }
void option::Parser::parse (const Descriptor usage[], int argc, const char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX parse() (gnu==false).
Definition at line 1350 of file optionparser.h.
{
             parse(false, usage, argc, argv, options, buffer, min_abbr_len,
                   single_minus_longopt, bufmax);
         }
void option::Parser::parse (const Descriptor usage[], int argc, char ** argv, Option options[], Option buffer[], int min_abbr_len = 0, bool single_minus_longopt = false, int bufmax = -1) inline
POSIX parse() (gnu==false) with non-const argv.
Definition at line 1358 of file optionparser.h.
{
             parse(false, usage, argc, (const char**)argv, options, buffer,
                   min_abbr_len, single_minus_longopt, bufmax);
         }
virtual bool option::Parser::perform (Option &) inline virtual
Called by Parser::workhorse() for each Option that has been successfully parsed (including unknown options if they have a Descriptor whose Descriptor::check_arg does not return ARG_ILLEGAL.
Returns false iff a fatal error has occured and the parse should be aborted.
Definition at line 1568 of file optionparser.h.
 { return true; }
bool option::Parser::perform (Option & option) inline
Definition at line 1648 of file optionparser.h.
References option::Option::desc, and option::Descriptor::index.
{
             if (bufmax < 0 || parser.op_count < bufmax) {
                 if (parser.op_count == 0x7fffffff)
                     return false; // overflow protection: don't accept number of
                                   // options that doesn't fit signed int
                 buffer[parser.op_count] = option;
                 int idx = buffer[parser.op_count].desc->index;
                 if (options[idx])
                     options[idx].append(buffer[parser.op_count]);
                 else
                     options[idx] = buffer[parser.op_count];
                 ++parser.op_count;
             }
             return true; // NOTE: an option that is discarded because of a full
                          // buffer is not fatal
         }
static void option::Parser::shift (const char ** args, int count) inline static private
Definition at line 1541 of file optionparser.h.
Referenced by workhorse().
{
             for (int i = 0; i > -count; --i) {
                 const char* temp = args[i];
                 args[i] = args[i - 1];
                 args[i - 1] = temp;
             }
         }
option::Parser::StoreOptionAction (Parser & parser_, Option options_[], Option buffer_[], int bufmax_) inline
Number of slots in buffer. -1 means "large enou.h>.
Creates a new StoreOption action.
Parameters
parser_ the parser whose op_count should be updated.
options_ each Option o is chained into the linked list options_[o.desc->index]
buffer_ each Option is appended to this array as long as there's a free slot.
bufmax_ number of slots in buffer_. -1 means "large enou.h>.
Definition at line 1635 of file optionparser.h.
             : parser(parser_), options(options_), buffer(buffer_),
               bufmax(bufmax_) {
             // find first empty slot in buffer (if any)
             int bufidx = 0;
             while ((bufmax < 0 || bufidx < bufmax) && buffer[bufidx])
                 ++bufidx;
             // set parser's optionCount
             parser.op_count = bufidx;
         }
static bool option::Parser::streq (const char * st1, const char * st2) inline static private
Definition at line 1478 of file optionparser.h.
Referenced by workhorse().
{
             while (*st1 != 0)
                 if (*st1++ != *st2++)
                     return false;
             return (*st2 == 0 || *st2 == '=');
         }
static bool option::Parser::streqabbr (const char * st1, const char * st2, long long min) inline static private
Definition at line 1511 of file optionparser.h.
Referenced by workhorse().
{
             const char* st1start = st1;
             while (*st1 != 0 && (*st1 == *st2)) {
                 ++st1;
                 ++st2;
             }
             return (*st1 == 0 || (min > 0 && (st1 - st1start) >= min)) &&
                    (*st2 == 0 || *st2 == '=');
         }
bool option::Parser::workhorse (bool gnu, const Descriptor usage[], int numargs, const char ** args, Action & action, bool single_minus_longopt, bool print_errors, int min_abbr_len) inline static private
Definition at line 1707 of file optionparser.h.
References option::Option::arg, option::ARG_IGNORE, option::ARG_ILLEGAL, option::ARG_NONE, option::ARG_OK, option::Descriptor::check_arg, instr(), shift(), option::Descriptor::shortopt, streq(), and streqabbr().
Referenced by option::Stats::add(), and parse().
{
         // protect against NULL pointer
         if (args == 0)
             numargs = 0;
         int nonops = 0;
         while (numargs != 0 && *args != 0) {
             const char* param = *args; // param can be --long-option, -srto or
                                        // non-option argument
             // in POSIX mode the first non-option argument terminates the option
             // list
             // a lone minus character is a non-option argument
             if (param[0] != '-' || param[1] == 0) {
                 if (gnu) {
                     ++nonops;
                     ++args;
                     if (numargs > 0)
                         --numargs;
                     continue;
                 } else
                     break;
             }
             // -- terminates the option list. The -- itself is skipped.
             if (param[1] == '-' && param[2] == 0) {
                 shift(args, nonops);
                 ++args;
                 if (numargs > 0)
                     --numargs;
                 break;
             }
             bool handle_short_options;
             const char* longopt_name;
             if (param[1] == '-') { // if --long-option
                 handle_short_options = false;
                 longopt_name = param + 2;
             } else {
                 handle_short_options = true;
                 longopt_name = param + 1; // for testing a potential
                                           // -long-option
             }
             bool try_single_minus_longopt = single_minus_longopt;
             bool have_more_args =
                 (numargs > 1 || numargs < 0); // is referencing argv[1] valid?
             do { // loop over short options in group, for long options the body
                  // is executed only once
                 int idx;
                 const char* optarg;
                 /******************** long option **********************/
                 if (handle_short_options == false || try_single_minus_longopt) {
                     idx = 0;
                     while (usage[idx].longopt != 0 &&
                            !streq(usage[idx].longopt, longopt_name))
                         ++idx;
                     if (usage[idx].longopt == 0 &&
                         min_abbr_len > 0) { // if we should try to match
                                             // abbreviated long options
                         int i1 = 0;
                         while (usage[i1].longopt != 0 &&
                                !streqabbr(usage[i1].longopt, longopt_name,
                                           min_abbr_len))
                             ++i1;
                         if (usage[i1].longopt != 0) {
                             // now test if the match is unambiguous by checking
                             // for another match
                             int i2 = i1 + 1;
                             while (usage[i2].longopt != 0 &&
                                    !streqabbr(usage[i2].longopt, longopt_name,
                                               min_abbr_len))
                                 ++i2;
                             if (usage[i2].longopt == 0) // if there was no
                                                         // second match it's
                                                         // unambiguous, so
                                                         // accept i1 as idx
                                 idx = i1;
                         }
                     }
                     // if we found something, disable handle_short_options (only
                     // relevant if single_minus_longopt)
                     if (usage[idx].longopt != 0)
                         handle_short_options = false;
                     try_single_minus_longopt = false; // prevent looking for
                                                       // longopt in the middle
                                                       // of shortopt group
                     optarg = longopt_name;
                     while (*optarg != 0 && *optarg != '=')
                         ++optarg;
                     if (*optarg == '=') // attached argument
                         ++optarg;
                     else
                         // possibly detached argument
                         optarg = (have_more_args ? args[1] : 0);
                 }
                 /************************ short option
                 * ***********************************/
                 if (handle_short_options) {
                     if (*++param == 0) // point at the 1st/next option character
                         break;         // end of short option group
                     idx = 0;
                     while (usage[idx].shortopt != 0 &&
                            !instr(*param, usage[idx].shortopt))
                         ++idx;
                     if (param[1] == 0) // if the potential argument is separate
                         optarg = (have_more_args ? args[1] : 0);
                     else
                         // if the potential argument is attached
                         optarg = param + 1;
                 }
                 const Descriptor* descriptor = &usage[idx];
                 if (descriptor->shortopt ==
                     0) { /**************  unknown option ********************/
                     // look for dummy entry (shortopt == "" and longopt == "")
                     // to use as Descriptor for unknown options
                     idx = 0;
                     while (usage[idx].shortopt != 0 &&
                            (usage[idx].shortopt[0] != 0 ||
                             usage[idx].longopt[0] != 0))
                         ++idx;
                     descriptor = (usage[idx].shortopt == 0 ? 0 : &usage[idx]);
                 }
                 if (descriptor != 0) {
                     Option option(descriptor, param, optarg);
                     switch (descriptor->check_arg(option, print_errors)) {
                     case ARG_ILLEGAL:
                         return false; // fatal
                     case ARG_OK:
                         // skip one element of the argument vector, if it's a
                         // separated argument
                         if (optarg != 0 && have_more_args &&
                             optarg == args[1]) {
                             shift(args, nonops);
                             if (numargs > 0)
                                 --numargs;
                             ++args;
                         }
                         // No further short options are possible after an
                         // argument
                         handle_short_options = false;
                         break;
                     case ARG_IGNORE:
                     case ARG_NONE:
                         option.arg = 0;
                         break;
                     }
                     if (!action.perform(option))
                         return false;
                 }
             } while (handle_short_options);
             shift(args, nonops);
             ++args;
             if (numargs > 0)
                 --numargs;
         } // while
         if (numargs > 0 && *args == 0) // It's a bug in the caller if numargs is
                                        // greater than the actual number
             numargs = 0; // of arguments, but as a service to the user we fix
                          // this if we spot it.
         if (numargs < 0) { // if we don't know the number of remaining
                            // non-option arguments
                            // we need to count them
             numargs = 0;
             while (args[numargs] != 0)
                 ++numargs;
         }
         return action.finished(numargs + nonops, args - nonops);
     }
Friends And Related Function Documentation
friend struct API Stats friend
Definition at line 1448 of file optionparser.h.
Member Data Documentation
struct API option::Parser::Action private
Definition at line 1452 of file optionparser.h.
Option* option::Parser::buffer private
Definition at line 1621 of file optionparser.h.
int option::Parser::bufmax private
Definition at line 1622 of file optionparser.h.
bool option::Parser::err private
Definition at line 1194 of file optionparser.h.
Referenced by parse().
const char** option::Parser::nonop_args private
Definition at line 1193 of file optionparser.h.
int option::Parser::nonop_count private
Definition at line 1192 of file optionparser.h.
int option::Parser::op_count private
Definition at line 1191 of file optionparser.h.
Option* option::Parser::options private
Definition at line 1620 of file optionparser.h.
Parser& option::Parser::parser private
Definition at line 1619 of file optionparser.h.
class API option::Parser::StoreOptionAction private
Definition at line 1450 of file optionparser.h.
Referenced by parse().