Beam Longitudinal Dynamics code (BLonD): blond::optionparser::PrintUsageImplementation::LineWrapper Class Reference
blond::optionparser::PrintUsageImplementation::LineWrapper Class Reference
#include <optionparser.h>
Public Member Functions
LineWrapper (int x1, int x2)
Constructs a LineWrapper that wraps its output to fit into screen columns x1 (incl.) to x2 (excl.).
void flush (IStringWriter &write)
Writes out all remaining data from the LineWrapper using write. Unlike process() this method indents all lines including the first and will output a \n at the end (but only if something has been written).
void process (IStringWriter &write, const char *data, int len)
Process, wrap and output the next piece of data.
Private Member Functions
bool buf_empty ()
bool buf_full ()
void buf_next ()
Call BEFORE reading ...buf[tail].
void buf_store (const char *data, int len)
void output (IStringWriter &write, const char *data, int len)
Writes (data,len) into the ring buffer. If the buffer is full, a single line is flushed out of the buffer into write.
void write_one_line (IStringWriter &write)
Writes a single line of output from the buffer to write.
Private Attributes
const char * datbuf [bufmask+1]
Ring buffer for data component of pair (data, length).
int head
index for next write
int lenbuf [bufmask+1]
Ring buffer for length component of pair (data, length).
int tail
index for next read - 1 (i.e. increment tail BEFORE read)
int width
The width of the column to line wrap.
bool wrote_something
Multiple methods of LineWrapper may decide to flush part of the buffer to free up space. The contract of process() says that only 1 line is output. So this variable is used to track whether something has output a line. It is reset at the beginning of process() and checked at the end to decide if output has already occurred or is still needed.
int x
The indentation of the column to which the LineBuffer outputs. LineBuffer assumes that the indentation has already been written when process() is called, so this value is only used when a buffer flush requires writing additional lines of output.
Static Private Attributes
static const int bufmask = 15
Must be a power of 2 minus 1.
Detailed Description
Definition at line 2472 of file optionparser.h.
Constructor & Destructor Documentation
blond::optionparser::PrintUsageImplementation::LineWrapper::LineWrapper (int x1, int x2) inline
Constructs a LineWrapper that wraps its output to fit into screen columns x1 (incl.) to x2 (excl.).
x1 gives the indentation LineWrapper uses if it needs to indent.
Definition at line 2701 of file optionparser.h.
References width.
                     : x(x1), width(x2 - x1), head(0), tail(bufmask)
                 {
                     if (width < 2) // because of wide characters we need at least
                         // width 2 or the code breaks
                         width = 2;
                 }
Member Function Documentation
bool blond::optionparser::PrintUsageImplementation::LineWrapper::buf_empty () inline private
Definition at line 2513 of file optionparser.h.
References bufmask, head, and tail.
Referenced by flush(), and write_one_line().
 { return ((tail + 1) & bufmask) == head; }
bool blond::optionparser::PrintUsageImplementation::LineWrapper::buf_full () inline private
Definition at line 2515 of file optionparser.h.
References head, and tail.
Referenced by output().
 { return tail == head; }
void blond::optionparser::PrintUsageImplementation::LineWrapper::buf_next () inline private
Call BEFORE reading ...buf[tail].
Definition at line 2525 of file optionparser.h.
References bufmask, and tail.
Referenced by write_one_line().
 { tail = (tail + 1) & bufmask; }
void blond::optionparser::PrintUsageImplementation::LineWrapper::buf_store (const char * data, int len) inline private
Definition at line 2517 of file optionparser.h.
References bufmask, datbuf, head, and lenbuf.
Referenced by output().
                 {
                     lenbuf[head] = len;
                     datbuf[head] = data;
                     head = (head + 1) & bufmask;
                 }
void blond::optionparser::PrintUsageImplementation::LineWrapper::flush (IStringWriter & write) inline
Writes out all remaining data from the LineWrapper using write. Unlike process() this method indents all lines including the first and will output a \n at the end (but only if something has been written).
Definition at line 2570 of file optionparser.h.
References buf_empty(), blond::optionparser::PrintUsageImplementation::indent(), write_one_line(), wrote_something, and x.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     if (buf_empty())
                         return;
                     int _ = 0;
                     indent(write, _, x);
                     wrote_something = false;
                     while (!buf_empty())
                         write_one_line(write);
                     write("\n", 1);
                 }
void blond::optionparser::PrintUsageImplementation::LineWrapper::output (IStringWriter & write, const char * data, int len) inline private
Writes (data,len) into the ring buffer. If the buffer is full, a single line is flushed out of the buffer into write.
Definition at line 2532 of file optionparser.h.
References buf_full(), buf_store(), and write_one_line().
Referenced by process().
                 {
                     if (buf_full())
                         write_one_line(write);
                     buf_store(data, len);
                 }
void blond::optionparser::PrintUsageImplementation::LineWrapper::process (IStringWriter & write, const char * data, int len) inline
Process, wrap and output the next piece of data.
process() will output at least one line of output. This is not necessarily the data passed in. It may be data queued from a prior call to process(). If the internal buffer is full, more than 1 line will be output.
process() assumes that the a proper amount of indentation has already been output. It won't write any further indentation before the 1st line. If more than 1 line is written due to buffer constraints, the lines following the first will be indented by this method, though.
No \n is written by this method after the last line that is written.
Parameters
write where to write the data.
data the new chunk of data to write.
len the length of the chunk of data to write.
Definition at line 2606 of file optionparser.h.
References blond::optionparser::PrintUsageImplementation::isWideChar(), output(), width, write_one_line(), and wrote_something.
Referenced by blond::optionparser::PrintUsageImplementation::printUsage().
                 {
                     wrote_something = false;
                     while (len > 0) {
                         if (len <= width) { // quick test that works because
                             // utf8width <= len (all wide chars have
                             // at least 2 bytes)
                             output(write, data, len);
                             len = 0;
                         } else { // if (len > width)  it's possible (but not
                             // guaranteed) that utf8len > width
                             int utf8width = 0;
                             int maxi = 0;
                             while (maxi < len && utf8width < width) {
                                 int charbytes = 1;
                                 unsigned ch = (unsigned char)data[maxi];
                                 if (ch > 0xC1) { // everything <= 0xC1 (yes, even
                                     // 0xC1 itself) is not a valid
                                     // UTF-8 start byte
                                     // int __builtin_clz (unsigned int x)
                                     // Returns the number of leading 0-bits in x,
                                     // starting at the most significant bit
                                     unsigned mask =
                                         (unsigned) - 1 >> __builtin_clz(ch ^ 0xff);
                                     ch = ch & mask; // mask out length bits, we
                                     // don't verify their
                                     // correctness
                                     while ((maxi + charbytes < len) && //
                                             (((unsigned char)data[maxi + charbytes] ^
                                               0x80) <= 0x3F)) { // while next byte is
                                         // continuation byte
                                         ch = (ch << 6) ^
                                              (unsigned char)data[maxi + charbytes] ^
                                              0x80; // add continuation to char code
                                         ++charbytes;
                                     }
                                     // ch is the decoded unicode code point
                                     if (ch >= 0x1100 &&
                                             isWideChar(ch)) { // the test for 0x1100 is
                                         // here to avoid the
                                         // function call in the
                                         // Latin case
                                         if (utf8width + 2 > width)
                                             break;
                                         ++utf8width;
                                     }
                                 }
                                 ++utf8width;
                                 maxi += charbytes;
                             }
                             // data[maxi-1] is the last byte of the UTF-8 sequence
                             // of the last character that fits
                             // onto the 1st line. If maxi == len, all characters fit
                             // on the line.
                             if (maxi == len) {
                                 output(write, data, len);
                                 len = 0;
                             } else { // if (maxi < len)  at least 1 character
                                 // (data[maxi] that is) doesn't fit on the line
                                 int i;
                                 for (i = maxi; i >= 0; --i)
                                     if (data[i] == ' ')
                                         break;
                                 if (i >= 0) {
                                     output(write, data, i);
                                     data += i + 1;
                                     len -= i + 1;
                                 } else { // did not find a space to split at =>
                                     // split before data[maxi]
                                     // data[maxi] is always the beginning of a
                                     // character, never a continuation byte
                                     output(write, data, maxi);
                                     data += maxi;
                                     len -= maxi;
                                 }
                             }
                         }
                     }
                     if (!wrote_something) // if we didn't already write something to
                         // make space in the buffer
                         write_one_line(
                             write); // write at most one line of actual output
                 }
void blond::optionparser::PrintUsageImplementation::LineWrapper::write_one_line (IStringWriter & write) inline private
Writes a single line of output from the buffer to write.
Definition at line 2544 of file optionparser.h.
References buf_empty(), buf_next(), datbuf, blond::optionparser::PrintUsageImplementation::indent(), lenbuf, tail, wrote_something, and x.
Referenced by flush(), output(), and process().
                 {
                     if (wrote_something) { // if we already wrote something, we need
                         // to start a new line
                         write("\n", 1);
                         int _ = 0;
                         indent(write, _, x);
                     }
                     if (!buf_empty()) {
                         buf_next();
                         write(datbuf[tail], lenbuf[tail]);
                     }
                     wrote_something = true;
                 }
Member Data Documentation
const int blond::optionparser::PrintUsageImplementation::LineWrapper::bufmask = 15 static private
Must be a power of 2 minus 1.
Definition at line 2473 of file optionparser.h.
Referenced by buf_empty(), buf_next(), and buf_store().
const char* blond::optionparser::PrintUsageImplementation::LineWrapper::datbuf[bufmask+1] private
Ring buffer for data component of pair (data, length).
Definition at line 2481 of file optionparser.h.
Referenced by buf_store(), and write_one_line().
int blond::optionparser::PrintUsageImplementation::LineWrapper::head private
index for next write
Definition at line 2496 of file optionparser.h.
Referenced by buf_empty(), buf_full(), and buf_store().
int blond::optionparser::PrintUsageImplementation::LineWrapper::lenbuf[bufmask+1] private
Ring buffer for length component of pair (data, length).
Definition at line 2477 of file optionparser.h.
Referenced by buf_store(), and write_one_line().
int blond::optionparser::PrintUsageImplementation::LineWrapper::tail private
index for next read - 1 (i.e. increment tail BEFORE read)
Definition at line 2497 of file optionparser.h.
Referenced by buf_empty(), buf_full(), buf_next(), and write_one_line().
int blond::optionparser::PrintUsageImplementation::LineWrapper::width private
The width of the column to line wrap.
Definition at line 2495 of file optionparser.h.
Referenced by LineWrapper(), and process().
bool blond::optionparser::PrintUsageImplementation::LineWrapper::wrote_something private
Multiple methods of LineWrapper may decide to flush part of the buffer to free up space. The contract of process() says that only 1 line is output. So this variable is used to track whether something has output a line. It is reset at the beginning of process() and checked at the end to decide if output has already occurred or is still needed.
Definition at line 2511 of file optionparser.h.
Referenced by flush(), process(), and write_one_line().
int blond::optionparser::PrintUsageImplementation::LineWrapper::x private
The indentation of the column to which the LineBuffer outputs. LineBuffer assumes that the indentation has already been written when process() is called, so this value is only used when a buffer flush requires writing additional lines of output.
Definition at line 2491 of file optionparser.h.
Referenced by flush(), and write_one_line().