Beam Longitudinal Dynamics code (BLonD): plot_xy.h File Reference
plot_xy.h File Reference
#include <blond/utilities.h>
Functions
int plot_xy (f_vector_t xArray, f_vector_t yArray, std::string figureName, std::string dirName, std::string saveFigName, double xMax=0)
Function Documentation
int plot_xy (f_vector_t xArray, f_vector_t yArray, std::string figureName, std::string dirName, std::string saveFigName, double xMax = 0)
Definition at line 13 of file plot_xy.cpp.
References python::convert_double(), python::convert_double_array(), python::convert_string(), and python::import().
{
   python::import();
   auto pFunc = python::import("plot_xy", "plot_xy");
   auto py_xArray = python::convert_double_array(xArray.data(), xArray.size());
   auto py_yArray = python::convert_double_array(yArray.data(), yArray.size());
   auto py_figureName = python::convert_string(figureName);
   auto py_dirName = python::convert_string(dirName);
   auto py_saveFigName = python::convert_string(saveFigName);
   auto py_xMax = python::convert_double(xMax);
   auto ret = PyObject_CallFunctionObjArgs(pFunc, py_xArray, py_yArray, py_figureName, py_dirName, py_saveFigName, py_xMax, NULL);
   return ret != nullptr;
 }