Beam Longitudinal Dynamics code (BLonD): blond::optionparser::Stats Struct Reference
blond::optionparser::Stats Struct Reference
Determines the minimum lengths of the buffer and options arrays used for Parser.
#include <optionparser.h>
Classes
class CountOptionsAction
Public Member Functions
Stats ()
Creates a Stats object with counts set to 1 (for the sentinel element).
Stats (bool gnu, const Descriptor usage[], int argc, const char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
Creates a new Stats object and immediately updates it for the given usage and argument vector. You may pass 0 for argc and/or argv, if you just want to update options_max.
Stats (bool gnu, const Descriptor usage[], int argc, char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
Stats(...) with non-const argv.
Stats (const Descriptor usage[], int argc, const char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
POSIX Stats(...) (gnu==false).
Stats (const Descriptor usage[], int argc, char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
POSIX Stats(...) (gnu==false) with non-const argv.
void add (bool gnu, const Descriptor usage[], int argc, const char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
Updates this Stats object for the given usage and argument vector. You may pass 0 for argc and/or argv, if you just want to update options_max.
void add (bool gnu, const Descriptor usage[], int argc, char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
add() with non-const argv.
void add (const Descriptor usage[], int argc, const char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
POSIX add() (gnu==false).
void add (const Descriptor usage[], int argc, char **argv, int min_abbr_len=0, bool single_minus_longopt=false)
POSIX add() (gnu==false) with non-const argv.
Public Attributes
unsigned buffer_max
Number of elements needed for a buffer[] array to be used for parsing the same argument vectors that were fed into this Stats object.
unsigned options_max
Number of elements needed for an options[] array to be used for parsing the same argument vectors that were fed into this Stats object.
Detailed Description
Determines the minimum lengths of the buffer and options arrays used for Parser.
Because Parser doesn't use dynamic memory its output arrays have to be pre-allocated. If you don't want to use fixed size arrays (which may turn out too small, causing command line arguments to be dropped), you can use Stats to determine the correct sizes. Stats work cumulative. You can first pass in your default options and then the real options and afterwards the counts will reflect the union.
Definition at line 1056 of file optionparser.h.
Constructor & Destructor Documentation
blond::optionparser::Stats::Stats () inline
Creates a Stats object with counts set to 1 (for the sentinel element).
Definition at line 1093 of file optionparser.h.
                 : buffer_max(1), options_max(1) // 1 more than necessary as sentinel
             {}
blond::optionparser::Stats::Stats (bool gnu, const Descriptor usage[], int argc, const char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
Creates a new Stats object and immediately updates it for the given usage and argument vector. You may pass 0 for argc and/or argv, if you just want to update options_max.
Note
The calls to Stats methods must match the later calls to Parser methods. See Parser::parse() for the meaning of the arguments.
Definition at line 1108 of file optionparser.h.
References add().
                 : buffer_max(1), options_max(1) // 1 more than necessary as sentinel
             {
                 add(gnu, usage, argc, argv, min_abbr_len, single_minus_longopt);
             }
blond::optionparser::Stats::Stats (bool gnu, const Descriptor usage[], int argc, char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
Stats(...) with non-const argv.
Definition at line 1117 of file optionparser.h.
References add().
                 : buffer_max(1), options_max(1) // 1 more than necessary as sentinel
             {
                 add(gnu, usage, argc, (const char **)argv, min_abbr_len,
                     single_minus_longopt);
             }
blond::optionparser::Stats::Stats (const Descriptor usage[], int argc, const char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
POSIX Stats(...) (gnu==false).
Definition at line 1127 of file optionparser.h.
References add().
                 : buffer_max(1), options_max(1) // 1 more than necessary as sentinel
             {
                 add(false, usage, argc, argv, min_abbr_len, single_minus_longopt);
             }
blond::optionparser::Stats::Stats (const Descriptor usage[], int argc, char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
POSIX Stats(...) (gnu==false) with non-const argv.
Definition at line 1136 of file optionparser.h.
References add().
                 : buffer_max(1), options_max(1) // 1 more than necessary as sentinel
             {
                 add(false, usage, argc, (const char **)argv, min_abbr_len,
                     single_minus_longopt);
             }
Member Function Documentation
void blond::optionparser::Stats::add (bool gnu, const Descriptor usage[], int argc, const char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
Updates this Stats object for the given usage and argument vector. You may pass 0 for argc and/or argv, if you just want to update options_max.
Note
The calls to Stats methods must match the later calls to Parser methods. See Parser::parse() for the meaning of the arguments.
Definition at line 1726 of file optionparser.h.
References buffer_max, blond::optionparser::Descriptor::index, options_max, and blond::optionparser::Parser::workhorse().
Referenced by add(), and Stats().
         {
             // determine size of options array. This is the greatest index used in
             // the usage + 1
             int i = 0;
             while (usage[i].shortopt != 0) {
                 if (usage[i].index + 1 >= options_max)
                     options_max = (usage[i].index + 1) +
                                   1; // 1 more than necessary as sentinel
                 ++i;
             }
             CountOptionsAction action(&buffer_max);
             Parser::workhorse(gnu, usage, argc, argv, action, single_minus_longopt,
                               false, min_abbr_len);
         }
void blond::optionparser::Stats::add (bool gnu, const Descriptor usage[], int argc, char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
add() with non-const argv.
Definition at line 1162 of file optionparser.h.
References add().
             {
                 add(gnu, usage, argc, (const char **)argv, min_abbr_len,
                     single_minus_longopt);
             }
void blond::optionparser::Stats::add (const Descriptor usage[], int argc, const char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
POSIX add() (gnu==false).
Definition at line 1171 of file optionparser.h.
References add().
             {
                 add(false, usage, argc, argv, min_abbr_len, single_minus_longopt);
             }
void blond::optionparser::Stats::add (const Descriptor usage[], int argc, char ** argv, int min_abbr_len = 0, bool single_minus_longopt = false) inline
POSIX add() (gnu==false) with non-const argv.
Definition at line 1179 of file optionparser.h.
References add().
             {
                 add(false, usage, argc, (const char **)argv, min_abbr_len,
                     single_minus_longopt);
             }
Member Data Documentation
unsigned blond::optionparser::Stats::buffer_max
Number of elements needed for a buffer[] array to be used for parsing the same argument vectors that were fed into this Stats object.
Note
This number is always 1 greater than the actual number needed, to give you a sentinel element.
Definition at line 1069 of file optionparser.h.
Referenced by add().
unsigned blond::optionparser::Stats::options_max
Number of elements needed for an options[] array to be used for parsing the same argument vectors that were fed into this Stats object.
Note
This number is always 1 greater than the actual number needed, to give you a sentinel element.
This number depends only on the usage, not the argument vectors, because the options array needs exactly one slot for each possible Descriptor::index.
Definition at line 1087 of file optionparser.h.
Referenced by add().