Beam Longitudinal Dynamics code (BLonD): vdt Namespace Reference
vdt Namespace Reference
Namespaces
namespace details
Functions
void expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double fast_exp (double initial_x)
Exponential Function double precision.
float fast_expf (float initial_x)
Exponential Function single precision.
void fast_expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void fast_expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double fast_sin (double x)
Double precision sine: just call sincos.
void fast_sincos (const double xx, double &s, double &c)
Double precision sincos.
void fast_sincosf (const float xx, float &s, float &c)
Single precision sincos.
float fast_sinf (float x)
void fast_sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void fast_sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
void sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
Function Documentation
void vdt::expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void vdt::expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double vdt::fast_exp (double initial_x) inline
Exponential Function double precision.
Definition at line 70 of file exp.h.
References vdt::details::EXP_LIMIT, vdt::details::fpfloor(), vdt::details::LOG2E, vdt::details::PX1exp, vdt::details::PX2exp, vdt::details::PX3exp, vdt::details::QX1exp, vdt::details::QX2exp, vdt::details::QX3exp, vdt::details::QX4exp, and vdt::details::uint642dp().
Referenced by mymath::fast_exp().
{
         double x = initial_x;
         double px = details::fpfloor(details::LOG2E * x + 0.5);
         const int32_t n = int32_t(px);
         x -= px * 6.93145751953125E-1;
         x -= px * 1.42860682030941723212E-6;
         const double xx = x * x;
         // px = x * P(x**2).
         px = details::PX1exp;
         px *= xx;
         px += details::PX2exp;
         px *= xx;
         px += details::PX3exp;
         px *= x;
         // Evaluate Q(x**2).
         double qx = details::QX1exp;
         qx *= xx;
         qx += details::QX2exp;
         qx *= xx;
         qx += details::QX3exp;
         qx *= xx;
         qx += details::QX4exp;
         // e**x = 1 + 2x P(x**2)/( Q(x**2) - P(x**2) )
         x = px / (qx - px);
         x = 1.0 + 2.0 * x;
         // Build 2^n in double.
         x *= details::uint642dp((((uint64_t)n) + 1023) << 52);
         if (initial_x > details::EXP_LIMIT)
             x = std::numeric_limits<double>::infinity();
         if (initial_x < -details::EXP_LIMIT)
             x = 0.;
         return x;
     }
float vdt::fast_expf (float initial_x) inline
Exponential Function single precision.
Definition at line 118 of file exp.h.
References vdt::details::C1F, vdt::details::C2F, vdt::details::fpfloor(), vdt::details::LOG2EF, vdt::details::MAXLOGF, vdt::details::MINLOGF, vdt::details::PX1expf, vdt::details::PX2expf, vdt::details::PX3expf, vdt::details::PX4expf, vdt::details::PX5expf, vdt::details::PX6expf, and vdt::details::uint322sp().
{
         float x = initial_x;
         float z =
             details::fpfloor(details::LOG2EF * x +
                              0.5f); /* floor() truncates toward -infinity. */
         x -= z * details::C1F;
         x -= z * details::C2F;
         const int32_t n = int32_t(z);
         const float x2 = x * x;
         z = x * details::PX1expf;
         z += details::PX2expf;
         z *= x;
         z += details::PX3expf;
         z *= x;
         z += details::PX4expf;
         z *= x;
         z += details::PX5expf;
         z *= x;
         z += details::PX6expf;
         z *= x2;
         z += x + 1.0f;
         /* multiply by power of 2 */
         z *= details::uint322sp((n + 0x7f) << 23);
         if (initial_x > details::MAXLOGF)
             z = std::numeric_limits<float>::infinity();
         if (initial_x < details::MINLOGF)
             z = 0.f;
         return z;
     }
void vdt::fast_expfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void vdt::fast_expv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
double vdt::fast_sin (double x) inline
Double precision sine: just call sincos.
Definition at line 39 of file sin.h.
References constant::c, fast_sincos(), and s.
Referenced by mymath::fast_cos(), and mymath::fast_sin().
{
         double s, c;
         fast_sincos(x, s, c);
         return s;
     }
void vdt::fast_sincos (const double xx, double & s, double & c) inline
Double precision sincos.
Definition at line 110 of file sincos.h.
References constant::c, vdt::details::fast_sincos_m45_45(), vdt::details::reduce2quadrant(), and s.
Referenced by fast_sin().
{
         // I have to use doubles to make it vectorise...
         int j;
         double x = details::reduce2quadrant(xx, j);
         const double signS = (j & 4);
         j -= 2;
         const double signC = (j & 4);
         const double poly = j & 2;
         details::fast_sincos_m45_45(x, s, c);
         // swap
         if (poly == 0) {
             const double tmp = c;
             c = s;
             s = tmp;
         }
         if (signC == 0.)
             c = -c;
         if (signS != 0.)
             s = -s;
         if (xx < 0.)
             s = -s;
     }
void vdt::fast_sincosf (const float xx, float & s, float & c) inline
Single precision sincos.
Definition at line 180 of file sincos.h.
References vdt::details::fast_sincosf_m45_45(), and vdt::details::reduce2quadrant().
Referenced by fast_sinf().
{
         int j;
         const float x = details::reduce2quadrant(xx, j);
         int signS = (j & 4);
         j -= 2;
         const int signC = (j & 4);
         const int poly = j & 2;
         float ls, lc;
         details::fast_sincosf_m45_45(x, ls, lc);
         // swap
         if (poly == 0) {
             const float tmp = lc;
             lc = ls;
             ls = tmp;
         }
         if (signC == 0)
             lc = -lc;
         if (signS != 0)
             ls = -ls;
         if (xx < 0)
             ls = -ls;
         c = lc;
         s = ls;
     }
float vdt::fast_sinf (float x) inline
Definition at line 47 of file sin.h.
References constant::c, fast_sincosf(), and s.
{
         float s, c;
         fast_sincosf(x, s, c);
         return s;
     }
void vdt::fast_sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void vdt::fast_sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)
void vdt::sinfv (const uint32_t size, float const *__restrict iarray, float *__restrict oarray)
void vdt::sinv (const uint32_t size, double const *__restrict iarray, double *__restrict oarray)