Beam Longitudinal Dynamics code (BLonD): FullRingAndRf Class Reference
FullRingAndRf Class Reference
#include <Tracker.h>
Public Types
enum main_harmonic_t { lowest_freq = 0, highest_voltage = 1 }
Public Member Functions
FullRingAndRf (std::vector< RingAndRfSection * > &RingList)
~FullRingAndRf ()
void potential_well_generation (const uint turn=0, const uint n_points=100000, const ftype option=lowest_freq, const ftype dt_margin_percent=0.0)
void track ()
Public Attributes
f_vector_t fPotentialWell
f_vector_t fPotentialWellCoordinates
ftype fRingCircumference
std::vector< RingAndRfSection * > fRingList
ftype fRingRadius
f_vector_t fTotalVoltage
Detailed Description
Definition at line 71 of file Tracker.h.
Member Enumeration Documentation
enum FullRingAndRf::main_harmonic_t
Enumerator
lowest_freq
highest_voltage
Definition at line 74 of file Tracker.h.
 { lowest_freq = 0, highest_voltage = 1 };
Constructor & Destructor Documentation
FullRingAndRf::FullRingAndRf (std::vector< RingAndRfSection * > & RingList)
Definition at line 360 of file Tracker.cpp.
References fRingCircumference, fRingList, fRingRadius, and constant::pi.
 {
     fRingList = RingList;
     fRingCircumference = 0;
     for (auto &ring : fRingList)
         fRingCircumference += ring->fRfP->section_length;
     fRingRadius = fRingCircumference / (2 * constant::pi);
 }
FullRingAndRf::~FullRingAndRf ()
Definition at line 371 of file Tracker.cpp.
 {}
Member Function Documentation
void FullRingAndRf::potential_well_generation (const uint turn = 0, const uint n_points = 100000, const ftype option = lowest_freq, const ftype dt_margin_percent = 0.0)
Definition at line 380 of file Tracker.cpp.
References mymath::cum_trapezoid(), mymath::fast_sin(), fPotentialWell, fPotentialWellCoordinates, fRingList, fTotalVoltage, Context::GP, mymath::linspace(), mymath::max(), mymath::min(), constant::pi, and mymath::sign().
Referenced by matched_from_distribution_density(), and matched_from_line_density().
 {
     auto GP = Context::GP;
     f_vector_t voltages;
     f_vector_t omega_rf;
     f_vector_t phi_offsets;
     for (const auto &ring : fRingList) {
         for (uint i = 0; i < ring->fRfP->n_rf; ++i) {
             voltages.push_back(ring->fRfP->voltage[i][turn]);
             omega_rf.push_back(ring->fRfP->omega_RF[i][turn]);
             phi_offsets.push_back(ring->fRfP->phi_RF[i][turn]);
         }
     }
     ftype main_omega_rf;
     if (option == 0) {
         auto k = mymath::min(omega_rf.data(), omega_rf.size());
         main_omega_rf = omega_rf[k];
     } else if (option == 1) {
         auto k = mymath::max(voltages.data(), voltages.size());
         auto maxV = voltages[k];
         f_vector_t temp;
         for (uint i = 0; i < voltages.size(); ++i)
             if (voltages[i] == maxV)
                 temp.push_back(omega_rf[i]);
         k = mymath::min(temp.data(), temp.size());
         main_omega_rf = temp[k];
     } else {
         f_vector_t temp;
         std::copy_if(omega_rf.begin(), omega_rf.end(), back_inserter(temp),
         [option](const ftype x) { return x == option; });
         if (temp.empty()) {
             std::cerr << "[ERROR] The desired harmonic to compute"
                       << "the potential well does not"
                       << "match the RF parameters...\n";
             exit(-1);
         }
         main_omega_rf = option;//temp[k];
     }
     auto time_array_margin =
         dt_margin_percent * 2 * constant::pi / main_omega_rf;
     auto slippage_factor = fRingList[0]->fRfP->eta_0(turn);
     auto first_dt = -time_array_margin / 2;
     auto last_dt = 2 * constant::pi / main_omega_rf + time_array_margin / 2;
     f_vector_t time_array(n_points);
     mymath::linspace(time_array.data(), first_dt, last_dt, n_points);
     fTotalVoltage.resize(time_array.size());
     for (int i = 0; i < (int)time_array.size(); ++i) {
         ftype sum = 0.0;
         for (int j = 0; j < (int)voltages.size(); ++j) {
             sum += voltages[j] * mymath::fast_sin(omega_rf[j] * time_array[i] +
                                                   phi_offsets[j]);
         }
         fTotalVoltage[i] = sum;
     }
     const auto eom_factor_potential =
         mymath::sign(slippage_factor) * GP->charge / GP->t_rev[turn];
     auto tempVec = fTotalVoltage;
     for (int i = 0; i < (int)fTotalVoltage.size(); ++i)
         tempVec[i] =
             eom_factor_potential *
             (tempVec[i] -
              (-fRingList[0]->acceleration_kick[turn]) / std::abs(GP->charge));
     auto tempArr = mymath::cum_trapezoid(
                        tempVec.data(), time_array[1] - time_array[0], n_points);
     std::transform(tempArr.begin(), tempArr.end(), tempArr.begin(),
     [](ftype x) { return -x; });
     auto min_i = mymath::min(tempArr.data(), tempArr.size());
     auto min = tempArr[min_i] > 0 ? 0 : tempArr[min_i];
     fPotentialWell.resize(tempArr.size() + 1);
     fPotentialWell[0] = - min;
     for (uint i = 0; i < tempArr.size(); ++i)
         fPotentialWell[i + 1] = tempArr[i] - min;
     fPotentialWellCoordinates = time_array;
 }
void FullRingAndRf::track ()
Definition at line 373 of file Tracker.cpp.
References fRingList.
 {
     // Loops over all the RingAndRFSection.track methods.
     for (auto &ring : fRingList)
         ring->track();
 }
Member Data Documentation
f_vector_t FullRingAndRf::fPotentialWell
Definition at line 76 of file Tracker.h.
Referenced by matched_from_distribution_density(), matched_from_line_density(), and potential_well_generation().
f_vector_t FullRingAndRf::fPotentialWellCoordinates
Definition at line 77 of file Tracker.h.
Referenced by matched_from_distribution_density(), matched_from_line_density(), and potential_well_generation().
ftype FullRingAndRf::fRingCircumference
Definition at line 79 of file Tracker.h.
Referenced by FullRingAndRf().
std::vector<RingAndRfSection *> FullRingAndRf::fRingList
Definition at line 81 of file Tracker.h.
Referenced by FullRingAndRf(), potential_well_generation(), and track().
ftype FullRingAndRf::fRingRadius
Definition at line 80 of file Tracker.h.
Referenced by FullRingAndRf().
f_vector_t FullRingAndRf::fTotalVoltage
Definition at line 78 of file Tracker.h.
Referenced by potential_well_generation().