Beam Longitudinal Dynamics code (BLonD): plot_slices.h File Reference
plot_slices.h File Reference
#include <blond/input_parameters/GeneralParameters.h>
#include <blond/input_parameters/RfParameters.h>
#include <blond/beams/Slices.h>
Functions
int plot_beam_profile (Slices *Slices, int counter, std::string style="-", std::string dirname="fig")
int plot_beam_profile_derivative (Slices *Slices, int counter, std::string style="-", std::string dirname="fig", string_vector_t modes={"diff"})
int plot_beam_spectrum (Slices *Slices, int counter, std::string style="-", std::string dirname="fig")
Function Documentation
int plot_beam_profile (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig")
Definition at line 5 of file plot_slices.cpp.
References Slices::bin_centers, python::convert_double_array(), python::convert_int(), python::convert_string(), python::import(), and Slices::n_macroparticles.
 {
     // python::initialize();
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_profile");
     auto pBinCenters = python::convert_double_array(Slices->bin_centers.data(),
                        Slices->bin_centers.size());
     auto pNMacropaticles = python::convert_double_array(Slices->n_macroparticles.data(),
                            Slices->n_macroparticles.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBinCenters, pNMacropaticles,
                                             pCounter, pStyle,  pDirname,
                                             NULL);
     return ret != nullptr;
     // python::finalize();
 }
int plot_beam_profile_derivative (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig", string_vector_t modes = {"diff"})
Definition at line 30 of file plot_slices.cpp.
References Slices::beam_profile_derivative(), python::convert_double_2d_array(), python::convert_int(), python::convert_string(), python::convert_string_array(), and python::import().
 {
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_profile_derivative");
     f_vector_2d_t x(modes.size(), f_vector_t());
     f_vector_2d_t derivative(modes.size(), f_vector_t());
     for (uint i = 0; i < modes.size(); i++)
         Slices->beam_profile_derivative(x[i], derivative[i], modes[i]);
     auto pX = python::convert_double_2d_array(x);
     auto pDerivative = python::convert_double_2d_array(derivative);
     auto pModes = python::convert_string_array(modes.data(), modes.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pX, pDerivative, pCounter,
                                             pStyle, pDirname, pModes, NULL);
     return ret != nullptr;
 }
int plot_beam_spectrum (Slices * Slices, int counter, std::string style = "-", std::string dirname = "fig")
Definition at line 58 of file plot_slices.cpp.
References python::convert_complex_array(), python::convert_double_array(), python::convert_int(), python::convert_string(), Slices::fBeamSpectrum, Slices::fBeamSpectrumFreq, and python::import().
 {
     python::import();
     auto pFunc = python::import("plot_slices", "plot_beam_spectrum");
     auto pBeamSpectrumFreq = python::convert_double_array(
                                  Slices->fBeamSpectrumFreq.data(),
                                  Slices->fBeamSpectrumFreq.size());
     auto pBeamSpectrum = python::convert_complex_array(
                              Slices->fBeamSpectrum.data(),
                              Slices->fBeamSpectrum.size());
     auto pCounter = python::convert_int(counter);
     auto pStyle = python::convert_string(style);
     auto pDirname = python::convert_string(dirname);
     auto ret = PyObject_CallFunctionObjArgs(pFunc, pBeamSpectrumFreq,
                                             pBeamSpectrum, pCounter, pStyle,
                                             pDirname, NULL);
     return ret != nullptr;
 }