Beam Longitudinal Dynamics code (BLonD): fft Namespace Reference
fft Namespace Reference
Classes
struct fft_plan_t
Enumerations
enum fft_type_t { FFT, IFFT, RFFT, IRFFT }
Functions
static void complex_to_real (const std::vector< complex_t > &in, std::vector< double > &out)
static void convolution_with_ffts (f_vector_t signal, f_vector_t kernel, f_vector_t &res)
static void destroy_fft (fftw_plan &p)
static void destroy_plans ()
static void fft (complex_vector_t &in, complex_vector_t &out, uint n=0, const uint threads=1)
static fft_plan_t find_plan (uint n, fft_type_t type, uint threads, std::vector< fft_plan_t > &v)
static void ifft (complex_vector_t &in, complex_vector_t &out, uint n=0, const uint threads=1)
static fftw_plan init_fft (const int n, complex_t *in, complex_t *out, const int sign=FFTW_FORWARD, const unsigned flag=FFTW_ESTIMATE, const int threads=1)
static fftw_plan init_irfft (const int n, complex_t *in, double *out, const unsigned flag=FFTW_ESTIMATE, const int threads=1)
static fftw_plan init_rfft (const int n, double *in, complex_t *out, const unsigned flag=FFTW_ESTIMATE, const int threads=1)
static void irfft (complex_vector_t in, f_vector_t &out, uint n=0, const uint threads=1)
static void pack_to_complex (const std::vector< double > &in, std::vector< complex_t > &out)
static void real_to_complex (const std::vector< double > &in, std::vector< complex_t > &out)
static void rfft (f_vector_t &in, complex_vector_t &out, uint n=0, const uint threads=1)
static f_vector_t rfftfreq (const uint n, const double d=1.0)
static void run_fft (const fftw_plan &p)
static void unpack_complex (const std::vector< complex_t > &in, std::vector< double > &out)
Variables
const uint FFTW_FLAGS = FFTW_ESTIMATE | FFTW_DESTROY_INPUT
static std::vector
< fft::fft_plan_t > planV
Enumeration Type Documentation
enum fft::fft_type_t
Enumerator
FFT
IFFT
RFFT
IRFFT
Definition at line 40 of file fft.h.
 { FFT, IFFT, RFFT, IRFFT };
Function Documentation
static void fft::complex_to_real (const std::vector< complex_t > & in, std::vector< double > & out) inline static
Definition at line 73 of file fft.h.
     {
         assert(out.empty());
         out.reserve(in.size());
         for (const auto &z : in)
             out.push_back(z.real());
     }
static void fft::convolution_with_ffts (f_vector_t signal, f_vector_t kernel, f_vector_t & res) inline static
Definition at line 354 of file fft.h.
References irfft(), omp_get_max_threads(), and rfft().
Referenced by InducedVoltageTime::induced_voltage_generation().
     {
         complex_vector_t v1; //(signal.size());
         complex_vector_t v2; //(kernel.size());
         const long unsigned size = signal.size() + kernel.size() - 1;
         res.resize(size);
         fft::rfft(signal, v1, size, omp_get_max_threads());
         fft::rfft(kernel, v2, size, omp_get_max_threads());
         std::transform(v1.begin(), v1.end(), v2.begin(), v1.begin(),
                        std::multiplies<complex_t>());
         fft::irfft(v1, res, size, omp_get_max_threads());
     }
static void fft::destroy_fft (fftw_plan & p) inline static
Definition at line 151 of file fft.h.
 { fftw_destroy_plan(p); }
static void fft::destroy_plans () inline static
Definition at line 153 of file fft.h.
References planV.
Referenced by InducedVoltageFreq::~InducedVoltageFreq(), InducedVoltageTime::~InducedVoltageTime(), LHCFlatSpectrum::~LHCFlatSpectrum(), PSBPhaseNoiseInjection::~PSBPhaseNoiseInjection(), Slices::~Slices(), and TotalInducedVoltage::~TotalInducedVoltage().
     {
         // std::cout<<"planV size = " << planV.size()<<"\n";
         for (auto &i : planV) {
             fftw_destroy_plan(i.p);
             fftw_free(i.in);
             fftw_free(i.out);
         }
         planV.clear();
     }
static void fft::fft (complex_vector_t & in, complex_vector_t & out, uint n = 0, const uint threads = 1) inline static
Definition at line 272 of file fft.h.
References FFT, find_plan(), planV, and run_fft().
Referenced by PhaseNoise::spectrum_to_phase_noise().
     {
         if (n == 0)
             n = in.size();
         out.resize(n);
         auto plan = fft::find_plan(n, FFT, threads, planV);
         auto from = (complex_t *)plan.in;
         auto to = (complex_t *)plan.out;
         std::copy(in.begin(), in.end(), from);
         run_fft(plan.p);
         std::copy(&to[0], &to[n], out.begin());
     }
static fft_plan_t fft::find_plan (uint n, fft_type_t type, uint threads, std::vector< fft_plan_t > & v) inline static
Definition at line 166 of file fft.h.
References FFT, FFTW_FLAGS, IFFT, fft::fft_plan_t::in, init_fft(), init_irfft(), init_rfft(), IRFFT, fft::fft_plan_t::n, fft::fft_plan_t::out, fft::fft_plan_t::p, RFFT, and fft::fft_plan_t::type.
Referenced by fft(), ifft(), irfft(), and rfft().
     {
         const uint flag = FFTW_FLAGS;
         auto it =
         std::find_if(v.begin(), v.end(), [n, type](const fft_plan_t &s) {
             return ((s.n == n) && (s.type == type));
         });
         if (it == v.end()) {
             // std::cout << "I have to create a new plan :(\n";
             fft_plan_t plan;
             plan.n = n;
             plan.type = type;
             if (type == FFT) {
                 fftw_complex *in =
                     (fftw_complex *)fftw_malloc(sizeof(fftw_complex) * n);
                 fftw_complex *out =
                     (fftw_complex *)fftw_malloc(sizeof(fftw_complex) * n);
                 auto p = init_fft(n, reinterpret_cast<complex_t *>(in),
                                   reinterpret_cast<complex_t *>(out),
                                   FFTW_FORWARD, flag, threads);
                 plan.p = p;
                 plan.in = in;
                 plan.out = out;
             } else if (type == IFFT) {
                 fftw_complex *in =
                     (fftw_complex *)fftw_malloc(sizeof(fftw_complex) * n);
                 fftw_complex *out =
                     (fftw_complex *)fftw_malloc(sizeof(fftw_complex) * n);
                 auto p = init_fft(n, reinterpret_cast<complex_t *>(in),
                                   reinterpret_cast<complex_t *>(out),
                                   FFTW_BACKWARD, flag, threads);
                 plan.p = p;
                 plan.in = in;
                 plan.out = out;
             } else if (type == RFFT) {
                 double *in = (double *)fftw_malloc(sizeof(double) * n);
                 fftw_complex *out = (fftw_complex *)fftw_malloc(
                                         sizeof(fftw_complex) * (n / 2 + 1));
                 auto p = init_rfft(n, in, reinterpret_cast<complex_t *>(out),
                                    flag, threads);
                 // std::cout << "threads : " << threads << "\n";
                 plan.p = p;
                 plan.in = in;
                 plan.out = out;
             } else if (type == IRFFT) {
                 double *out = (double *)fftw_malloc(sizeof(double) * n);
                 fftw_complex *in = (fftw_complex *)fftw_malloc(
                                        sizeof(fftw_complex) * (n / 2 + 1));
                 auto p = init_irfft(n, reinterpret_cast<complex_t *>(in), out,
                                     flag, threads);
                 plan.p = p;
                 plan.in = in;
                 plan.out = out;
             } else {
                 std::cerr << "[fft::find_plan]: ERROR "
                           << "Wrong fft type!\n";
                 exit(-1);
             }
             v.push_back(plan);
             // planV.push_back(plan);
             return plan;
         } else {
             return *it;
         }
     }
static void fft::ifft (complex_vector_t & in, complex_vector_t & out, uint n = 0, const uint threads = 1) inline static
Definition at line 296 of file fft.h.
References find_plan(), IFFT, planV, and run_fft().
Referenced by PhaseNoise::spectrum_to_phase_noise().
     {
         if (n == 0)
             n = in.size();
         out.resize(n);
         auto plan = fft::find_plan(n, IFFT, threads, planV);
         auto from = (complex_t *)plan.in;
         auto to = (complex_t *)plan.out;
         std::copy(in.begin(), in.end(), from);
         run_fft(plan.p);
         std::transform(&to[0], &to[n], out.begin(),
                        std::bind2nd(std::divides<complex_t>(), n));
     }
static fftw_plan fft::init_fft (const int n, complex_t * in, complex_t * out, const int sign = FFTW_FORWARD, const unsigned flag = FFTW_ESTIMATE, const int threads = 1) inline static
Definition at line 94 of file fft.h.
References mymath::sign().
Referenced by find_plan().
     {
 #ifdef USE_FFTW_OMP
         if (threads > 1) {
             fftw_init_threads();
             fftw_plan_with_nthreads(threads);
             // std::min(
             //     threads,
             //     (int)((n + ELEMS_PER_THREAD_FFT - 1) / ELEMS_PER_THREAD_FFT)));
         }
 #endif
         fftw_complex *a, *b;
         a = reinterpret_cast<fftw_complex *>(in);
         b = reinterpret_cast<fftw_complex *>(out);
         return fftw_plan_dft_1d(n, a, b, sign, flag);
     }
static fftw_plan fft::init_irfft (const int n, complex_t * in, double * out, const unsigned flag = FFTW_ESTIMATE, const int threads = 1) inline static
Definition at line 132 of file fft.h.
Referenced by find_plan().
     {
 #ifdef USE_FFTW_OMP
         if (threads > 1) {
             fftw_init_threads();
             fftw_plan_with_nthreads(threads);
             // std::min(threads, (int)((n + ELEMS_PER_THREAD_FFT - 1) /
             //                         ELEMS_PER_THREAD_FFT)));
         }
 #endif
         fftw_complex *b;
         b = reinterpret_cast<fftw_complex *>(in);
         return fftw_plan_dft_c2r_1d(n, b, out, flag);
     }
static fftw_plan fft::init_rfft (const int n, double * in, complex_t * out, const unsigned flag = FFTW_ESTIMATE, const int threads = 1) inline static
Definition at line 114 of file fft.h.
Referenced by find_plan().
     {
 #ifdef USE_FFTW_OMP
         if (threads > 1) {
             fftw_init_threads();
             fftw_plan_with_nthreads(threads);
             // std::min(threads, (int)((n + ELEMS_PER_THREAD_RFFT - 1) /
             //                         ELEMS_PER_THREAD_RFFT)));
         }
 #endif
         fftw_complex *b;
         b = reinterpret_cast<fftw_complex *>(out);
         return fftw_plan_dft_r2c_1d(n, in, b, flag);
     }
static void fft::irfft (complex_vector_t in, f_vector_t & out, uint n = 0, const uint threads = 1) inline static
Definition at line 319 of file fft.h.
References find_plan(), IRFFT, planV, and run_fft().
Referenced by convolution_with_ffts(), InducedVoltageFreq::induced_voltage_generation(), and PhaseNoise::spectrum_to_phase_noise().
     {
         n = (n == 0) ? 2 * (in.size() - 1) : n;
         // std::cout << "out size will be " << n << "\n";
         out.resize(n);
         auto plan = fft::find_plan(n, IRFFT, threads, planV);
         auto from = (complex_t *)plan.in;
         auto to = (double *)plan.out;
         std::copy(in.begin(), in.end(), from);
         run_fft(plan.p);
         std::transform(&to[0], &to[n], out.begin(),
                        std::bind2nd(std::divides<double>(), n));
     }
static void fft::pack_to_complex (const std::vector< double > & in, std::vector< complex_t > & out) inline static
Definition at line 63 of file fft.h.
     {
         assert(out.empty());
         assert(in.size() % 2 == 0);
         out.reserve(in.size() / 2);
         for (unsigned int i = 0; i < in.size(); i += 2)
             out.push_back(complex_t(in[i], in[i + 1]));
     }
static void fft::real_to_complex (const std::vector< double > & in, std::vector< complex_t > & out) inline static
Definition at line 54 of file fft.h.
     {
         assert(out.empty());
         out.reserve(in.size());
         for (const auto &real : in)
             out.push_back(complex_t(real, 0));
     }
static void fft::rfft (f_vector_t & in, complex_vector_t & out, uint n = 0, const uint threads = 1) inline static
Definition at line 246 of file fft.h.
References find_plan(), planV, RFFT, and run_fft().
Referenced by Slices::beam_spectrum_generation(), convolution_with_ffts(), and PhaseNoise::spectrum_to_phase_noise().
     {
         if (n == 0)
             n = in.size();
         else
             in.resize(n);
         out.resize(n / 2 + 1);
         auto plan = fft::find_plan(n, RFFT, threads, planV);
         auto from = (double *)plan.in;
         auto to = (complex_t *)plan.out;
         std::copy(in.begin(), in.end(), from);
         run_fft(plan.p);
         std::copy(&to[0], &to[n / 2 + 1], out.begin());
     }
static f_vector_t fft::rfftfreq (const uint n, const double d = 1.0) inline static
Definition at line 342 of file fft.h.
Referenced by Slices::beam_spectrum_generation(), and InducedVoltageFreq::InducedVoltageFreq().
     {
         f_vector_t v(n / 2 + 1);
         const double factor = 1.0 / (d * n);
         #pragma omp parallel for
         for (int i = 0; i < (int)v.size(); ++i) {
             v[i] = i * factor;
         }
         return v;
     }
static void fft::run_fft (const fftw_plan & p) inline static
Definition at line 149 of file fft.h.
Referenced by fft(), ifft(), irfft(), and rfft().
 { fftw_execute(p); }
static void fft::unpack_complex (const std::vector< complex_t > & in, std::vector< double > & out) inline static
Definition at line 82 of file fft.h.
     {
         assert(out.empty());
         out.reserve(2 * in.size());
         for (const auto &z : in) {
             out.push_back(z.real());
             out.push_back(z.imag());
         }
     }
Variable Documentation
const uint fft::FFTW_FLAGS = FFTW_ESTIMATE | FFTW_DESTROY_INPUT
Definition at line 35 of file fft.h.
Referenced by find_plan().
std::vector<fft::fft_plan_t> fft::planV static
Definition at line 50 of file fft.h.
Referenced by destroy_plans(), fft(), ifft(), irfft(), and rfft().