Beam Longitudinal Dynamics code (BLonD): blond::TotalInducedVoltage Class Reference
blond::TotalInducedVoltage Class Reference
#include <InducedVoltage.h>
Public Member Functions
TotalInducedVoltage (Beams *beam, Slices *slices, const std::vector< InducedVoltage * > &InducedVoltageList, int NTurnsMemory=0, f_vector_t RevTimeArray=f_vector_t())
~TotalInducedVoltage ()
f_vector_t induced_voltage_generation (Beams *beam, int length=0)
f_vector_t induced_voltage_sum (Beams *beam, int length=0)
void reprocess (Slices *newSlices)
void track (Beams *beam)
void track_ghosts_particles (Beams *ghostBeam)
void track_memory ()
Public Member Functions inherited from blond::InducedVoltage
InducedVoltage ()
virtual ~InducedVoltage ()
Public Attributes
Beams * fBeam
int fCounterTurn = 0
std::vector< InducedVoltage * > fInducedVoltageList
bool fInductiveImpedanceOn = false
int fNTurnsMemory
f_vector_t fRevTimeArray
f_vector_t fTimeArray
Public Attributes inherited from blond::InducedVoltage
f_vector_t fInducedVoltage
Slices * fSlices
Detailed Description
Definition at line 119 of file InducedVoltage.h.
Constructor & Destructor Documentation
TotalInducedVoltage::TotalInducedVoltage (Beams * beam, Slices * slices, const std::vector< InducedVoltage * > & InducedVoltageList, int NTurnsMemory = 0, f_vector_t RevTimeArray = f_vector_t())
Definition at line 403 of file InducedVoltage.cpp.
References blond::Slices::bin_centers, fBeam, blond::InducedVoltage::fInducedVoltage, fInducedVoltageList, fNTurnsMemory, blond::InducedVoltage::fSlices, and fTimeArray.
 {
     fBeam = beam;
     fSlices = slices;
     fInducedVoltageList = InducedVoltageList;
     fNTurnsMemory = NTurnsMemory;
     fInducedVoltage = f_vector_t();
     fTimeArray = fSlices->bin_centers;
 }
TotalInducedVoltage::~TotalInducedVoltage ()
Definition at line 416 of file InducedVoltage.cpp.
References blond::fft::destroy_plans().
 { fft::destroy_plans(); }
Member Function Documentation
f_vector_t blond::TotalInducedVoltage::induced_voltage_generation (Beams * beam, int length = 0) inline virtual
Implements blond::InducedVoltage.
Definition at line 136 of file InducedVoltage.h.
         {
             return f_vector_t();
         };
f_vector_t TotalInducedVoltage::induced_voltage_sum (Beams * beam, int length = 0)
Definition at line 441 of file InducedVoltage.cpp.
References blond::InducedVoltage::fInducedVoltage, and fInducedVoltageList.
Referenced by blond::matched_from_distribution_density(), and track().
 {
     // Method to sum all the induced voltages in one single array.
     f_vector_t tempIndVolt;
     f_vector_t extIndVolt;
     for (auto &v : fInducedVoltageList) {
         auto a = v->induced_voltage_generation(beam, length);
         if (length > 0) {
             extIndVolt.resize(a.size(), 0);
             extIndVolt += a;
         }
         tempIndVolt.resize(v->fInducedVoltage.size(), 0);
         tempIndVolt += v->fInducedVoltage;
     }
     fInducedVoltage = tempIndVolt;
     return extIndVolt;
 }
void TotalInducedVoltage::reprocess (Slices * newSlices) virtual
Implements blond::InducedVoltage.
Definition at line 433 of file InducedVoltage.cpp.
References fInducedVoltageList, and blond::InducedVoltage::fSlices.
Referenced by blond::matched_from_distribution_density(), and blond::matched_from_line_density().
 {
     fSlices = newSlices;
     for (auto &v : fInducedVoltageList)
         v->reprocess(newSlices);
 }
void TotalInducedVoltage::track (Beams * beam) virtual
Implements blond::InducedVoltage.
Definition at line 418 of file InducedVoltage.cpp.
References blond::Slices::bin_centers, blond::Beams::charge, blond::Beams::dE, blond::Beams::dt, blond::InducedVoltage::fInducedVoltage, blond::InducedVoltage::fSlices, induced_voltage_sum(), blond::linear_interp_kick(), blond::Beams::n_macroparticles, and blond::Slices::n_slices.
 {
     this->induced_voltage_sum(beam);
     auto v = this->fInducedVoltage * beam->charge;
     linear_interp_kick(beam->dt.data(), beam->dE.data(), v.data(),
                        fSlices->bin_centers.data(), fSlices->n_slices,
                        beam->n_macroparticles);
 }
void TotalInducedVoltage::track_ghosts_particles (Beams * ghostBeam)
Definition at line 431 of file InducedVoltage.cpp.
 {}
void TotalInducedVoltage::track_memory ()
Definition at line 429 of file InducedVoltage.cpp.
 {}
Member Data Documentation
Beams* blond::TotalInducedVoltage::fBeam
Definition at line 128 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().
int blond::TotalInducedVoltage::fCounterTurn = 0
Definition at line 124 of file InducedVoltage.h.
std::vector<InducedVoltage *> blond::TotalInducedVoltage::fInducedVoltageList
Definition at line 121 of file InducedVoltage.h.
Referenced by induced_voltage_sum(), reprocess(), and TotalInducedVoltage().
bool blond::TotalInducedVoltage::fInductiveImpedanceOn = false
Definition at line 126 of file InducedVoltage.h.
int blond::TotalInducedVoltage::fNTurnsMemory
Definition at line 125 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().
f_vector_t blond::TotalInducedVoltage::fRevTimeArray
Definition at line 123 of file InducedVoltage.h.
f_vector_t blond::TotalInducedVoltage::fTimeArray
Definition at line 122 of file InducedVoltage.h.
Referenced by TotalInducedVoltage().