Beam Longitudinal Dynamics code (BLonD): mymath Namespace Reference
mymath Namespace Reference
Classes
class Ham
Functions
template<typename T >
static std::vector< T > arange (T start, T stop, T step=1)
static void convolution (const double *__restrict signal, const int SignalLen, const double *__restrict kernel, const int KernelLen, double *__restrict res)
template<typename T >
static f_vector_t cum_trapezoid (const T *f, const T deltaX, const int nsub)
template<typename T >
static f_vector_t cum_trapezoid (const T *f, const T deltaX, const T initial, const int nsub)
template<typename T >
static f_vector_t cum_trapezoid (const std::vector< T > &f, const T deltaX)
template<typename T >
static f_vector_t cum_trapezoid (const std::vector< T > &f, const T deltaX, const T initial)
static double fast_cos (double x)
static double fast_exp (double x)
static double fast_sin (double x)
template<typename T >
static std::vector< T > flatten (const std::vector< std::vector< T > > &a)
static void interp (const std::vector< double > &x, const std::vector< double > &xp, const std::vector< double > &yp, std::vector< double > &y, const double left, const double right)
static void interp (const std::vector< double > &x, const std::vector< double > &xp, const std::vector< double > &yp, std::vector< double > &y)
static f_vector_t interp (const f_vector_t &x, const f_vector_t &xp, const f_vector_t &yp)
static f_vector_t interp (const f_vector_t &x, const f_vector_t &xp, const f_vector_t &yp, const double left, const double right)
static void linspace (double *a, const double start, const double end, const int n, const int keep_from=0)
static f_vector_t linspace (const double start, const double end, const int n)
template<typename T >
static uint max (T *a, uint size, uint step=1)
template<typename T >
static double mean (const T data[], const int n)
template<typename T >
static double mean (const std::vector< T > data)
template<typename T >
static void meshgrid (const std::vector< T > &in1, const std::vector< T > &in2, std::vector< std::vector< T > > &out1, std::vector< std::vector< T > > &out2)
template<typename T >
static uint min (T *a, uint size, uint step=1)
static uint next_regular (uint target)
template<typename T >
static std::vector< T > random_choice (const std::vector< T > &elems, const int size, std::vector< double > weights=std::vector< double >())
template<typename T >
int sign (const T val)
template<typename T >
static double standard_deviation (const T data[], const int n, const double mean)
template<typename T >
static double standard_deviation (const std::vector< T > data, const double mean)
template<typename T >
static double standard_deviation (const T data[], const int n)
template<typename T >
static double standard_deviation (const std::vector< T > data)
template<typename T >
static double sum (const T data[], const int n)
template<typename T >
static double sum (const std::vector< T > &data)
template<typename T >
static double trapezoid (const T *f, const double *deltaX, const int nsub)
template<typename T >
static double trapezoid (const std::vector< T > &f, const std::vector< double > &deltaX)
template<typename T >
static double trapezoid (const T *f, const double deltaX, const int nsub)
template<typename T >
static double trapezoid (const std::vector< T > &f, const double deltaX)
Function Documentation
template<typename T > static std::vector<T> mymath::arange (T start, T stop, T step = 1) inline static
Definition at line 327 of file math_functions.h.
Referenced by matched_from_distribution_density(), and matched_from_line_density().
     {
         std::vector<T> values;
         for (T value = start; value < stop; value += step)
             values.push_back(value);
         return values;
     }
static void mymath::convolution (const double *__restrict signal, const int SignalLen, const double *__restrict kernel, const int KernelLen, double *__restrict res) inline static
Definition at line 71 of file math_functions.h.
Referenced by InducedVoltageTime::induced_voltage_generation().
     {
         const int size = KernelLen + SignalLen - 1;
         #pragma omp parallel for
         for (auto n = 0; n < size; ++n) {
             res[n] = 0;
             const int kmin = (n >= KernelLen - 1) ? n - (KernelLen - 1) : 0;
             const int kmax = (n < SignalLen - 1) ? n : SignalLen - 1;
             for (int k = kmin; k <= kmax; k++) {
                 res[n] += signal[k] * kernel[n - k];
                 //--j;
             }
         }
     }
template<typename T > static f_vector_t mymath::cum_trapezoid (const T * f, const T deltaX, const int nsub) inline static
Definition at line 166 of file math_functions.h.
Referenced by RfParameters::calc_phi_s(), matched_from_distribution_density(), matched_from_line_density(), and FullRingAndRf::potential_well_generation().
     {
         // initialize the partial sum to be f(a)+f(b) and
         // deltaX to be the step size using nsub subdivisions
         // double *psum = new double[nsub];
         f_vector_t psum(nsub - 1);
         // psum[0] = 0;
         const auto half_dx = deltaX / 2.0;
         psum[0] = (f[1] + f[0]) * half_dx;
         // increment the partial sum
         // #pragma omp parallel for
         for (int i = 1; i < nsub - 1; ++i)
             psum[i] = psum[i - 1] + (f[i + 1] + f[i]) * half_dx;
         return psum;
     }
template<typename T > static f_vector_t mymath::cum_trapezoid (const T * f, const T deltaX, const T initial, const int nsub) inline static
Definition at line 188 of file math_functions.h.
     {
         // initialize the partial sum to be f(a)+f(b) and
         // deltaX to be the step size using nsub subdivisions
         // double *psum = new double[nsub];
         f_vector_t psum(nsub);
         const auto half_dx = deltaX / 2.0;
         psum[0] = initial;
         psum[1] = (f[1] + f[0]) * half_dx;
         // increment the partial sum
         for (int i = 2; i < nsub; ++i)
             psum[i] = psum[i - 1] + (f[i] + f[i - 1]) * half_dx;
         return psum;
     }
template<typename T > static f_vector_t mymath::cum_trapezoid (const std::vector< T > & f, const T deltaX) inline static
Definition at line 209 of file math_functions.h.
     {
         return cum_trapezoid<T>(f.data(), deltaX, f.size());
     }
template<typename T > static f_vector_t mymath::cum_trapezoid (const std::vector< T > & f, const T deltaX, const T initial) inline static
Definition at line 216 of file math_functions.h.
     {
         return cum_trapezoid<T>(f.data(), deltaX, initial, f.size());
     }
static double mymath::fast_cos (double x) inline static
Definition at line 66 of file math_functions.h.
References vdt::fast_sin().
Referenced by hamiltonian().
 { return vdt::fast_sin(x + M_PI_2); }
static double mymath::fast_exp (double x) inline static
Definition at line 68 of file math_functions.h.
References vdt::fast_exp().
 { return vdt::fast_exp(x); }
static double mymath::fast_sin (double x) inline static
Definition at line 64 of file math_functions.h.
References vdt::fast_sin().
Referenced by hamiltonian(), RingAndRfSection::kick(), and FullRingAndRf::potential_well_generation().
 { return vdt::fast_sin(x); }
template<typename T > static std::vector<T> mymath::flatten (const std::vector< std::vector< T > > & a) inline static
Definition at line 421 of file math_functions.h.
References FOR.
Referenced by matched_from_distribution_density(), and matched_from_line_density().
     {
         std::vector<T> result;
         FOR(a, row) {
             result.insert(result.end(), (*row).begin(), (*row).end());
         }
         return result;
     }
static void mymath::interp (const std::vector< double > & x, const std::vector< double > & xp, const std::vector< double > & yp, std::vector< double > & y, const double left, const double right) inline static
Definition at line 98 of file math_functions.h.
References max(), and min().
Referenced by Slices::beam_profile_derivative(), InputTable::imped_calc(), interp(), matched_from_distribution_density(), matched_from_line_density(), minmax_location(), and InputTable::wake_calc().
     {
         assert(xp.size() == yp.size());
         assert(std::is_sorted(xp.begin(), xp.end()));
         y.resize(x.size());
         const int M = xp.size();
         const int N = x.size();
         if (N == 0) return;
         const auto max = xp.back();
         const auto min = xp.front();
         // #pragma omp parallel for
         for (int i = 0; i < N; ++i) {
             int pos = std::lower_bound(xp.begin(), xp.end(), x[i]) - xp.begin();
             if (pos == M)
                 y[i] = right;
             else if (xp[pos] == x[i])
                 y[i] = yp[pos];
             else if (pos == 0)
                 y[i] = left;
             else {
                 y[i] = yp[pos - 1] +
                        (yp[pos] - yp[pos - 1]) * (x[i] - xp[pos - 1]) /
                        (xp[pos] - xp[pos - 1]);
             }
         }
     }
static void mymath::interp (const std::vector< double > & x, const std::vector< double > & xp, const std::vector< double > & yp, std::vector< double > & y) inline static
Definition at line 133 of file math_functions.h.
References interp().
     {
         auto left = yp.front();
         auto right = yp.back();
         interp(x, xp, yp, y, left, right);
     }
static f_vector_t mymath::interp (const f_vector_t & x, const f_vector_t & xp, const f_vector_t & yp) inline static
Definition at line 143 of file math_functions.h.
References interp().
     {
         f_vector_t res;
         interp(x, xp, yp, res);
         return res;
     }
static f_vector_t mymath::interp (const f_vector_t & x, const f_vector_t & xp, const f_vector_t & yp, const double left, const double right) inline static
Definition at line 152 of file math_functions.h.
References interp().
     {
         f_vector_t res;
         interp(x, xp, yp, res, left, right);
         return res;
     }
static void mymath::linspace (double * a, const double start, const double end, const int n, const int keep_from = 0) inline static
Definition at line 305 of file math_functions.h.
Referenced by RfParameters::calc_phi_s(), LHCFlatSpectrum::generate(), PSBPhaseNoiseInjection::generate(), linspace(), matched_from_distribution_density(), matched_from_line_density(), FullRingAndRf::potential_well_generation(), Slices::set_cuts(), PhaseNoise::spectrum_generation(), and PhaseNoise::spectrum_to_phase_noise().
     {
         const double step = (end - start) / (n - 1);
         // double value = start;
         //#pragma omp parallel for
         for (int i = 0; i < n; ++i) {
             if (i >= keep_from)
                 a[i - keep_from] = start + i * step;
             // value += step;
         }
     }
static f_vector_t mymath::linspace (const double start, const double end, const int n) inline static
Definition at line 318 of file math_functions.h.
References linspace().
     {
         f_vector_t res(n);
         linspace(res.data(), start, end, n);
         return res;
     }
template<typename T > static uint mymath::max (T * a, uint size, uint step = 1) inline static
Definition at line 291 of file math_functions.h.
Referenced by Slices::fwhm(), LHCNoiseFB::fwhm_single_bunch(), Slices::gaussian_fit(), interp(), matched_from_line_density(), and LHCNoiseFB::track().
     {
         uint p = 0;
         T max = a[0];
         //#pragma omp parallel for shared(p) reduction(max : max)
         for (uint i = 1; i < size; i += step) {
             if (a[i] > max) {
                 max = a[i];
                 p = i;
             }
         }
         return p;
     }
template<typename T > static double mymath::mean (const T data[], const int n) inline static
Definition at line 353 of file math_functions.h.
References sum().
Referenced by LHCNoiseFB::fwhm_multi_bunch(), Slices::gaussian_fit(), mean(), Slices::set_cuts(), and standard_deviation().
     {
         return sum(data, n) / n;
     }
template<typename T > static double mymath::mean (const std::vector< T > data) inline static
Definition at line 359 of file math_functions.h.
References mean().
     {
         return mean(data.data(), data.size());
     }
template<typename T > static void mymath::meshgrid (const std::vector< T > & in1, const std::vector< T > & in2, std::vector< std::vector< T > > & out1, std::vector< std::vector< T > > & out2) inline static
Definition at line 406 of file math_functions.h.
References constant::e, and FOR.
Referenced by matched_from_distribution_density(), and matched_from_line_density().
     {
         out1.clear();
         out1.resize(in2.size(), in1);
         out2.clear();
         const int cols = in1.size();
         FOR(in2, e) out2.push_back(std::vector<T>(cols, *e));
     }
template<typename T > static uint mymath::min (T * a, uint size, uint step = 1) inline static
Definition at line 276 of file math_functions.h.
Referenced by RfParameters::calc_phi_s(), Slices::histogram(), interp(), potential_well_cut(), and LHCNoiseFB::track().
     {
         uint p = 0;
         T min = a[0];
         //#pragma omp parallel for  shared(p) reduction(min : min)
         for (uint i = 1; i < size; i += step) {
             if (a[i] < min) {
                 min = a[i];
                 p = i;
             }
         }
         return p;
     }
static uint mymath::next_regular (uint target) inline static
Definition at line 53 of file math_functions.h.
Referenced by PSBPhaseNoiseInjection::generate(), InducedVoltageFreq::InducedVoltageFreq(), InducedVoltageTime::InducedVoltageTime(), InducedVoltageTime::reprocess(), and InducedVoltageFreq::reprocess().
     {
         for (auto i : Ham({2, 3, 5})) {
             if (i > target)
                 return i;
         }
         return 0;
     }
template<typename T > static std::vector<T> mymath::random_choice (const std::vector< T > & elems, const int size, std::vector< double > weights = std::vector<double>()) inline static
Definition at line 431 of file math_functions.h.
References ALL.
Referenced by matched_from_distribution_density(), and matched_from_line_density().
     {
         if (weights.empty()) weights.resize(elems.size(), 1);
         assert(weights.size() == elems.size());
         // calculate cumulative sum
         for (uint i = 1; i < weights.size(); i++) {
             weights[i] += weights[i - 1];
         }
         std::default_random_engine gen(0);
         std::uniform_real_distribution<double> d(0.0, weights.back());
         std::vector<T> result(size);
         for (int i = 0; i < size; i++) {
             auto w = d(gen);
             auto it = std::lower_bound(ALL(weights), w);
             result[i] = elems[it - weights.begin()];
         }
         return result;
     }
template<typename T > int mymath::sign (const T val)
Definition at line 399 of file math_functions.h.
Referenced by fft::init_fft(), matched_from_distribution_density(), matched_from_line_density(), FullRingAndRf::potential_well_generation(), RfParameters::RfParameters(), and Resonators::wake_calc().
     {
         return (T(0) < val) - (val < T(0));
     }
template<typename T > static double mymath::standard_deviation (const T data[], const int n, const double mean) inline static
Definition at line 365 of file math_functions.h.
References mean().
Referenced by Slices::gaussian_fit(), LHCFlatSpectrum::generate(), PSBPhaseNoiseInjection::generate(), Slices::set_cuts(), and standard_deviation().
     {
         double sum_deviation = 0.0;
         #pragma omp parallel for reduction(+ : sum_deviation)
         for (int i = 0; i < n; ++i)
             sum_deviation += (data[i] - mean) * (data[i] - mean);
         return std::sqrt(sum_deviation / n);
     }
template<typename T > static double mymath::standard_deviation (const std::vector< T > data, const double mean) inline static
Definition at line 376 of file math_functions.h.
References mean(), and standard_deviation().
     {
         return standard_deviation(data.data(), data.size(), mean);
     }
template<typename T > static double mymath::standard_deviation (const T data[], const int n) inline static
Definition at line 383 of file math_functions.h.
References mean().
     {
         const double mean = mymath::mean(data, n);
         double sum_deviation = 0.0;
         #pragma omp parallel for reduction(+ : sum_deviation)
         for (int i = 0; i < n; ++i)
             sum_deviation += (data[i] - mean) * (data[i] - mean);
         return std::sqrt(sum_deviation / n);
     }
template<typename T > static double mymath::standard_deviation (const std::vector< T > data) inline static
Definition at line 394 of file math_functions.h.
References standard_deviation().
     {
         return standard_deviation(data.data(), data.size());
     }
template<typename T > static double mymath::sum (const T data[], const int n) inline static
Definition at line 336 of file math_functions.h.
Referenced by InducedVoltageFreq::induced_voltage_generation(), matched_from_distribution_density(), matched_from_line_density(), mean(), FullRingAndRf::potential_well_generation(), PhaseLoop::radial_difference(), RingAndRfSection::rf_voltage_calculation(), and sum().
     {
         double m = 0.0;
         #pragma omp parallel for reduction(+ : m)
         for (int i = 0; i < n; ++i) {
             m += data[i];
         }
         return m;
     }
template<typename T > static double mymath::sum (const std::vector< T > & data) inline static
Definition at line 347 of file math_functions.h.
References sum().
     {
         return sum(data.data(), data.size());
     }
template<typename T > static double mymath::trapezoid (const T * f, const double * deltaX, const int nsub) inline static
Definition at line 225 of file math_functions.h.
Referenced by PhaseLoop::beam_phase(), matched_from_distribution_density(), matched_from_line_density(), and Slices::rms().
     {
         // initialize the partial sum to be f(a)+f(b) and
         // deltaX to be the step size using nsub subdivisions
         double psum = 0.0;
 // increment the partial sum
         #pragma omp parallel for reduction(+ : psum)
         for (int i = 1; i < nsub; ++i) {
             psum += (f[i] + f[i - 1]) * (deltaX[i] - deltaX[i - 1]);
         }
         // return approximation
         return psum / 2;
     }
template<typename T > static double mymath::trapezoid (const std::vector< T > & f, const std::vector< double > & deltaX) inline static
Definition at line 242 of file math_functions.h.
     {
         return trapezoid<T>(f.data(), deltaX.data(), f.size());
     }
template<typename T > static double mymath::trapezoid (const T * f, const double deltaX, const int nsub) inline static
Definition at line 249 of file math_functions.h.
     {
         // initialize the partial sum to be f(a)+f(b) and
         // deltaX to be the step size using nsub subdivisions
         double psum = f[0] + f[nsub - 1]; // f(a)+f(b);
 // double deltaX = (b-a)/nsub;
 // increment the partial sum
         #pragma omp parallel for reduction(+ : psum)
         for (int i = 1; i < nsub - 1; ++i) {
             psum += 2 * f[i];
         }
         // multiply the sum by the constant deltaX/2.0
         psum = (deltaX / 2) * psum;
         // return approximation
         return psum;
     }
template<typename T > static double mymath::trapezoid (const std::vector< T > & f, const double deltaX) inline static
Definition at line 270 of file math_functions.h.
     {
         return trapezoid<T>(f.data(), deltaX, f.size());
     }