Beam Longitudinal Dynamics code (BLonD): InducedVoltage.cpp File Reference
InducedVoltage.cpp File Reference
#include <blond/constants.h>
#include <blond/globals.h>
#include <blond/impedances/InducedVoltage.h>
#include <blond/math_functions.h>
#include <blond/utilities.h>
Functions
void linear_interp_kick (const ftype *__restrict beam_dt, ftype *__restrict beam_dE, const ftype *__restrict voltage_array, const ftype *__restrict bin_centers, const int n_slices, const int n_macroparticles)
Function Documentation
void linear_interp_kick (const ftype *__restrict beam_dt, ftype *__restrict beam_dE, const ftype *__restrict voltage_array, const ftype *__restrict bin_centers, const int n_slices, const int n_macroparticles)
Definition at line 9 of file InducedVoltage.cpp.
Referenced by RingAndRfSection::track(), TotalInducedVoltage::track(), InducedVoltageFreq::track(), and InducedVoltageTime::track().
{
    const ftype binFirst = bin_centers[0];
    const ftype binLast = bin_centers[n_slices - 1];
    const ftype inv_bin_width = (n_slices - 1) / (binLast - binFirst);
    #pragma omp parallel for
    for (int i = 0; i < n_macroparticles; ++i) {
        const ftype a = beam_dt[i];
        const int ffbin = static_cast<int>((a - binFirst) * inv_bin_width);
        const ftype voltageKick =
            ((a < binFirst) || (a > binLast))
            ? 0.0
            : voltage_array[ffbin] +
            (a - bin_centers[ffbin]) *
            (voltage_array[ffbin + 1] - voltage_array[ffbin]) *
            inv_bin_width;
        beam_dE[i] += voltageKick;
    }
}