Beam Longitudinal Dynamics code (BLonD): blond::util::Arg Struct Reference
blond::util::Arg Struct Reference
#include <utilities.h>
Static Public Member Functions
static optionparser::ArgStatus NonEmpty (const optionparser::Option &option, bool msg)
static optionparser::ArgStatus Numeric (const optionparser::Option &option, bool msg)
static void printError (const char *msg1, const optionparser::Option &opt, const char *msg2)
static optionparser::ArgStatus Required (const optionparser::Option &option, bool msg)
static optionparser::ArgStatus Unknown (const optionparser::Option &option, bool msg)
Static Public Member Functions inherited from blond::optionparser::Arg
static ArgStatus None (const Option &, bool)
For options that don't take an argument: Returns ARG_NONE.
static ArgStatus Optional (const Option &option, bool)
Returns ARG_OK if the argument is attached and ARG_IGNORE otherwise.
Detailed Description
Definition at line 276 of file utilities.h.
Member Function Documentation
static optionparser::ArgStatus blond::util::Arg::NonEmpty (const optionparser::Option & option, bool msg) inline static
Definition at line 304 of file utilities.h.
References blond::optionparser::Option::arg, blond::optionparser::ARG_ILLEGAL, blond::optionparser::ARG_OK, and printError().
             {
                 if (option.arg != 0 && option.arg[0] != 0)
                     return optionparser::ARG_OK;
                 if (msg)
                     printError("Option '", option,
                                "' requires a non-empty argument\n");
                 return optionparser::ARG_ILLEGAL;
             }
static optionparser::ArgStatus blond::util::Arg::Numeric (const optionparser::Option & option, bool msg) inline static
Definition at line 316 of file utilities.h.
References blond::optionparser::Option::arg, blond::optionparser::ARG_ILLEGAL, blond::optionparser::ARG_OK, and printError().
             {
                 // printf("Inside here\n");
                 char *endptr = 0;
                 if (option.arg != 0 && strtol(option.arg, &endptr, 10)) {
                 };
                 if (endptr != option.arg && *endptr == 0)
                     return optionparser::ARG_OK;
                 if (msg)
                     printError("Option '", option,
                                "' requires a numeric argument\n");
                 return optionparser::ARG_ILLEGAL;
             }
static void blond::util::Arg::printError (const char * msg1, const optionparser::Option & opt, const char * msg2) inline static
Definition at line 277 of file utilities.h.
References blond::optionparser::Option::name, and blond::optionparser::Option::namelen.
Referenced by NonEmpty(), Numeric(), Required(), and Unknown().
             {
                 fprintf(stderr, "%s", msg1);
                 fwrite(opt.name, opt.namelen, 1, stderr);
                 fprintf(stderr, "%s", msg2);
             }
static optionparser::ArgStatus blond::util::Arg::Required (const optionparser::Option & option, bool msg) inline static
Definition at line 293 of file utilities.h.
References blond::optionparser::Option::arg, blond::optionparser::ARG_ILLEGAL, blond::optionparser::ARG_OK, and printError().
             {
                 if (option.arg != 0)
                     return optionparser::ARG_OK;
                 if (msg)
                     printError("Option '", option, "' requires an argument\n");
                 return optionparser::ARG_ILLEGAL;
             }
static optionparser::ArgStatus blond::util::Arg::Unknown (const optionparser::Option & option, bool msg) inline static
Definition at line 285 of file utilities.h.
References blond::optionparser::ARG_ILLEGAL, and printError().
             {
                 if (msg)
                     printError("Unknown option '", option, "'\n");
                 return optionparser::ARG_ILLEGAL;
             }