Beam Longitudinal Dynamics code (BLonD): openmp.h File Reference
openmp.h File Reference
Functions
static int omp_get_max_threads ()
static int omp_get_num_threads ()
static int omp_get_thread_num ()
static void omp_set_num_threads (int threads)
Function Documentation
static int omp_get_max_threads () inline static
Definition at line 18 of file openmp.h.
Referenced by fft::convolution_with_ffts().
 {return 1;}
static int omp_get_num_threads () inline static
Definition at line 17 of file openmp.h.
Referenced by Slices::histogram().
 {return 1;}
static int omp_get_thread_num () inline static
Definition at line 19 of file openmp.h.
Referenced by Slices::histogram().
 {return 0;}
static void omp_set_num_threads (int threads) inline static
Definition at line 20 of file openmp.h.
 {}