Beam Longitudinal Dynamics code (BLonD): util Namespace Reference
util Namespace Reference
Classes
struct Arg
Functions
static std::string double_vector_to_string (f_vector_t &numbers)
template<typename T >
static void dump (const T *a, const unsigned n, const char *s)
template<typename T >
static void dump (const std::vector< T > &a, const char *s, uint n=0)
template<typename T >
static void dump (const T a, const char *s)
template<typename T >
static void dump_to_file (std::vector< T > &v, std::string file)
static std::string exec (const char *cmd)
static void get_time (timespec &ts)
static timespec get_time ()
static char const * GETENV (char const *envstr)
static size_t getFileSize (const std::string &file)
static void print_time (char const *prompt, timespec const &begin, timespec const &end)
static void print_time (char const *prompt, double diff)
static void print_time_elapsed (char const *prompt, timespec const &begin)
static std::string read_from_file (std::string filename)
template<typename T >
static void read_vector_from_file (std::vector< T > &v, std::string file)
static f_vector_t string_to_double_vector (std::string &numbers)
static double time_diff (timespec const &end, timespec const &begin)
static double time_elapsed (timespec const &begin)
Function Documentation
static std::string util::double_vector_to_string (f_vector_t & numbers) inline static
Definition at line 47 of file utilities.h.
     {
         std::ostringstream oss;
         for (auto &n : numbers)
             oss << n << " ";
         return oss.str();
     }
template<typename T > static void util::dump (const T * a, const unsigned n, const char * s) inline static
Definition at line 143 of file utilities.h.
References PRECISION.
     {
 #ifdef PRINT_RESULTS
         std::cout.precision(PRECISION);
         std::cout << s;
         std::cout << std::scientific << std::showpos;
         for (uint i = 0; i < n; ++i)
             std::cout << a[i] << std::endl;
         std::cout << std::endl;
 #endif
     }
template<typename T > static void util::dump (const std::vector< T > & a, const char * s, uint n = 0) inline static
Definition at line 156 of file utilities.h.
References PRECISION.
     {
 #ifdef PRINT_RESULTS
         n = (n == 0) ? a.size() : n;
         std::cout.precision(PRECISION);
         std::cout << s;
         std::cout << std::scientific << std::showpos;
         for (uint i = 0; i < n; ++i)
             std::cout << a[i] << std::endl;
         std::cout << std::endl;
 #endif
     }
template<typename T > static void util::dump (const T a, const char * s) inline static
Definition at line 170 of file utilities.h.
References PRECISION.
     {
 #ifdef PRINT_RESULTS
         std::cout.precision(PRECISION);
         std::cout << s;
         std::cout << std::scientific << std::showpos;
         std::cout << a << std::endl;
 #endif
     }
template<typename T > static void util::dump_to_file (std::vector< T > & v, std::string file) inline static
Definition at line 87 of file utilities.h.
     {
         std::ofstream output_file(file);
         std::ostream_iterator<T> output_iterator(output_file, "\n");
         std::copy(v.begin(), v.end(), output_iterator);
         output_file.close();
     }
static std::string util::exec (const char * cmd) inline static
Definition at line 250 of file utilities.h.
     {
 #ifdef WIN32
         std::shared_ptr<FILE> pipe(_popen(cmd, "r"), _pclose);
 #else
         std::shared_ptr<FILE> pipe(popen(cmd, "r"), pclose);
 #endif
         if (!pipe)
             return "ERROR";
         char buffer[128];
         std::string result = "";
         while (!feof(pipe.get())) {
             if (fgets(buffer, 128, pipe.get()) != NULL)
                 result += buffer;
         }
         return result;
     }
static void util::get_time (timespec & ts) inline static
Definition at line 194 of file utilities.h.
Referenced by get_time(), and time_elapsed().
     {
 #ifdef TIMING
         auto time = std::chrono::system_clock::now();
         ts.tv_sec = std::chrono::duration_cast<std::chrono::seconds>(
                         time.time_since_epoch())
                     .count();
         ts.tv_nsec = std::chrono::duration_cast<std::chrono::microseconds>(
                          time.time_since_epoch())
                      .count();
 #endif
     }
static timespec util::get_time () inline static
Definition at line 207 of file utilities.h.
References get_time().
     {
         timespec t;
 #ifdef TIMING
         get_time(t);
 #endif
         return t;
     }
static char const* util::GETENV (char const * envstr) inline static
Definition at line 118 of file utilities.h.
     {
         char const *env = getenv(envstr);
         if (!env)
             return "0";
         else
             return env;
     }
static size_t util::getFileSize (const std::string & file) inline static
Definition at line 55 of file utilities.h.
     {
         struct stat st;
         if (stat(file.c_str(), &st) != 0) {
             return 0;
         }
         return st.st_size;
     }
static void util::print_time (char const * prompt, timespec const & begin, timespec const & end) inline static
Definition at line 227 of file utilities.h.
References dprintf, and time_diff().
     {
 #ifdef TIMING
         dprintf("%s : %.3f\n", prompt, time_diff(end, begin));
 #endif
     }
static void util::print_time (char const * prompt, double diff) inline static
Definition at line 235 of file utilities.h.
References dprintf.
     {
 #ifdef TIMING
         dprintf("%s : %.3f\n", prompt, diff);
 #endif
     }
static void util::print_time_elapsed (char const * prompt, timespec const & begin) inline static
Definition at line 242 of file utilities.h.
References dprintf, and time_elapsed().
     {
 #ifdef TIMING
         dprintf("%s : %.3f\n", prompt, time_elapsed(begin));
 #endif
     }
static std::string util::read_from_file (std::string filename) inline static
Definition at line 268 of file utilities.h.
     {
         std::ifstream t(filename);
         std::stringstream res;
         res << t.rdbuf();
         return res.str();
     }
template<typename T > static void util::read_vector_from_file (std::vector< T > & v, std::string file) inline static
Definition at line 65 of file utilities.h.
Referenced by longitudinal_bigaussian(), and PhaseNoise::spectrum_to_phase_noise().
     {
         v.clear();
         std::ifstream source(file);
         if (!source.good()) {
             std::cout << "Error: file " << file << " does not exist\n";
             source.close();
             exit(-1);
         }
         for (std::string line; std::getline(source, line);) {
             std::istringstream in(line);
             T type;
             while (in >> type)
                 v.push_back(type);
         }
         source.close();
     }
static f_vector_t util::string_to_double_vector (std::string & numbers) inline static
Definition at line 37 of file utilities.h.
Referenced by matched_from_line_density().
     {
         f_vector_t res;
         std::istringstream iss(numbers);
         std::copy(std::istream_iterator<double>(iss),
                   std::istream_iterator<double>(),
                   std::back_inserter(res));
         return res;
     }
static double util::time_diff (timespec const & end, timespec const & begin) inline static
Definition at line 180 of file utilities.h.
Referenced by print_time(), and time_elapsed().
     {
 #ifdef TIMING
         double result;
         result = end.tv_sec - begin.tv_sec;
         result += (end.tv_nsec - begin.tv_nsec) / (double)1000000000;
         return result;
 #else
         return 0;
 #endif
     }
static double util::time_elapsed (timespec const & begin) inline static
Definition at line 216 of file utilities.h.
References get_time(), and time_diff().
Referenced by print_time_elapsed().
     {
 #ifdef TIMING
         timespec now;
         get_time(now);
         return time_diff(now, begin);
 #else
         return 0;
 #endif
     }