Beam Longitudinal Dynamics code (BLonD): python Namespace Reference
python Namespace Reference
Classes
struct multi_t
Functions
static PyObject * convert_bool (bool value)
static PyObject * convert_complex_array (std::complex< double > *array, int size)
static PyObject * convert_complex_array (complex_vector_t &v)
static PyObject * convert_dictionary (std::map< std::string, std::string > &map)
static PyObject * convert_dictionary (std::map< std::string, multi_t > &map)
static PyObject * convert_double (double value)
static PyObject * convert_double_2d_array (f_vector_2d_t &v)
static PyArrayObject * convert_double_array (double *array, int size)
static PyArrayObject * convert_double_array (std::vector< double > &v)
static PyObject * convert_double_list (double *array, int size)
static PyObject * convert_double_list (std::vector< double > &v)
static PyObject * convert_int (int value)
static PyArrayObject * convert_int_array (int *array, int size)
static PyArrayObject * convert_int_array (std::vector< int > &v)
static PyObject * convert_string (std::string &value)
static PyObject * convert_string_array (std::string *array, int size)
static PyObject * convert_string_array (std::vector< std::string > &v)
static void finalize ()
static PyObject * get_none ()
static int import ()
static PyObject * import (std::string module, std::string function)
static int initialize ()
Function Documentation
static PyObject* python::convert_bool (bool value) inline static
Definition at line 93 of file python.h.
Referenced by plot_long_phase_space().
     {
         auto pVar = PyBool_FromLong((long) value);
         assert(pVar);
         return pVar;
     }
static PyObject* python::convert_complex_array (std::complex< double > * array, int size) inline static
Definition at line 185 of file python.h.
Referenced by convert_complex_array(), plot_beam_spectrum(), and plot_impedance_vs_frequency().
     {
         auto pList = PyList_New(size);
         assert(pList);
         for (int i = 0; i < size; i++) {
             auto z = array[i];
             auto pZ = PyComplex_FromDoubles(z.real(), z.imag());
             assert(pZ);
             PyList_SET_ITEM(pList, i, pZ);
         }
         return pList;
     }
static PyObject* python::convert_complex_array (complex_vector_t & v) inline static
Definition at line 199 of file python.h.
References convert_complex_array().
     {
         return convert_complex_array(v.data(), v.size());
     }
static PyObject* python::convert_dictionary (std::map< std::string, std::string > & map) inline static
Definition at line 204 of file python.h.
Referenced by Slices::beam_profile_filter_chebyshev().
     {
         if (map.size() > 0) {
             auto pDict = PyDict_New();
             assert(pDict);
             for (const auto &pair : map) {
                 auto pKey = PyString_FromString(pair.first.c_str());
                 auto pVal = PyString_FromString(pair.second.c_str());
                 PyDict_SetItem(pDict, pKey, pVal);
             }
             return pDict;
         } else {
             return Py_None;
         }
     }
static PyObject* python::convert_dictionary (std::map< std::string, multi_t > & map) inline static
Definition at line 221 of file python.h.
References convert_double(), convert_double_list(), convert_int(), and convert_string().
     {
         if (map.size() > 0) {
             auto pDict = PyDict_New();
             assert(pDict);
             for (auto &pair : map) {
                 auto pKey = PyString_FromString(pair.first.c_str());
                 if (pair.second.type == "double") {
                     auto pVal = convert_double(pair.second.d);
                     PyDict_SetItem(pDict, pKey, pVal);
                 } else if (pair.second.type == "int") {
                     auto pVal = convert_int(pair.second.i);
                     PyDict_SetItem(pDict, pKey, pVal);
                 } else if (pair.second.type == "string") {
                     auto pVal = convert_string(pair.second.s);
                     PyDict_SetItem(pDict, pKey, pVal);
                 } else if (pair.second.type == "f_vector_t") {
                     auto pVal = convert_double_list(pair.second.v);
                     PyDict_SetItem(pDict, pKey, pVal);
                 } else {
                     std::cerr << "Warning: type " << pair.second.type
                               << " was not recognized.\n";
                 }
             }
             return pDict;
         } else {
             return Py_None;
         }
     }
static PyObject* python::convert_double (double value) inline static
Definition at line 71 of file python.h.
Referenced by Slices::beam_profile_filter_chebyshev(), convert_dictionary(), convert_double_list(), Slices::gradient(), plot_long_phase_space(), and plot_xy().
     {
         auto pVar = PyFloat_FromDouble(value);
         assert(pVar);
         return pVar;
     }
static PyObject* python::convert_double_2d_array (f_vector_2d_t & v) inline static
Definition at line 165 of file python.h.
Referenced by plot_beam_profile_derivative(), plot_impedance_vs_frequency(), and plot_LHCNoiseFB_FWHM_bbb().
     {
         int xsize = v.size();
         auto pList = PyList_New(xsize);
         assert(pList);
         for (int i = 0; i < xsize; i++) {
             int ysize = v[i].size();
             auto pRow = PyList_New(ysize);
             for (int j = 0; j < ysize; j++) {
                 auto pVar = PyFloat_FromDouble(v[i][j]);
                 assert(pVar);
                 PyList_SET_ITEM(pRow, j, pVar);
             }
             PyList_SET_ITEM(pList, i, pRow);
         }
         return pList;
     }
static PyArrayObject* python::convert_double_array (double * array, int size) inline static
Definition at line 117 of file python.h.
Referenced by Slices::beam_profile_filter_chebyshev(), convert_double_array(), Slices::gaussian_filter1d(), Slices::gaussian_fit(), Slices::gradient(), plot_beam_profile(), plot_beam_spectrum(), plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_generated_bunch(), plot_impedance_vs_frequency(), plot_induced_voltage_vs_bin_centers(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_long_phase_space(), plot_noise_spectrum(), plot_phase_noise(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), plot_voltage_programme(), and plot_xy().
     {
         int dims[1] = {size};
         auto pVar = (PyArrayObject *) PyArray_FromDimsAndData(1, dims,
                     NPY_DOUBLE, (char *)array);
         assert(pVar);
         return pVar;
     }
static PyArrayObject* python::convert_double_array (std::vector< double > & v) inline static
Definition at line 128 of file python.h.
References convert_double_array().
     {
         return convert_double_array(v.data(), v.size());
     }
static PyObject* python::convert_double_list (double * array, int size) inline static
Definition at line 133 of file python.h.
References convert_double().
Referenced by convert_dictionary(), and convert_double_list().
     {
         auto pList = PyList_New(size);
         assert(pList);
         for (int i = 0; i < size; i++) {
             auto pVar = convert_double(array[i]);
             PyList_SET_ITEM(pList, i, pVar);
         }
         return pList;
     }
static PyObject* python::convert_double_list (std::vector< double > & v) inline static
Definition at line 144 of file python.h.
References convert_double_list().
     {
         return convert_double_list(v.data(), v.size());
     }
static PyObject* python::convert_int (int value) inline static
Definition at line 79 of file python.h.
Referenced by Slices::beam_profile_filter_chebyshev(), convert_dictionary(), Slices::gaussian_filter1d(), plot_beam_profile(), plot_beam_profile_derivative(), plot_beam_spectrum(), plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_impedance_vs_frequency(), plot_induced_voltage_vs_bin_centers(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_LHCNoiseFB_FWHM_bbb(), plot_long_phase_space(), plot_noise_spectrum(), plot_phase_noise(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), plot_transmitted_particles(), and plot_voltage_programme().
     {
         auto pVar = PyInt_FromLong(value);
         assert(pVar);
         return pVar;
     }
static PyArrayObject* python::convert_int_array (int * array, int size) inline static
Definition at line 101 of file python.h.
Referenced by convert_int_array(), plot_long_phase_space(), and plot_transmitted_particles().
     {
         int dims[1] = {size};
         auto pVar = (PyArrayObject *) PyArray_FromDimsAndData(1, dims,
                     NPY_INT, (char *)array);
         assert(pVar);
         return pVar;
     }
static PyArrayObject* python::convert_int_array (std::vector< int > & v) inline static
Definition at line 111 of file python.h.
References convert_int_array().
     {
         return convert_int_array(v.data(), v.size());
     }
static PyObject* python::convert_string (std::string & value) inline static
Definition at line 86 of file python.h.
Referenced by convert_dictionary(), Slices::gaussian_filter1d(), plot_beam_profile(), plot_beam_profile_derivative(), plot_beam_spectrum(), plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_generated_bunch(), plot_impedance_vs_frequency(), plot_induced_voltage_vs_bin_centers(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_LHCNoiseFB_FWHM_bbb(), plot_long_phase_space(), plot_noise_spectrum(), plot_phase_noise(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), plot_transmitted_particles(), plot_voltage_programme(), and plot_xy().
     {
         auto pVar = PyString_FromString(value.c_str());
         assert(pVar);
         return pVar;
     }
static PyObject* python::convert_string_array (std::string * array, int size) inline static
Definition at line 149 of file python.h.
Referenced by convert_string_array(), and plot_beam_profile_derivative().
     {
         std::string result = array[0];
         for (int i = 1; i < size; i++)
             result += " " + array[i];
         auto pVar = PyString_FromString(result.c_str());
         assert(pVar);
         return pVar;
     }
static PyObject* python::convert_string_array (std::vector< std::string > & v) inline static
Definition at line 159 of file python.h.
References convert_string_array().
     {
         return convert_string_array(v.data(), v.size());
     }
static void python::finalize () inline static
Definition at line 49 of file python.h.
     {
         Py_Finalize();
     }
static PyObject* python::get_none () inline static
Definition at line 66 of file python.h.
Referenced by plot_long_phase_space().
     {
         return Py_None;
     }
static int python::import () inline static
Definition at line 43 of file python.h.
Referenced by Slices::beam_profile_filter_chebyshev(), Slices::gaussian_filter1d(), Slices::gaussian_fit(), Slices::gradient(), plot_beam_profile(), plot_beam_profile_derivative(), plot_beam_spectrum(), plot_bunch_length_evol(), plot_bunch_length_evol_gaussian(), plot_COM_motion(), plot_energy_evol(), plot_generated_bunch(), plot_impedance_vs_frequency(), plot_induced_voltage_vs_bin_centers(), plot_LHCNoiseFB(), plot_LHCNoiseFB_FWHM(), plot_LHCNoiseFB_FWHM_bbb(), plot_long_phase_space(), plot_noise_spectrum(), plot_phase_noise(), plot_PL_bunch_phase(), plot_PL_freq_corr(), plot_PL_phase_corr(), plot_PL_RF_freq(), plot_PL_RF_phase(), plot_position_evol(), plot_RF_phase_error(), plot_RL_radial_error(), plot_transmitted_particles(), plot_voltage_programme(), and plot_xy().
     {
         import_array1(0);
         return 0;
     }
static PyObject* python::import (std::string module, std::string function) inline static
Definition at line 54 of file python.h.
     {
         // TODO try to prepend the path to python folder
         auto pModule = PyImport_ImportModule(module.c_str());
         assert(pModule);
         auto pFunc = PyObject_GetAttrString(pModule, function.c_str());
         assert(pFunc);
         return pFunc;
     }
static int python::initialize () inline static
Definition at line 35 of file python.h.
     {
         putenv("PYTHONPATH=" PYPATH);
         Py_SetPythonHome(PYHOME);
         Py_Initialize();
         return 0;
     }